--事件类型
EventType = {
    -- 场景相关管理
    CITY_CAMERA_DISABLED = "CITY_CAMERA_DISABLED",
    CITY_CAMERA_ENABLED = "CITY_CAMERA_ENABLED",

    UPGRADE_ZONE_BEGIN = "UPGRADE_ZONE_BEGIN",
    UPGRADE_ZONE = "UPGRADE_ZONE",
    UPGRADE_FURNITURE = "UPGRADE_FURNITURE",
    UPDATE_ZONE_GRID_DATA = "UPDATE_ZONE_GRID_DATA",
    COLLECT_ITEM = "COLLECT_ITEM",
    COLLECT_FOOD = "COLLECT_FOOD",
    USE_ITEM = "USE_ITEM",
    SCHEDULES_ADD = "SCHEDULES_ADD",
    SCHEDULES_REMOVE = "SCHEDULES_REMOVE",
    TIME_CITY_UPDATE = "TIME_CITY_UPDATE",
    TIME_CITY_PER_HOUR = "TIME_CITY_PER_HOUR",
    TIME_CITY_NEW_DAY = "TIME_CITY_NEW_DAY",
    TIME_CITY_PER_REFRESH = "TIME_CITY_PER_REFRESH",
    TIME_CITY_FORCE_REFRESH = "TIME_CITY_FORCE_REFRESH",
    TIME_REAL_PER_SECOND = "TIME_REAL_PER_SECOND",
    REFRESH_GENERATOR = "REFRESH_GENERATOR",
    CHARACTER_REFRESH = "CHARACTER_REFRESH",
    CHARACTER_VIEW_COMPLETED = "CHARACTER_VIEW_COMPLETED",
    CHARACTER_STATE_CHANGE = "CHARACTER_STATE_CHANGE",
    CHARACTER_PROFESSION_CHANGE = "CHARACTER_PROFESSION_CHANGE",
    CHARACTER_ATTRIBUTE_WARNING = "CHARACTER_ATTRIBUTE_WARNING",
    CHARACTER_ATTRIBUTE_BOOST = "CHARACTER_ATTRIBUTE_BOOST",
    CHARACTER_EATING_FOOD = "CHARACTER_EATING_FOOD",
    TASK_FINISH = "TASK_FINISH", --任务完成，但是还没有领取时触发
    TASK_COMPLETE = "TASK_COMPLETE", --任务完成后，领取了奖励时触发
    -- TASK_REFRESH是在TASK_FINISH 或者 TASK_COMPLETE 之后触发
    TASK_REFRESH = "TASK_REFRESH",
    -- TASK_CHANGE 是在Check后，taskCurrCount有变化，就会触发
    TASK_CHANGE = "TASK_CHANGE",
    -- 任务状态发生变化时
    TASK_STATUS_REFRESH = "TASK_STATUS_REFRESH",
    TASK_MILESTONE_REFRESH = "TASK_MILESTONE_REFRESH", --章节任务完成并领奖后触发
    PLAYER_HP = "PLAYER_HP",
    PLAYER_HP_IMMLY = "PLAYER_HP_IMMLY",
    ENEMY_HP = "ENEMY_HP",
    BATTLRESULT = "BATTLRESULT",
    CREATE_PLAYER = "CREATE_PLAYER",
    BEGIN_BATTLE = "BEGIN_BATTLE",
    SHOW_PROTEST_DEBUFF = "SHOW_PROTEST_DEBUFF",
    BLACK_MARKET_REFRESH = "BLACK_MARKET_REFRESH",
    BLACK_MARKET_TIME = "BLACK_MARKET_TIME",
    UIADVENTUREFULL = "UIADVENTUREFULL",
    UIADVENTURECOUNT = "AdventurePanel",
    UPDATE_STATISTICAL = "UPDATE_STATISTICAL",
    COMPLETE_TUTORIAL = "COMPLETE_TUTORIAL",
    ADD_REFRESH_OFFICE = "AddREFRESH_OFFICE",
    FUNCTIONS_UNLOCK = "FUNCTIONS_UNLOCK",
    FUNCTIONS_OPEN = "FUNCTIONS_OPEN",
    ALL_PANEL_CLOSE = "ALL_PANEL_CLOSE",
    ADD_CARD = "ADD_CARD",
    REFRESH_HELPSHIFT_REDPOINT = "REFRESH_HELPSHIFT_REDPOINT",
    SCENE_VIEW_CHANGE = "SCENE_VIEW_CHANGE",
    AUDIO_POSITION_CHANGE = "AUDIO_POSITION_CHANGE",
    AUDIO_EFFECT_SWITCH = "AUDIO_EFFECT_SWITCH",
    ZONE_CARD_CHANGE = "ZONE_CARD_CHANGE",
    WARM_WARNING_CHANEG = "WARM_WARNING_CHANEG",
    WORK_STATE_CHANGE = "WORK_STATE_CHANGE",
    BATTLE_MAINUI_RD = "BATTLE_MAINUI_RD",
    NEXT_EAT_FOOD = "NEXT_EAT_FOOD",
    CITY_NIGHT_CHANGE = "CITY_NIGHT_CHANGE",
    PROTEST_STATE_CHANGE = "PROTEST_STATE_CHANGE",
    PROTEST_TIME_CHANGE = "PROTEST_TIME_CHANGE",
    PROTEST_CARD_LEVEL_CHANGE = "PROTEST_CARD_LEVEL_CHANGE",
    PROTEST_APPEASE_TIME_CHANGE = "PROTEST_APPEASE_TIME_CHANGE",
    PROTEST_APPEASE_COUNT_CHANGE = "PROTEST_APPEASE_COUNT_CHANGE",
    WAREHOUSE_LOADPORT_SWITCH_CHANGE = "WAREHOUSE_LOADPORT_SWITCH_CHANGE",
    WEATHER_TYPE_CHANGE = "WEATHER_TYPE_CHANGE",
    WEATHER_TIME_CHANGE = "WEATHER_TIME_CHANGE",
    --AI GameTool
    AI_RUNNING = "AI_RUNNING",
    AI_GAME_SPEED = "AI_GAME_SPEED",
    AI_RUNNING_DAY = "AI_RUNNING_DAY",
    AI_STOP_WAIT = "AI_STOP_WAIT",
    AI_PRINT_LOG = "AI_PRINT_LOG",
    AI_LOG_SWITCH_SCHEDULES = "AI_LOG_SWITCH_SCHEDULES",
    CHARACTER_IMMEDIATELY_SICK = "CHARACTER_SICK",
    CHARACTER_IMMEDIATELY_HEALTH = "CHARACTER_IMMEDIATELY_HEALTH",
    CHARACTER_IMMEDIATELY_DEAD = "CHARACTER_IMMEDIATELY_DEAD",
    CHARACTER_IMMEDIATELY_PROTEST = "CHARACTER_IMMEDIATELY_PROTEST",
    CHARACTER_LOCK_HEALTH = "CHARACTER_LOCK_HEALTH",
    CHARACTER_LOCK_EVENTSTRIKE = "CHARACTER_LOCK_EVENTSTRIKE",
    CHARACTER_LOCK_HOPE = "CHARACTER_LOCK_HOPE",
    CHARACTER_LOCK_HAPPNESS = "CHARACTER_LOCK_HAPPNESS",
    --
    BATTLE_HERO_HP = "BATTLE_HERO_HP",
    BATTLE_NOTUSEMAINSKILL = "BATTLE_NOTUSEMAINSKILL",
    HALO_DATA_HERO = "HALO_DATA_HERO",
    HALO_DATA_ENEMY = "HALO_DATA_ENEMY",
    BATTLE_MUIL_SKILL_UI_P = "BATTLE_MUIL_SKILL_UI_P",
    BATTLE_FINISH_CB = "BATTLE_FINISH_CB",
    BATTLE_MUIL_SKILL_UI_M = "BATTLE_MUIL_SKILL_UI_M",
    BATTLE_HALO_FLY = "BATTLE_HALO_FLY",
    SHOP_DAILY_REFRESH = "SHOP_DAILY_REFRESH", -- 分解商店刷新
    SHOP_0_CLOCK_REFRESH = "SHOP_REFRESH", -- 商店0点刷新
    SHOP_BUY = "SHOP_BUY", -- 商店购买
    SHOP_COOL_DOWN = "SHOP_COOL_DOWN", -- 商店项目cd完成
    LEADERBOARD_REFRESH = "LEADERBOARD_REFRESH",
    PAYMENT_SUBSCRIPTION_SUCCESS = "PAYMENT_SUBSCRIPTION_SUCCESS", --PaymentManager 订阅成功
    Battle_HALO_ADDTROOPS_HERO = "Battle_HALO_ADDTROOPS_HERO",
    MAIL_LIST_CHANGE = "MAIL_LIST_CHANGE",
    UPGRADE_CARD_LEVEL = "UPGRADE_CARD_LEVEL",
    UPGRADE_CARD_STAR = "UPGRADE_CARD_STAR",
    OPEN_BOX = "OPEN_BOX", --开宝箱
    ROGULE_GET_REWARD = "ROGULE_GET_REWARD",
    ROGUE_ENERGY = "ROGUE_ENERGY",
    ROGUE_BOX_FRAG_COUNT = "ROGUE_BOX_FRAG_COUNT",
    ROGUE_SCHEDULE_BAR = "ROGUE_SCHEDULE_BAR",
    MAP_ROOF_REFRESH = "MAP_ROOF_REFRESH",
    ---
    REFRESH_TRICK_BOOST = "REFRESH_TRICK_BOOST",
    REFRESH_EVENT_MILESTONE = "REFRESH_EVENT_MILESTONE",
    REFRESH_EVENT_CASH = "REFRESH_EVENT_CASH",
    REFRESH_EVENT_PROFILE = "REFRESH_EVENT_PROFILE",
    REWARD_BOOST_ADD = "REWARD_BOOST_ADD",
    ---
    SDK_COMMON_EVENT = "SDK_COMMON_EVENT",
    ---
    EFFECT_RES_ADD_COMPLETE = "EFFECT_RES_ADD_COMPLETE",
    ---
    APPLICATION_JOIN_GAME = "APPLICATION_JOIN_GAME",
    APPLICATION_LEAVE_GAME = "APPLICATION_LEAVE_GAME",
    GENERATOR_ADD_FIRE = "GENERATOR_ADD_FIRE",
    GENERATOR_REDUCE_FIRE = "GENERATOR_REDUCE_FIRE",
    ---
    REFRESH_AD_VIDEO = "REFRESH_AD_VIDEO",
    AD_LOADED = "AD_LOADED",
    ---
    OverTimeProductionChange = "OverTimeProductionChange",
    TeQuanAutohange = "TeQuanAutohange",
    CHANGE_DUQI = "CHANGE_DUQI", -- 毒气UI变化
    TUTORIAL_INIT = "TUTORIAL_INIT", -- 引导初始化完成 
    FACTORY_GAME_BUILD_FIRST = "FACTORY_GAME_BUILD_FIRST", -- 工厂游戏机首次解锁
    FACTORY_GAME_UNLOCK = "FACTORY_GAME_UNLOCK",    -- 工厂游戏机解锁
    FACTORY_GAME_ONDRAW_SUCCESS = "FACTORY_GAME_ONDRAW_SUCCESS",  -- 扭蛋机抽卡
    FACTORY_GAME_ONGASHAPON_UPDATA = "FACTORY_GAME_ONGASHAPON_UPDATA", -- 扭蛋机抽卡
}

EventManager = {}
EventManager.__cname = "EventManager"
--EventManager.event = Event:New()

local this = EventManager

function EventManager.AddListener(event, handler)
    Event.AddListener(event, handler)
end

function EventManager.Brocast(event, ...)
    Event.Brocast(event, ...)
end

function EventManager.RemoveListener(event, handler)
    Event.RemoveListener(event, handler)
end

function EventManager.Reset()
    --EventManager.event = Event:New()
end


