-- require("Game/Framework/Libs/rapidjson")
Rx = require("Game/Framework/Libs/rx")
-- Split = require("Game/Framework/Libs/split").split
-- Base64 = require("Game/Framework/Libs/base64")
--UnityEngine = require("Game.Framework.UnityEngine.UnityEngine")
luaVector3 = require("Game.Framework.UnityEngine.LuaVector3")

------ LuaLogger = CS.CenturyGame.Framework.Lua.LuaLogger
------ NetworkManager = CS.GameLogic.GameEntry.Network
------ MsgProcesser = CS.GameLogic.GameEntry.MsgProcesser
------ NetworkTrace = CS.CenturyGame.Framework.Network.Trace.Instance
------ EWindowLayer = CS.CenturyGame.Framework.UI.EWindowLayer

----SceneManager = UnityEngine.SceneManagement.SceneManager
--Application = UnityEngine.Application
-- RuntimePlatform = UnityEngine.RuntimePlatform
--GameObject = UnityEngine.GameObject
--Transform = UnityEngine.Transform
--Debug = UnityEngine.Debug
--Time = UnityEngine.Time
----Vector3 = UnityEngine.Vector3
----Vector4 = UnityEngine.Vector4
----Vector2 = UnityEngine.Vector2
--Color = UnityEngine.Color
--Quaternion = UnityEngine.Quaternion
--Mathf = UnityEngine.Mathf
--Rect = UnityEngine.Rect
--Ease = DG.Tweening.Ease
--LoopType = DG.Tweening.LoopType
--RotateMode = DG.Tweening.RotateMode
----AssetBundleManager = CS.CenturyGame.AssetBundleManager.Runtime.AssetBundleManager
--Object = UnityEngine.Object
--Camera = UnityEngine.Camera
--Shader = UnityEngine.Shader
--Space = UnityEngine.Space
--Material = UnityEngine.Material
----Localization = CS.Polyglot.Localization
----LocalizationImporter = CS.Polyglot.LocalizationImporter
----LanguageType = CS.Polyglot.Language
--RectTransformUtility = UnityEngine.RectTransformUtility
--ExecuteEvents = UnityEngine.ExecuteEvents
--Screen = UnityEngine.Screen
--Canvas = UnityEngine.Canvas
----LayoutRebuilder = UnityEngine.UI.LayoutRebuilder
--Input = UnityEngine.Input
----SpriteState = UnityEngine.UI.SpriteState
----EventSystem = UnityEngine.EventSystems.EventSystem
----PointerEventData = UnityEngine.EventSystems.PointerEventData
--Char = System.Char
----CSUtils = CS.FrozenCity.Utils

--Resource = UnityEngine.Resource
--PlayerPrefs = UnityEngine.PlayerPrefs
--Physics = UnityEngine.Physics
--WaitForSeconds = UnityEngine.WaitForSeconds
----OptionData = UnityEngine.UI.Dropdown.OptionData

----AppScreen = CS.FrozenCity.AppScreen
----AppAudio = CS.FrozenCity.AppAudio
----AppRender = CS.FrozenCity.AppRender
----AppCenter = CS.FrozenCity.AppCenter
----ButtonPlus = CS.FrozenCity.View.ButtonPlus
----ImagePlus = CS.FrozenCity.View.ImagePlus
----TextPlus = CS.FrozenCity.View.TextPlus
----SliderPlus = CS.FrozenCity.View.SliderPlus
----AppHttp = CS.FrozenCity.AppHttp
----SDKWrap = CS.FrozenCity.SDK
----AdSDK = CS.FrozenCity.SDKAd
----AnalyticsSDK = CS.FrozenCity.SDKAnalytics
----PaymentSDK = CS.FrozenCity.SDKPayment
----SurveySDK = CS.FrozenCity.SDKSurvey
----HelpShiftSDK = CS.FrozenCity.SDKHelpShift
----FirebaseSDK = CS.FrozenCity.SDKFirebase
----AppRateSDK = CS.FrozenCity.SDKAppRate
----AkActionOnEventType = CS.AkActionOnEventType
----CGSdk = CS.centurygame.CGSdk
----CGAccount = CS.centurygame.CGAccount
----CGSdkUtils = CS.centurygame.CGSdkUtils

----TypeLuaEventBehaviour = typeof(CS.FrozenCity.Framework.LuaEventBehaviour)
----TypeLuaMonoBehaviour = typeof(CS.FrozenCity.Framework.LuaMonoBehaviour)
----TypeLuaComponentBinder = typeof(CS.FrozenCity.Framework.LuaComponentBinder)
--TypeCanvas = typeof(UnityEngine.Canvas)
--TypeGameObject = typeof(UnityEngine.GameObject)
--TypeCanvasGroup = typeof(UnityEngine.CanvasGroup)
--TypeBoxCollider = typeof(UnityEngine.BoxCollider)
--TypeSphereCollider = typeof(UnityEngine.SphereCollider)
----TypeImage = typeof(UnityEngine.UI.Image)
----TypeButton = typeof(UnityEngine.UI.Button)
----TypeText = typeof(UnityEngine.UI.Text)
----TypeSlider = typeof(UnityEngine.UI.Slider)
----TypeToggle = typeof(UnityEngine.UI.Toggle)
----TypeToggleGroup = typeof(UnityEngine.UI.ToggleGroup)
----TypeInputField = typeof(UnityEngine.UI.InputField)
--TypeSprite = typeof(UnityEngine.Sprite)
----TypeSpriteAtlas = typeof(UnityEngine.U2D.SpriteAtlas)
--TypeAnimator = typeof(UnityEngine.Animator)
--TypeAnimation = typeof(UnityEngine.Animation)
--TypeAnimationClip = typeof(UnityEngine.AnimationClip)
--TypeRenderer = typeof(UnityEngine.Renderer)
----TypeEmissionUtils = typeof(CS.FrozenCity.EmissionUtils)
----TypeEmissionUtilsBuilt = typeof(CS.FrozenCity.EmissionUtilsBuilt)
----TypeEmissionUtilsNewBuilding = typeof(CS.FrozenCity.EmissionUtilsNewBuilding)
--TypeMeshRender = typeof(UnityEngine.MeshRenderer)
----TyPiontNode = typeof(CS.FrozenCity.PiontNode)
--TypeTextAsset = typeof(UnityEngine.TextAsset)
----TypeDropdown = typeof(UnityEngine.UI.Dropdown)
----TypeBulletPath = typeof(CS.FrozenCity.BulletPath)
----TypePoolUnit = typeof(CS.FrozenCity.PoolUnit)
----TypeAnimationEventHelper = typeof(CS.FrozenCity.View.AnimationEventHelper)
----TypeBuildAnimationHelper = typeof(CS.FrozenCity.View.BuildAnimationHelper)
----TypeOutline = typeof(UnityEngine.UI.Outline)
----TypeEffectNode = typeof(CS.FrozenCity.EffectNode)
----TypePreloader = typeof(CS.FrozenCity.Preloader)
--TypeSpriteRenderer = typeof(UnityEngine.SpriteRenderer)
--TypeRectTransform = typeof(UnityEngine.RectTransform)
----TypeMoveNode = typeof(CS.FrozenCity.MoveNode)
--TypeMaterial = typeof(UnityEngine.Material)
----TypeAnimationCurveItem = typeof(CS.FrozenCity.View.AnimationCurveItem)
--DOTween = DG.Tweening.DOTween
----TypeMoveAgent = typeof(CS.FrozenCity.Agent.MoveAgent)
----TypeAnimatorAgent = typeof(CS.FrozenCity.Agent.AnimatorAgent)
----TypeLoopListView2 = typeof(CS.SuperScrollView.LoopListView2)
----TypeSelectSceneConfig = typeof(CS.FrozenCity.View.SelectSceneConfig)
----TypeFitHeightText = typeof(CS.Polyglot.FitHeightText)
----TypeLuaComponentBinder = typeof(CS.FrozenCity.Framework.LuaComponentBinder)
----TypeSimpleScrollSnap = typeof(CS.DanielLochner.Assets.SimpleScrollSnap.SimpleScrollSnap)
----TypeClickAndScrollView = typeof(CS.FrozenCity.UI.ClickAndScrollView)
----TypeCardStarComponent = typeof(CS.FrozenCity.UI.CardStarComponent)

MonoEventType = {
    Update = "Update",
    LateUpdate = "LateUpdate",
    FixedUpdate = "FixedUpdate",
    OnApplicationFocus = "OnApplicationFocus",
    OnApplicationPause = "OnApplicationPause",
    OnApplicationQuit = "OnApplicationQuit",
    OnPressEsc = "OnPressEsc",
    OnMouseDown = "OnMouseDown",
    AnimationEvent = "AnimationEvent",
    OnScreenResize = "OnScreenResize"
}
