----------------------------------------------
-- 提示字符串的统一表格
----------------------------------------------

StrEnum = 
{
	ServerConnectErr 				= 1, --服务器连接错误
	HaveNoPlayerList 				= 2, --没有角色列表
	FormatRoundNum 					= 3,
	MarchingState 					= 4,
	MarchingBackState 				= 5,
	MarchingStayState 				= 6,
	MyCastle 						= 7,
	MailPVPAttackTitle 				= 8,
	MailPVPDefenceTitle 			= 9,
	MailPVPBattleResultWin 			= 10,
	MailPVPBattleResultFailed 		= 11,
	JustMinute 						= 12,
	MinuteAgo 						= 13,
	HoursAgo 						= 14,
	MessageMainTitle 				= 15,
	MessageBattleTitle 				= 16,
	MessageScoutTitle 				= 17,
	BuildNeedJumpTo 				= 18,
	BuildNeedFinishNow 				= 19,
	BuildNeedMore 					= 20,
	SoldierBuildingUnLock 			= 21,
	SelectMailTip 					= 22,
	ScoutToState 					= 23,
	ScoutBackState 					= 24,
	ScoutStayState 					= 25,
	HomeStateTipLevelUp 			= 26,
	HomeStateTipCreate 				= 27,
	MailScoutSuccess 				= 28,
	MailScoutFailed 				= 29,
	MailScoutTips 					= 30,
	MailScoutWarningTips 			= 31,
	MailScoutProtected 				= 32,
	MailScoutMisty 					= 33,
	HomeStateTipRecruitSoldier 		= 34;
	ScoutTowerDesc 					= 35,
	Offline 						= 41,
	Online  						= 42,
	BuindingCreating 				= 43,
	BuindingUpdating 				= 44,
	BuindingIdle 					= 45, 
	BuindingFree 					= 46,
	AllianceEventCreate 			= 47,
	AllianceEventKick  			 	= 48,
	AllianceEventAgree  			= 49,
	HomeStateHpsoitalRecover 		= 50,
	UnFormation 					= 51,
	MarchingRequestBattle 			= 52,
	MarchingBattling 				= 53,
	ChoseMarchGeneral 				= 54,
	Countryside 					= 55,
	ZhaoMu 							= 56,
	ChuZhan 						= 57,
	DaiMing 						= 58,
	BuildingCampBu 					= 59,
	BuildingCampQi 					= 60,
	BuildingCampGong 				= 61,
	BuildingCampFa 					= 62,
	AttackWin 						= 63,		--进攻%s胜利	
	AttackLost 						= 64,	--进攻%s失败	
	DefenceWin 						= 65,	--防守%s胜利	
	DefenceLost 					= 66,	--防守%s失败	
	MissinTypeRecommend 			= 67,
	MissinTypeDaily 				= 68,
	MissinTypeArmament 				= 69, 
	MissinTypeConstruction 			= 70,
	MissinTypeOther 				= 71,
	MarchChuZhen 					= 72,
	MarchFanHui 					= 73,
	DispatchCanMartch 				= 74,
	DispatchUnMartch 				= 75,
	MailScoutContentTips 			= 76,
	PhyAttack 						= 77,
	MagicAttack 					= 78,
	GeneralState_Free 				= 79,
	GeneralState_Marching_PVP 		= 80,
	GeneralState_Marching_PVE 		= 81,
	GeneralState_Marching_Reinforcement = 82, 
	GeneralState_Marching_Wait 		= 83,
	GeneralState_Reinforcement_Saty = 84,
	GeneralState_Waiting_Battle 	= 85,
	GeneralState_Battle 			= 86,
	GeneralState_Dead   			= 87,
	GeneralState_Reliving 			= 88,
	GeneralState_Learning 			= 89,
	BattleReportNoBattleHero 		= 90, 	--没有英雄参加战斗
	MailMsgRequset					= 91,
	DispatchUnSetSoldier			= 92, --未配置兵种 
	DispatchSoldierLimit			= 93, --兵力不足 
	DispatchGenCountLimit			= 94, --最多可带%s个武将出征
	AttackWinWithAlliance 			= 95,	--进攻(%s)%s胜利	
	AttackLostWithAlliance 			= 96,	--进攻(%s)%s失败	
	DefenceWinWithAlliance 			= 97,	--防守(%s)%s胜利	
	DefenceLostWithAlliance 		= 98,	--防守(%s)%s失败	
	
	COMBAT_PROP_HPMAX				= 140,
	COMBAT_PROP_BODY_FORCE_MAX 		= 141,
	COMBAT_PROP_SOLDIER_COUNT 		= 142,
	COMBAT_PROP_BODY_FORCE			= 143,
	COMBAT_PROP_PHY_ATTACK 			= 144,
	COMBAT_PROP_MANA_ATTACK 		= 145,
	COMBAT_PROP_PHY_DEF 			= 146,
	COMBAT_PROP_MANA_DEF 			= 147,
	COMBAT_PROP_BLOOD				= 148,
	COMBAT_PROP_BLOCK				= 149,
	COMBAT_PROP_RESIST				= 150,
	COMBAT_PROP_CRIT				= 151,
	COMBAT_PROP_ATTACK_SPEED  		= 152,
	COMBAT_PROP_HATRED				= 153,
	COMBAT_PROP_PYH_PENETRATE 		= 154,
	COMBAT_PROP_MAGIC_PENETRATE 	= 155,
	COMBAT_PROP_SWORD				= 156,
	COMBAT_PROP_INTELLIGENCE 		= 157,
	COMBAT_PROP_CONTROL				= 158,
	COMBAT_PROP_SPEED				= 159,
	COMBAT_PROP_GENERAL_LEVEL 		= 160,
	EQUIP_CATEGORY_ARMORS 			= 161,	--盔甲 
	EQUIP_CATEGORY_ARMS 			= 162,	--武器
	EQUIP_CATEGORY_ORNAMENTS 		= 163,	--饰品
	CONFIRM_FINISH					= 164,
	CONFIRM_OPEN_SLOT				= 165,
	CHANGE_EQUIP					= 166,	--换装备
	CHANGE_SOLDIER_TYPE				= 167,	--换兵种
	ALTER_SOLDIER_COUNT				= 168,	--修改士兵数量
	GENERAL_UP_LEVEL				= 169,	--升级
	GENERAL_UP_STAR					= 170,	--升星
	GENERAL_OPT_ERROR_TIP			= 171,  --【英雄名】正在【状态】，无法【操作名】
    BATTLE_FIELD_ATTACKER           = 172,  --攻击方
    BATTLE_FIELD_DEFENCER           = 173,  --防守方
    BATTLE_FIELD_MYSELF             = 174,  --我方
    BATTLE_FIELD_ENEMY              = 175,  --敌方
    BATTLE_FIELD_MY_HERO_COUNT      = 176,  --我方英雄数量
    BATTLE_FIELD_ENEMY_HERO_COUNT   = 177,  --敌方英雄数量
    BATTLE_FIELD_ATTACK_HERO_COUNT  = 178,  --进攻方英雄数量
    BATTLE_FIELD_DEFENCE_HERO_COUNT = 179,  --防守方英雄数量
    BATTLE_FIELD_HERO_STATE_FIGHTING = 180, --交战中
    BATTLE_FIELD_HERO_STATE_WAITING  = 181, --等待中
	EQUIP_STATE_HAS					 = 182, --已装备
	EQUIP_STATE_HAVING				 = 183, --装备中
	
	AttackMonsterInfoWin			 = 200, --打怪 xxx lv.xxx 胜利
	AttackMonsterInfoLost			 = 201, --打怪 xxx lv.xxx 失败

	MarchOpErr 					 	 = 202, 
	MarchOpFull						 = 203,
	MarchOpChangeFormationFailed     = 204,
	MarchOpScoutLimit				 = 205,
	MarchOpMonsterInvalid			 = 206,
	MarchOpMonsterLevelErr			 = 207,

	RELIVE_GENERAL_NOT_ENOUGH_DIAMOND = 208,
	RELIVE_GENERAL_NOT_ITEM_COOLDOWN  = 209,
	
	FirstMonsterKillTip				  = 210,
	QuickFind						  = 211,
	AttackTip						  = 212,
	
	WAITING_RELIVE = 213,
	RELIVE_POINT_MAX_COUNT = 214,
	RELIVE_POINT_RECOVERY_TIP = 215,
	
	GENERAL_SKILL_RATE_INFO = 216,
	GENERAL_PASSIVITY_SKILL = 217,
	GENERAL_PASSIVITY_SKILL_UNLOCK_TEXT = 218,
	GENERAL_TIANFU_SKILL_UNLOCK_TEXT = 219,
	GENERAL_TIANFU_SKILL_INFO = 220,


	MARCH_TIPS_ATTACK = 221,
	MARCH_TIPS_CRUSADE = 222,
	MARCH_TIPS_SCOUT = 223,
	MARCH_TIPS_GATHER = 224,
	MARCH_TIPS_ATTACK_BACK = 225,
	MARCH_TIPS_CRUSADE_BACK = 226,
	MARCH_TIPS_WAIT_MARCH = 227,
	MARCH_TIPS_GATHING = 228,
	MARCH_TIPS_GATHER_BACK = 229,
	WORD_SPEEDUP = 230,
	WORD_LOOKOVER = 231,

	SpeedUpNoItem = 232,
	ArmySoliderNameCountInfo = 233,
	MARCH_TIPS_STAY = 234,
	SpeedUpOk						= 235,
	UI_HERO_DETAIL_1				= 236,	--<color=#ddd8d1ff>Lv.1加成效果：</color>
	UI_HERO_DETAIL_2				= 237,	--<color=#ffd25aff>当前加成效果：</color>
	UI_HERO_DETAIL_3				= 238,	--<color=#f53e2bff>该天赋镶嵌符文可以提升等级</color>
	UI_HERO_DETAIL_4				= 239,  --<color=#f53e2bff>已满级</color>
	UI_HERO_DETAIL_5				= 240,  --<color=#f53e2bff>%s 后可以免费重置</color>
	UI_HERO_DETAIL_6				= 241,  --<color=#ff0000ff>%s</color>	
	UI_HERO_DETAIL_7				= 242,  --已开启天赋技能 %s	
	
	
	UI_HERO_DETAIL_FUWEN_UNLOCK_TIP = 243,  --英雄等级达到%s级时开启
	MessageMultiPVPNoAlliance		= 244,  --没有联盟
	
	UI_HERO_DETAIL_8				= 245,  --镶嵌符文可以提升对应天赋的等级，天赋激活即可生效。
	SoldierRecruitOpenLevel			= 246,  --该兵种在兵营%d级时解锁
	
	GeneralState_Marching_Gather	= 247,
	GeneralState_Gathering			= 248,
	ZhuFangSettingAuto				= 249,	--
	EQUIP_WEAR_GENERAL_LEVEL_LOW	= 250,	--英雄等级过低，无法穿戴
	ZhuFangUnAutoFullSoldier		= 251,  --您的英雄将无法自动补充兵力
	ZhuFangAutoFullSoldier			= 252,  --您的英雄战斗结束后将自动补充兵力
	ZhuFangHeroCountZhan			= 253,	--当前拥有战士英雄:12
	ZhuFangHeroCountQi				= 254,	--当前拥有战士英雄:12
	ZhuFangHeroCountGong			= 255,	--当前拥有战士英雄:12
	ZhuFangHeroCountFa				= 256,	--当前拥有战士英雄:12
	KuangSmallNoHero				= 257,	--无
	
	UI_HERO_DETAIL_FUWEN_TIP 		= 258,	--<color=#FF9113FF>提示:</color>
	UI_HERO_DETAIL_FUWEN_1			= 259,  --<color=#f53e2bff>还未镶嵌符文</color>
	UI_HERO_DETAIL_FUWEN_2			= 260,  --<color=#f53e2bff>可以镶嵌类型</color>
	UI_FUWEN_TYPE_GREEN				= 261,	--<color=#7ed71fff>绿色符文</color>
	UI_FUWEN_TYPE_RED				= 262,  --<color=#7ed71fff>红色符文</color>
	UI_FUWEN_TYPE_BLUE				= 263,	--<color=#7ed71fff>蓝色符文</color>
	UI_FUWEN_XIEXIA					= 264,  --卸下
	UI_FUWEN_XIANGQIAN				= 265,  --镶嵌
	UI_FUWEN_TIHUAN					= 266,  --替换
	UI_FUWEN_XIANQIAN_USED			= 267,  --该符文正在被%s使用，是否进行镶嵌
	UI_FUWEN_XIEXIA_OPEN_SHOP		= 268,  --符文商店
	UI_FUWEN_KAIQI_TIAOJIAN			= 269,  --武将等级达到%d级开启
	
	UI_TILI_DRAW 					= 270,
	UI_TILI_BUY 					= 271,
	UI_TILI_BUY_LIMIT 				= 272,
	UI_TILI_DRAW_LIMIT 				= 273,
	UIDispatchHaveNoSoldier			= 274,  --所带兵种数量严重不足
	MessageKillCount				= 275, --消灭
	MessageLostCount				= 276, --损失
	MessageGetExp					= 277, --获得经验 
	MessageGetRongYu				= 278, --获得荣誉
	MessageGetJunGong				= 279, --获得军功 
	GENERAL_SKILL_NAME_TITLE 		= 280, --英雄详情技能名称
	GENERAL_SKILL_INFO_DETAILS 		= 281, --英雄详情技能描述

	ResAllFormat			 		= 282,
	ResProtectFormat			 	= 283,
	ResUnProtectFormat			 	= 284,
	ResSafeFormat			 		= 285,	
	ResSafeDesc				 		= 286,
	ResProtectDesc			 		= 287,
	ResUnProtectDesc			 	= 288,
	HospitalCureTime			 	= 289,
	HospitalDeleteSoldier			= 290,
	HospitalDeleteSoldierOk			= 291,
	HurtSoldierRecoverOk			= 292, --伤兵回复成功
	HomeOpenAreaLevelLimit			= 293,
	HomeOpenAreaOk					= 294,
	HospitalCapacity				= 295,
	HospitalCureLimit				= 296,
	BuildingLevelUpOk				= 297,
	BuildingCreateOk				= 298,
	PleaseInputRightCoords			= 299,
	HeroTalentOpenLvLimit			= 300,
	OpenArmyRecruitNoBuilding		= 301,
	MessageProduceTitle				= 302,
	MessageCollectionTitle			= 303,
	MessageInfoProduce				= 304,
	MessageInfoCollection			= 305,
	ProduceReportReasonAttack		= 306,
	ProduceReportReasonGiveUp		= 307,
	TargetNameFood					= 308,
	TargetNameWood					= 309,	
	TargetNameIron					= 310,
	TargetNameStone					= 311,
	UseMoneyComplete				= 312,
	PowerAddCount					= 313,
	TalentAddLimitNoPoint			= 314,
	TalentAddLimitUnLock			= 315,
	TalentAddLimitMutex				= 316,	
	EquipSuitCountEffect			= 317,
	OnKeyEquipWearOk				= 318,
	OnKeyEquipWearIsMostGood		= 319,
	WoodLand 						= 320, --伐木场
	FoodLand 						= 321, --农场
	StoneLand 						= 322, --采石
	IronLand 						= 323, --铁矿
	ResProduceCount					= 324, 
	SearchObjectLevel				= 325,
	SearchObjectNotFound			= 326,
	ChallengeFormat					= 327,
	PlayerLevelUp					= 328,
	HeroStarUpSkillInfo				= 329,
	DungeonAlreadPassed				= 330,
	HeroStarUpMaxStar				= 331,
	BuildingIsMaxLevel				= 332,
	eMsgCopySceneUnknow				= 333,
	eMsgCopySceneNOGeneralId        = 334,
	eMsgCopySceneNOSoldierId		= 335,
	eMsgCopySceneFewSoldierNum		= 336,
	eMsgCopySceneFewScenePoint		= 337,
	eMsgCopySceneNoCurrState		= 338,
	eMsgCopySceneMaxMarchNum		= 339,
	eMsgCopySceneMarchScnId			= 340,
	eMsgCopySceneMarchTime			= 341,
	eMsgCopySceneMarchMaxZone		= 342, 
	eMsgCopySceneMarchLockZone		= 343,
	eMsgCopySceneMarchHaveDo		= 344,
	eMsgCopySceneMarchLockScn		= 345,
	eMsgCopySceneMarchNoNum			= 346,
	eMsgCopySceneMarchHaveRandom	= 347,
	eMsgCopySceneMarchViewEnd		= 348,
	eMsgCopySceneMarchPreRandom		= 349,
	eBuildingLevelUpFree			= 350,
	MustSelectOneHeroTips			= 351,
	FuWenShopUnSellCurrent			= 352,
	FwShopTitleShopSelect			= 353,
	FwShopTitleShopSell				= 354,
	FwShopTitleShopBuy				= 355,
	FwShowSellNoValidSelect			= 356,
	Producing						= 357,
	MARCH_TIPS_OCCUPYMINE           = 358,
	MARCH_TIPS_OCCUPYMINE_BACK		= 359,
	eRaceType_Human		 			= 360,		--人族
	eRaceType_Orc 					= 361,	--兽族
	eRaceType_Elf 					= 362;		--精灵族
	eRaceType_Undead 				= 363,	--亡灵族
	eRaceType_Dwarf 				= 364,		--矮人
	eRaceType_Trolls 				= 365,	--巨魔
	eSoldier_Infantryinfo 			= 366,	--步兵
	eSoldier_Cavalry 				= 367,		--骑兵
	eSoldier_Archer 				= 368,			--弓箭手
	eSoldier_Master 				= 369,			--法师
	HeroResetTalentAskAgain			= 370,
	NetStatusIsNotGood				= 371,
	NetStopedPleaseCheck			= 372,
	LimitBuildingCreateUpMaxCount	= 373, --已达最大建筑数量
	LimitBuildingCreateUpMoney		= 374, 
	LimitBuildingCreateUpItem		= 375,
	LimitBuildingCreateUpBuildingLv	= 376,
	ChatAllianceChannelLink			= 377,--聊天跳转按钮
	ChatGroupChannelLink			= 378,--聊天跳转按钮
	ChatAllianceReminder			= 379,--联盟聊天频道提示
	ChatGroupReminder				= 380,--联盟聊天频道提示
	EnsureDiscardMine				= 381, --
	AttackerFormatName				= 382,
	DefenderFormatName				= 383,
	FightIsOver						= 384,
	Nothing							= 385,
	MissionHaveGotActivity			= 386,
	MissionDailyNoBoxLimit			= 387,
	MissionDailyBoxOverState		= 388,
	MissionHaveGotActivityWeek		= 389,
	MissionActivityWeekCanAward		= 390,
	MissionFinalDesc				= 391,
	MissionDailyDesc				= 392,
	MissionGrowthSubMissionTip		= 393,
	MissionGrowthFinalMissionTip	= 394,
	PowerSubCount					= 395,
	HeroLevelUpMaxLevel				= 396,
	HeroLevelUpCastleLimit			= 397,
	ArmyHallMaxSoldierCount			= 398,
	AllianceCostPoints				= 399,--消耗积分
	AllianceCostDiamond				= 400,--消耗钻石
	AllianceChairman     			= 401,--盟主
	AllianceBuilding				= 402,--建造
	AllianceUpgradge				= 403,--升级
	AllianceGoTo					= 404,
	AllianceRecruit					= 405,--招募
	AllianceTreatment				= 406,--治疗伤兵
	AllianceScientificResearch      = 407,--科研
	PromotionAwardGained 			= 408,--已领取
	AllianceBuildingFlagMax			= 409,--旗帜数量上限：%s,联盟等级到达Lv.%d+%d个旗子
	AllianceBuildingFlagNotUsed 	= 410,--当前空闲旗子
	AllianceBuilding   				= 411,--建造
	AllianceBuildingRecover   		= 412,--回收
	AllianceBuildingFlag    		= 413,--联盟旗帜
	CostAlliancePoints      		= 414,--是否消耗联盟积分
	CostDiamond    					= 415,--是否消耗钻石
	HeroLevelUpCastleLimitMax		= 416,
	DestoryAlliance  				= 417,--解散联盟
	LeaveAlliance          			= 418,--离开联盟	
	PromotionAwardPurchased 		= 419,--您已累计购买%s个
	PromotionAwardRepurchase		= 420,--再购买%s个,即可领取以下奖励
	PromotionRestTimerFormat		= 421,--%s天%02d:%02d:%02d
	LimitBuy		= 422,--限购%s
	PromotionAwardToComplete		= 423,--去完成
	PromotionAwardToGain			= 424,--领取
	SaleOff			= 425,--%sOFF
	EnsureAgainDefaultYes			= 426,
	EnsureAgainDefaultNo			= 427,
	eMarchOpRetType_MonsterNoPhy	= 428,
	eMarchOpRetType_PVE_MONSTER_NOT_CHAPTER_TASK = 429,
	eMarchOpRetType_SUPER_MINE_HAS_MARCH = 430,
	eMarchOpRetType_SUPER_MINE_NO_ALLIANCE = 431,
	eMarchOpRetType_SUPER_MINE_NO_ALLIANCE_RANGE = 432,
	GENERAL_GODEQUIP_SKILL_UNLOCK_TEXT = 433,
	GENERAL_GODEQUIP_SKILL_INFO 	= 434,
	AllFightValue 	                = 435,
	AllianceArena 					= 436,
	RewardScore					 	= 437,
	Score 						 	= 438,
	CurrentLevel					= 439,
	AllianceAllActivityPoints       = 440, --联盟总活跃点数
	PersonalActivityPoints          = 441, --(我提供了%s点)
	MaxActivityPoints               = 442, --你本周获得的活跃点上限：
	AllianceNotEnough               = 443, --联盟总活跃点数需要达到%s才能开启
	PersonalNotEnough               = 444, --个人联盟活跃点数需要达到%s才能开启
	HasReceived                     = 445, --已领取
	AllianceDutyChairman            = 446, --盟主	       	
	AllianceDutyDeputychairman1		= 447, --军事
	AllianceDutyDeputychairman2     = 448, --外交	
	AllianceDutyDeputychairman3   	= 449, --财政
	AllianceDutyDeputychairman4  	= 450, --大主教
	AllianceDutyOfficial         	= 451, --亲信	
	AllianceDutyElite           	= 452, --精英
	AllianceDutyWarrior         	= 453, --勇士
	AllianceDutyWorker              = 454, --成员	
	OpenBox						    = 455, 
	PutBox							= 456, 
	eMarchOpRetType_MINE_GATHER_NO_TASK	= 457,
	FunOpenLevelLimitFuben			= 458,
	FunOpenLevelLimitAlliance		= 459,
	DungeonChapterLockTips			= 460,
	FunOpenLevelLimitFriend			= 461,
	StoreNotOpen					= 462, --该商店未开启
	TextUse							= 463,
	TextBuyAndUse					= 464,
	InDecorating					= 465,
	TextDecorate					= 466,
	MainTower	 					= 467, --主城
	BuCamp 	 						= 468,
	QiCamp 	 						= 469,
	GongCamp 	 					= 470,
	FaCamp 	 						= 471,
	--WoodLand 	 					= 467, --有
	--FoodLand 	 					= 467, --有
	--StoneLand  	 				= 467, --有
	--IronLand  	 				= 467, --有
	GoldLand  	 					= 472,
	WarHall  	 					= 473,
	SpyTower 	 					= 474,
	Hospital  	 					= 475,
	Library 	 					= 476,
	EventHall  	 					= 477,
	DipHall  	 					= 478,
	Vendor 	 						= 479,
	WareHouse  	 					= 480,
	CityWall 	 					= 481,
	HomeBuildingCaptureLock			= 482,
	CastleLevel						= 483,
	CurrentAllianceName 			= 484,
	CurrentAllianceShortName		= 485,
	HomeCreateChapterLockEnsure		= 486,
	HomeCreateChapterLockNoEnsure	= 487,
	HomeBuildingUnLockTitle			= 488,
	Forever							= 489,
	AllianceKickMember				= 490,
	TryReconnectingTips				= 491,
	TryReconnectFailed				= 492,
	TryReconnectFailedAndCheckDeviceNetWork = 493,
	PurchaseStamp = 494,--%d点券
	FirstPurchaseExtra = 495,--首冲额外赠送%d钻石
	PurchaseExtra = 496,--额外赠送%d钻石
	PurchaseDiamond = 497,--%d钻石
	ChangeAllianceDuty      = 499,	--改变职位
	AllianceKick            = 500,	--逐出联盟
	AllianceSendMessage     = 501,	--发送信息
	AllianceAddFriend       = 502,	--添加好友
	eMarchOpRetType_MARCH_CAPACITY = 503,
	AllianceKickMember      = 504, --成员逐出联盟 文字提示
	CreateAllianceEvent		= 505, --创建了联盟
	AllianceKickEvent		= 506, --踢出成员
	JoinAllianceEvent1		= 507, --同意加入
	JoinAllianceEvent2      = 508, --离开联盟
	LeaveAllianceEvent      = 509, --离开联盟
	FunctionNoOpen			= 510,
	PromotionCurrency		= 511,--￥%s	
	PrivilegeCardStateOff	= 512,--未激活
	PrivilegeCardStateOn	= 513,--剩余%s天
	PrivilegePurchase		= 514,--购买
	PrivilegeRenew			= 515,--续费
	SoldierFireHurtFirstTips 		=516,
	HeroPanelSortByLevel			= 517,
	HeroPanelSortByQuality			= 518,
	HeroPanelSortByFightValue		= 519,
	FirstRechargeRedirect			= 520,--前往
	FirstRechargeGain				= 521,--领取
	MarchTime                       = 522,
	TreasureFullDesc                = 523,
	apply							= 524,
	applied							= 525,
	GrowthFundPurchased 			= 526,--已购买
	PlayerBoxFullNotify 			= 527,--宝箱位已满，无法获得奖励
	MissionTarget					= 528,--任务目标
	HasContribution					= 529,--
	CurrentMissionProgress			= 530,--当前任务进度
	BuildingLimitGotoSubTip			= 531; --
	BuildingLimitGotoYes			= 532; --
	BuildingLimitGotoNo				= 533; --
	AllianceTaskConditionNotEnough  = 534,--联盟任务开启条件为联盟人数大于等于20人
	SpeedUpTimeFormat 				= 535,
	ArmyHallAll 					= 536,--总览
	ArmyHallWarrior					= 537,--战
	ArmyHallKnight					= 538,--骑
	ArmyHallAttack					= 539,--攻
	ArmyHallMagic					= 540,--法
	EnsureConvert = 541, --确认兑换?
	EnsureSell = 542, --您出售的物品中含有高品质装备,确定要出售吗?
	LvString=543, --Lv.%d
	LimitString=544, --(%d/%d)
	DungeonLockByTaskChapter = 545,
	HomeCampUnLockNewSoldierTitle	= 546,
	ArmyHallHurtSoldierCount 		= 547,--受伤士兵
	SkillTypeMain					= 548,
	SkillTypePassive				= 549,
	SkillTypeNormal					= 550,
	BuildResTypeProduce				= 551,
	BuildResTypeSave				= 552,
	WeiwangLv = 553, --威望Lv%d
	WeiwangUnLockLv = 554, --威望%d解锁
	PrivilegeCardRenewFail 			= 555,--续费失败，超过最大续费天数
	ChatWordDeficient				= 556,--请输入内容
	ChatGroupLocked 				= 557,--队伍功能尚未开启
	HeroHasBeenKilled               = 558,--该英雄已死亡
	NoHero  						= 559,--无空闲武将
	Studying						= 560,--当前%d人正在研究:
	HasSkillCount					= 561,--持有数量
	AllianceLevelUnLock				= 562,--联盟%d级解锁
	WeiwangOneKeyLevel 				= 563,--你即将一键升级至<color=#b7e23a>威望%d</color>
	WeiwangOneKeyExp 				= 564,--购买<color=#f34432>%d</color>威望补足？
	NameIsNull						= 565,--名字空缺
	JunShiTitle = 566, --军事标题
	ZiYuanTitle = 567, --资源标题
	NeiZhengTitle = 568, --内政标题
	SpeedUpUseItemCount 			= 569,
	HomeDragGoldLandNoMonthCard		= 570,
	HomeDragGoldLandWithMonthCard   = 571,
	HomeDragTipsChapterLimit	    = 572,
	TechnologyNeedSchoolLv	    = 573, --%d级书院解锁该科技
	PreTechnologyConStr1	    = 574, --and
	PreTechnologyConStr2	    = 575, --or
	TechnologyLiJiWanCheng	    = 576, --立即完成
	LeagueAlliance   			    = 577,
	FriendAlliance                  = 578,
	EnemyAlliance					= 579,
	ApplyAlliance                   = 580,
	HadRelieveAllianceRelation1     = 581,
	Chinese							= 582,
	English							= 583,
	HadBuildAllianceRelation        = 584,
	LeagueAllianceMessage           = 585,
	HaveItem 						= 586,
	BeginnerQuestReminder			= 587,
	BuildingQueueIdle				= 588,
	BuildingQueueHaveTime			= 589,
	BuildingQueueLeaveTimeUnEnough	= 590,
	BuildingQueueUnActiveState		= 591,
	BuildingQueueNeedItem			= 592,
	BuildingQueueUseItemOk			= 593,
	RefreshTip = 594,--当前存在超值商品, 是否继续刷新?
	BoxRefreshTip = 595,--当前商品包含 钻石宝箱 继续刷新有几率失去该宝箱 是否继续刷新?
	BuildingQueueAskUseItem			= 596,
	BuildingQueueIsFull				= 597,
	DeleteMailHaveAwardEnsure		= 598,
	DeleteMailHaveAwardGetAward		= 599,
	DeleteMailHaveAwardDel			= 600,
	BuildingInfoTitle			= 601,--%s Lv.%d
   	MainDetail_OccupyNum			= 602,
	MainDetail_CreateSpeed			= 603,
	HomeDragCampIsIdle				= 604,
	WhiteColorStr				= 605,--<color=#FFFFFF>%s</color>
	RedColorStr				= 606,--<color=#FF0000FF>%s</color>
	ActivationPYX                   = 607, --已激活神器
	NoActivationPYX                 = 608, --激活神器
	CityWallMaxDefence				= 609,
	CityWallBurnLeaveTime			= 610,
	HeroPxyOpenLvLimit				= 611,
	HeroFuWenOpenLvLimit			= 612,
	RecruitOkTips					= 613,
	RecruitOkPowerAdd				= 614,
	HeroStarUpFragLimit				= 615,
	GetItemBoxFull					= 616,
	PromotionSignPrestige 			= 617,
	PromotionSignSup 				= 618,
	PromotionSignedDay 				= 619,
	PromotionSignedAwardPrestige 	= 620,
	PromotionSignedAwardDay 		= 621,
	MoneyNotEnoughTip 				= 622,
	ItemNotEnoughTip 				= 623,
	SoldierFullNoSoldier			= 624,
	PromotionSignSupButton 			= 625,
	SpeedUpSuccess					= 626,
	PromotionSignSupStart			= 627,
	MoreAlliance                    = 628,
	MilitaryLvStr                   = 629,
	SuperMinesMaxCount              = 630,--联盟超级总矿数量：
	SuperMinesCanUse				= 631,--可采集：
	ExhaustedCount    				= 632,--枯竭中：
	SuperMinesPlayerMax             = 633,--采集人数已满：
	SnatchingCount					= 634,--抢夺中：
	CurrentSuperMinesPlayer			= 635,--当前采集部队
	SuperMinesRemain				= 636,--资源剩余量 
	ItIsNull                        = 637,--空缺
	ThisAllianceIsNotFound			= 638,--未搜索到该联盟
	AllianceListIsRefresh			= 639,--联盟列表已更新
	GuideMissionIsRunning			= 640, --引导任务进行中
	CityWallRecoverTime				= 641,
	CityWallBurnDesc				= 642,
	CityWallOutFileUseMoneyEnsure	= 643,
	CityWallRecoverUseMoneyEnsure	= 644,
	GoldLandStateReNew				= 645,
	GoldLandStateActive				= 646,
	GoldLandDetailProduce			= 647,
	GoldLandDetailStorage			= 648,
	GrowthFundTitleFirst			= 649,--购买可获得
	GrowthFundTitleOther 			= 650,--需要城堡等级%s
	GoldLandActiveSelectCount		= 651,
	GoldLandActiveAddTime			= 652,
	ColorNameWhite					= 653,--白色
	ColorNameGreen					= 654,
	ColorNameBlue					= 655,
	ColorNamePurple					= 656,
	ColorNameOrange					= 657,
	PromotionSignAwardGain			= 658,--领取奖励
	CityWallRecoverSpeed			= 659,
	XunBaoRiZhi	=660,--%d %d 发现了%dX%s
	GatherMineOK					= 661,
	GatherMineCDError				= 662,
	DiamondNotEnough				= 663,
	AttackAllianceMemberError		= 664,
	DiamondResMineMaxCountError		= 665,
	TimerMarchTimeError				= 666,
	PhyCanDrawTip					= 667,
	PhyDrawRecoverIng				= 668,
	PhyDrawCountOver				= 669,
	PhyDrawOk						= 670,
	PhyBuyOk						= 671,
	PhyDrawOkInfo					= 672,
	PhyBuyOkInfo					= 673,
	PhyFreeDrawCountFmt				= 674,
	PhyBuyCountFmt					= 675,
	MARCH_TIPS_HOLD_BUILD			= 676,
	MARCH_TIPS_HOLD_BUILD_BACK		= 677,
	CastlePosChanged				= 678,
	WareUseUseFmtCount				= 679,
	WareUseShareTips				= 680,
	WareItemUseCountFmt				= 681,
	UseBagPhyItemOk					= 682,
	BoxRecords						= 683,
	WeiWangExp	=684,--威望经验:%d / %d
	FuWenShopBuyTitle				= 685,
	FuWenShopSellTitle				= 686,
	SellFuWenEnsure					= 687,
	EnsureCommonDefaultYes			= 688,
	CancelCommon					= 689,
	EnsureCommon					= 690,
	Activity                        = 691,--活跃
	Contribution                    = 692,--捐献
    Recharge                        = 693,--充值	
	AllianceMemberActivity          = 694,--每位联盟内成员日活跃到
    GetAllianceActivity             = 695,--获得	
	ActivityExp                     = 696,--点经验
	AllianceMemberRecharge          = 697,--联盟内任意成员每充值--
	GetRecharge                     = 698,--点券获得
    RechargeExp                     = 699,--点经验	
	AllianceExpContribution         = 700,--联盟经验贡献
	ContributionExp                 = 701,--贡献经验
	DiamondRank                     = 702,--钻石消耗排行榜
	CostDiamondCount                = 703,--消耗钻石数量
	WeekActivityRank                = 704,--本周活跃排行
	ActivityPoints                  = 705,--活跃点数
	RemarksNoNil					= 706,--备注不能为空
	RemarksToLong					= 707,--备注需要在1-20个字符之间
	CollectSuccessful				= 708,--收藏成功
	HuntLog	=709,--%s %s 发现了%sX%d
	HuntNum	=710,--探索%d次
	HuntResultNow	=711,--立即完成本次寻访
	SelectHero	=712,--请先选择一个英雄
	SearchTen	=713,--立即完成%d次探索
	eMsgCopySceneMarchOccupy	=714,--未占领该关卡
	eMsgCopySceneMarchHunting	=715,--已有寻访
	eMsgCopySceneMarchGeneralState	=716,--寻访，武将非空闲状态
	eMsgCopySceneMarchHuntDiamond	=717,--寻访，钻石不足
	eMsgCopySceneMarchHuntNoItem	=718,--寻访兑换，没有物品
	eMsgCopySceneMarchHuntConDia	=719,--寻访兑换，钻石不足
	eMsgCopySceneMarchHuntState	=720,--寻访兑换，状态不对
	TecDescJunShi	=721,--提升军事科技可有效的增强部队的作战能力
	TecDescNeiZheng	=722,--提升内政科技可使您的城堡发展胜人一筹
	TecDescZiYuan	=723,--提升资源科技可大大提高资源的生产效率
	UseDiamondToolItemOk			= 724,
	RecruitSoldier	        = 725,	--招募士兵
	CollectResources	    = 726,	--采集资源	
	KillMonsters	        = 727,	--击杀野怪
	CurrentAllianceLevel	= 728,	--当前联盟等级：;

	GongFangTitle	=729,--废弃的战争工坊
	GongGangDesc	=730,--这里曾经是神匠们为侍奉的领主打造终极武器的工坊，如今已经荒废了数年，进行探索也许会有所发现，要试试看吗？
	XianZheTitle	=731,--没落的贤者之塔
	XianZheDesc	=732,--这里曾经是贤者们为侍奉的领主研究强力符文的场所，如今看起来已经没落了，进行探索也许会有所发现，要试试看吗?
	BuyPhysicalEnsureTip			 = 733,
	BuyResetTalentEnsureTip			 = 734,
	SelectHeroDes	=735,--请选择英雄进行探索!
	Hunting	=736,--探索中
	GiveupHunt	=737,--是否放弃本次寻宝
	GeneralState_Hunt	=738,--寻宝中
	GiveupReward	=739,--放弃会获得%sX%d,确定要放弃吗?
	ResGatherUnHave					=740,
	GoldLandGatherOverTime			=741,
	ResGatherSmallOk				=742,
	WareStoreNoExistResPackage		=743,
	WareStoreOneKeyFullEnsure		=744,
	CityWallDefenceOk				=745,
	CityWallDefenceRecovering		=746,
	CityWallDefenceBurning			=747,

	JoinAlliance                    = 748, --加入了联盟
	KickMember                      = 749, --%s 踢出成员%s 
	LeaceAlliance                   = 750, --%s 离开联盟
	ChangeDuty                      = 751, --%s的职位从%s变为%s
	BuildLeagueRelation             = 752, --我盟和%s建立同盟关系
	BuildFriendRelation             = 753, --我盟和%s建立友盟关系
	BuildEnemyRelation              = 754, --我盟和%s建立敌盟关系
	UnfriendLeague                  = 755, --我盟和%s同盟关系解除
	UnfriendFriend                  = 756, --我盟和%s友盟关系解除
	UnfriendEnemy                   = 757, --我盟和%s敌盟关系解除
	MainBuffBuyAndUse 				= 758, --购买使用
	DefeatCanHunt	=759,--击败守卫可探索宝物
	CanHunt	=760,--可以开始探索宝物了
	HuntingWaitSecond	=761,--正在探索宝物,还需%s秒
	ViewHuntResult	=762,--已探索到宝物,快来看看
	stateCanHunt	=763,--可探索
	stateHunting	=764,--探索中
	stateReward	=765,--完成
	RecruitArmyHallFull				= 766, --军事大厅满了
	AllianceContribution            = 767, --联盟捐献
	ResetTalentUseMoney				= 768,
	writecorrectnametips			= 769,
	writecorrectnametips_toolong	= 770,
	writecorrectnametips_tooshort	= 771,
	TransPointName					= 772,
	GetCountdownTimer				= 773,
	CanGetFree						= 774,
	FubenTiliIsFull					= 775,
	GetFubenTiliSuccess				= 776,
	GetFubenTiliTimeError			= 777,
	FubenTiliBuyFull				= 778,
	MarchError_TargetHasShied		= 779,
	ScoutError_TargetHasFog			= 780,
	TransferChairman						= 781, --是否转让盟主
	NewDuty									= 782, --是否改变职位为%s
	ItsUnLockedWhenAllianceMemberCountOver  = 783, --联盟人数达到%d人解锁
	MailDeleteHaveReWard			= 784,
	ImpeachSuccess							= 785, --弹劾成功
	ContinueFight	=786,--继续闯关
	MARCH_TIPS_Reinforcement		= 787,
	MARCH_TIPS_Reinforcement_back	= 788,
	PrivilegeCardAwardDesc 			= 789,
	ServerTimeFormat				= 790,
	LocalTimeFormat					= 791,
	MarchTimeFormat					= 792,
	EarlyReachTimeFormat			= 793,
	SetArriveTimeUseGoldEnsure		= 794,
	AllianceJoinRequirements        = 795, --申请条件
	AllianceNoNeedCheck				= 796, --无申请条件
	AllianceJoinCastleLevel			= 797, --城堡等级
	AllianceJoinMilitaryLevel  		= 798, --军衔等级
	WareUseShareTipsFillUseMoney	= 799,
	AllianceLevelUnLock             = 800, --联盟等级达到%d级解锁
	StringLimitation 				= 801, --超过最大字数%s 
	OpenBoxGuideNoBox				= 802, --没有可以开启的宝箱
	SuperMinesTips					= 803,
	COMBAT_PROP_SKILLRATE			= 804,	--技能概率
	COMBAT_PROP_REFLECT				= 805,	--反射伤害
	COMBAT_PROP_CRITDAMAGE			= 806,	--暴击伤害
	COMBAT_PROP_EX_PYH_PENETRATE	= 807,	--额外破甲
	COMBAT_PROP_EX_MAGIC_PENETRATE	= 808,	--额外穿透
	COMBAT_PROP_EX_BLOCK			= 809,	--额外格档
	COMBAT_PROP_EX_RESIST			= 810,	--额外抵抗
	COMBAT_PROP_EX_CRIT				= 811,	--额外暴击率
	AllianceDefenseOpenFunction		= 812,	--是否消耗%s联盟积分开启保护?
	AllianceDefenseClearCD			= 813,  --是否消耗%s点券清除CD?
	LeaveAllianceTips               = 814,  --您已离开联盟
	UseMoneyTimeMarch				= 815, 	--用于定时出征
	TimeMarchTimeLimit				= 816, --
	TimeMarchTimeReSet				= 817,
	TimeMarchTimeEnsure				= 818,
	AllianceBuildingDefense         = 819,  --防御值
	SkillReleaseSuccessful          = 820, --释放技能成功
	PutOnFire					    = 821, --灭火？
	RecoveryAllianceBuilding        = 822, --恢复城防？
	BuildAllianceRelation           = 823, --向<color=#ffe58c>%s</color>，发起同盟申请
	MainBuffDetailConfirm 			= 824, --购买并使用该道具
	MARCH_TIPS_RESTRANSPORT			= 825,
	StoreMilitaryRankLimit			= 826,--军衔达到%s可购买
	CreateCharNameExist 			= 827,
	UnknownError					= 828,
	NoFreeHero						= 829,--没有空闲英雄
	MessageInfoProduceGot			= 830,
	NotEnoughStamp	                = 831,--点券不足	
	LogoutQuestion 					= 832,--是否退出登陆
	ChangeSucced 					= 833,--修改成功
	NotJoinAllianceYet 				= 834,--尚未加入联盟
	ConsumeGainReminder 			= 835,--s后可领取
	PurchaseSucced 					= 836,--购买成功
	AllianceSetChangedSuccessfully	= 837,--修改成功
	AskProtectWhenMarch				= 838,
	ProtectTimeShow					= 839,
	AskProtectWhenCastleLevelup		= 840,
	MainBuffUseSucced				= 841,--使用%s成功
	MainBuffReplaceSucced			= 842,--【%s】已成功替换为【%s】
	MainBuffLastTo 					= 843,--【%s】已经成功延长至【%s】
	AttrTipsSword					= 844,--力量
	AttrTipsIntelligence			= 845,--智力
	AttrTipsSpeed					= 846,--速度
	AttrTipsControl					= 847,--统御
	MarchTypeMineAttack				= 848,--进攻采集单位
	MarchTypeSuperMineAttack		= 849,--进攻超级矿
	MarchTypeAllianceBuildingAttack	= 850,--进攻联盟建筑
	AllianceMemberPhyAtk	        = 851,--联盟成员的物攻
	AllianceMemberMagicAtk	        = 852,--联盟成员的法攻
	AllianceMemberPhyDef	        = 853,--联盟成员的物防
	AllianceMemberMagicDef	        = 854,--联盟成员的法防
	HuntRewardOverData				= 855,--宝物已过期,详情请查看邮件
	LimitBuildingCreateUpMaxCountNextStep = 856,
	HaveBuildingNumber				= 857,
	eGeneralState_AllianceStudy     = 858,--研究技能
	MoveCityCastleLevelError		= 859,
	NoGeneralsCanStudy              = 860, --没有武将可以研究
	HasActivated                    = 861,--已激活(神器)
	NoInRank                        = 862,--未上榜
	AllianceMemberHelpsYou          = 863,--%d公里外的%s帮助了您
	PromotionExchangeCount			= 864,--兑换次数
	PromotionExchangeDesc			= 865,--活动兑换说明
	ArmyBackNoticeStr 				= 881, --后边的要从881开始,前边的用了.	
	ClientVersionTooOld				= 882,
	ObjectTypeBuildings				= 883, --城堡
	ObjectTypeResMine				= 884, --资源田
	ObjectTypeSuperMineFood			= 885, --超级农庄
	ObjectTypeSuperMineWood			= 886, --超级伐木场
	ObjectTypeSuperMineIron			= 887, --超级铁矿
	ObjectTypeSuperMineStone		= 888, --超级石场
	ObjectTypeSuperAllianceBuilding	= 889, --联盟建筑
	Target7Task						= 890, --七日描述
	NoSchoolLv	=901,--学院等级不足
	NoPreTec	=902,--前置科技未达成
	NoTecPoint	=903,--科技点不足
	NoWood	=904,--木材不足
	NoIron	=905,--钢铁不足
	NoFood	=906,--粮食不足
	NoStone	=907,--石材不足
	FmtCityDef						= 908,
	FmtAllPower						= 909,
	MailResMineCanGet				= 910,
	MailMarkReadAll					= 911,
	MailMarkGetAwardAll				= 912,
	MailDeleteNoMail				= 913,
	MailTypeTimeLimit				= 914,
	InvalidString					= 915,
	MailTypeResMineReportWin		= 916,
	MailTypeResMineReportLost		= 917,
	MailTypeResMineReportInfo		= 918,
	
	WorldBossOnlyOne				= 927, --同时只能攻击一个世界boss
	ResMinePlayerLvToLow			= 928, --领主不低于%d级
	SuperMineAllianceLvToLow		= 929, --联盟等级不低于%d级
	ResMineMaxCountError			= 930, --占领的资源矿达到上限
	MaxMarchCountError				= 931, --行军数量达到上限
	ResSuperMineMaxCountError		= 932, --采集的超级矿达到上限

	MarchNum_SuperMine 				= 933,
	MarchNum_Mine                   = 934,
	MarchNum_March                  = 935,

	AllianceShieldOpen              = 936,	--开启要塞保护
	AllianceShieldHasClear          = 937,	--要塞CD已清除

	ImpeachTitle                    = 938,	--弹劾盟主
	AllianceGradeAWardTitle         = 939,	--联盟评级奖励
	AllianceTaskAwardTitle          = 940,  --联盟任务奖励
	AllianceSkillAwardTitle         = 941,	--联盟技能研究奖励
	TargetLostTitle                 = 942,  --目标消失
	AllianceInviteTitle             = 943,  --联盟邀请
	AllianceLeagueReplyTitle        = 944,  --同盟关系变更
	AllianceLeagueRelieveReplyTitle = 945,	--同盟解除申请
	eMailType_AllianceImpeachRemindContent    = 946,	--%s小时后开始弹劾盟主%s
	eMailType_AllianceImpeachStartContent     = 947,	--弹劾盟主申请新盟主，到%s结束
	eMailType_AllianceImpeachSuccessContent   = 948,	--弹劾成功,盟主从%s变为%s
	eMailType_AllianceImpeachInterruptContent = 949,	--弹劾盟主中断,盟主为%s
	eMailType_AlliacneImpeachNoApplyContent   = 950,	--弹劾盟主无人申请
	eMailType_AllianceGradeAwardContent       = 951,	--经过大家不懈的努力，联盟评级达到Lv.%d！
	eMailType_AllianceTaskAwardContent        = 952,	--恭喜！您的联盟完成任务%s！(outline重复使用)
	eMailType_AllianceSkillAwardContent       = 953,	--联盟技能%s研究已完成！(outline重复使用)
	TargetLostStr1Content = 954, --您攻击的目标已逃之夭夭，您的出征部队即将返回
	TargetLostStr2Content = 955, --您攻击的目标已消失，您的出征部队即将返回
	TargetLostStr3Content = 956, --您攻击的目标已被其他领主率先击杀，您的出征部队即将返回。本次消耗的体力已全部返还
	TargetLostStr4Content = 957, --您采集的目标已消失，您的出征部队即将返回
	TargetLostStr5Content = 958, --您行军目标已消失，您的出征部队即将返回
	eMailType_AllianceInviteContent              = 959,	 --%s邀请你加入%s联盟	(outline重复使用)
	eMailType_AllianceGradeAwardOutline          = 960,	 --恭喜！联盟评级达到Lv.%d！
	eMailType_AllianceLeagueReplyOutline         = 961,	 --%s联盟的盟主%s已处理与我盟的关系
	eMailType_AllianceLeagueRelieveOutline       = 962,	 --%s的%s申请与我盟解除同盟关系，等待审核！
	eMailType_AllianceLeagueRelieveReplyOutline  = 963,	 --%s的%s已处理与我盟的同盟关系
	eMailType_AllianceLeagueReply1Content        = 964,	 --%s联盟的盟主%s与我盟结为同盟，从此共同发展，共谋大业;
    eMailType_AllianceLeagueReply2Content        = 965,	 --%s联盟的盟主%s不同意和我盟建立同盟关系	
	eMailType_AllianceLeagueOverTimeContent      = 966,	 --申请%s联盟同盟关系超时
	eMailType_AllianceLeagueRelieveContent       = 967,	 --%s联盟的盟主%s申请与我盟解除同盟关系，等待审核！(outline重复使用)
	eMailType_AllianceLeagueRelieveReply1Content = 968,	 --%s联盟的盟主%s同意和我盟解除同盟关系
	eMailType_AllianceLeagueRelieveReply2Content = 969,	 --%s联盟的盟主%s不同意和我盟解除同盟关系
		
	AtkPowerRecord 		 =970,--战力统计
	BuildingAtkPower 	 =971,--建筑战力
	TechAtkPower 		 =972,--科技战力
	ArmyAtkPower 		 =973,--部队战力
	MillitaryRankAtkPower=974,--军衔战力
	ArmyRecord 			=975,--部队统计
	IndieBattleHeroLimit=976,--单队列出征英雄上限
	DefenceHeroLimit 	=977,--驻守英雄上限
	MarchCount 			=978,--行军队列数量
	FieldSourceCount	=979,--野外资源队列数量
	SuperGatherCount	=980,--超级采集队列数量
	OwnedHeroLimit 		=981,--拥有英雄数量
	OwnedSoldierCount	=982,--拥有士兵数量上限
	ChurchCapacity 		=983,--教堂容量
	SourceRecord		=984,--资源统计
	SourceGather		=985,--资源采集
	AllianceAssistCount	=986,--联盟帮助次数
	BattleRecord 		=987,--战斗统计
	HighestAtkPower 	=988,--历史最高战力
	BattleVictoryCount	=989,--战斗胜利次数
	BattleFailedCount 	=990,--战斗失败次数
	DeadSoldierCount  	=991,--阵亡士兵数量
	SpyCount 			=992,--侦查次数

	AllianceImpeachRemindTitle					 = 993,  --弹劾盟主提醒
	AllianceImpeachStartTitle 					 = 994,  --弹劾盟主开始	
 	AllianceImpeachSuccessTitle					 = 995,  --弹劾盟主成功	
	AllianceImpeachInterruptTitle				 = 996,  --弹劾盟主中断	
	AlliacneImpeachNoApplyTitle      			 = 997,  --弹劾盟主无人申请	
	eMailType_AllianceImpeachRemindOutline       = 998,  --由于盟主%s长时间未登陆，将要弹劾盟主	
    eMailType_AllianceImpeachStartOutline        = 999,  --开始弹劾盟主	
	eMailType_AllianceImpeachSuccessOutline      = 1000,  --弹劾盟主成功,盟主由%s变为%s	
	eMailType_AllianceImpeachInterruptOutline    = 1001,  --弹劾盟主中断,盟主是%s	
	eMailType_AlliacneImpeachNoApplyOutline      = 1002,  --弹劾盟主无人申请	
	NowTecLevel	=1003,--当前等级
	NextTecLevel	=1004,--下一等级
	NotStudyTec	=1005,--暂未学习
	ArmyRecuritNumOneBatch = 1006,
	MailFmtResMineLeaveCount 						= 1007, --	剩余储量：33
	MailFmtRecruitSoldierTip						= 1008,
	MailTitleCopySceneReport						= 1009, --战役战报
	MailDetailCopySceneReport						= 1010,
	MailInfoFormatRoundCount						= 1011,
	MailInfoFormatSoldierAlive						= 1012,
	MailInfoFormatSoldierDie						= 1013,
	MailInfoFormatSoldierHurt						= 1014,
	MailInfoFormatSoldierLeave						= 1015,
	MailInfoFormatKillGenCount						= 1016,
	MailInfoFormatDieGenCount						= 1017,
	MailInfoFormatAllArmyPower						= 1018,
	MailTitleVipMail								= 1019,
	MailInfoVipMail									= 1020,
	MailTitleCopySceneHunt							= 1021,
	MailInfoCopySceneHunt							= 1022,
	MailDetailCopySceneHunt							= 1023,
	EnterGameTimeOutTips							= 1024,
	MailInfoSuperMineGather           			    = 1025,
	DoSkillTime 									= 1026, --	每天%s:%s-%s:%s可释放	
	MailInfoSuperMineGatherNoResult					= 1027,
	MailInfoResMineDetailInfoVictory  				= 1028,
	MailInfoResMineDetailInfoDefeat  				= 1029,
	MailInfoFormatSoldierKill						= 1030,
	LoginUserError									= 1031,
	LoginServerError								= 1032,
	LoginUserDataError								= 1033,
	LoginPlatformError								= 1034,
	UserNickNameError								= 1035,
	UserIdEmpty										= 1036,
	UserTokenEmpty									= 1037,
	LanguageError									= 1038,
	DeviceIdEmpty									= 1039,
	RequestServerListError							= 1040,
	EnterGameError									= 1041,
	RequestLoginResultError							= 1042,
	RequestLoginVerificationError					= 1043,
	RequestLoginAdditionalError						= 1044,
	LoginFailedAndTryAgain							= 1045,
	RequestServerListFailedAndTryAgain				= 1046,
	TryAgain                                        = 1047,
	ServerIdError									= 1048,
	ServerApiError									= 1049,
	PayResultProblem								= 1050,
	PayResultError									= 1051,
	RequestPurchaseError							= 1052,
	RequestPayResulEmpty							= 1053,
	RequestPayOrderEmpty							= 1054,
	RequestPayAdditionalEmpty						= 1055,
	GetLoginUsernameEmpty							= 1056,
	
	targetCastle = 1057,	--%s的城堡

	SkillReportInfo2  = 1058,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>,使我军在进攻该城堡时，会有一只强力援军加入我方部队同时对其进行攻击。持续24小时
	SkillReportInfo3  = 1059,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌盟<color=#f5ead7>%s%s</color>释放了技能<%s>,使我军在进攻该建筑时，会有一只强力援军加入我方部队同时对其进行攻击。持续24小时
	SkillReportInfo4  = 1060,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，共击杀敌军%d名士兵
	SkillReportInfo5  = 1061,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，共击杀敌军%d名士兵
	SkillReportInfo6  = 1062,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对我盟<color=#f5ead7>%s%s</color>释放了技能<%s>，使该建筑无法被敌方侦查。持续12小时
	SkillReportInfo7  = 1063,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，使敌军%s的部队落荒而逃
	SkillReportInfo8  = 1064,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，使敌军损失%s
	SkillReportInfo9  = 1065,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，使敌军城堡城防燃烧速度增加200%%。持续12小时
	SkillReportInfo10 = 1066,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，共毒杀敌军%d名伤兵
	SkillReportInfo11 = 1067,	--战场风云变幻莫测，%s<color=#f5ead7>%s</color>运筹帷幄，对敌军<color=#f5ead7>%s%s</color>释放了技能<%s>，共遣散敌军%d名士兵

	SkillInfoReportKillSoliders 		  = 1068,	--共击杀%d名士兵
	SkillInfoReportArmyRetreats 		  = 1069,	--共%d只部队撤退
	SkillInfoReportLostSoliders 		  = 1070,	--共损失%s名士兵
	SkillInfoReportkillWithPoisonSoliders = 1071,	--共毒杀%d名士兵
	SkillInfoReportDismissSoliders 		  = 1072,	--共遣散%d名士兵
	SkillInfoReportLostResources          = 1073,   --共损失%s
	TargetNameDiamond								= 1074, --大地图的钻石矿名,防止和家园的一样之后策划要改，其它大地图的都是TargetNameXXX
	AllianceNameTooLongToCreate = 1075,	--联盟名称应为4-14个字符	

	AllianceTaskAnyLevelMonster = 1076,	--任意等级	
	AllianceTaskMonsterLevel    = 1077, --%d等级	

	NoAllianceMemberHelp = 1078, --当前暂无盟友帮助
	UseBuffItemOk 		 = 1079, --使用xx道具成功
	HeroStarUpNeedLevel								= 1080,
	HeroStarUpNeedLevelLimit						= 1081,
	ConnectServerTimeOut = 1082,
	RequestErrorWithMessage = 1083,
	NetworkInaccessible = 1084,
	ReadServerListError = 1085,
	EnterGameErrorWithMessage = 1086,
	EnterGameTimeOut = 1087,
	CurGameVersion = 1088,
	MailScoutContentTipsMine						= 1089,
	HelpAllianceMember = 1090, --您帮助了%d个盟友,
	MainHall   = 1091,	--联盟主殿
	ShieldFort = 1092,	--庇护要塞
	ClawFort   = 1093,	--利爪要塞
	MagicFort  = 1094,	--秘法要塞
	BlackFort  = 1095,	--黑钢要塞
	SkillHasStudied = 1096, --技能研究结束	
	MailPvpWinAtAll					 	= 1097, --敌人一击即溃，毫无抵抗之力
	MailPvpLostAtAll					= 1098, --敌人过于强大，我军毫无还手之力
	InviteSuccessful 					= 1099, --邀请成功
	TwentyFourHoursAgo                  = 1100,	--24小时前
	AllianceBuildingFlagCount           = 1101, --旗帜数量上限：<color=#ecd3b2>%s</color>,联盟等级已到达Max	
	RecoveryBuildingTips                = 1102, --收回后，该建筑将失去现有效果，建筑将会在库存中显示，再次建造该建筑无需消耗联盟积分，但需等待建造时间	
	RecoveryBuildingName                = 1103, --是否收回%s	
	BoxTodayAllGetTips					= 1104,
	YouHaveNoEnoughPermissions          = 1105, --权限不足
	ProduceReportReasonAttackInfo		= 1106,
	IsImpeachChairman					= 1107,
	MyServer							= 1108,
	RecommendedServer					= 1109,
	SelectServer						= 1110,
	LastLogin							= 1111,
	ServerFull							= 1112,
	ServerSmooth						= 1113,
	ServerMaintain						= 1114,
	OccupyMinePlayerLevelError			= 1115,
	GatherSuperMineLevelError			= 1116,
	CountryName1						= 1117,
	CountryName2						= 1118,
	CountryName3						= 1119,
	CountryName4						= 1120,
	CountryName5						= 1121,
	CountryName6						= 1122,
	CountryName7						= 1123,
	TargetLostStr6Content               = 1124,	--您要驻守的建筑物已不在当前位置，您的出征部队即将返回	
	CityWallDefenceLimitTip				= 1125,
	SetCityWallDefenceOk				= 1126,
	CanNotFinishTheAllianceTask         = 1127,	--入盟24小时内无法完成联盟任务
	NotEnoughAllianceMembers1           = 1128,	--联盟成员不足%d人时无法完成任务
	DoNotDoAllianceTask                 = 1129,	--今日已完成任务上限	
	NotEnoughAllianceMembers2           = 1130,	--联盟成员不足%d人时无法刷新任务
	RefreshAllianceTask					= 1131,	--已完成当前任务，等待刷新！
	AllianceTaskExpired					= 1132,	--任务已过期
	Alliance_ApplyList 					= 1133, --查看申请列表
	Alliance_Join                       = 1134, --成员审核
	Alliance_KickMember                 = 1135,	--踢出成员
	Alliance_Invite  					= 1136,	--邀请成员
	Alliance_Destory 					= 1137,	--解散联盟
	Alliance_CreateFlag                 = 1138,	--创建联盟旗帜
	Alliance_CreateBuilding             = 1139,	--建筑联盟建筑
	Alliance_AlterName                  = 1140,	--修改联盟名字
	Alliance_Quit                       = 1141,	--退出联盟
	Alliance_AlterNotice                = 1142,	--修改联盟宣言
	Alliance_AlterFlag       			= 1143,	--修改联盟旗帜
	Alliance_AlterLanguage   			= 1144,	--修改联盟语言
	Alliance_AlterNeedCheck  			= 1145,	--修改招募设置
	Alliance_AlterDutyToOffucual        = 1146,	--副盟主到成员任命
	Alliance_AlterDutyToMainforce       = 1147,	--亲信到成员任命
	Alliance_SpendPoints     			= 1148,	--使用联盟积分
	Alliance_RecoverBuilding 			= 1149,	--回收联盟建筑
	Alliance_Skill     					= 1150,	--联盟技能
	Alliance_SetUpSign 					= 1151,	--联盟标记
	Alliance_Relation  					= 1152,	--处理联盟关系
	Alliance_BuildingEffect 			= 1153,	--联盟建筑物功能
	Alliance_SetChairMan    			= 1154,	--转让盟主
	Alliance_StartActivity 				= 1155,	--开启活动
	Alliance_OfferAward    				= 1156,	--发布联盟悬赏
	Alliance_AllMemberMail 				= 1157,	--联盟全员邮件
	Alliance__ImpeachChairman 		    = 1158,	--弹劾盟主
	AllianceMemberDes                   = 1159,	--联盟成员相关描述
	AllianceBuildingDes                 = 1160,	--联盟建筑相关描述	
	AllianceSkillDes           			= 1161,	--联盟技能相关描述	
	CanNotChoiceSameDuty  				= 1162,	--不能选择与之前相同的职位
	huntingInOtherScene					= 1163,--正在其他章节中,探索相同类型的宝藏
	GENERAL_OP_FUWEN_XIANGQIAN			= 1164,	--符文镶嵌
	GENERAL_OP_COMPOSITION_GODEQUIP		= 1165, --合成神器
	GENERAL_OP_TALENT_CHANGE			= 1166, --修改天赋
	RechargeNotTurnedOn					= 1167, --充值功能暂未开启
	RequestServerListFailed             = 1168, --请求服务器列表失败
	ChatSend 							= 1169, --发送
	ChatSendCount 						= 1170, --发送(%s)
	ChatSendSensitive 					= 1171, --发送失败，文字包含敏感词汇
	ServerHandShakeFailed  				= 1172, --服务器握手失败
	ServerHandShakeTimeout 				= 1173, --服务器握手超时	
	PlatformInitFailed					= 1174,	--平台初始化失败	
	PlatformInitCancel 					= 1175,	--平台初始化取消
	PlatformInitProcessing 				= 1176, --平台初始化进行中	
	PlatformLoginFailed 				= 1177, --平台登录失败
	PlatformLoginCancel 				= 1178, --平台登录取消
	PlatformLoginProcessing 			= 1179, --平台登录进行中
	PlatformLogoutFailed 				= 1180, --平台登出失败	
	PlatformLogoutCancel 				= 1181,	--平台登出取消
	PlatformLogoutProcessing 			= 1182, --平台登出进行中
	PlatformSwitchAccountFailed 		= 1183, --平台切换账号失败
	PlatformSwitchAccountCancel 		= 1184, --平台切换账号取消
	PlatformSwitchAccountProcessing 	= 1185, --平台切换账号进行中
	PlatformExitFailed 					= 1186, --平台退出失败
	PlatformExitCancel 					= 1187, --平台退出取消
	PlatformExitProcessing 				= 1188, --平台退出进行中
	PlatformPayFailed 					= 1189, --平台支付失败
	PlatformPayCancel 					= 1190, --平台支付取消
	PlatformPayProcessing 				= 1191, --平台支付进行中
	LookSpyTowerNoArmy					= 1192,
	MonstersLocation                    = 1193,	--领地归属：%s
	MonstersPower                       = 1194,	--守卫战斗力：%s	
	MonstersType                        = 1195,	--守卫兵种：%s	
	ContributionRemainCnt               = 1196,	--今日剩余捐献次数：%d
	ContributionMax                     = 1197,	--今日已达最大捐献次数
	ContributieSuccessful               = 1198,	--捐献成功！
	HadRelieveAllianceRelation2         = 1199,	--已解除友盟关系
	HadSendRelieveMessage               = 1200,	--已发送解除邮件	
	ExitGame							= 1201, --退出游戏
	ReturnGame							= 1202,--返回游戏
	ConfirmQuitGame						= 1203,	--确定退出游戏吗?
	CreateCharFailWithCode				= 1204, --创建角色失败
	ChatLevelLimit						= 1205, --领主等级需要大于10
	DayMilitaryRankMax					= 1206,--每日军工获取上限%s
	ExitForUpdateResTips 				= 1207,
	DispatchPhyLimit					= 1208, --出征体力不足
	DiamondLimitNeedExChange			= 1209, --钻石不足，请先兑换
	AllianceResourcesRecovery			= 1210,	--%s后恢复
	AllianceCityContributionCount		= 1211,	--今日可捐献次数：%s/%s	
	NotEnoughContribute 				= 1212,	--今日捐献次数不足	
	SetAllianceCityOfficerSuccessfully  = 1213,	--官职设置成功
	AllianceCityPowerValue				= 1214,	--势力值：%d
	MoreThanAllianceAllFightValue		= 1215,	--联盟总战力>%d
	AllianceCityLevel					= 1216,	--等级：%d
	HasOccupiedCityCount				= 1217,	--已占领城市 %d/%d
	HasGivenUpCity						= 1218,	--已放弃城市%s
	GoToCity							= 1219,	--是否前往城市?(坐标:%d,%d)
	AllianceCityHasStatrThatCantGiveUpCity = 1220,	--攻城战已开启，暂不可放弃！;
	AreYouSureToGiveUpAllianceCity		= 1221,	--是否确定要放弃当前城市?(攻城战开启期间不可放弃城市)
	OccupyAllianceCitySuccessfully		= 1222,	--众志成城！在全体联盟成员的努力下，成功占领 <color=#fd5f11>"..cityName.." ！</color>
	GatherSuperMinePlayerLevelLimit		= 1223,
	BossTitle							= 1224,--进攻Lv.%d%s
	BagGenFragHaveGen					= 1225,--已拥有此英雄
	HurtNumFmt							= 1226,--伤害：
	DispatchGenCountLimitSmallMine		= 1227,
	BattleEventCityWarDesc 				= 1228,--每周%s 服务器时间 %s-%s 开启
	AllianceMemberBlood                 = 1229,--联盟成员的血量	
	AllianceMemberBlock					= 1230,--联盟成员的格挡	
	AllianceMemberResist                = 1231,--联盟成员的抵抗	
	AllianceMemberCrit					= 1232,--联盟成员的暴击	
	AllianceMemberAttackSpeed           = 1233,--联盟成员的速度	
	AllianceMemberHatred 				= 1234,--联盟成员的仇恨	
	AllianceMemberPyhPenetrate          = 1235,--联盟成员的破甲	
	AllianceMemberMagicPenetrate        = 1236,--联盟成员的穿透
	ServerMaintained					= 1237,--服务器维护中

	MARCH_TIPS_MASS						= 1238,
	MARCH_TIPS_MASS_BACK			    = 1239,
	MARCH_TIPS_AttackMonsterMassing		= 1240,
	MarchSpeedUpRightsError				= 1241,

	CurrentAllianceCityProsperLv         = 1242,--当前城市繁荣度等级为 Lv.%d	
	AddAllianceCityProsper				 = 1243,--捐献成功，您获得了声望值%d点，城市繁荣度提升10点	
	ThisAllianceCityYouHaveProsperPoints = 1244,--您在本城市的声望值 : %d	
	AllianceCityGuanZhiBuff				 = 1245,--增益项：
	AllianceCityAttackBuff				 = 1246,--攻击
	AllianceCityDefenseBuff 			 = 1247,--防御	
	AllianceCityCritBuff				 = 1248,--暴击	
	AllianceCityPyhPenetrateBuff		 = 1249,--破甲
	AllianceCityMagicPenetrateBuff       = 1250,--穿透	
	CurrentAllianceCityProsperEffect     = 1251,--当前繁荣度效果:%d%
	AssembleFailDueToAlliance		     = 1252,--集结失败,尚未加入联盟
	AssembleParticipate 				 = 1253,--参与
	AssembleDismiss						 = 1254,--解散
	AssembleCancel						 = 1255,--召回
	AssembleRemove						 = 1256,--遣散
	AssembleLaunchSucced			     = 1257,--集结发起成功
	AssembleDepartSucced				 = 1258,--集结出发成功
	AssembleGetDetailFail				 = 1259,--获取详情失败
	AssembleDismissSucced			     = 1260,--解散成功
	AssembleRemoveSucced				 = 1261,--遣散成功
	AssembleRemoveFail				     = 1262,--遣散失败
	AssembleParticipateSucced			 = 1263,--参与成功
	DispatchGenCountLimitWildMonster	 = 1264,
	AllianceCityOccupyTitle				 = 1265, --联盟城市占领	
	AllianceCityOccupyContent			 = 1266, --我盟成功占领城市%s	
	AllianceCityLostTitle				 = 1267, --联盟城市失守	
	AllianceCityLostContent				 = 1268, --我盟的城市%s被其他联盟占领	
	TargetLostStr7Content				 = 1269, --攻城战已结束，您的出征部队已按原路返回	
	PromotionAccuCouponRechargeDesc 	 = 1270, --点券累充说明
	PromotionAccuCouponConsumeDesc 	 	 = 1271, --点券累消说明
	PromotionAccuDiamondConsumeDesc 	 = 1272, --钻石累消说明
	AccuCouponRechargeExchange 	 		 = 1273, --累计充值点券不足
	AccuCouponConsumeExchange 	 		 = 1274, --累计消费点券不足
	AccuDiamondConsumeExchange 			 = 1275, --累计消费钻石不足
	AccuCouponRechargeTitle 			 = 1276, --累计充值%s点券
	AccuCouponConsumeTitle 				 = 1277, --累计消费%s点券
	AccuDiamondConsumeTitle 			 = 1278, --累计消费%s钻石
	cityShengWangLimit 					 = 1279, --城市声望值不满足,差%d
	AccuExchangeSucced					 = 1280, --兑换成功
	MailInfoDragonMineGather             = 1281, --
	MailInfoDragonMineNoResult           = 1282, -- 
	ResDragonMineMaxCountError			 = 1283, --采集的龙矿数量达到上限
	DragonMinesTips						 = 1284, --
	DragonMinePlayerLevelLimit			 = 1285,
	DragonAllianceLevelLimit			 = 1286,
	AssembleFailDueToDiamond 			 = 1287,--集结失败,钻石不足
	AssembleFailDueToItem 			 	 = 1288,--集结失败,道具不足
	MailInfoDragonMineRob				 = 1289,
	MailInfoDragonMineRobNoResult		 = 1290,
	MarchTypeDragonMineAttack			 = 1291,
	MyAllianceBuildingBeAtkTitle 		 = 1292,--联盟遭受攻击
	MyAllianceBuildingBeAtkContent1		 = 1293,--我盟的%s遭受攻击
	MyAllianceBuildingBeAtkContent2		 = 1294,--我盟的%s(%d,%d)遭受攻击
	MyAllianceBuildingBeAtkContent3 	 = 1295,--我盟的%s(%d,%d)遭受敌盟%s的攻击
	PayOkWait							= 1296,
	AttackMonsterLevelLimit				= 1297,
	GlobalBossDesc						= 1298, --活动开启时间：每天%s（托维恩大陆时间)
	HeroCount							= 1299,	--英雄数量：%d
	SoliderCount						= 1300,	--士兵数量：%d
	AllianceMemberHelpCityCount			= 1301,	--援防人数：%d
	AllianceMemberSoliderCount			= 1302,	--援防士兵数：%d
	CannotEnterCity1					= 1303,	--该城市正在占领中，无法进入
	CannotEnterCity2					= 1304,	--该城市不属于您的联盟，无法进入
	CannotEnterCity3					= 1305,	--您还没有联盟，请先加入一个联盟
	SceneCityFuncNotOpen				= 1306,	--城市争夺战未开启，请查看规则说明
	FightValueNotEnough					= 1307,	--当前战斗力达到%d开启
	AssembleSettingLimitDesc			= 1308, --设置玩家自动出发的数量，当前可集结最大玩家数量为%s
	BuildingLibTecCompleteTips			= 1309,
	BuildingLibTecCompleteTipsMore		= 1310,
	AllianceCityOccupied				= 1311,	--归属：%s
	AllianceCityNoOccupy				= 1312,	--归属：中立
	AllianceCityEffect					= 1313,	--城市效果：%s
	MarchAllianceCityFailedThatNoAlliance 			   = 1314, --行军失败，需要加入一个联盟!
	MarchAllianceCityFailedThatAllianceCityHasOccupied = 1315, --行军失败，该城市已被占领!
	EnterGameEmpty						= 1316,	--EnterGameEmpty
	ArenaLogTitle 						= 1317, --挑战-%s%s-<color=#5ABC18>胜利</color>
	ArenaLogPointDesc 					= 1318, --获得积分:%d
	ArenaLogRankRisen 					= 1319, --排名上升至:%d(%s)
	ArenaLogRankUnChanged 				= 1320, --无排名变化
	AllianceCityAutoGiveUpTitle			= 1321,	--联盟城市自动放弃
	AllianceCityAutoGiveUpContent		= 1322,	--联盟城市已满，将自动放弃城市%s

	BuildingCampGuYong	=1323,--雇佣兵营
	humanJiban	=1324,--人类羁绊
	shourenJiBan	=1325,--兽人羁绊
	jinglingJiBan	=1326,--精灵羁绊
	wanglingJiBan	=1327,--亡灵羁绊
	bubingJiBan	=1328,--步兵羁绊
	qibingJiBan	=1329,--骑兵羁绊
	fashiJiBan	=1330,--法师羁绊
	gongjianshouJiBan	=1331,--弓箭手羁绊
	curJiBanLv	=1332,--当前等级: %d
	nextJiBanLv	=1333,--下一等级等级: %d
	JiBanLevelMax	=1334,--已满级
	JiBanWeiShengXiao	=1335,--尚未开启该羁绊
	JiBanLevelupFail	=1336,--羁绊升级失败
	ErrJiBanLevelMax	=1337,--羁绊已满级
	ErrJiBanItemNum	=1338,--羁绊升级所需道具不足
	JiBanLevelUpSuccess	=1339,--%s升级成功
	SevenDaySignName	=1340,--七日签到
	EveryDayRankName	=1341,--每日排行
	SignDataOver	=1342,--必须创建角色后的第%d天才能领取,已超时
	SignOverTime	=1343,--已超时
	SignUnlock	=1344,--未解锁
	SignGet	=1345,--领取
	SignNDay	=1346,--第%d天
	SignDesc	=1347,--每日上线即可领取奖励
	SevenDaySignTitle	=1348,--七日签到
	EveryDayTaskTitle	=1349,--每日排行
	EveryDayTaskRankMailTitle	=1350,--每日排行奖励
	EveryDayTaskRankMailInfo	=1351,--每日排行奖励
	ArenaRankMailTitle	=1352,--竞技场排行奖励
	ArenaRankMailInfo	=1353,--根据您在竞技场中的名次,获得了以下奖励
}
