-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- HeroCamp
HeroCamp = {
  XH = 1; -- 协会
  ZM = 2; -- 宗门
  SH = 3; -- 商会
  JT = 4; -- 集团
  ZZ = 5; -- 组织
}

-- HeroElement
HeroElement = {
  Water = 1; -- 水
  Fire = 2; -- 火
  Nature = 3; -- 自然
  Light = 4; -- 光
  Dark = 5; -- 暗
  None = 0; -- 无
}

-- HeroJob
HeroJob = {
  None = 0; -- 无
  ZS = 1; -- 战士
  FS = 2; -- 法师
  YX = 3; -- 游侠
}

-- HeroQuality
HeroQuality = {
  R = 1;
  SR = 2;
  SSR = 3;
  UR = 4;
}

-- HeroSkillAction
HeroSkillAction = {
  Damage = 1; -- 造成伤害
  Grow = 2; -- 提升成长资质
  Module = 3; -- 提升系统产出
}

-- ItemType
ItemType = {
  Resource = 1; -- 资源
  Prop = 2; -- 道具
  Card = 3; -- 卡牌
  Gift = 4; -- 礼包
  Task = 5; -- 任务
}

-- Quality
Quality = {
  Q1 = 1; -- Q1
  Q2 = 2; -- Q2
  Q3 = 3; -- Q3
  Q4 = 4;
  Q5 = 5;
}

-- StageItemType
StageItemType = {
  Item = 1; -- 道具
  EggMachine = 2; -- 扭蛋机
  Ring = 3; -- 擂台
  JumpTo = 4; -- 跳转
  Act = 5; -- 活动
  BuffBuilding = 6; -- Buff建筑
  Prickle = 7; -- 地刺
  Slide = 8; -- 滑道
  Portal = 9; -- 传送门
  DiceTrap = 10; -- 骰子陷阱
  Bomb = 11; -- 炸弹
  God = 12; -- 神灵
  Fight = 13; -- 战斗
  RandomEvent = 14; -- 随机事件
  Dream = 15; -- 梦境
  Boss = 16; -- Boss
  TurnTo = 17; -- 转向
  Treasure = 18; -- 宝箱
  WorldBoss = 19; -- 世界Boss
  Bkb = 20; -- Bkb
}


