-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Global= {
  [1001]={ID=1001,Value={5,5,4,3,6,6,6,},},
  [1002]={ID=1002,Value={35,80,100,},},
  [1003]={ID=1003,Value={1001,7,1002,10,},},
  [1004]={ID=1004,Value={56642535,},},
  [1005]={ID=1005,Value={300,},},
  [1006]={ID=1006,Value={3,},},
  [1007]={ID=1007,Value={50,},},
}

-- export table: Global
return Global
