-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local StorageDefault = {Mode=1,Share=false,Type=3,}
local Storage= {
  [1]={ID=1,Key="SETTING",Share=true,},
  [2]={ID=2,Key="HOME_BUILDING",},
  [3]={ID=3,Key="HOME_DATA",},
  [4]={ID=4,Key="LOGIN_MEMORY",Share=true,},
  [5]={ID=5,Key="FIGHT_LINEUP",},
  [6]={ID=6,Key="WORLD_BOSS",},
  [7]={ID=7,Key="GM",Share=true,},
  [8]={ID=8,Key="FIGHT_DATA",},
  [9]={ID=9,Key="SAVE_TIME",Type=2,},
  [10]={ID=10,Key="AD",},
  [11]={ID=11,Key="CHARACTER_MANAGER",},
}
for k,v in pairs(Storage) do
    setmetatable(v, {['__index'] = StorageDefault})
end

-- export table: Storage
return Storage
