return {
    [1] = {
        ["id"] = 1,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?color=blue',
        ["weight"] = 93,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'high_chance',
        ["unlock_zone_id"] = '',
    },
    [2] = {
        ["id"] = 2,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?color=purple',
        ["weight"] = 7,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'high_chance',
        ["unlock_zone_id"] = '',
    },
    [3] = {
        ["id"] = 3,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?color=purple',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'high_chance_guarantee',
        ["unlock_zone_id"] = '',
    },
    [4] = {
        ["id"] = 4,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [5] = {
        ["id"] = 5,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=3',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [6] = {
        ["id"] = 6,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=6',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [7] = {
        ["id"] = 7,
        ["city_id"] = 3,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=2',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [8] = {
        ["id"] = 8,
        ["city_id"] = 3,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [9] = {
        ["id"] = 9,
        ["city_id"] = 4,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=7',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [10] = {
        ["id"] = 10,
        ["city_id"] = 4,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=11',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [11] = {
        ["id"] = 11,
        ["city_id"] = 4,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=13',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [12] = {
        ["id"] = 12,
        ["city_id"] = 5,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=5',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [13] = {
        ["id"] = 13,
        ["city_id"] = 6,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=15',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [14] = {
        ["id"] = 14,
        ["city_id"] = 6,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=12',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [15] = {
        ["id"] = 15,
        ["city_id"] = 6,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=4',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [16] = {
        ["id"] = 16,
        ["city_id"] = 6,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=8',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [17] = {
        ["id"] = 17,
        ["city_id"] = 6,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance_new',
        ["unlock_zone_id"] = '',
    },
    [18] = {
        ["id"] = 18,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=10',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [19] = {
        ["id"] = 19,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=2',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [20] = {
        ["id"] = 20,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=4',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [21] = {
        ["id"] = 21,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=6',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [22] = {
        ["id"] = 22,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItem*2?id=Gem',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [23] = {
        ["id"] = 23,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=3',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [24] = {
        ["id"] = 24,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItem*2?id=Gem',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [25] = {
        ["id"] = 25,
        ["city_id"] = 2,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItem*2?id=Gem',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [26] = {
        ["id"] = 26,
        ["city_id"] = 3,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=12',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [27] = {
        ["id"] = 27,
        ["city_id"] = 3,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=15',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [28] = {
        ["id"] = 28,
        ["city_id"] = 3,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItem*2?id=Gem',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [29] = {
        ["id"] = 29,
        ["city_id"] = 10,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=8',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [30] = {
        ["id"] = 30,
        ["city_id"] = 13,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=13',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [31] = {
        ["id"] = 31,
        ["city_id"] = 4,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 10,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'street_chance',
        ["unlock_zone_id"] = '',
    },
    [32] = {
        ["id"] = 32,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?color=blue',
        ["weight"] = 9,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'free_chance',
        ["unlock_zone_id"] = '',
    },
    [33] = {
        ["id"] = 33,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToCard*1?color=purple',
        ["weight"] = 1,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'free_chance',
        ["unlock_zone_id"] = '',
    },
    [34] = {
        ["id"] = 34,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToOverTime*600?id=Heart',
        ["weight"] = 500,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'free_chance',
        ["unlock_zone_id"] = '',
    },
    [35] = {
        ["id"] = 35,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItem*10?id=Gem',
        ["weight"] = 20,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'free_chance',
        ["unlock_zone_id"] = '',
    },
    [36] = {
        ["id"] = 36,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItemOverTime*600?guarantee=1',
        ["weight"] = 1000,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'free_chance',
        ["unlock_zone_id"] = '',
    },
    [37] = {
        ["id"] = 37,
        ["city_id"] = 1,
        ["city_end_id"] = 99,
        ["reward"] = 'addToItemOverTime*60?guarantee=1',
        ["weight"] = 1,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'random_resource',
        ["unlock_zone_id"] = '',
    },
    [38] = {
        ["id"] = 38,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=12',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = 'C2_CollectionStation_1',
    },
    [39] = {
        ["id"] = 39,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = 'C2_Carpentry_1',
    },
    [40] = {
        ["id"] = 40,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=4',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [41] = {
        ["id"] = 41,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=3',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [42] = {
        ["id"] = 42,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=6',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [43] = {
        ["id"] = 43,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=15',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [44] = {
        ["id"] = 44,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=2',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [45] = {
        ["id"] = 45,
        ["city_id"] = 5,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=10',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [46] = {
        ["id"] = 46,
        ["city_id"] = 6,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=7',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [47] = {
        ["id"] = 47,
        ["city_id"] = 7,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=1',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [48] = {
        ["id"] = 48,
        ["city_id"] = 8,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=5',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [49] = {
        ["id"] = 49,
        ["city_id"] = 9,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=24',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [50] = {
        ["id"] = 50,
        ["city_id"] = 10,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=8',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [51] = {
        ["id"] = 51,
        ["city_id"] = 13,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=13',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [52] = {
        ["id"] = 52,
        ["city_id"] = 16,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=11',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_purple',
        ["unlock_zone_id"] = '',
    },
    [53] = {
        ["id"] = 53,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=12',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = 'C2_CollectionStation_1',
    },
    [54] = {
        ["id"] = 54,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = 'C2_Carpentry_1',
    },
    [55] = {
        ["id"] = 55,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=4',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [56] = {
        ["id"] = 56,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=3',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [57] = {
        ["id"] = 57,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=6',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [58] = {
        ["id"] = 58,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=15',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [59] = {
        ["id"] = 59,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=2',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [60] = {
        ["id"] = 60,
        ["city_id"] = 5,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=10',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [61] = {
        ["id"] = 61,
        ["city_id"] = 6,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=7',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [62] = {
        ["id"] = 62,
        ["city_id"] = 7,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=1',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [63] = {
        ["id"] = 63,
        ["city_id"] = 8,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=5',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [64] = {
        ["id"] = 64,
        ["city_id"] = 9,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=24',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [65] = {
        ["id"] = 65,
        ["city_id"] = 10,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=8',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [66] = {
        ["id"] = 66,
        ["city_id"] = 13,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=13',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [67] = {
        ["id"] = 67,
        ["city_id"] = 16,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=11',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [68] = {
        ["id"] = 68,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [69] = {
        ["id"] = 69,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [70] = {
        ["id"] = 70,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [71] = {
        ["id"] = 71,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [72] = {
        ["id"] = 72,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [73] = {
        ["id"] = 73,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [74] = {
        ["id"] = 74,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [75] = {
        ["id"] = 75,
        ["city_id"] = 5,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [76] = {
        ["id"] = 76,
        ["city_id"] = 6,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [77] = {
        ["id"] = 77,
        ["city_id"] = 7,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [78] = {
        ["id"] = 78,
        ["city_id"] = 8,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [79] = {
        ["id"] = 79,
        ["city_id"] = 9,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [80] = {
        ["id"] = 80,
        ["city_id"] = 10,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [81] = {
        ["id"] = 81,
        ["city_id"] = 13,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [82] = {
        ["id"] = 82,
        ["city_id"] = 16,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 900,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_purple_10',
        ["unlock_zone_id"] = '',
    },
    [83] = {
        ["id"] = 83,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=21',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = '',
    },
    [84] = {
        ["id"] = 84,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=19',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = 'C2_CoalMine_1',
    },
    [85] = {
        ["id"] = 85,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=23',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = 'C2_Metal_1',
    },
    [86] = {
        ["id"] = 86,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=20',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = 'C2_Carpentry2_1',
    },
    [87] = {
        ["id"] = 87,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=9',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = 'C2_Infirmary_1',
    },
    [88] = {
        ["id"] = 88,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=16',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = '',
    },
    [89] = {
        ["id"] = 89,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=18',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = '',
    },
    [90] = {
        ["id"] = 90,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=17',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = 'C3_Watchtower_1',
    },
    [91] = {
        ["id"] = 91,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=22',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue',
        ["unlock_zone_id"] = '',
    },
    [92] = {
        ["id"] = 92,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=21',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [93] = {
        ["id"] = 93,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=19',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = 'C2_CoalMine_1',
    },
    [94] = {
        ["id"] = 94,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=23',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = 'C2_Metal_1',
    },
    [95] = {
        ["id"] = 95,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=20',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = 'C2_Carpentry2_1',
    },
    [96] = {
        ["id"] = 96,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=9',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = 'C2_Infirmary_1',
    },
    [97] = {
        ["id"] = 97,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=16',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [98] = {
        ["id"] = 98,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=18',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [99] = {
        ["id"] = 99,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=17',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = 'C3_Watchtower_1',
    },
    [100] = {
        ["id"] = 100,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=22',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [101] = {
        ["id"] = 101,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [102] = {
        ["id"] = 102,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [103] = {
        ["id"] = 103,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [104] = {
        ["id"] = 104,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [105] = {
        ["id"] = 105,
        ["city_id"] = 2,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [106] = {
        ["id"] = 106,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [107] = {
        ["id"] = 107,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [108] = {
        ["id"] = 108,
        ["city_id"] = 3,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [109] = {
        ["id"] = 109,
        ["city_id"] = 4,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blue_50',
        ["unlock_zone_id"] = '',
    },
    [110] = {
        ["id"] = 110,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100201',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = '',
    },
    [111] = {
        ["id"] = 111,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100202',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = 'C1002_OysterFarm_1',
    },
    [112] = {
        ["id"] = 112,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100203',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = 'C1002_CrabFarm_1',
    },
    [113] = {
        ["id"] = 113,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100204',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = 'C1002_LobsterFarm_1',
    },
    [114] = {
        ["id"] = 114,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100205',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = 'C1002_SardineFarm_1',
    },
    [115] = {
        ["id"] = 115,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100206',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = 'C1002_TunaFarm_1',
    },
    [116] = {
        ["id"] = 116,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100207',
        ["weight"] = 100,
        ["weight_fix_card"] = 40,
        ["chance_group"] = 'event1002_chance_purple',
        ["unlock_zone_id"] = 'C1002_SeafoodFactory_1',
    },
    [117] = {
        ["id"] = 117,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100201',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = '',
    },
    [118] = {
        ["id"] = 118,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100202',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_OysterFarm_1',
    },
    [119] = {
        ["id"] = 119,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100203',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_CrabFarm_1',
    },
    [120] = {
        ["id"] = 120,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100204',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_LobsterFarm_1',
    },
    [121] = {
        ["id"] = 121,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100205',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_SardineFarm_1',
    },
    [122] = {
        ["id"] = 122,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100206',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_TunaFarm_1',
    },
    [123] = {
        ["id"] = 123,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100207',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_SeafoodFactory_1',
    },
    [124] = {
        ["id"] = 124,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = '',
    },
    [125] = {
        ["id"] = 125,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_OysterFarm_1',
    },
    [126] = {
        ["id"] = 126,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_CrabFarm_1',
    },
    [127] = {
        ["id"] = 127,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_LobsterFarm_1',
    },
    [128] = {
        ["id"] = 128,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_SardineFarm_1',
    },
    [129] = {
        ["id"] = 129,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_TunaFarm_1',
    },
    [130] = {
        ["id"] = 130,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 300,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_purple_25',
        ["unlock_zone_id"] = 'C1002_SeafoodFactory_1',
    },
    [131] = {
        ["id"] = 131,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100251',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'event1002_chance_orange',
        ["unlock_zone_id"] = '',
    },
    [132] = {
        ["id"] = 132,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100252',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'event1002_chance_orange',
        ["unlock_zone_id"] = '',
    },
    [133] = {
        ["id"] = 133,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100253',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'event1002_chance_orange',
        ["unlock_zone_id"] = '',
    },
    [134] = {
        ["id"] = 134,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100254',
        ["weight"] = 100,
        ["weight_fix_card"] = 20,
        ["chance_group"] = 'event1002_chance_orange',
        ["unlock_zone_id"] = '',
    },
    [135] = {
        ["id"] = 135,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100251',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_50',
        ["unlock_zone_id"] = '',
    },
    [136] = {
        ["id"] = 136,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100252',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_50',
        ["unlock_zone_id"] = '',
    },
    [137] = {
        ["id"] = 137,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100253',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_50',
        ["unlock_zone_id"] = '',
    },
    [138] = {
        ["id"] = 138,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100254',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_50',
        ["unlock_zone_id"] = '',
    },
    [139] = {
        ["id"] = 139,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 400,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_50',
        ["unlock_zone_id"] = '',
    },
    [140] = {
        ["id"] = 140,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100251',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_10',
        ["unlock_zone_id"] = '',
    },
    [141] = {
        ["id"] = 141,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100252',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_10',
        ["unlock_zone_id"] = '',
    },
    [142] = {
        ["id"] = 142,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100253',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_10',
        ["unlock_zone_id"] = '',
    },
    [143] = {
        ["id"] = 143,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100254',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_10',
        ["unlock_zone_id"] = '',
    },
    [144] = {
        ["id"] = 144,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = '',
        ["weight"] = 3600,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_orange_10',
        ["unlock_zone_id"] = '',
    },
    [145] = {
        ["id"] = 145,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToItem*1?id=BlackCoin1002',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_blackcoin',
        ["unlock_zone_id"] = '',
    },
    [146] = {
        ["id"] = 146,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToOverTime*60?id=Cash1002&guarantee=1',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_cash',
        ["unlock_zone_id"] = '',
    },
    [147] = {
        ["id"] = 147,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToOverTime*60?id=Heart1002&guarantee=1',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'event1002_chance_heart',
        ["unlock_zone_id"] = '',
    },
    [148] = {
        ["id"] = 148,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToItem*1?id=BlackCoin',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blackcoin',
        ["unlock_zone_id"] = '',
    },
    [149] = {
        ["id"] = 149,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToItem*1?id=BlackCoin',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blackcoin_half',
        ["unlock_zone_id"] = '',
    },
    [150] = {
        ["id"] = 150,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = '',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_blackcoin_half',
        ["unlock_zone_id"] = '',
    },
    [151] = {
        ["id"] = 151,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToOverTime*60?id=Heart&guarantee=1',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_heart',
        ["unlock_zone_id"] = '',
    },
    [152] = {
        ["id"] = 152,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToItem*1300?id=Heart',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_heart_19',
        ["unlock_zone_id"] = '',
    },
    [153] = {
        ["id"] = 153,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=1',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_1',
        ["unlock_zone_id"] = '',
    },
    [154] = {
        ["id"] = 154,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=2',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_2',
        ["unlock_zone_id"] = '',
    },
    [155] = {
        ["id"] = 155,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=3',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_3',
        ["unlock_zone_id"] = '',
    },
    [156] = {
        ["id"] = 156,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=4',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_4',
        ["unlock_zone_id"] = '',
    },
    [157] = {
        ["id"] = 157,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=5',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_5',
        ["unlock_zone_id"] = '',
    },
    [158] = {
        ["id"] = 158,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=6',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_6',
        ["unlock_zone_id"] = '',
    },
    [159] = {
        ["id"] = 159,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=7',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_7',
        ["unlock_zone_id"] = '',
    },
    [160] = {
        ["id"] = 160,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=8',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_8',
        ["unlock_zone_id"] = '',
    },
    [161] = {
        ["id"] = 161,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=9',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_9',
        ["unlock_zone_id"] = '',
    },
    [162] = {
        ["id"] = 162,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=10',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_10',
        ["unlock_zone_id"] = '',
    },
    [163] = {
        ["id"] = 163,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=21',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_11',
        ["unlock_zone_id"] = '',
    },
    [164] = {
        ["id"] = 164,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=12',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_12',
        ["unlock_zone_id"] = 'C2_CollectionStation_1',
    },
    [165] = {
        ["id"] = 165,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=21',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_13',
        ["unlock_zone_id"] = '',
    },
    [166] = {
        ["id"] = 166,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=14',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_14',
        ["unlock_zone_id"] = '',
    },
    [167] = {
        ["id"] = 167,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=15',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_15',
        ["unlock_zone_id"] = '',
    },
    [168] = {
        ["id"] = 168,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=16',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_16',
        ["unlock_zone_id"] = '',
    },
    [169] = {
        ["id"] = 169,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=17',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_17',
        ["unlock_zone_id"] = '',
    },
    [170] = {
        ["id"] = 170,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=18',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_18',
        ["unlock_zone_id"] = '',
    },
    [171] = {
        ["id"] = 171,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=19',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_19',
        ["unlock_zone_id"] = '',
    },
    [172] = {
        ["id"] = 172,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=20',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_20',
        ["unlock_zone_id"] = '',
    },
    [173] = {
        ["id"] = 173,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=21',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_21',
        ["unlock_zone_id"] = '',
    },
    [174] = {
        ["id"] = 174,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=22',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_22',
        ["unlock_zone_id"] = '',
    },
    [175] = {
        ["id"] = 175,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=23',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_23',
        ["unlock_zone_id"] = '',
    },
    [176] = {
        ["id"] = 176,
        ["city_id"] = 1,
        ["city_end_id"] = 999,
        ["reward"] = 'addToCard*1?id=24',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_24',
        ["unlock_zone_id"] = '',
    },
    [177] = {
        ["id"] = 177,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100201',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100201',
        ["unlock_zone_id"] = '',
    },
    [178] = {
        ["id"] = 178,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100202',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100202',
        ["unlock_zone_id"] = '',
    },
    [179] = {
        ["id"] = 179,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100203',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100203',
        ["unlock_zone_id"] = '',
    },
    [180] = {
        ["id"] = 180,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100204',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100204',
        ["unlock_zone_id"] = '',
    },
    [181] = {
        ["id"] = 181,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100205',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100205',
        ["unlock_zone_id"] = '',
    },
    [182] = {
        ["id"] = 182,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100206',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100206',
        ["unlock_zone_id"] = '',
    },
    [183] = {
        ["id"] = 183,
        ["city_id"] = 1002,
        ["city_end_id"] = 1002,
        ["reward"] = 'addToCard*1?id=100207',
        ["weight"] = 100,
        ["weight_fix_card"] = 0,
        ["chance_group"] = 'chance_card_100207',
        ["unlock_zone_id"] = '',
    },
}
