return {
    ["high_box_C1_1"] = {
        ["id"] = "high_box_C1_1",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 1,
        ["reward"] = "addToCard*1?id=19",
        ["sort"] = 1,
    },
    ["high_box_C1_10"] = {
        ["id"] = "high_box_C1_10",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 10,
        ["reward"] = "addToCard*1?id=18",
        ["sort"] = 10,
    },
    ["high_box_C1_11"] = {
        ["id"] = "high_box_C1_11",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 11,
        ["reward"] = "addToCard*1?id=17",
        ["sort"] = 11,
    },
    ["high_box_C1_2"] = {
        ["id"] = "high_box_C1_2",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 2,
        ["reward"] = "addToCard*1?id=21",
        ["sort"] = 2,
    },
    ["high_box_C1_3"] = {
        ["id"] = "high_box_C1_3",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 3,
        ["reward"] = "addToCard*1?id=12",
        ["sort"] = 3,
    },
    ["high_box_C1_4"] = {
        ["id"] = "high_box_C1_4",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 4,
        ["reward"] = "addToCard*1?id=9",
        ["sort"] = 4,
    },
    ["high_box_C1_5"] = {
        ["id"] = "high_box_C1_5",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 5,
        ["reward"] = "addToCard*1?id=14",
        ["sort"] = 5,
    },
    ["high_box_C1_6"] = {
        ["id"] = "high_box_C1_6",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 6,
        ["reward"] = "addToCard*1?id=23",
        ["sort"] = 6,
    },
    ["high_box_C1_7"] = {
        ["id"] = "high_box_C1_7",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 7,
        ["reward"] = "addToCard*1?id=16",
        ["sort"] = 7,
    },
    ["high_box_C1_8"] = {
        ["id"] = "high_box_C1_8",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 8,
        ["reward"] = "addToCard*1?id=19",
        ["sort"] = 8,
    },
    ["high_box_C1_9"] = {
        ["id"] = "high_box_C1_9",
        ["box_id"] = "high_box",
        ["cityId_end"] = 99,
        ["cityId_start"] = 1,
        ["city_id"] = 1,
        ["index"] = 9,
        ["reward"] = "addToCard*1?id=20",
        ["sort"] = 9,
    },
}
