return {
    ["cook_pizza"] = {
        ["id"] = "cook_pizza",
        ["alert"] = "ui_card_not_assign_tips_cook",
        ["assign_desc_tips"] = "assign_desc_increase_speed",
        ["boost_effects"] = {
            0.4,
            0.45,
            0.5,
            0.55,
            0.6,
            0.65,
            0.7,
            0.75,
            0.8,
            0.85,
            0.9,
            0.95,
            1,
            1.05,
            1.1,
            1.15,
            1.2,
            1.25,
            1.3,
            1.35,
            1.4,
            1.45,
            1.5,
            1.55,
            1.6,
            1.65,
            1.7,
            1.75,
            1.8,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
            ["item_id"] = "FoodPizza",
        },
        ["boost_type"] = "INCREASE_COOK_SPEED",
        ["desc"] = "desc_skill_cook_pizza",
        ["effect_icon_1"] = "effect_icon_food_recipe",
        ["effect_icon_2"] = "effect_icon_increase_speed",
        ["effect_icon_tip1"] = "effect_tooltip_food_recipe",
        ["effect_icon_tip2"] = "effect_tooltip_increase_speed",
        ["icon"] = "icon_skill_cook_pizza",
        ["item_icon"] = "FoodSushi",
        ["logic_name"] = "IncreaseCookSpeed",
        ["name"] = "name_skill_cook_pizza",
        ["scope"] = "City",
    },
    ["cook_sushi"] = {
        ["id"] = "cook_sushi",
        ["alert"] = "ui_card_not_assign_tips_cook",
        ["assign_desc_tips"] = "assign_desc_increase_speed",
        ["boost_effects"] = {
            0.1,
            0.15,
            0.2,
            0.25,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
            ["item_id"] = "FoodSushi",
        },
        ["boost_type"] = "INCREASE_COOK_SPEED",
        ["desc"] = "desc_skill_cook_sushi",
        ["effect_icon_1"] = "effect_icon_food_recipe",
        ["effect_icon_2"] = "effect_icon_increase_speed",
        ["effect_icon_tip1"] = "effect_tooltip_food_recipe",
        ["effect_icon_tip2"] = "effect_tooltip_increase_speed",
        ["icon"] = "icon_skill_cook_sushi",
        ["item_icon"] = "FoodSushi",
        ["logic_name"] = "IncreaseCookSpeed",
        ["name"] = "name_skill_cook_sushi",
        ["scope"] = "City",
    },
    ["cook_taco"] = {
        ["id"] = "cook_taco",
        ["alert"] = "ui_card_not_assign_tips_cook",
        ["assign_desc_tips"] = "assign_desc_increase_speed",
        ["boost_effects"] = {
            0.1,
            0.15,
            0.2,
            0.25,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
            ["item_id"] = "FoodTaco",
        },
        ["boost_type"] = "INCREASE_COOK_SPEED",
        ["desc"] = "desc_skill_cook_taco",
        ["effect_icon_1"] = "effect_icon_food_recipe",
        ["effect_icon_2"] = "effect_icon_increase_speed",
        ["effect_icon_tip1"] = "effect_tooltip_food_recipe",
        ["effect_icon_tip2"] = "effect_tooltip_increase_speed",
        ["icon"] = "icon_skill_cook_taco",
        ["item_icon"] = "FoodSushi",
        ["logic_name"] = "IncreaseCookSpeed",
        ["name"] = "name_skill_cook_taco",
        ["scope"] = "City",
    },
    ["generator_energy_blue"] = {
        ["id"] = "generator_energy_blue",
        ["alert"] = "ui_card_not_assign_tips_coal_master",
        ["assign_desc_tips"] = "assign_desc_decrease_gen_cost",
        ["boost_effects"] = {
            0.05,
            0.06,
            0.07,
            0.08,
        },
        ["boost_params"] = {
            ["autoOverload"] = "true",
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "DECREASE_GENERATOR_COST",
        ["desc"] = "desc_skill_generator",
        ["effect_icon_1"] = "effect_icon_gen_auto",
        ["effect_icon_2"] = "effect_icon_decrease_gen_cost",
        ["effect_icon_tip1"] = "effect_tooltip_gen_auto",
        ["effect_icon_tip2"] = "effect_tooltip_decrease_gen_cost",
        ["icon"] = "icon_skill_coal_master",
        ["item_icon"] = "",
        ["logic_name"] = "DecreaseGeneratorCost",
        ["name"] = "name_skill_generator",
        ["scope"] = "City",
    },
    ["generator_energy_purple"] = {
        ["id"] = "generator_energy_purple",
        ["alert"] = "ui_card_not_assign_tips_coal_master",
        ["assign_desc_tips"] = "assign_desc_decrease_gen_cost",
        ["boost_effects"] = {
            0.1,
            0.12,
            0.14,
            0.16,
            0.18,
            0.2,
            0.22,
            0.24,
            0.26,
            0.28,
            0.3,
            0.32,
            0.34,
            0.36,
            0.38,
            0.4,
            0.42,
            0.44,
            0.46,
            0.48,
            0.5,
            0.51,
            0.52,
            0.53,
            0.54,
            0.55,
            0.56,
            0.57,
            0.58,
        },
        ["boost_params"] = {
            ["autoOverload"] = "true",
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "DECREASE_GENERATOR_COST",
        ["desc"] = "desc_skill_generator",
        ["effect_icon_1"] = "effect_icon_gen_auto",
        ["effect_icon_2"] = "effect_icon_decrease_gen_cost",
        ["effect_icon_tip1"] = "effect_tooltip_gen_auto",
        ["effect_icon_tip2"] = "effect_tooltip_decrease_gen_cost",
        ["icon"] = "icon_skill_coal_master",
        ["item_icon"] = "",
        ["logic_name"] = "DecreaseGeneratorCost",
        ["name"] = "name_skill_generator",
        ["scope"] = "City",
    },
    ["medical_blue"] = {
        ["id"] = "medical_blue",
        ["alert"] = "ui_card_not_assign_tips_medical",
        ["assign_desc_tips"] = "assign_desc_treatment_level",
        ["boost_effects"] = {
            30,
            50,
            80,
            130,
        },
        ["boost_params"] = {
            ["cureRate"] = "0.2",
            ["cure_duration"] = "10",
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MEDICAL_VALUE",
        ["desc"] = "desc_skill_medical",
        ["effect_icon_1"] = "effect_icon_treatment",
        ["effect_icon_2"] = "effect_icon_treatment_level",
        ["effect_icon_tip1"] = "effect_tooltip_treatment",
        ["effect_icon_tip2"] = "effect_tooltip_treatment_level",
        ["icon"] = "icon_skill_medical",
        ["item_icon"] = "effect_icon_treatment_true",
        ["logic_name"] = "IncreaseMedicalValue",
        ["name"] = "name_skill_medical",
        ["scope"] = "City",
    },
    ["medical_purple"] = {
        ["id"] = "medical_purple",
        ["alert"] = "ui_card_not_assign_tips_medical",
        ["assign_desc_tips"] = "assign_desc_treatment_level",
        ["boost_effects"] = {
            50,
            75,
            100,
            200,
            400,
            800,
            1600,
            3200,
            6400,
            12800,
            25600,
            51200,
            102400,
            204800,
            409600,
            819200,
            1.6384e+06,
            3.2768e+06,
            6.5536e+06,
            1.31072e+07,
            2.62144e+07,
            5.24288e+07,
            1.048576e+08,
            2.097152e+08,
            4.194304e+08,
            8.388608e+08,
            1.6777216e+09,
            3.3554432e+09,
            6.7108864e+09,
        },
        ["boost_params"] = {
            ["cureRate"] = "0.4",
            ["cure_duration"] = "10",
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MEDICAL_VALUE",
        ["desc"] = "desc_skill_medical",
        ["effect_icon_1"] = "effect_icon_treatment",
        ["effect_icon_2"] = "effect_icon_treatment_level",
        ["effect_icon_tip1"] = "effect_tooltip_treatment",
        ["effect_icon_tip2"] = "effect_tooltip_treatment_level",
        ["icon"] = "icon_skill_medical",
        ["item_icon"] = "effect_icon_treatment_true",
        ["logic_name"] = "IncreaseMedicalValue",
        ["name"] = "name_skill_medical",
        ["scope"] = "City",
    },
    ["profit_resource1_blue"] = {
        ["id"] = "profit_resource1_blue",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            0.1,
            0.2,
            0.3,
            0.4,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_1",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_1",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_1",
        ["scope"] = "City",
    },
    ["profit_resource1_purple"] = {
        ["id"] = "profit_resource1_purple",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            0.2,
            0.4,
            0.6,
            0.8,
            1,
            1.2,
            1.4,
            1.6,
            1.8,
            2,
            2.2,
            2.4,
            2.6,
            2.8,
            3,
            3.2,
            3.4,
            3.6,
            3.8,
            4,
            4.2,
            4.4,
            4.6,
            4.8,
            5,
            5.2,
            5.4,
            5.6,
            5.8,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_1",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_1",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_1",
        ["scope"] = "City",
    },
    ["profit_resource2_blue"] = {
        ["id"] = "profit_resource2_blue",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            0.5,
            1,
            1.5,
            2,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_2",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_2",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_2",
        ["scope"] = "City",
    },
    ["profit_resource2_purple"] = {
        ["id"] = "profit_resource2_purple",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            1,
            1.5,
            2.5,
            3.5,
            5,
            6.5,
            8,
            10.5,
            14,
            18,
            23.5,
            30.5,
            39.5,
            51,
            66.5,
            86.5,
            112.5,
            146,
            190,
            247,
            321,
            417.5,
            543,
            705.5,
            917.5,
            1192.5,
            1550.5,
            2015.5,
            2620,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_2",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_2",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_2",
        ["scope"] = "City",
    },
    ["profit_resource3_blue"] = {
        ["id"] = "profit_resource3_blue",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            0.5,
            1,
            1.5,
            2,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_3",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_3",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_3",
        ["scope"] = "City",
    },
    ["profit_resource3_purple"] = {
        ["id"] = "profit_resource3_purple",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            1,
            1.5,
            2.5,
            3.5,
            5,
            6.5,
            8,
            10.5,
            14,
            18,
            23.5,
            30.5,
            39.5,
            51,
            66.5,
            86.5,
            112.5,
            146,
            190,
            247,
            321,
            417.5,
            543,
            705.5,
            917.5,
            1192.5,
            1550.5,
            2015.5,
            2620,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_3",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_3",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_3",
        ["scope"] = "City",
    },
    ["profit_resource4_blue"] = {
        ["id"] = "profit_resource4_blue",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            0.5,
            1,
            1.5,
            2,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_4",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_4",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_4",
        ["scope"] = "City",
    },
    ["profit_resource4_purple"] = {
        ["id"] = "profit_resource4_purple",
        ["alert"] = "ui_card_not_assign_tips_profit",
        ["assign_desc_tips"] = "assign_desc_increase_production",
        ["boost_effects"] = {
            1,
            1.5,
            2.5,
            3.5,
            5,
            6.5,
            8,
            10.5,
            14,
            18,
            23.5,
            30.5,
            39.5,
            51,
            66.5,
            86.5,
            112.5,
            146,
            190,
            247,
            321,
            417.5,
            543,
            705.5,
            917.5,
            1192.5,
            1550.5,
            2015.5,
            2620,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
        },
        ["boost_type"] = "INCREASE_MATERIAL_PRODUCTION",
        ["desc"] = "desc_skill_profit_4",
        ["effect_icon_1"] = "effect_icon_increase_item_count",
        ["effect_icon_2"] = "effect_icon_increase_production",
        ["effect_icon_tip1"] = "effect_tooltip_increase_item_count",
        ["effect_icon_tip2"] = "effect_tooltip_increase_production",
        ["icon"] = "icon_skill_profit_4",
        ["item_icon"] = "",
        ["logic_name"] = "IncreaseMaterialProduction",
        ["name"] = "name_skill_profit_4",
        ["scope"] = "City",
    },
    ["protest_blue"] = {
        ["id"] = "protest_blue",
        ["alert"] = "ui_card_not_assign_tips_protst_time",
        ["assign_desc_tips"] = "assign_desc_decrease_protest_person",
        ["boost_effects"] = {
            0.1,
            0.15,
            0.2,
            0.25,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
            ["protestDuration"] = "60",
        },
        ["boost_type"] = "DECREASE_PROTEST_PEOPLE",
        ["desc"] = "desc_skill_protest",
        ["effect_icon_1"] = "effect_icon_decrease_protest_time",
        ["effect_icon_2"] = "effect_icon_decrease_protest_person",
        ["effect_icon_tip1"] = "effect_tooltip_decrease_protest_time",
        ["effect_icon_tip2"] = "effect_tooltip_decrease_protest_person",
        ["icon"] = "icon_skill_protest_time",
        ["item_icon"] = "",
        ["logic_name"] = "DecreaseProtestPeople",
        ["name"] = "name_skill_protest",
        ["scope"] = "City",
    },
    ["protest_purple"] = {
        ["id"] = "protest_purple",
        ["alert"] = "ui_card_not_assign_tips_protst_time",
        ["assign_desc_tips"] = "assign_desc_decrease_protest_person",
        ["boost_effects"] = {
            0.3,
            0.335,
            0.368,
            0.4,
            0.43,
            0.459,
            0.486,
            0.512,
            0.536,
            0.559,
            0.581,
            0.602,
            0.622,
            0.641,
            0.659,
            0.676,
            0.692,
            0.707,
            0.722,
            0.736,
            0.749,
            0.762,
            0.774,
            0.785,
            0.796,
            0.806,
            0.816,
            0.825,
            0.834,
        },
        ["boost_params"] = {
            ["duration"] = "-1",
            ["index"] = "2",
            ["protestDuration"] = "120",
        },
        ["boost_type"] = "DECREASE_PROTEST_PEOPLE",
        ["desc"] = "desc_skill_protest",
        ["effect_icon_1"] = "effect_icon_decrease_protest_time",
        ["effect_icon_2"] = "effect_icon_decrease_protest_person",
        ["effect_icon_tip1"] = "effect_tooltip_decrease_protest_time",
        ["effect_icon_tip2"] = "effect_tooltip_decrease_protest_person",
        ["icon"] = "icon_skill_protest_time",
        ["item_icon"] = "",
        ["logic_name"] = "DecreaseProtestPeople",
        ["name"] = "name_skill_protest",
        ["scope"] = "City",
    },
}
