return {
    [1] = {
        ["level"] = 1,
        ["exp"] = 3,
        ["rwd"] = 1,
        ["times_max"] = 3,
        ["times_max_ad"] = 10,
        ["frequency"] = 18000,
        ["rwd_times"] = 5,
    },
    [2] = {
        ["level"] = 2,
        ["exp"] = 5,
        ["rwd"] = 2,
        ["times_max"] = 5,
        ["times_max_ad"] = 10,
        ["frequency"] = 14400,
        ["rwd_times"] = 8,
    },
    [3] = {
        ["level"] = 3,
        ["exp"] = 12,
        ["rwd"] = 3,
        ["times_max"] = 8,
        ["times_max_ad"] = 10,
        ["frequency"] = 14400,
        ["rwd_times"] = 10,
    },
    [4] = {
        ["level"] = 4,
        ["exp"] = 25,
        ["rwd"] = 4,
        ["times_max"] = 10,
        ["times_max_ad"] = 10,
        ["frequency"] = 10800,
        ["rwd_times"] = 11,
    },
    [5] = {
        ["level"] = 5,
        ["exp"] = 50,
        ["rwd"] = 5,
        ["times_max"] = 11,
        ["times_max_ad"] = 10,
        ["frequency"] = 10800,
        ["rwd_times"] = 12,
    },
    [6] = {
        ["level"] = 6,
        ["exp"] = 100,
        ["rwd"] = 6,
        ["times_max"] = 12,
        ["times_max_ad"] = 10,
        ["frequency"] = 9000,
        ["rwd_times"] = 13,
    },
    [7] = {
        ["level"] = 7,
        ["exp"] = 150,
        ["rwd"] = 7,
        ["times_max"] = 13,
        ["times_max_ad"] = 10,
        ["frequency"] = 9000,
        ["rwd_times"] = 14,
    },
    [8] = {
        ["level"] = 8,
        ["exp"] = 200,
        ["rwd"] = 8,
        ["times_max"] = 14,
        ["times_max_ad"] = 10,
        ["frequency"] = 7200,
        ["rwd_times"] = 15,
    },
    [9] = {
        ["level"] = 9,
        ["exp"] = 300,
        ["rwd"] = 9,
        ["times_max"] = 15,
        ["times_max_ad"] = 10,
        ["frequency"] = 7200,
        ["rwd_times"] = 15,
    },
    [10] = {
        ["level"] = 10,
        ["exp"] = 0,
        ["rwd"] = 10,
        ["times_max"] = 15,
        ["times_max_ad"] = 10,
        ["frequency"] = 5400,
        ["rwd_times"] = 0,
    },
}
