return {
    [1] = {
        ["id"] = 1,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 5,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 500,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 1,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [2] = {
        ["id"] = 2,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 10,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 1000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 1,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [3] = {
        ["id"] = 3,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 10,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 1500,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 1,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [4] = {
        ["id"] = 4,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 10,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 2000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 1,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [5] = {
        ["id"] = 5,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 15,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 3000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 1,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [6] = {
        ["id"] = 6,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 15,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 4000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 2,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [7] = {
        ["id"] = 7,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 15,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 5000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 2,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [8] = {
        ["id"] = 8,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 20,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 10000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 2,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources30",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [9] = {
        ["id"] = 9,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 20,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 20000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 2,
                ["order"] = 10,
                ["id"] = "TimeSkip30",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 50,
                ["num"] = 1,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
    [10] = {
        ["id"] = 10,
        ["rwd"] = {
            {
                ["prob"] = 10,
                ["num"] = 30,
                ["order"] = 1,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 250,
                ["num"] = 1,
                ["order"] = 2,
                ["id"] = "Resources10",
            },
            {
                ["prob"] = 150,
                ["num"] = 30000,
                ["order"] = 3,
                ["id"] = "Heart",
            },
            {
                ["prob"] = 13,
                ["num"] = 1,
                ["order"] = 4,
                ["id"] = "Train",
            },
            {
                ["prob"] = 200,
                ["num"] = 1,
                ["order"] = 5,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 6,
                ["id"] = "Hunger",
            },
            {
                ["prob"] = 50,
                ["num"] = 5,
                ["order"] = 7,
                ["id"] = "Gem",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 8,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 100,
                ["num"] = 1,
                ["order"] = 9,
                ["id"] = "Sleep",
            },
            {
                ["prob"] = 30,
                ["num"] = 2,
                ["order"] = 10,
                ["id"] = "TimeSkip120",
            },
            {
                ["prob"] = 150,
                ["num"] = 1,
                ["order"] = 11,
                ["id"] = "Resources60",
            },
            {
                ["prob"] = 50,
                ["num"] = 2,
                ["order"] = 12,
                ["id"] = "Gamecoins2",
            },
        },
    },
}
