return {
    [100] = {
        ["id"] = 100,
        ["city_id"] = 1001,
        ["combo"] = 3,
        ["icon"] = "event_1001/icon_slot_Gem",
        ["reward"] = "addToItem*1000?id=Gem",
        ["reward_icon"] = "event_1001/icon_slot_Gem",
        ["show_reward"] = true,
        ["symbol"] = "Gem",
        ["weight"] = 1,
    },
    [101] = {
        ["id"] = 101,
        ["city_id"] = 1001,
        ["combo"] = 2,
        ["icon"] = "event_1001/icon_slot_Gem",
        ["reward"] = "addToItem*30?id=Gem",
        ["reward_icon"] = "event_1001/icon_slot_Gem",
        ["show_reward"] = false,
        ["symbol"] = "Gem",
        ["weight"] = 50,
    },
    [200] = {
        ["id"] = 200,
        ["city_id"] = 1001,
        ["combo"] = 3,
        ["icon"] = "event_1001/icon_slot_Cash",
        ["reward"] = "addToOverTime*3600?id=Cash1001",
        ["reward_icon"] = "event_1001/icon_slot_Cash",
        ["show_reward"] = true,
        ["symbol"] = "Cash1001",
        ["weight"] = 500,
    },
    [201] = {
        ["id"] = 201,
        ["city_id"] = 1001,
        ["combo"] = 2,
        ["icon"] = "event_1001/icon_slot_Cash",
        ["reward"] = "addToOverTime*600?id=Cash1001",
        ["reward_icon"] = "event_1001/icon_slot_Cash",
        ["show_reward"] = false,
        ["symbol"] = "Cash1001",
        ["weight"] = 1000,
    },
    [300] = {
        ["id"] = 300,
        ["city_id"] = 1001,
        ["combo"] = 3,
        ["icon"] = "event_1001/icon_slot_Heart",
        ["reward"] = "addToOverTime*3600?id=Heart1001",
        ["reward_icon"] = "event_1001/icon_slot_Heart",
        ["show_reward"] = true,
        ["symbol"] = "Heart1001",
        ["weight"] = 500,
    },
    [301] = {
        ["id"] = 301,
        ["city_id"] = 1001,
        ["combo"] = 2,
        ["icon"] = "event_1001/icon_slot_Heart",
        ["reward"] = "addToOverTime*600?id=Heart1001",
        ["reward_icon"] = "event_1001/icon_slot_Heart",
        ["show_reward"] = false,
        ["symbol"] = "Heart1001",
        ["weight"] = 1000,
    },
    [400] = {
        ["id"] = 400,
        ["city_id"] = 1001,
        ["combo"] = 3,
        ["icon"] = "event_1001/icon_slot_Trick",
        ["reward"] = "addToItem*10?id=Trick1001",
        ["reward_icon"] = "event_1001/icon_slot_Trick",
        ["show_reward"] = true,
        ["symbol"] = "Trick1001",
        ["weight"] = 100,
    },
    [401] = {
        ["id"] = 401,
        ["city_id"] = 1001,
        ["combo"] = 2,
        ["icon"] = "event_1001/icon_slot_Trick",
        ["reward"] = "addToItem*2?id=Trick1001",
        ["reward_icon"] = "event_1001/icon_slot_Trick",
        ["show_reward"] = false,
        ["symbol"] = "Trick1001",
        ["weight"] = 1000,
    },
    [500] = {
        ["id"] = 500,
        ["city_id"] = 1001,
        ["combo"] = 3,
        ["icon"] = "event_1001/icon_slot_777",
        ["reward"] = "addToItem*100?id=PlayCoin1001",
        ["reward_icon"] = "event_1001/icon_slot_Coin",
        ["show_reward"] = true,
        ["symbol"] = "CardIcon",
        ["weight"] = 7,
    },
    [501] = {
        ["id"] = 501,
        ["city_id"] = 1001,
        ["combo"] = 2,
        ["icon"] = "event_1001/icon_slot_777",
        ["reward"] = "addToItem*20?id=PlayCoin1001",
        ["reward_icon"] = "event_1001/icon_slot_Coin",
        ["show_reward"] = false,
        ["symbol"] = "CardIcon",
        ["weight"] = 30,
    },
    [99] = {
        ["id"] = 99,
        ["city_id"] = 1001,
        ["combo"] = 0,
        ["icon"] = "",
        ["reward"] = "addToOverTime*120?id=Cash1001",
        ["reward_icon"] = "",
        ["show_reward"] = false,
        ["symbol"] = "Empty",
        ["weight"] = 500,
    },
}
