return {
    ["Bean"] = {
        ["id"] = "Bean",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            25,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 5,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
    ["Bread"] = {
        ["id"] = "Bread",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            25,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 3,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
    ["Corn1001"] = {
        ["id"] = "Corn1001",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            30,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 2,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
    ["Egg"] = {
        ["id"] = "Egg",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            30,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 4,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
    ["Milk"] = {
        ["id"] = "Milk",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            30,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 6,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
    ["Pizza"] = {
        ["id"] = "Pizza",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            30,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 7,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
    ["Wheat"] = {
        ["id"] = "Wheat",
        ["city_id"] = 1001,
        ["load_count"] = {
            100,
            200,
            300,
            400,
            500,
        },
        ["load_time"] = {
            25,
            20,
            15,
            15,
            10,
        },
        ["sell_price"] = {
            1,
            2,
            3,
            4,
            5,
        },
        ["sort"] = 1,
        ["upgrade_cash_cost"] = {
            10,
            20,
            40,
            80,
            100,
        },
    },
}
