return {
    [101] = {
        ["id"] = 101,
        ["cash_conditions"] = 100000,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*1?id=box_blue",
        ["sort"] = 1,
    },
    [102] = {
        ["id"] = 102,
        ["cash_conditions"] = 4e+08,
        ["group"] = 1001,
        ["rewards"] = "addToItem*100?id=Gem",
        ["sort"] = 2,
    },
    [103] = {
        ["id"] = 103,
        ["cash_conditions"] = 2e+10,
        ["group"] = 1001,
        ["rewards"] = "addToItem*50?id=BlackCoin",
        ["sort"] = 3,
    },
    [104] = {
        ["id"] = 104,
        ["cash_conditions"] = 4e+11,
        ["group"] = 1001,
        ["rewards"] = "addToItem*150?id=Gem",
        ["sort"] = 4,
    },
    [105] = {
        ["id"] = 105,
        ["cash_conditions"] = 8e+12,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*1?id=random_purple",
        ["sort"] = 5,
    },
    [106] = {
        ["id"] = 106,
        ["cash_conditions"] = 1.6e+14,
        ["group"] = 1001,
        ["rewards"] = "addToItem*200?id=Gem",
        ["sort"] = 6,
    },
    [107] = {
        ["id"] = 107,
        ["cash_conditions"] = 3.2e+15,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*1?id=box_purple",
        ["sort"] = 7,
    },
    [108] = {
        ["id"] = 108,
        ["cash_conditions"] = 6.4e+16,
        ["group"] = 1001,
        ["rewards"] = "addToItem*300?id=Gem",
        ["sort"] = 8,
    },
    [109] = {
        ["id"] = 109,
        ["cash_conditions"] = 1.3e+18,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*2?id=random_purple",
        ["sort"] = 9,
    },
    [110] = {
        ["id"] = 110,
        ["cash_conditions"] = 2.6e+19,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*1?id=box_gold",
        ["sort"] = 10,
    },
    [111] = {
        ["id"] = 111,
        ["cash_conditions"] = 5.2e+20,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*3?id=box_purple",
        ["sort"] = 11,
    },
    [112] = {
        ["id"] = 112,
        ["cash_conditions"] = 1e+22,
        ["group"] = 1001,
        ["rewards"] = "addToOpenBox*2?id=box_gold",
        ["sort"] = 12,
    },
    [113] = {
        ["id"] = 113,
        ["cash_conditions"] = 100000,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*1?id=box_blue",
        ["sort"] = 1,
    },
    [114] = {
        ["id"] = 114,
        ["cash_conditions"] = 5e+07,
        ["group"] = 1002,
        ["rewards"] = "addToItem*100?id=Gem",
        ["sort"] = 2,
    },
    [115] = {
        ["id"] = 115,
        ["cash_conditions"] = 5e+09,
        ["group"] = 1002,
        ["rewards"] = "addToItem*50?id=BlackCoin",
        ["sort"] = 3,
    },
    [116] = {
        ["id"] = 116,
        ["cash_conditions"] = 1.3e+11,
        ["group"] = 1002,
        ["rewards"] = "addToItem*150?id=Gem",
        ["sort"] = 4,
    },
    [117] = {
        ["id"] = 117,
        ["cash_conditions"] = 3.3e+12,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*1?id=random_purple",
        ["sort"] = 5,
    },
    [118] = {
        ["id"] = 118,
        ["cash_conditions"] = 8.3e+13,
        ["group"] = 1002,
        ["rewards"] = "addToItem*200?id=Gem",
        ["sort"] = 6,
    },
    [119] = {
        ["id"] = 119,
        ["cash_conditions"] = 2.1e+15,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*1?id=box_purple",
        ["sort"] = 7,
    },
    [120] = {
        ["id"] = 120,
        ["cash_conditions"] = 5.3e+16,
        ["group"] = 1002,
        ["rewards"] = "addToItem*300?id=Gem",
        ["sort"] = 8,
    },
    [121] = {
        ["id"] = 121,
        ["cash_conditions"] = 1.3e+18,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*2?id=random_purple",
        ["sort"] = 9,
    },
    [122] = {
        ["id"] = 122,
        ["cash_conditions"] = 3.3e+19,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*1?id=box_gold",
        ["sort"] = 10,
    },
    [123] = {
        ["id"] = 123,
        ["cash_conditions"] = 8.3e+20,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*3?id=box_purple",
        ["sort"] = 11,
    },
    [124] = {
        ["id"] = 124,
        ["cash_conditions"] = 2.1e+22,
        ["group"] = 1002,
        ["rewards"] = "addToOpenBox*2?id=box_gold",
        ["sort"] = 12,
    },
}
