return {
    ["cashBoost1001_2"] = {
        ["id"] = "cashBoost1001_2",
        ["boost_id"] = "profit_cash_2_event",
        ["city_id"] = 1001,
        ["desc"] = "ui_event_trick_cash1_desc",
        ["icon"] = "event_1001/icon_trick_farmer",
        ["name"] = "ui_event_trick_cash1_title",
        ["sort"] = 3,
        ["upgrade_cash_cost"] = {
            1,
            1,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            9,
            9,
            9,
            9,
            10,
            10,
            10,
            10,
            11,
            11,
            11,
            11,
            12,
            12,
            12,
            12,
            13,
            13,
            13,
            13,
            14,
            14,
            14,
            14,
            15,
            15,
            15,
        },
    },
    ["cashBoost1001_3"] = {
        ["id"] = "cashBoost1001_3",
        ["boost_id"] = "profit_cash_3_event",
        ["city_id"] = 1001,
        ["desc"] = "ui_event_trick_cash2_desc",
        ["icon"] = "event_1001/icon_trick_processor",
        ["name"] = "ui_event_trick_cash2_title",
        ["sort"] = 4,
        ["upgrade_cash_cost"] = {
            1,
            1,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            9,
            9,
            9,
            9,
            10,
            10,
            10,
            10,
            11,
            11,
            11,
            11,
            12,
            12,
            12,
            12,
            13,
            13,
            13,
            13,
            14,
            14,
            14,
            14,
            15,
            15,
            15,
        },
    },
    ["cashBoost1001_4"] = {
        ["id"] = "cashBoost1001_4",
        ["boost_id"] = "profit_cash_4_event",
        ["city_id"] = 1001,
        ["desc"] = "ui_event_trick_cash3_desc",
        ["icon"] = "event_1001/icon_trick_seller",
        ["name"] = "ui_event_trick_cash3_title",
        ["sort"] = 5,
        ["upgrade_cash_cost"] = {
            1,
            1,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            9,
            9,
            9,
            9,
            10,
            10,
            10,
            10,
            11,
            11,
            11,
            11,
            12,
            12,
            12,
            12,
            13,
            13,
            13,
            13,
            14,
            14,
            14,
            14,
            15,
            15,
            15,
        },
    },
    ["heartBoost1001"] = {
        ["id"] = "heartBoost1001",
        ["boost_id"] = "profit_heart_event",
        ["city_id"] = 1001,
        ["desc"] = "ui_event_trick_heart_desc",
        ["icon"] = "event_1001/icon_trick_queen",
        ["name"] = "ui_event_trick_heart_title",
        ["sort"] = 2,
        ["upgrade_cash_cost"] = {
            1,
            1,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            9,
            9,
            9,
            9,
            10,
            10,
            10,
            10,
            11,
            11,
            11,
            11,
            12,
            12,
            12,
            12,
            13,
            13,
            13,
            13,
            14,
            14,
            14,
            14,
            15,
            15,
            15,
        },
    },
    ["reduceBuildCost1001"] = {
        ["id"] = "reduceBuildCost1001",
        ["boost_id"] = "reduce_build_cost_event",
        ["city_id"] = 1001,
        ["desc"] = "ui_event_trick_cost_desc",
        ["icon"] = "event_1001/icon_trick_builder",
        ["name"] = "ui_event_trick_cost_title",
        ["sort"] = 1,
        ["upgrade_cash_cost"] = {
            1,
            1,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
        },
    },
    ["vanSpeed1001"] = {
        ["id"] = "vanSpeed1001",
        ["boost_id"] = "van_speed_event",
        ["city_id"] = 1001,
        ["desc"] = "ui_event_trick_van_desc",
        ["icon"] = "event_1001/icon_trick_driver",
        ["name"] = "ui_event_trick_van_title",
        ["sort"] = 6,
        ["upgrade_cash_cost"] = {
            1,
            1,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
        },
    },
}
