return {
    [1] = {
        ["id"] = 1,
        ["group"] = 1001,
        ["rank_end"] = 1,
        ["rank_start"] = 1,
        ["rewards"] = "addToOpenBox*3?id=box_gold,addToOpenBox*3?id=random_purple,addToItem*1500?id=Gem",
    },
    [10] = {
        ["id"] = 10,
        ["group"] = 1002,
        ["rank_end"] = 2,
        ["rank_start"] = 2,
        ["rewards"] = "addToOpenBox*2?id=box_gold,addToOpenBox*2?id=random_purple,addToItem*1000?id=Gem",
    },
    [11] = {
        ["id"] = 11,
        ["group"] = 1002,
        ["rank_end"] = 3,
        ["rank_start"] = 3,
        ["rewards"] = "addToOpenBox*1?id=box_gold,addToOpenBox*1?id=random_purple,addToItem*500?id=Gem",
    },
    [12] = {
        ["id"] = 12,
        ["group"] = 1002,
        ["rank_end"] = 10,
        ["rank_start"] = 4,
        ["rewards"] = "addToOpenBox*1?id=box_gold,addToOpenBox*1?id=random_purple",
    },
    [13] = {
        ["id"] = 13,
        ["group"] = 1002,
        ["rank_end"] = 30,
        ["rank_start"] = 11,
        ["rewards"] = "addToOpenBox*1?id=box_gold",
    },
    [14] = {
        ["id"] = 14,
        ["group"] = 1002,
        ["rank_end"] = 50,
        ["rank_start"] = 31,
        ["rewards"] = "addToOpenBox*1?id=box_purple,addToOpenBox*2?id=box_blue",
    },
    [15] = {
        ["id"] = 15,
        ["group"] = 1002,
        ["rank_end"] = 100,
        ["rank_start"] = 51,
        ["rewards"] = "addToOpenBox*1?id=box_purple",
    },
    [16] = {
        ["id"] = 16,
        ["group"] = 1002,
        ["rank_end"] = 150,
        ["rank_start"] = 101,
        ["rewards"] = "addToOpenBox*1?id=random_purple",
    },
    [2] = {
        ["id"] = 2,
        ["group"] = 1001,
        ["rank_end"] = 2,
        ["rank_start"] = 2,
        ["rewards"] = "addToOpenBox*2?id=box_gold,addToOpenBox*2?id=random_purple,addToItem*1000?id=Gem",
    },
    [3] = {
        ["id"] = 3,
        ["group"] = 1001,
        ["rank_end"] = 3,
        ["rank_start"] = 3,
        ["rewards"] = "addToOpenBox*1?id=box_gold,addToOpenBox*1?id=random_purple,addToItem*500?id=Gem",
    },
    [4] = {
        ["id"] = 4,
        ["group"] = 1001,
        ["rank_end"] = 10,
        ["rank_start"] = 4,
        ["rewards"] = "addToOpenBox*1?id=box_gold,addToOpenBox*1?id=random_purple",
    },
    [5] = {
        ["id"] = 5,
        ["group"] = 1001,
        ["rank_end"] = 30,
        ["rank_start"] = 11,
        ["rewards"] = "addToOpenBox*1?id=box_gold",
    },
    [6] = {
        ["id"] = 6,
        ["group"] = 1001,
        ["rank_end"] = 50,
        ["rank_start"] = 31,
        ["rewards"] = "addToOpenBox*1?id=box_purple,addToOpenBox*2?id=box_blue",
    },
    [7] = {
        ["id"] = 7,
        ["group"] = 1001,
        ["rank_end"] = 100,
        ["rank_start"] = 51,
        ["rewards"] = "addToOpenBox*1?id=box_purple",
    },
    [8] = {
        ["id"] = 8,
        ["group"] = 1001,
        ["rank_end"] = 150,
        ["rank_start"] = 101,
        ["rewards"] = "addToOpenBox*1?id=random_purple",
    },
    [9] = {
        ["id"] = 9,
        ["group"] = 1002,
        ["rank_end"] = 1,
        ["rank_start"] = 1,
        ["rewards"] = "addToOpenBox*3?id=box_gold,addToOpenBox*3?id=random_purple,addToItem*1500?id=Gem",
    },
}
