return {
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0.7,
        ["monster_count"] = {
            "2",
            "2",
        },
        ["monster_count_flag"] = "false",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 0,
        ["point_index"] = "1",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0.7,
        ["monster_count"] = {
            "3",
            "5",
        },
        ["monster_count_flag"] = "false",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 0,
        ["point_index"] = "2",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0.7,
        ["monster_count"] = {
            "-2",
            "-1",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 0,
        ["point_index"] = "3",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0.7,
        ["monster_count"] = {
            "-2",
            "-1",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 0,
        ["point_index"] = "4",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0.7,
        ["monster_count"] = {
            "-1",
            "2",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 0,
        ["point_index"] = "5",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 1,
        ["monster_count"] = {
            "0",
            "1",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 0,
        ["point_index"] = "6",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 1.15,
        ["monster_count"] = {
            "0",
            "1",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 2,
        ["point_index"] = "7",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 1.45,
        ["monster_count"] = {
            "0",
            "1",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 2,
        ["point_index"] = "8",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 1.75,
        ["monster_count"] = {
            "1",
            "3",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 2,
        ["point_index"] = "9",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {},
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 2,
        ["item_drop"] = {
            {
                ["time_Heart"] = 300,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 2.05,
        ["monster_count"] = {
            "1",
            "3",
        },
        ["monster_count_flag"] = "true",
        ["monster_id"] = {
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "103",
            "104",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
        },
        ["monster_level_scale"] = 6,
        ["point_index"] = "10",
        ["point_type"] = 1,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "city3_a0113_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_Gem"] = 5,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1001",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "car_snowA_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_BlackCoin"] = 1,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1002",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "car_snowB_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_Gem"] = 5,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1003",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "car_snowC_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_BlackCoin"] = 1,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1004",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "car_snowD_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_Gem"] = 5,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1005",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "city5_prop2_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_BlackCoin"] = 1,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1006",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "city3_a0102_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_Gem"] = 5,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1007",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "city3_a0113_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_BlackCoin"] = 1,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1008",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "city3_a0113_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_Gem"] = 5,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1009",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
    {
        ["collect_apprearance"] = {
            "city3_a0113_explore",
        },
        ["hero_for_sure"] = "TRUE",
        ["interact_radius"] = 0.5,
        ["item_drop"] = {
            {
                ["item_BlackCoin"] = 1,
            },
            {
                ["chest_fragment"] = 1,
            },
        },
        ["monster_ap_scale"] = 0,
        ["monster_count"] = {},
        ["monster_count_flag"] = "",
        ["monster_id"] = {},
        ["monster_level_scale"] = 0,
        ["point_index"] = "1010",
        ["point_type"] = 2,
        ["product_level_drop"] = {
            {
                ["level_2"] = 360,
            },
            {
                ["level_max"] = 360,
            },
        },
        ["unit_drop_group"] = {
            "unit_1",
            "unit_2",
            "unit_3",
            "unit_4",
            "unit_5",
            "unit_6",
            "unit_7",
            "unit_8",
            "unit_9",
            "unit_10",
            "unit_11",
            "unit_12",
            "unit_13",
            "unit_14",
        },
    },
}
