return {
    ["FunBoost"] = {
        ["id"] = "FunBoost",
        ["constant_a"] = 30,
        ["constant_b"] = 0.1,
        ["constant_c"] = 90,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["RestBoost"] = {
        ["id"] = "RestBoost",
        ["constant_a"] = 30,
        ["constant_b"] = 0.1,
        ["constant_c"] = 90,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["bodyTemp"] = {
        ["id"] = "bodyTemp",
        ["constant_a"] = 2.5,
        ["constant_b"] = 15,
        ["constant_c"] = 1,
        ["constant_d"] = 10,
        ["constant_e"] = -40,
        ["constant_f"] = 0,
    },
    ["cashSpeedByStage"] = {
        ["id"] = "cashSpeedByStage",
        ["constant_a"] = 1.1027136607698829,
        ["constant_b"] = 1,
        ["constant_c"] = 1,
        ["constant_d"] = 1,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["energyLevel"] = {
        ["id"] = "energyLevel",
        ["constant_a"] = 15,
        ["constant_b"] = 1,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["generatorPercent"] = {
        ["id"] = "generatorPercent",
        ["constant_a"] = 25,
        ["constant_b"] = 50,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["heartOfflineFix"] = {
        ["id"] = "heartOfflineFix",
        ["constant_a"] = 0.02,
        ["constant_b"] = 0.001,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["hopeValue"] = {
        ["id"] = "hopeValue",
        ["constant_a"] = 0,
        ["constant_b"] = 0,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["hungerBoost"] = {
        ["id"] = "hungerBoost",
        ["constant_a"] = 30,
        ["constant_b"] = 0.1,
        ["constant_c"] = 90,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["hungerSpeedBoost"] = {
        ["id"] = "hungerSpeedBoost",
        ["constant_a"] = 20,
        ["constant_b"] = 0.5,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["leaveRate"] = {
        ["id"] = "leaveRate",
        ["constant_a"] = 0,
        ["constant_b"] = 0.001670787129,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["necessitiesFix"] = {
        ["id"] = "necessitiesFix",
        ["constant_a"] = 0.05,
        ["constant_b"] = 0.05,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["overdriveControl"] = {
        ["id"] = "overdriveControl",
        ["constant_a"] = 60,
        ["constant_b"] = 90,
        ["constant_c"] = 2,
        ["constant_d"] = 3,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["protestRate"] = {
        ["id"] = "protestRate",
        ["constant_a"] = 0.01523334789,
        ["constant_b"] = 0.002307823473,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["protestTrigger"] = {
        ["id"] = "protestTrigger",
        ["constant_a"] = 30,
        ["constant_b"] = 0,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["securityScore"] = {
        ["id"] = "securityScore",
        ["constant_a"] = 2,
        ["constant_b"] = 0,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["sickDays"] = {
        ["id"] = "sickDays",
        ["constant_a"] = 864,
        ["constant_b"] = 288,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["sickRate"] = {
        ["id"] = "sickRate",
        ["constant_a"] = 0.0009622411662,
        ["constant_b"] = 0.0003098735783,
        ["constant_c"] = 30,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["starveRate"] = {
        ["id"] = "starveRate",
        ["constant_a"] = 0,
        ["constant_b"] = 0.001670787129,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["strikeRate"] = {
        ["id"] = "strikeRate",
        ["constant_a"] = 0.0005981306542,
        ["constant_b"] = 0.0003098735783,
        ["constant_c"] = 30,
        ["constant_d"] = 70,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["tempScore"] = {
        ["id"] = "tempScore",
        ["constant_a"] = 2,
        ["constant_b"] = 70,
        ["constant_c"] = 0,
        ["constant_d"] = 0,
        ["constant_e"] = 0,
        ["constant_f"] = 0,
    },
    ["weatherChange"] = {
        ["id"] = "weatherChange",
        ["constant_a"] = 90,
        ["constant_b"] = 300,
        ["constant_c"] = 1440,
        ["constant_d"] = 3600,
        ["constant_e"] = -20,
        ["constant_f"] = -50,
    },
}
