return {
    ["Ads"] = {
        ["id"] = 'Ads',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTutorialComplete',
        ["unlockParams"] = {
            ["step"] = 7,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Attributes"] = {
        ["id"] = 'Attributes',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTutorialComplete',
        ["unlockParams"] = {
            ["step"] = 7,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Map"] = {
        ["id"] = 'Map',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTutorialComplete',
        ["unlockParams"] = {
            ["step"] = 7,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Setting"] = {
        ["id"] = 'Setting',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTutorialComplete',
        ["unlockParams"] = {
            ["step"] = 7,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Statistical"] = {
        ["id"] = 'Statistical',
        ["city"] = 1,
        ["is_highlight"] = true,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Carpentry",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Survey1"] = {
        ["id"] = 'Survey1',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 5,
            ["taskId"] = 10050001,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Survey11"] = {
        ["id"] = 'Survey11',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Carpentry",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["SurveyNewCard1"] = {
        ["id"] = 'SurveyNewCard1',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 10011008,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["SurveySoftLaunch1"] = {
        ["id"] = 'SurveySoftLaunch1',
        ["city"] = 1,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 10011008,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Tasks"] = {
        ["id"] = 'Tasks',
        ["city"] = 1,
        ["is_highlight"] = true,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTutorialComplete',
        ["unlockParams"] = {
            ["step"] = 7,
        },
        ["is_modal_panel"] = true,
        ["scope"] = 'global',
    },
    ["WorkerManagement"] = {
        ["id"] = 'WorkerManagement',
        ["city"] = 1,
        ["is_highlight"] = true,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsFurnitureBuildComplete',
        ["unlockParams"] = {
            ["count"] = 3,
            ["furnitureId"] = "C1_Dorm_Bed",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["FirstCharge"] = {
        ["id"] = 'FirstCharge',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 20012003,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Assist"] = {
        ["id"] = 'Assist',
        ["city"] = 2,
        ["is_highlight"] = true,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 20011006,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["BuildCoalMine_2"] = {
        ["id"] = 'BuildCoalMine_2',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "CoalMine",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["BuildingManagement"] = {
        ["id"] = 'BuildingManagement',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "CollectionStation",
            ["level"] = 2,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Cards"] = {
        ["id"] = 'Cards',
        ["city"] = 2,
        ["is_highlight"] = true,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 20012003,
        },
        ["is_modal_panel"] = true,
        ["scope"] = 'global',
    },
    ["Fight"] = {
        ["id"] = 'Fight',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsManual',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["HeartGeneration"] = {
        ["id"] = 'HeartGeneration',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Carpentry",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["ResourceAlertTips"] = {
        ["id"] = 'ResourceAlertTips',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Generator",
            ["level"] = 2,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Shop"] = {
        ["id"] = 'Shop',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["ShopBox"] = {
        ["id"] = 'ShopBox',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 20012003,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["ShopGem"] = {
        ["id"] = 'ShopGem',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["ShopPack"] = {
        ["id"] = 'ShopPack',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsTaskComplete',
        ["unlockParams"] = {
            ["part"] = 1,
            ["taskId"] = 20012003,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Survey12"] = {
        ["id"] = 'Survey12',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBattleFinished',
        ["unlockParams"] = {
            ["level"] = 8,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Survey2"] = {
        ["id"] = 'Survey2',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBattleFinished',
        ["unlockParams"] = {
            ["level"] = 5,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["SurveyNewCard2"] = {
        ["id"] = 'SurveyNewCard2',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBattleFinished',
        ["unlockParams"] = {
            ["level"] = 2,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["SurvivorSick"] = {
        ["id"] = 'SurvivorSick',
        ["city"] = 2,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = true,
        ["unlockLogic"] = 'FunctionsFurnitureBuildComplete',
        ["unlockParams"] = {
            ["count"] = 3,
            ["furnitureId"] = "C2_Dorm_Bed",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["BuildCarpentry_3"] = {
        ["id"] = 'BuildCarpentry_3',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Carpentry",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["BuildCoalMine_3"] = {
        ["id"] = 'BuildCoalMine_3',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "CoalMine",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["EventCity"] = {
        ["id"] = 'EventCity',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Watchtower",
            ["level"] = 1,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Protest"] = {
        ["id"] = 'Protest',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = true,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["PushNotify"] = {
        ["id"] = 'PushNotify',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Storm"] = {
        ["id"] = 'Storm',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["Survey3"] = {
        ["id"] = 'Survey3',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsBuildComplete',
        ["unlockParams"] = {
            ["count"] = 1,
            ["zoneType"] = "Watchtower",
            ["level"] = 2,
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["SurveySoftLaunch2"] = {
        ["id"] = 'SurveySoftLaunch2',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
    ["WorkOverTime"] = {
        ["id"] = 'WorkOverTime',
        ["city"] = 3,
        ["is_highlight"] = false,
        ["is_read_city_conf"] = false,
        ["unlockLogic"] = 'FunctionsCityEnter',
        ["unlockParams"] = {
        },
        ["is_modal_panel"] = false,
        ["scope"] = 'global',
    },
}
