return {
    ["C1_Carpentry_Boost1ForCarpentry"] = {
        ["id"] = "C1_Carpentry_Boost1ForCarpentry",
        ["_tags_"] = {},
        ["animation"] = "",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "CarpentryFireplace",
        ["boost_reward"] = {},
        ["building_exp"] = {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        },
        ["capacity"] = 0,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
        },
        ["desc_key"] = "furniture_desc_CarpentryFireplace",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Boost1ForCarpentry",
        ["heart_fix"] = 0,
        ["icon"] = "CarpentryFireplace",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            230,
        },
        ["name_key"] = "furniture_name_CarpentryFireplace",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 0,
        ["recover_reward"] = {},
        ["right_hand_id"] = {},
        ["right_hand_name"] = "",
        ["sort"] = 8,
        ["stage"] = {
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
            25.7,
        },
        ["usage_duration"] = {
            0,
            -0.8,
            -1.59,
            -2.35,
            -3.11,
            -3.84,
            -4.56,
            -5.28,
            -5.97,
            -6.65,
            -7.32,
            -7.97,
            -8.61,
            -9.24,
            -9.85,
            -10.45,
            -11.05,
            -11.63,
            -12.2,
            -12.75,
            -13.29,
            -13.83,
            -14.35,
            -14.87,
            -15.37,
            -15.87,
            -16.35,
            -16.81,
            -17.28,
            -17.73,
            -18.19,
            -18.61,
            -19.04,
            -19.47,
            -19.88,
            -20.28,
            -20.67,
            -21.05,
            -21.44,
            -21.81,
            -22.17,
            -22.53,
            -22.88,
            -23.23,
            -23.56,
            -23.88,
            -24.21,
            -24.52,
            -24.83,
            -25.13,
            -25.43,
            -25.72,
            -26.01,
            -26.29,
            -26.56,
            -26.83,
            -27.09,
            -27.36,
            -27.61,
            -27.85,
            -28.09,
            -28.33,
            -28.57,
            -28.8,
            -29.03,
            -29.24,
            -29.45,
            -29.67,
            -29.88,
            -30.08,
            -30.28,
            -30.47,
            -30.67,
            -30.85,
            -31.03,
            -31.21,
            -31.39,
            -31.56,
            -31.72,
            -31.89,
            -32.05,
            -32.21,
            -32.37,
            -32.52,
            -32.67,
            -32.81,
            -32.96,
            -33.11,
            -33.24,
            -33.37,
            -33.51,
            -33.64,
            -33.76,
            -33.89,
            -34.01,
            -34.13,
            -34.25,
            -34.36,
            -34.48,
            -34.59,
            -34.69,
            -34.8,
            -34.91,
            -35.01,
            -35.11,
            -35.2,
            -35.31,
            -35.4,
            -35.49,
            -35.57,
            -35.61,
            -35.65,
            -35.69,
            -35.73,
            -35.77,
            -35.81,
            -35.85,
            -35.89,
            -35.93,
            -35.97,
            -36.01,
            -36.05,
            -36.09,
            -36.13,
            -36.17,
            -36.21,
            -36.25,
            -36.29,
            -36.33,
            -36.37,
            -36.41,
            -36.45,
            -36.49,
            -36.53,
            -36.57,
            -36.61,
            -36.65,
            -36.69,
            -36.72,
            -36.75,
            -36.77,
            -36.8,
            -36.83,
            -36.85,
            -36.88,
            -36.91,
            -36.93,
            -36.96,
            -36.99,
            -37.01,
            -37.04,
            -37.07,
            -37.09,
            -37.12,
            -37.15,
            -37.17,
            -37.2,
            -37.23,
            -37.25,
            -37.28,
            -37.31,
            -37.33,
            -37.36,
            -37.39,
            -37.41,
            -37.44,
            -37.47,
            -37.49,
            -37.52,
            -37.55,
            -37.57,
            -37.6,
            -37.63,
            -37.65,
            -37.68,
            -37.71,
            -37.73,
            -37.76,
            -37.79,
            -37.81,
            -37.84,
            -37.87,
            -37.89,
            -37.92,
            -37.95,
            -37.97,
            -38,
            -38.01,
            -38.03,
            -38.04,
            -38.05,
            -38.07,
            -38.08,
            -38.09,
            -38.11,
            -38.12,
            -38.13,
            -38.15,
            -38.16,
            -38.17,
            -38.19,
            -38.2,
            -38.21,
            -38.23,
            -38.24,
            -38.25,
            -38.27,
            -38.28,
            -38.29,
            -38.31,
            -38.32,
            -38.33,
            -38.35,
            -38.36,
            -38.37,
            -38.39,
            -38.4,
            -38.41,
            -38.43,
            -38.44,
            -38.45,
            -38.47,
            -38.48,
            -38.49,
            -38.51,
            -38.52,
            -38.53,
            -38.55,
            -38.56,
            -38.57,
        },
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Carpentry",
    },
    ["C1_Carpentry_Tool1ForCarpentry"] = {
        ["id"] = "C1_Carpentry_Tool1ForCarpentry",
        ["_tags_"] = {},
        ["animation"] = "hammerwork",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "Tool",
        ["boost_reward"] = {},
        ["building_exp"] = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
        },
        ["capacity"] = 1,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            2,
        },
        ["desc_key"] = "furniture_desc_Tool",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Tool1ForCarpentry",
        ["heart_fix"] = 83,
        ["icon"] = "Tool",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {
            "C1_Carpentry_Boost1ForCarpentry",
        },
        ["load_limit"] = {},
        ["max_level"] = {
            20,
        },
        ["name_key"] = "furniture_name_Tool",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 4,
        ["recover_reward"] = {},
        ["right_hand_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["right_hand_name"] = "HandTool",
        ["sort"] = 7,
        ["stage"] = {
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
        },
        ["usage_duration"] = {
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
            40,
        },
        ["usage_output"] = {
            {
                ["WoodenBoard"] = 5,
            },
            {
                ["WoodenBoard"] = 6,
            },
            {
                ["WoodenBoard"] = 7,
            },
            {
                ["WoodenBoard"] = 8,
            },
            {
                ["WoodenBoard"] = 9,
            },
            {
                ["WoodenBoard"] = 10,
            },
            {
                ["WoodenBoard"] = 11,
            },
            {
                ["WoodenBoard"] = 12,
            },
            {
                ["WoodenBoard"] = 13,
            },
            {
                ["WoodenBoard"] = 14,
            },
            {
                ["WoodenBoard"] = 15,
            },
            {
                ["WoodenBoard"] = 16,
            },
            {
                ["WoodenBoard"] = 17,
            },
            {
                ["WoodenBoard"] = 18,
            },
            {
                ["WoodenBoard"] = 19,
            },
            {
                ["WoodenBoard"] = 20,
            },
            {
                ["WoodenBoard"] = 21,
            },
            {
                ["WoodenBoard"] = 22,
            },
            {
                ["WoodenBoard"] = 23,
            },
            {
                ["WoodenBoard"] = 36,
            },
        },
        ["van_count"] = {},
        ["zone_type"] = "Carpentry",
    },
    ["C1_Dorm_Bed"] = {
        ["id"] = "C1_Dorm_Bed",
        ["_tags_"] = {},
        ["animation"] = "sleeping",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "Bed",
        ["boost_reward"] = {},
        ["building_exp"] = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
        },
        ["capacity"] = 2,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
            2,
        },
        ["desc_key"] = "furniture_desc_Bed",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Bed",
        ["heart_fix"] = 313,
        ["icon"] = "Bed",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {
            "C1_Dorm_Boost1ForDorm",
        },
        ["load_limit"] = {},
        ["max_level"] = {
            20,
            20,
        },
        ["name_key"] = "furniture_name_Bed",
        ["necessities_reward"] = {
            {
                ["Rest"] = 10,
            },
            {
                ["Rest"] = 10.5,
            },
            {
                ["Rest"] = 11,
            },
            {
                ["Rest"] = 11.5,
            },
            {
                ["Rest"] = 12,
            },
            {
                ["Rest"] = 12.5,
            },
            {
                ["Rest"] = 13,
            },
            {
                ["Rest"] = 13.5,
            },
            {
                ["Rest"] = 14,
            },
            {
                ["Rest"] = 14.5,
            },
            {
                ["Rest"] = 15,
            },
            {
                ["Rest"] = 15.5,
            },
            {
                ["Rest"] = 16,
            },
            {
                ["Rest"] = 16.5,
            },
            {
                ["Rest"] = 17,
            },
            {
                ["Rest"] = 17.5,
            },
            {
                ["Rest"] = 18,
            },
            {
                ["Rest"] = 18.5,
            },
            {
                ["Rest"] = 19,
            },
            {
                ["Rest"] = 19.5,
            },
        },
        ["necessities_reward_sick"] = {
            {
                ["Health"] = 1,
            },
            {
                ["Health"] = 1.1,
            },
            {
                ["Health"] = 1.2,
            },
            {
                ["Health"] = 1.3,
            },
            {
                ["Health"] = 1.4,
            },
            {
                ["Health"] = 1.5,
            },
            {
                ["Health"] = 1.6,
            },
            {
                ["Health"] = 1.7,
            },
            {
                ["Health"] = 1.8,
            },
            {
                ["Health"] = 1.9,
            },
            {
                ["Health"] = 2,
            },
            {
                ["Health"] = 2.1,
            },
            {
                ["Health"] = 2.2,
            },
            {
                ["Health"] = 2.3,
            },
            {
                ["Health"] = 2.4,
            },
            {
                ["Health"] = 2.5,
            },
            {
                ["Health"] = 2.6,
            },
            {
                ["Health"] = 2.7,
            },
            {
                ["Health"] = 2.8,
            },
            {
                ["Health"] = 2.9,
            },
        },
        ["productor_type"] = 0,
        ["recover_reward"] = {
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
            {
                ["CureRate"] = 0.5,
            },
        },
        ["right_hand_id"] = {},
        ["right_hand_name"] = "",
        ["sort"] = 9,
        ["stage"] = {
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
        },
        ["usage_duration"] = {
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
            150,
        },
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Dorm",
    },
    ["C1_Dorm_Boost1ForDorm"] = {
        ["id"] = "C1_Dorm_Boost1ForDorm",
        ["_tags_"] = {},
        ["animation"] = "",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "Torch",
        ["boost_reward"] = {},
        ["building_exp"] = {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        },
        ["capacity"] = 0,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
            1,
        },
        ["desc_key"] = "furniture_desc_Torch",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Boost1ForDorm",
        ["heart_fix"] = 0,
        ["icon"] = "Torch",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            20,
            20,
        },
        ["name_key"] = "furniture_name_Torch",
        ["necessities_reward"] = {
            {
                ["Rest"] = 8,
            },
            {
                ["Rest"] = 8.4,
            },
            {
                ["Rest"] = 8.8,
            },
            {
                ["Rest"] = 9.2,
            },
            {
                ["Rest"] = 9.6,
            },
            {
                ["Rest"] = 10,
            },
            {
                ["Rest"] = 10.4,
            },
            {
                ["Rest"] = 10.8,
            },
            {
                ["Rest"] = 11.2,
            },
            {
                ["Rest"] = 11.6,
            },
            {
                ["Rest"] = 12,
            },
            {
                ["Rest"] = 12.4,
            },
            {
                ["Rest"] = 12.8,
            },
            {
                ["Rest"] = 13.2,
            },
            {
                ["Rest"] = 13.6,
            },
            {
                ["Rest"] = 14,
            },
            {
                ["Rest"] = 14.4,
            },
            {
                ["Rest"] = 14.8,
            },
            {
                ["Rest"] = 15.2,
            },
            {
                ["Rest"] = 15.6,
            },
        },
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 0,
        ["recover_reward"] = {},
        ["right_hand_id"] = {},
        ["right_hand_name"] = "",
        ["sort"] = 10,
        ["stage"] = {
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
            16.7,
        },
        ["usage_duration"] = {},
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Dorm",
    },
    ["C1_HunterCabin_Tool1ForHunterCabin"] = {
        ["id"] = "C1_HunterCabin_Tool1ForHunterCabin",
        ["_tags_"] = {},
        ["animation"] = "breed",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        },
        ["assets_name"] = "Spear",
        ["boost_reward"] = {},
        ["building_exp"] = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
        },
        ["capacity"] = 1,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            2,
            4,
        },
        ["desc_key"] = "furniture_desc_Spear",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Tool1ForHunterCabin",
        ["heart_fix"] = 250,
        ["icon"] = "Spear",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            20,
            20,
        },
        ["name_key"] = "furniture_name_Spear",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 2,
        ["recover_reward"] = {},
        ["right_hand_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["right_hand_name"] = "HandSpear",
        ["sort"] = 1,
        ["stage"] = {
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
        },
        ["usage_duration"] = {
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
        },
        ["usage_output"] = {
            {
                ["RawFood"] = 5,
            },
            {
                ["RawFood"] = 5.2,
            },
            {
                ["RawFood"] = 5.4,
            },
            {
                ["RawFood"] = 5.6,
            },
            {
                ["RawFood"] = 5.8,
            },
            {
                ["RawFood"] = 6,
            },
            {
                ["RawFood"] = 6.2,
            },
            {
                ["RawFood"] = 6.4,
            },
            {
                ["RawFood"] = 6.6,
            },
            {
                ["RawFood"] = 6.8,
            },
            {
                ["RawFood"] = 7,
            },
            {
                ["RawFood"] = 7.2,
            },
            {
                ["RawFood"] = 7.4,
            },
            {
                ["RawFood"] = 7.6,
            },
            {
                ["RawFood"] = 7.8,
            },
            {
                ["RawFood"] = 8,
            },
            {
                ["RawFood"] = 8.2,
            },
            {
                ["RawFood"] = 8.4,
            },
            {
                ["RawFood"] = 8.6,
            },
            {
                ["RawFood"] = 10.3,
            },
        },
        ["van_count"] = {},
        ["zone_type"] = "HunterCabin",
    },
    ["C1_Kitchen_Boost4ForKitchen"] = {
        ["id"] = "C1_Kitchen_Boost4ForKitchen",
        ["_tags_"] = {},
        ["animation"] = "",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "StorageShelf",
        ["boost_reward"] = {},
        ["building_exp"] = {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        },
        ["capacity"] = 0,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
        },
        ["desc_key"] = "furniture_desc_StorageShelf",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Boost4ForKitchen",
        ["heart_fix"] = 0,
        ["icon"] = "StorageShelf",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            10,
        },
        ["name_key"] = "furniture_name_StorageShelf",
        ["necessities_reward"] = {
            {
                ["Rest"] = 0.5,
            },
            {
                ["Rest"] = 1,
            },
            {
                ["Rest"] = 1.5,
            },
            {
                ["Rest"] = 2,
            },
            {
                ["Rest"] = 2.5,
            },
            {
                ["Rest"] = 3,
            },
            {
                ["Rest"] = 3.5,
            },
            {
                ["Rest"] = 4,
            },
            {
                ["Rest"] = 4.5,
            },
            {
                ["Rest"] = 5,
            },
        },
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 0,
        ["recover_reward"] = {},
        ["right_hand_id"] = {},
        ["right_hand_name"] = "",
        ["sort"] = 5,
        ["stage"] = {
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.7,
            17.7,
            17.7,
            17.7,
            17.7,
            17.7,
            17.7,
            17.7,
            17.7,
            17.7,
        },
        ["usage_duration"] = {},
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Kitchen",
    },
    ["C1_Kitchen_Burner"] = {
        ["id"] = "C1_Kitchen_Burner",
        ["_tags_"] = {},
        ["animation"] = "cooking",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2",
            "2",
            "2",
            "2",
        },
        ["assets_name"] = "Burner",
        ["boost_reward"] = {},
        ["building_exp"] = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
        },
        ["capacity"] = 1,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
        },
        ["desc_key"] = "furniture_desc_Burner",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = true,
        ["furniture_type"] = "Burner",
        ["heart_fix"] = 21,
        ["icon"] = "Burner",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            10,
        },
        ["name_key"] = "furniture_name_Burner",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 1,
        ["recover_reward"] = {},
        ["right_hand_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["right_hand_name"] = "HandBurner",
        ["sort"] = 2,
        ["stage"] = {
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
        },
        ["usage_duration"] = {
            2,
            1.9,
            1.8,
            1.7,
            1.6,
            1.5,
            1.4,
            1.3,
            1.2,
            1,
        },
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Kitchen",
    },
    ["C1_Kitchen_ServingTable"] = {
        ["id"] = "C1_Kitchen_ServingTable",
        ["_tags_"] = {},
        ["animation"] = "takeupsth",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "ServingTable",
        ["boost_reward"] = {},
        ["building_exp"] = {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        },
        ["capacity"] = 1,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
        },
        ["desc_key"] = "furniture_desc_ServingTable",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = true,
        ["furniture_type"] = "ServingTable",
        ["heart_fix"] = 2,
        ["icon"] = "ServingTable",
        ["is_passive"] = false,
        ["left_hand_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2",
            "2",
            "2",
            "2",
        },
        ["left_hand_name"] = "HandServingTableWalk",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            10,
        },
        ["name_key"] = "furniture_name_ServingTable",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 0,
        ["recover_reward"] = {},
        ["right_hand_id"] = {},
        ["right_hand_name"] = "",
        ["sort"] = 3,
        ["stage"] = {
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
        },
        ["usage_duration"] = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
        },
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Kitchen",
    },
    ["C1_Kitchen_Table"] = {
        ["id"] = "C1_Kitchen_Table",
        ["_tags_"] = {},
        ["animation"] = "eattingfood",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["assets_name"] = "Table",
        ["boost_reward"] = {},
        ["building_exp"] = {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        },
        ["capacity"] = 1,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            1,
        },
        ["desc_key"] = "furniture_desc_Table",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = true,
        ["furniture_type"] = "Table",
        ["heart_fix"] = 21,
        ["icon"] = "Table",
        ["is_passive"] = false,
        ["left_hand_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2",
            "2",
            "2",
            "2",
        },
        ["left_hand_name"] = "HandServingTable",
        ["linked_furnitures"] = {
            "C1_Kitchen_Boost4ForKitchen",
        },
        ["load_limit"] = {},
        ["max_level"] = {
            10,
        },
        ["name_key"] = "furniture_name_Table",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 0,
        ["recover_reward"] = {},
        ["right_hand_id"] = {},
        ["right_hand_name"] = "",
        ["sort"] = 4,
        ["stage"] = {
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.1,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
            17.2,
        },
        ["usage_duration"] = {
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
        },
        ["usage_output"] = {},
        ["van_count"] = {},
        ["zone_type"] = "Kitchen",
    },
    ["C1_Sawmill_Tool1ForSawmill"] = {
        ["id"] = "C1_Sawmill_Tool1ForSawmill",
        ["_tags_"] = {},
        ["animation"] = "cutTree",
        ["assets_address"] = "furnitures",
        ["assets_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2",
            "2",
            "2",
            "2",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
        },
        ["assets_name"] = "Axe",
        ["boost_reward"] = {},
        ["building_exp"] = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
        },
        ["capacity"] = 1,
        ["card_level_require"] = {
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
        },
        ["city_id"] = 1,
        ["count_in_room"] = {
            2,
            4,
        },
        ["desc_key"] = "furniture_desc_Axe",
        ["energy_cost"] = {},
        ["energy_reward"] = {},
        ["finished"] = false,
        ["furniture_type"] = "Tool1ForSawmill",
        ["heart_fix"] = 21,
        ["icon"] = "Axe",
        ["is_passive"] = false,
        ["left_hand_id"] = {},
        ["left_hand_name"] = "",
        ["linked_furnitures"] = {},
        ["load_limit"] = {},
        ["max_level"] = {
            50,
            50,
        },
        ["name_key"] = "furniture_name_Axe",
        ["necessities_reward"] = {},
        ["necessities_reward_sick"] = {},
        ["productor_type"] = 3,
        ["recover_reward"] = {},
        ["right_hand_id"] = {
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        },
        ["right_hand_name"] = "HandAxe",
        ["sort"] = 6,
        ["stage"] = {
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
            19,
        },
        ["usage_duration"] = {
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
        },
        ["usage_output"] = {
            {
                ["Wood"] = 13,
            },
            {
                ["Wood"] = 15.6,
            },
            {
                ["Wood"] = 18.2,
            },
            {
                ["Wood"] = 20.8,
            },
            {
                ["Wood"] = 23.4,
            },
            {
                ["Wood"] = 26,
            },
            {
                ["Wood"] = 28.6,
            },
            {
                ["Wood"] = 31.2,
            },
            {
                ["Wood"] = 33.8,
            },
            {
                ["Wood"] = 36.4,
            },
            {
                ["Wood"] = 39,
            },
            {
                ["Wood"] = 41.6,
            },
            {
                ["Wood"] = 44.2,
            },
            {
                ["Wood"] = 46.8,
            },
            {
                ["Wood"] = 49.4,
            },
            {
                ["Wood"] = 52,
            },
            {
                ["Wood"] = 54.6,
            },
            {
                ["Wood"] = 57.2,
            },
            {
                ["Wood"] = 59.8,
            },
            {
                ["Wood"] = 91,
            },
            {
                ["Wood"] = 93.6,
            },
            {
                ["Wood"] = 96.2,
            },
            {
                ["Wood"] = 98.8,
            },
            {
                ["Wood"] = 101.4,
            },
            {
                ["Wood"] = 104,
            },
            {
                ["Wood"] = 106.6,
            },
            {
                ["Wood"] = 109.2,
            },
            {
                ["Wood"] = 111.8,
            },
            {
                ["Wood"] = 114.4,
            },
            {
                ["Wood"] = 117,
            },
            {
                ["Wood"] = 119.6,
            },
            {
                ["Wood"] = 122.2,
            },
            {
                ["Wood"] = 124.8,
            },
            {
                ["Wood"] = 127.4,
            },
            {
                ["Wood"] = 130,
            },
            {
                ["Wood"] = 132.6,
            },
            {
                ["Wood"] = 137.8,
            },
            {
                ["Wood"] = 143,
            },
            {
                ["Wood"] = 148.2,
            },
            {
                ["Wood"] = 153.4,
            },
            {
                ["Wood"] = 158.6,
            },
            {
                ["Wood"] = 163.8,
            },
            {
                ["Wood"] = 169,
            },
            {
                ["Wood"] = 174.2,
            },
            {
                ["Wood"] = 180,
            },
            {
                ["Wood"] = 185,
            },
            {
                ["Wood"] = 190,
            },
            {
                ["Wood"] = 195,
            },
            {
                ["Wood"] = 200,
            },
            {
                ["Wood"] = 300,
            },
        },
        ["van_count"] = {},
        ["zone_type"] = "Sawmill",
    }, 
} 
