return {
    {
        ["ShopConf"] = "ShopConf",
        ["ad_close_reg_time"] = 1659523200,
        ["ad_close_reg_time_switch"] = false,
        ["ad_resource_claim_limit_daily"] = 20,
        ["ad_resource_free_get"] = {
            9,
        },
        ["ad_resource_icon_cd"] = {
            300,
            600,
        },
        ["ad_resource_icon_first_show"] = {
            180,
            300,
        },
        ["ad_resource_icon_max_show"] = 60,
        ["ad_resource_icon_show_cd"] = {
            300,
        },
        ["ads_icon_show_cd"] = 40,
        ["ads_items_type_limit"] = 3,
        ["ads_resource_per_minute"] = 10,
        ["ads_switch"] = true,
        ["android_admob_aduid"] = "ca-app-pub-8451717056497276/9882802919",
        ["appease_btn1"] = {
            ["icon_riots_bad_contempt"] = "ui_riots_bad_contempt",
            ["icon_riots_bad_riot"] = "ui_riots_bad_riot",
            ["icon_riots_bad_stop"] = "ui_riots_bad_stop",
        },
        ["appease_btn2"] = {
            ["icon_riots_normal_talk"] = "ui_riots_normal_talk",
            ["icon_riots_normal_think"] = "ui_riots_normal_think",
        },
        ["appease_btn3"] = {
            ["icon_riots_good_agree"] = "ui_riots_good_agree",
            ["icon_riots_good_peace"] = "ui_riots_good_peace",
            ["icon_riots_good_shake"] = "ui_riots_good_shake",
        },
        ["base_build_queue"] = 2,
        ["battle_robot_speed"] = 5,
        ["battle_robot_try"] = 1,
        ["battle_speedup_data"] = {
            1,
            1.25,
            1.5,
            2,
        },
        ["battle_speedup_time"] = {
            0,
            30,
            60,
            90,
        },
        ["black_market_enabled"] = true,
        ["black_market_limit_enabled"] = false,
        ["box_temp_price"] = 100,
        ["build_ticket_time"] = 2,
        ["building_ticket_switch"] = false,
        ["card_dissolve_enable"] = true,
        ["card_property_group_3"] = {
            0.1,
            0.1,
            0.1,
            0.1,
            1,
        },
        ["card_property_group_3_2"] = {
            0.15,
            0.15,
            0.15,
            0.15,
            2,
        },
        ["card_property_group_4"] = {
            0.18,
            0.15,
            0.18,
            0.15,
            2,
        },
        ["card_property_group_5"] = {
            0.2,
            0.2,
            0.2,
            0.2,
            3,
        },
        ["card_star_level"] = {
            20,
            40,
            60,
            80,
            100,
            110,
        },
        ["character_data_structure_version"] = 1,
        ["chef_idle_after_arbeit"] = 100,
        ["close_roof_size"] = 55,
        ["color_factor_Happness"] = {
            0.4,
            0.7,
            0.9,
            1,
        },
        ["color_factor_Health"] = {
            0.4,
            0.7,
            0.9,
            1,
        },
        ["constant1"] = 1,
        ["constant2"] = 13,
        ["constant3"] = 12.5,
        ["constant4"] = 1,
        ["currency_tga_filter"] = true,
        ["data_analysis_factor"] = {
            0,
            0.8,
            1,
            1.2,
        },
        ["data_analysis_factor_food"] = {
            0,
            0.6,
            0.8,
            1,
        },
        ["data_analysis_meme_desc"] = {
            "data_analysis_meme_desc_1",
            "data_analysis_meme_desc_2",
            "data_analysis_meme_desc_3",
            "data_analysis_meme_desc_4",
        },
        ["deadRate_sick"] = 0.1,
        ["default_camera_size"] = 45,
        ["default_max_offline_time"] = 7200,
        ["default_ui_scale"] = 1.8,
        ["diamond_confirm_count"] = 4,
        ["discord_url"] = "https://discord.gg/QmKfUE5KKT",
        ["event_car_default_speed"] = 8,
        ["event_farm_rank_userinfo_cost"] = 20,
        ["event_farm_warehouse_notice_update"] = 15,
        ["event_farm_warehouse_show_count"] = {
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
        },
        ["event_farm_warehouse_show_factor"] = {
            0,
            1,
            2,
            3,
            5,
            7,
            9,
            11,
            13,
            15,
            17,
            19,
            22,
            25,
            30,
            35,
            40,
            45,
            50,
            100,
        },
        ["event_unlock_rank_milestone"] = 2,
        ["explore_monster_rank_make_up_level"] = {
            20,
            30,
            40,
            50,
            60,
            70,
            100,
            200,
        },
        ["explore_monster_rank_make_up_value"] = {
            1,
            1.2,
            1.5,
            1.8,
            2.1,
            2.4,
            2.5,
            2.6,
        },
        ["facebook_url"] = "https://www.facebook.com/frozencitygame",
        ["generator_consumption_alarm"] = 10,
        ["generator_overload_resource_times"] = 2,
        ["generator_overload_temp_buff"] = 2,
        ["guide_battle_skill_cd"] = 2,
        ["heavy_snow_show_random_period"] = {
            "100|200",
            "300|400",
            "2000|2100",
            "2200|2300",
        },
        ["hero_move_speed"] = 2.5,
        ["hide_building_info"] = 150,
        ["hide_camera_size"] = 55,
        ["host_dev1"] = "https://frozencity-develop-game-online.centurygame.com",
        ["host_prod1"] = "https://fct-prod-game-online-apa.centurygame.com",
        ["host_prod2"] = "https://fct-prod-game-online.centurygames.net",
        ["host_prod3"] = "https://frozencity-prod-game-online.centurygame.com",
        ["http_compress"] = true,
        ["http_scheme"] = 1,
        ["ios_admob_aduid"] = "ca-app-pub-8451717056497276/9882802919",
        ["is_necessities_low_die"] = true,
        ["is_skip_protest_talk"] = false,
        ["is_storm_offline_pause"] = true,
        ["last_scene_index"] = 0,
        ["level_idle_drop_gap"] = 5,
        ["level_idle_drop_minute"] = 120,
        ["limit_camera_size"] = 22,
        ["limit_ui_scale"] = 1,
        ["mission_discord_popup"] = {
            20011010,
            40011017,
        },
        ["night_settlement_icon_show_duration"] = 180,
        ["night_settlement_icon_show_time"] = 2400,
        ["night_settlement_switch"] = true,
        ["notice_unlock_city_level"] = 0,
        ["number_of_people_never_get_sick"] = 4,
        ["number_of_people_never_protest"] = 12,
        ["number_of_people_never_strike_event"] = 8,
        ["office_idle_gang"] = {
            "ManA_idle",
            "ManA_idle_3",
            "ManA_eattingsnack",
            "ManA_seeking",
            "ManA_idle_hungry",
        },
        ["office_idle_scientist"] = {
            "ManA_idle",
            "ManA_idle_2",
            "ManA_idle_3",
            "ManA_eattingsnack",
            "ManA_idle_hungry",
            "ManA_resarch",
            "ManA_look",
            "ManA_reading",
        },
        ["office_idle_soilder"] = {
            "ManA_idle",
            "ManA_idle_3",
            "ManA_eattingsnack",
            "ManA_seeking",
            "ManA_idle_hungry",
        },
        ["offline_default_factor"] = 0.3,
        ["offline_final_factor"] = 1,
        ["payment_subscription_delay_expire"] = 0,
        ["people_first4_come_immediately"] = true,
        ["people_move_speed"] = 2.5,
        ["people_new_cooldown"] = {
            3,
            3,
        },
        ["people_refresh_cooldown"] = {
            20,
            30,
        },
        ["people_refresh_cooldown_event"] = {
            3,
            5,
        },
        ["people_relive_cooldown"] = {
            180,
            180,
        },
        ["privacy_url"] = "https://www.centurygames.com/privacy-policy/",
        ["profile_change_free_count"] = 1,
        ["profile_change_gem_count"] = 20,
        ["protest_appease_count"] = 2,
        ["protest_appease_count_reflash"] = 30,
        ["protest_appease_effect"] = {
            ["Bad"] = 0.6,
            ["Good"] = 1.5,
            ["Normal"] = 1,
        },
        ["protest_boost_no_card"] = 10,
        ["protest_emoji_duration"] = 3,
        ["protest_enabled"] = true,
        ["protest_safe_line"] = 100,
        ["push_notify_cooldown"] = 3600,
        ["replenish_people_frequency"] = 300,
        ["replenish_people_frequency_event"] = 100,
        ["replenish_people_once"] = 1,
        ["replenish_people_once_event"] = 3,
        ["reply_desc_people1"] = {
            "protest_reply_bad_liar",
            "protest_reply_bad_frozen",
            "protest_reply_bad_sexism",
            "protest_reply_bad_stupid",
            "protest_reply_bad_not_work",
            "protest_reply_bad_disappointed",
            "protest_reply_bad_darkness",
        },
        ["reply_desc_people2"] = {
            "protest_reply_normal_doubt",
            "protest_reply_normal_upset",
            "protest_reply_normal_hard",
            "protest_reply_normal_tried",
            "protest_reply_normal_right",
            "protest_reply_normal_communicate",
            "protest_reply_normal_trouble",
        },
        ["reply_desc_people3"] = {
            "protest_reply_good_misunderstand",
            "protest_reply_good_hope",
            "protest_reply_good_generous",
            "protest_reply_good_effective",
            "protest_reply_good_satisfied",
            "protest_reply_good_thankful",
            "protest_reply_good_guilty",
            "protest_reply_good_believe",
        },
        ["reset_card_exp_price"] = {
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
        },
        ["reset_card_unlock_city"] = 2,
        ["resource_gem_price_hour"] = 100,
        ["resources_tip_int"] = 3,
        ["reward_panel_auto_close_sec"] = 30,
        ["rogue_after_battle_time"] = 3,
        ["rogue_before_battle_time"] = 2,
        ["rogue_collect_animation_name"] = "operate",
        ["rogue_interact_cost"] = 10,
        ["rogue_like_card_chest_price"] = 100,
        ["rogue_like_reset_clock"] = 0,
        ["rogue_like_reset_time_scale"] = 1,
        ["rogue_map_list"] = {
            "RoguelikeMap",
            "RoguelikeMap2",
        },
        ["rogue_max_energy"] = 150,
        ["screen_fronzen_effect"] = true,
        ["service_url"] = "https://www.centurygames.com/terms-of-service/",
        ["show_account_delete"] = true,
        ["show_appleid_bind"] = true,
        ["show_cdkeys"] = false,
        ["show_facebook_bind"] = true,
        ["show_google_bind"] = true,
        ["snow_show_random_period"] = {
            "700|800",
            "1000|1100",
            "1300|1400",
            "1600|1700",
            "1800|1900",
        },
        ["social_stay_time"] = {
            3,
            600,
        },
        ["speed_start_run"] = 4,
        ["standard_interactive_time"] = 30,
        ["storm_enable"] = true,
        ["survey_config"] = [==[{"id":"survey1","trigger":{"cityId":4,"zoneId":"C4_Kitchen_1"},"rewards":"addToItem*100?id=Gem","survey":[{"hash":"GN3LSW9","createTime":1644638400},{"hash":"GN3LSW9","createTime":1633017600}]}]==],
        ["test_firebase_ab"] = "A",
        ["test_firebase_bool"] = false,
        ["test_firebase_int"] = 123,
        ["test_firebase_json"] = {
            1,
            2,
            3,
        },
        ["test_firebase_str"] = [==["123"]==],
        ["time_wrap_diamonds_count"] = 1,
        ["time_wrap_min"] = 0.33333333333,
        ["unlock_battle_auto"] = 5,
        ["warm_stage"] = {
            -60,
            -40,
            -20,
            0,
            20,
        },
        ["warm_stage_name"] = {
            "极寒",
            "严寒",
            "寒冷",
            "微冷",
            "舒适",
            "温暖",
        },
        ["work_overtime_enabled"] = true,
        ["work_overtime_reset_clock"] = 700,
        ["x_header_key"] = "x-todo",
        ["x_header_val"] = "5",
        ["offline_day_ad"] = 3,
        ["ad_offline_timing"] = 1800,
        ["Kitchen_food_day_ad"] = 5,
        ["ad_food_rwd"] = "addToItem*10?id=FoodLow",
        ["Assist_day_ad"] = 3,
        ["ad_Assist_timing"] = 1800,
        ["ad_day_limit"] = 30,
    },
}
