return {
    ["C10000_Office_1"] = {
        ["id"] = "C10000_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 10000,
    },
    ["C10_Office_1"] = {
        ["id"] = "C10_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 10,
    },
    ["C2_Office_1"] = {
        ["id"] = "C2_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_move_speed",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "offline",
            "generator",
            "construction",
            "move_speed",
        },
        ["city_id"] = 2,
    },
    ["C3_Office_1"] = {
        ["id"] = "C3_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 3,
    },
    ["C4_Office_1"] = {
        ["id"] = "C4_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 4,
    },
    ["C5_Office_1"] = {
        ["id"] = "C5_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 5,
    },
    ["C6_Office_1"] = {
        ["id"] = "C6_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 6,
    },
    ["C7_Office_1"] = {
        ["id"] = "C7_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 7,
    },
    ["C8_Office_1"] = {
        ["id"] = "C8_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 8,
    },
    ["C9_Office_1"] = {
        ["id"] = "C9_Office_1",
        ["card_desc"] = {
            "office_assign_resource1",
            "office_assign_resource2",
            "office_assign_resource3",
            "office_assign_resource4",
            "office_assign_offline",
            "office_assign_generator",
            "office_assign_construction",
            "office_assign_idle_battle",
            "office_assign_move_speed",
            "office_assign_protest",
        },
        ["card_slot_types"] = {
            "resource1",
            "resource2",
            "resource3",
            "resource4",
            "offline",
            "generator",
            "construction",
            "idle_battle",
            "move_speed",
            "protest",
        },
        ["city_id"] = 9,
    },
}
