return {
    ["10001"] = {
        ["id"] = "10001",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 70,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_10001",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["10002"] = {
        ["id"] = "10002",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 40,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_10002",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["10003"] = {
        ["id"] = "10003",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_10003",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["10004"] = {
        ["id"] = "10004",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 50,
            ["Good"] = 50,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_10004",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["10005"] = {
        ["id"] = "10005",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 20,
            ["Good"] = 60,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_10005",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["10006"] = {
        ["id"] = "10006",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_10006",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["10007"] = {
        ["id"] = "10007",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 40,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_10007",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 2,
    },
    ["10008"] = {
        ["id"] = "10008",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 0,
            ["Normal"] = 70,
        },
        ["desc"] = "protest_appease_10008",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["10009"] = {
        ["id"] = "10009",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 0,
            ["Normal"] = 70,
        },
        ["desc"] = "protest_appease_10009",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["1001"] = {
        ["id"] = "1001",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_1001",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_frozen",
        },
        ["weight"] = 2,
    },
    ["10010"] = {
        ["id"] = "10010",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 40,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_10010",
        ["group"] = 10,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["1002"] = {
        ["id"] = "1002",
        ["appease_cost"] = -960,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_1002",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["1003"] = {
        ["id"] = "1003",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 0,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_1003",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 20,
    },
    ["1004"] = {
        ["id"] = "1004",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 50,
            ["Good"] = 0,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_1004",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["1005"] = {
        ["id"] = "1005",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_1005",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["1006"] = {
        ["id"] = "1006",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 20,
            ["Good"] = 20,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_1006",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_frozen",
        },
        ["weight"] = 2,
    },
    ["1007"] = {
        ["id"] = "1007",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_1007",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["1008"] = {
        ["id"] = "1008",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_1008",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["1009"] = {
        ["id"] = "1009",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_1009",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["1010"] = {
        ["id"] = "1010",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_1010",
        ["group"] = 1,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["11001"] = {
        ["id"] = "11001",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_11001",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["11002"] = {
        ["id"] = "11002",
        ["appease_cost"] = 1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_11002",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["11003"] = {
        ["id"] = "11003",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 80,
            ["Good"] = 10,
            ["Normal"] = 10,
        },
        ["desc"] = "protest_appease_11003",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["11004"] = {
        ["id"] = "11004",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_11004",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["11005"] = {
        ["id"] = "11005",
        ["appease_cost"] = -1200,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 40,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_11005",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["11006"] = {
        ["id"] = "11006",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_11006",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["11007"] = {
        ["id"] = "11007",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 40,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_11007",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["11008"] = {
        ["id"] = "11008",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 100,
            ["Good"] = 0,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_11008",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["11009"] = {
        ["id"] = "11009",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_11009",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 10,
    },
    ["11010"] = {
        ["id"] = "11010",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_11010",
        ["group"] = 11,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["12001"] = {
        ["id"] = "12001",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_12001",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["12002"] = {
        ["id"] = "12002",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_12002",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["12003"] = {
        ["id"] = "12003",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 50,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_12003",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["12004"] = {
        ["id"] = "12004",
        ["appease_cost"] = 1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 100,
            ["Good"] = 0,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_12004",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 10,
    },
    ["12005"] = {
        ["id"] = "12005",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_12005",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["12006"] = {
        ["id"] = "12006",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 50,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_12006",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["12007"] = {
        ["id"] = "12007",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_12007",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["12008"] = {
        ["id"] = "12008",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 90,
            ["Good"] = 10,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_12008",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 10,
    },
    ["12009"] = {
        ["id"] = "12009",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 80,
            ["Good"] = 20,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_12009",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 10,
    },
    ["12010"] = {
        ["id"] = "12010",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 60,
            ["Good"] = 40,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_12010",
        ["group"] = 12,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["13001"] = {
        ["id"] = "13001",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 70,
            ["Good"] = 10,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_13001",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 2,
    },
    ["13002"] = {
        ["id"] = "13002",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_13002",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["13003"] = {
        ["id"] = "13003",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_13003",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["13004"] = {
        ["id"] = "13004",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_13004",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["13005"] = {
        ["id"] = "13005",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_13005",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["13006"] = {
        ["id"] = "13006",
        ["appease_cost"] = -960,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 40,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_13006",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["13007"] = {
        ["id"] = "13007",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_13007",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["13008"] = {
        ["id"] = "13008",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_13008",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["13009"] = {
        ["id"] = "13009",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_13009",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["13010"] = {
        ["id"] = "13010",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_13010",
        ["group"] = 13,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["14001"] = {
        ["id"] = "14001",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_14001",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["14002"] = {
        ["id"] = "14002",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_14002",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["14003"] = {
        ["id"] = "14003",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_14003",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 2,
    },
    ["14004"] = {
        ["id"] = "14004",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_14004",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["14005"] = {
        ["id"] = "14005",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_14005",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["14006"] = {
        ["id"] = "14006",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_14006",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["14007"] = {
        ["id"] = "14007",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_14007",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["14008"] = {
        ["id"] = "14008",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_14008",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["14009"] = {
        ["id"] = "14009",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_14009",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 2,
    },
    ["14010"] = {
        ["id"] = "14010",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 20,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_14010",
        ["group"] = 14,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 10,
    },
    ["15001"] = {
        ["id"] = "15001",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_15001",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["15002"] = {
        ["id"] = "15002",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_15002",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["15003"] = {
        ["id"] = "15003",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_15003",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["15004"] = {
        ["id"] = "15004",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_15004",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 2,
    },
    ["15005"] = {
        ["id"] = "15005",
        ["appease_cost"] = 480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 30,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_15005",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["15006"] = {
        ["id"] = "15006",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_15006",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["15007"] = {
        ["id"] = "15007",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_15007",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["15008"] = {
        ["id"] = "15008",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_15008",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["15009"] = {
        ["id"] = "15009",
        ["appease_cost"] = 240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 70,
            ["Good"] = 10,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_15009",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["15010"] = {
        ["id"] = "15010",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_15010",
        ["group"] = 15,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["16001"] = {
        ["id"] = "16001",
        ["appease_cost"] = -960,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 80,
            ["Normal"] = 10,
        },
        ["desc"] = "protest_appease_16001",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["16002"] = {
        ["id"] = "16002",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_16002",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 10,
    },
    ["16003"] = {
        ["id"] = "16003",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_16003",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["16004"] = {
        ["id"] = "16004",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 50,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_16004",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["16005"] = {
        ["id"] = "16005",
        ["appease_cost"] = 480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 60,
            ["Good"] = 20,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_16005",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["16006"] = {
        ["id"] = "16006",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 20,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_16006",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 2,
    },
    ["16007"] = {
        ["id"] = "16007",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 20,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_16007",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["16008"] = {
        ["id"] = "16008",
        ["appease_cost"] = -960,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_16008",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["16009"] = {
        ["id"] = "16009",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 60,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_16009",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["16010"] = {
        ["id"] = "16010",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 80,
            ["Good"] = 0,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_16010",
        ["group"] = 16,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["2001"] = {
        ["id"] = "2001",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 50,
            ["Good"] = 30,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_2001",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["2002"] = {
        ["id"] = "2002",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_2002",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["2003"] = {
        ["id"] = "2003",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_2003",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["2004"] = {
        ["id"] = "2004",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_2004",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["2005"] = {
        ["id"] = "2005",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_2005",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["2006"] = {
        ["id"] = "2006",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_2006",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["2007"] = {
        ["id"] = "2007",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_2007",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["2008"] = {
        ["id"] = "2008",
        ["appease_cost"] = -720,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 40,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_2008",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["2009"] = {
        ["id"] = "2009",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_2009",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["2010"] = {
        ["id"] = "2010",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_2010",
        ["group"] = 2,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["3001"] = {
        ["id"] = "3001",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_3001",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["3002"] = {
        ["id"] = "3002",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_3002",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["3003"] = {
        ["id"] = "3003",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_3003",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["3004"] = {
        ["id"] = "3004",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_3004",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 2,
    },
    ["3005"] = {
        ["id"] = "3005",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_3005",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["3006"] = {
        ["id"] = "3006",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_3006",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 10,
    },
    ["3007"] = {
        ["id"] = "3007",
        ["appease_cost"] = -120,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 10,
            ["Normal"] = 90,
        },
        ["desc"] = "protest_appease_3007",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["3008"] = {
        ["id"] = "3008",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_3008",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 2,
    },
    ["3009"] = {
        ["id"] = "3009",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_3009",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 10,
    },
    ["3010"] = {
        ["id"] = "3010",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_3010",
        ["group"] = 3,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["4001"] = {
        ["id"] = "4001",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_4001",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["4002"] = {
        ["id"] = "4002",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_4002",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["4003"] = {
        ["id"] = "4003",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_4003",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["4004"] = {
        ["id"] = "4004",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_4004",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["4005"] = {
        ["id"] = "4005",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_4005",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["4006"] = {
        ["id"] = "4006",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_4006",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 10,
    },
    ["4007"] = {
        ["id"] = "4007",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_4007",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["4008"] = {
        ["id"] = "4008",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_4008",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["4009"] = {
        ["id"] = "4009",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 20,
            ["Good"] = 40,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_4009",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 2,
    },
    ["4010"] = {
        ["id"] = "4010",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_4010",
        ["group"] = 4,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["5001"] = {
        ["id"] = "5001",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 40,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_5001",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["5002"] = {
        ["id"] = "5002",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_5002",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["5003"] = {
        ["id"] = "5003",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 20,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_5003",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["5004"] = {
        ["id"] = "5004",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_5004",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["5005"] = {
        ["id"] = "5005",
        ["appease_cost"] = 240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 30,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_5005",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["5006"] = {
        ["id"] = "5006",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_5006",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["5007"] = {
        ["id"] = "5007",
        ["appease_cost"] = -1200,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 40,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_5007",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["5008"] = {
        ["id"] = "5008",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_5008",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["5009"] = {
        ["id"] = "5009",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_5009",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["5010"] = {
        ["id"] = "5010",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 80,
            ["Good"] = 0,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_5010",
        ["group"] = 5,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 2,
    },
    ["6001"] = {
        ["id"] = "6001",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 100,
            ["Good"] = 0,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_6001",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_sexism",
        },
        ["weight"] = 10,
    },
    ["6002"] = {
        ["id"] = "6002",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 20,
            ["Good"] = 60,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_6002",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["6003"] = {
        ["id"] = "6003",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 80,
            ["Good"] = 0,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_6003",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_guilty",
            "protest_reply_normal_upset",
            "protest_reply_bad_darkness",
        },
        ["weight"] = 2,
    },
    ["6004"] = {
        ["id"] = "6004",
        ["appease_cost"] = -3,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 60,
            ["Good"] = 20,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_6004",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_sexism",
        },
        ["weight"] = 2,
    },
    ["6005"] = {
        ["id"] = "6005",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 40,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_6005",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["6006"] = {
        ["id"] = "6006",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 40,
            ["Good"] = 20,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_6006",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["6007"] = {
        ["id"] = "6007",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_6007",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["6008"] = {
        ["id"] = "6008",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 50,
            ["Good"] = 20,
            ["Normal"] = 30,
        },
        ["desc"] = "protest_appease_6008",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["6009"] = {
        ["id"] = "6009",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 50,
            ["Good"] = 0,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_6009",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_sexism",
        },
        ["weight"] = 2,
    },
    ["6010"] = {
        ["id"] = "6010",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_6010",
        ["group"] = 6,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["7001"] = {
        ["id"] = "7001",
        ["appease_cost"] = -1200,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 100,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_7001",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["7002"] = {
        ["id"] = "7002",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_7002",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["7003"] = {
        ["id"] = "7003",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_7003",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["7004"] = {
        ["id"] = "7004",
        ["appease_cost"] = -960,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 40,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_7004",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["7005"] = {
        ["id"] = "7005",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_7005",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["7006"] = {
        ["id"] = "7006",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_7006",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 2,
    },
    ["7007"] = {
        ["id"] = "7007",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_7007",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 10,
    },
    ["7008"] = {
        ["id"] = "7008",
        ["appease_cost"] = -3,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_7008",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 2,
    },
    ["7009"] = {
        ["id"] = "7009",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_7009",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_liar",
        },
        ["weight"] = 20,
    },
    ["7010"] = {
        ["id"] = "7010",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_7010",
        ["group"] = 7,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 2,
    },
    ["8001"] = {
        ["id"] = "8001",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 100,
            ["Good"] = 40,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_8001",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 2,
    },
    ["8002"] = {
        ["id"] = "8002",
        ["appease_cost"] = -480,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 40,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_8002",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["8003"] = {
        ["id"] = "8003",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_8003",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_frozen",
        },
        ["weight"] = 20,
    },
    ["8004"] = {
        ["id"] = "8004",
        ["appease_cost"] = -1200,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_8004",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
    ["8005"] = {
        ["id"] = "8005",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_8005",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_tried",
            "protest_reply_bad_frozen",
        },
        ["weight"] = 2,
    },
    ["8006"] = {
        ["id"] = "8006",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 30,
            ["Good"] = 30,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_8006",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["8007"] = {
        ["id"] = "8007",
        ["appease_cost"] = -960,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 80,
            ["Normal"] = 20,
        },
        ["desc"] = "protest_appease_8007",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["8008"] = {
        ["id"] = "8008",
        ["appease_cost"] = -720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 60,
            ["Normal"] = 40,
        },
        ["desc"] = "protest_appease_8008",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["8009"] = {
        ["id"] = "8009",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_8009",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["8010"] = {
        ["id"] = "8010",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_8010",
        ["group"] = 8,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["9001"] = {
        ["id"] = "9001",
        ["appease_cost"] = -1,
        ["appease_type"] = "PeopleSick",
        ["appease_weight"] = {
            ["Bad"] = 100,
            ["Good"] = 20,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_9001",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 2,
    },
    ["9002"] = {
        ["id"] = "9002",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_9002",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["9003"] = {
        ["id"] = "9003",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_9003",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["9004"] = {
        ["id"] = "9004",
        ["appease_cost"] = 720,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 100,
            ["Good"] = 30,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_9004",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_thankful",
            "protest_reply_normal_hard",
            "protest_reply_bad_disappointed",
        },
        ["weight"] = 10,
    },
    ["9005"] = {
        ["id"] = "9005",
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_9005",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["9006"] = {
        ["id"] = "9006",
        ["appease_cost"] = -2,
        ["appease_type"] = "PeopleLose",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 40,
            ["Normal"] = 60,
        },
        ["desc"] = "protest_appease_9006",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 2,
    },
    ["9007"] = {
        ["id"] = "9007",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 0,
            ["Good"] = 20,
            ["Normal"] = 80,
        },
        ["desc"] = "protest_appease_9007",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_believe",
            "protest_reply_normal_doubt",
            "protest_reply_bad_stupid",
        },
        ["weight"] = 20,
    },
    ["9008"] = {
        ["id"] = "9008",
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 90,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_9008",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 10,
    },
    ["9009"] = {
        ["id"] = "9009",
        ["appease_cost"] = -240,
        ["appease_type"] = "Resources",
        ["appease_weight"] = {
            ["Bad"] = 80,
            ["Good"] = 20,
            ["Normal"] = 0,
        },
        ["desc"] = "protest_appease_9009",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 20,
    },
    ["9010"] = {
        ["id"] = "9010",
        ["appease_cost"] = -720,
        ["appease_type"] = "BurnRes",
        ["appease_weight"] = {
            ["Bad"] = 10,
            ["Good"] = 40,
            ["Normal"] = 50,
        },
        ["desc"] = "protest_appease_9010",
        ["group"] = 9,
        ["reply_desc"] = {
            "protest_reply_good_satisfied",
            "protest_reply_normal_not_bad",
            "protest_reply_bad_not_work",
        },
        ["weight"] = 15,
    },
}
