return {
    ["1001"] = {
        ["id"] = "1001",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -600,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 1,
        ["weight"] = 5,
    },
    ["1002"] = {
        ["id"] = "1002",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -640,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 1,
        ["weight"] = 15,
    },
    ["1003"] = {
        ["id"] = "1003",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 1,
        ["weight"] = 20,
    },
    ["1004"] = {
        ["id"] = "1004",
        ["anti_anger"] = 0.2,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_normal_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 2,
        ["weight"] = 5,
    },
    ["1005"] = {
        ["id"] = "1005",
        ["anti_anger"] = 0.08,
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["card_reply"] = "card_reply_normal_None_lose",
        ["group"] = 1,
        ["sub_group"] = 2,
        ["weight"] = 10,
    },
    ["1006"] = {
        ["id"] = "1006",
        ["anti_anger"] = 0.2,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_normal_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 2,
        ["weight"] = 5,
    },
    ["1007"] = {
        ["id"] = "1007",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -160,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
    ["1008"] = {
        ["id"] = "1008",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -160,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
    ["1009"] = {
        ["id"] = "1009",
        ["anti_anger"] = 0.12,
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["card_reply"] = "card_reply_good_None_lose",
        ["group"] = 1,
        ["sub_group"] = 3,
        ["weight"] = 10,
    },
    ["1010"] = {
        ["id"] = "1010",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 1,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
    ["2001"] = {
        ["id"] = "2001",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -800,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 1,
        ["weight"] = 5,
    },
    ["2002"] = {
        ["id"] = "2002",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -640,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 1,
        ["weight"] = 5,
    },
    ["2003"] = {
        ["id"] = "2003",
        ["anti_anger"] = 0.04,
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["card_reply"] = "card_reply_bad_None_lose",
        ["group"] = 2,
        ["sub_group"] = 1,
        ["weight"] = 10,
    },
    ["2004"] = {
        ["id"] = "2004",
        ["anti_anger"] = 0.2,
        ["appease_cost"] = -640,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_normal_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 2,
        ["weight"] = 20,
    },
    ["2005"] = {
        ["id"] = "2005",
        ["anti_anger"] = 0.08,
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["card_reply"] = "card_reply_normal_None_lose",
        ["group"] = 2,
        ["sub_group"] = 2,
        ["weight"] = 10,
    },
    ["2006"] = {
        ["id"] = "2006",
        ["anti_anger"] = 0.2,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_normal_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 2,
        ["weight"] = 5,
    },
    ["2007"] = {
        ["id"] = "2007",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 3,
        ["weight"] = 5,
    },
    ["2008"] = {
        ["id"] = "2008",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 3,
        ["weight"] = 15,
    },
    ["2009"] = {
        ["id"] = "2009",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -320,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
    ["2010"] = {
        ["id"] = "2010",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -160,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 2,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
    ["3001"] = {
        ["id"] = "3001",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -800,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 1,
        ["weight"] = 5,
    },
    ["3002"] = {
        ["id"] = "3002",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 1,
        ["weight"] = 20,
    },
    ["3003"] = {
        ["id"] = "3003",
        ["anti_anger"] = 0.1,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_bad_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 1,
        ["weight"] = 20,
    },
    ["3004"] = {
        ["id"] = "3004",
        ["anti_anger"] = 0.2,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_normal_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 2,
        ["weight"] = 5,
    },
    ["3005"] = {
        ["id"] = "3005",
        ["anti_anger"] = 0.2,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_normal_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 2,
        ["weight"] = 20,
    },
    ["3006"] = {
        ["id"] = "3006",
        ["anti_anger"] = 0.08,
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["card_reply"] = "card_reply_normal_None_lose",
        ["group"] = 3,
        ["sub_group"] = 2,
        ["weight"] = 10,
    },
    ["3007"] = {
        ["id"] = "3007",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
    ["3008"] = {
        ["id"] = "3008",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -480,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 3,
        ["weight"] = 5,
    },
    ["3009"] = {
        ["id"] = "3009",
        ["anti_anger"] = 0.12,
        ["appease_cost"] = 0,
        ["appease_type"] = "None",
        ["card_reply"] = "card_reply_good_None_lose",
        ["group"] = 3,
        ["sub_group"] = 3,
        ["weight"] = 10,
    },
    ["3010"] = {
        ["id"] = "3010",
        ["anti_anger"] = 0.3,
        ["appease_cost"] = -160,
        ["appease_type"] = "Resources",
        ["card_reply"] = "card_reply_good_Resources_lose",
        ["group"] = 3,
        ["sub_group"] = 3,
        ["weight"] = 20,
    },
}
