return {
    ["PushEventBuilding"] = {
        ["id"] = "PushEventBuilding",
        ["desc"] = "notice_content_event_building_desc",
        ["icon"] = "icon_notice_event_building",
        ["lang"] = {},
        ["params"] = "",
        ["title"] = "GameName",
        ["type"] = "",
    },
    ["PushEventOffline"] = {
        ["id"] = "PushEventOffline",
        ["desc"] = "notice_content_event_offline_desc",
        ["icon"] = "icon_notice_event_offline",
        ["lang"] = {},
        ["params"] = "",
        ["title"] = "GameName",
        ["type"] = "",
    },
    ["PushEventStart"] = {
        ["id"] = "PushEventStart",
        ["desc"] = "notice_content_event_start_desc",
        ["icon"] = "icon_notice_event_start",
        ["lang"] = {
            "en",
            "zh_cn",
        },
        ["params"] = "",
        ["title"] = "GameName",
        ["type"] = "global",
    },
    ["PushFightOffline"] = {
        ["id"] = "PushFightOffline",
        ["desc"] = "notice_content_fight_offline_desc",
        ["icon"] = "icon_notice_fight_offline",
        ["lang"] = {},
        ["params"] = "",
        ["title"] = "GameName",
        ["type"] = "",
    },
    ["PushFreeBox"] = {
        ["id"] = "PushFreeBox",
        ["desc"] = "notice_content_free_box_desc",
        ["icon"] = "icon_notice_free_box",
        ["lang"] = {},
        ["params"] = [==[{"shopId":[11,1110]}]==],
        ["title"] = "GameName",
        ["type"] = "",
    },
    ["PushMainBuilding"] = {
        ["id"] = "PushMainBuilding",
        ["desc"] = "notice_content_building_desc",
        ["icon"] = "icon_notice_building",
        ["lang"] = {},
        ["params"] = "",
        ["title"] = "GameName",
        ["type"] = "",
    },
    ["PushMainOffline"] = {
        ["id"] = "PushMainOffline",
        ["desc"] = "notice_content_main_offline_desc",
        ["icon"] = "icon_notice_main_offline",
        ["lang"] = {},
        ["params"] = "",
        ["title"] = "GameName",
        ["type"] = "",
    },
    ["PushMockEventStart"] = {
        ["id"] = "PushMockEventStart",
        ["desc"] = "notice_content_event_start_desc",
        ["icon"] = "icon_notice_event_start",
        ["lang"] = {
            "en",
            "zh_cn",
        },
        ["params"] = [==[{"env":"develop"}]==],
        ["title"] = "GameName",
        ["type"] = "global",
    },
}
