return {
    ["C1_Arbeit"] = {
        ["id"] = "C1_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 1,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "FarmerWood",
            "Worker",
            "Coalman",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "430|1200,1430|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C1_Cooking"] = {
        ["id"] = "C1_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 1,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "430|1200,1430|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C1_Eat"] = {
        ["id"] = "C1_Eat",
        ["StopType"] = 2,
        ["city_id"] = 1,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1430,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C1_Hunting"] = {
        ["id"] = "C1_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 1,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "430|1200,1430|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C1_Sleep"] = {
        ["id"] = "C1_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 1,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|430",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C2_Arbeit"] = {
        ["id"] = "C2_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 2,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Miner",
            "Digger",
            "Worker",
            "Metalman",
            "Worker2",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "430|1200,1500|2030",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C2_Arbeit_OverTime"] = {
        ["id"] = "C2_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 2,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Miner",
            "Digger",
            "Worker",
            "Metalman",
            "Worker2",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|430",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C2_Cooking"] = {
        ["id"] = "C2_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 2,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "430|1200,1500|2030",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C2_Eat"] = {
        ["id"] = "C2_Eat",
        ["StopType"] = 2,
        ["city_id"] = 2,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2030|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C2_Hunting"] = {
        ["id"] = "C2_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 2,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "430|1200,1500|2030",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C2_Sleep"] = {
        ["id"] = "C2_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 2,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|430",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C3_Arbeit"] = {
        ["id"] = "C3_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 3,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C3_Arbeit_OverTime"] = {
        ["id"] = "C3_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 3,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C3_Cooking"] = {
        ["id"] = "C3_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 3,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C3_Eat"] = {
        ["id"] = "C3_Eat",
        ["StopType"] = 2,
        ["city_id"] = 3,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C3_Hunting"] = {
        ["id"] = "C3_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 3,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C3_Sleep"] = {
        ["id"] = "C3_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 3,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C4_Arbeit"] = {
        ["id"] = "C4_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 4,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C4_Arbeit_OverTime"] = {
        ["id"] = "C4_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 4,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C4_Cooking"] = {
        ["id"] = "C4_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 4,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C4_Eat"] = {
        ["id"] = "C4_Eat",
        ["StopType"] = 2,
        ["city_id"] = 4,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C4_Hunting"] = {
        ["id"] = "C4_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 4,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C4_Sleep"] = {
        ["id"] = "C4_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 4,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C5_Arbeit"] = {
        ["id"] = "C5_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 5,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C5_Arbeit_OverTime"] = {
        ["id"] = "C5_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 5,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C5_Cooking"] = {
        ["id"] = "C5_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 5,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C5_Eat"] = {
        ["id"] = "C5_Eat",
        ["StopType"] = 2,
        ["city_id"] = 5,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C5_Hunting"] = {
        ["id"] = "C5_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 5,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C5_Sleep"] = {
        ["id"] = "C5_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 5,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C6_Arbeit"] = {
        ["id"] = "C6_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 6,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C6_Arbeit_OverTime"] = {
        ["id"] = "C6_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 6,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C6_Cooking"] = {
        ["id"] = "C6_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 6,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C6_Eat"] = {
        ["id"] = "C6_Eat",
        ["StopType"] = 2,
        ["city_id"] = 6,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C6_Hunting"] = {
        ["id"] = "C6_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 6,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C6_Sleep"] = {
        ["id"] = "C6_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 6,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C7_Arbeit"] = {
        ["id"] = "C7_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 7,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C7_Arbeit_OverTime"] = {
        ["id"] = "C7_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 7,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C7_Cooking"] = {
        ["id"] = "C7_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 7,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C7_Eat"] = {
        ["id"] = "C7_Eat",
        ["StopType"] = 2,
        ["city_id"] = 7,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C7_Hunting"] = {
        ["id"] = "C7_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 7,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C7_Sleep"] = {
        ["id"] = "C7_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 7,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C8_Arbeit"] = {
        ["id"] = "C8_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 8,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C8_Arbeit_OverTime"] = {
        ["id"] = "C8_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 8,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C8_Cooking"] = {
        ["id"] = "C8_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 8,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C8_Eat"] = {
        ["id"] = "C8_Eat",
        ["StopType"] = 2,
        ["city_id"] = 8,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C8_Hunting"] = {
        ["id"] = "C8_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 8,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C8_Sleep"] = {
        ["id"] = "C8_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 8,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C9_Arbeit"] = {
        ["id"] = "C9_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 9,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C9_Arbeit_OverTime"] = {
        ["id"] = "C9_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 9,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C9_Cooking"] = {
        ["id"] = "C9_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 9,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C9_Eat"] = {
        ["id"] = "C9_Eat",
        ["StopType"] = 2,
        ["city_id"] = 9,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C9_Hunting"] = {
        ["id"] = "C9_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 9,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C9_Sleep"] = {
        ["id"] = "C9_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 9,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
    ["C10_Arbeit"] = {
        ["id"] = "C10_Arbeit",
        ["StopType"] = 1,
        ["city_id"] = 10,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Arbeit_desc",
        ["lang_title"] = "UI_Schedule_Arbeit",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Arbeit",
        ["visible_on_menu"] = true,
    },
    ["C10_Arbeit_OverTime"] = {
        ["id"] = "C10_Arbeit_OverTime",
        ["StopType"] = 1,
        ["city_id"] = 10,
        ["is_overtime"] = true,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Worker",
            "Worker2",
            "Miner",
            "Metalman",
            "Engineer",
            "Researcher",
            "Digger",
            "Planter",
            "Miner2",
            "Metalman2",
            "Engineer2",
            "Researcher2",
            "Digger2",
            "Planter2",
            "FoodWorker",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "0|600",
        ["type"] = "Arbeit_OverTime",
        ["visible_on_menu"] = false,
    },
    ["C10_Cooking"] = {
        ["id"] = "C10_Cooking",
        ["StopType"] = 2,
        ["city_id"] = 10,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Chef",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Cooking",
        ["visible_on_menu"] = false,
    },
    ["C10_Eat"] = {
        ["id"] = "C10_Eat",
        ["StopType"] = 2,
        ["city_id"] = 10,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Eat_desc",
        ["lang_title"] = "UI_Schedule_Eat",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 1,
        ["schedule_times"] = "1200|1500,2100|2400",
        ["type"] = "Eat",
        ["visible_on_menu"] = true,
    },
    ["C10_Hunting"] = {
        ["id"] = "C10_Hunting",
        ["StopType"] = 3,
        ["city_id"] = 10,
        ["is_overtime"] = false,
        ["lang_desc"] = "",
        ["lang_title"] = "",
        ["people_limit"] = {
            "Hunter",
        },
        ["real_time"] = 300,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "600|1200,1500|2100",
        ["type"] = "Hunting",
        ["visible_on_menu"] = false,
    },
    ["C10_Sleep"] = {
        ["id"] = "C10_Sleep",
        ["StopType"] = 2,
        ["city_id"] = 10,
        ["is_overtime"] = false,
        ["lang_desc"] = "UI_Schedule_Sleep_desc",
        ["lang_title"] = "UI_Schedule_Sleep",
        ["people_limit"] = {
            "None",
        },
        ["real_time"] = 0,
        ["run_open"] = {
            0,
        },
        ["run_speed"] = {
            0,
        },
        ["schedule_priority"] = 2,
        ["schedule_times"] = "0|600",
        ["type"] = "Sleep",
        ["visible_on_menu"] = true,
    },
}
