return {
    [1] = {
        ["id"] = 1,
        ["cost"] = {},
        ["double"] = true,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.gems20",
        ["reward"] = "addToItem*8?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [101] = {
        ["id"] = 101,
        ["cost"] = {},
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.package299",
        ["reward"] = "addToOpenBox*1?id=street_box_new,addToItem*8000?id=Heart",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [102] = {
        ["id"] = 102,
        ["cost"] = {},
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.package999",
        ["reward"] = "addToCard*1?id=15,addToCard*8?color=blue",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [103] = {
        ["id"] = 103,
        ["cost"] = {},
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.package499",
        ["reward"] = "addToOpenBox*1?id=street_box,addToCard*2?color=blue,addToItem*200?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [104] = {
        ["id"] = 104,
        ["cost"] = {},
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.package4999",
        ["reward"] = "addToItem*500?id=BlackCoin,addToItem*1000?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [11] = {
        ["id"] = 11,
        ["cost"] = {
            ["Gem"] = 100,
        },
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "",
        ["reward"] = "addToBox*1?id=high_box",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [12] = {
        ["id"] = 12,
        ["cost"] = {
            ["Gem"] = 1000,
        },
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "",
        ["reward"] = "addToBox*10?id=high_box",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [2] = {
        ["id"] = 2,
        ["cost"] = {},
        ["double"] = true,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.gems100",
        ["reward"] = "addToItem*50?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [201] = {
        ["id"] = 201,
        ["cost"] = {},
        ["double"] = false,
        ["duration_in_editor"] = 2592000,
        ["product_id"] = "com.fct.global.subscriptiondiamond",
        ["reward"] = "addToItem*500?id=Gem",
        ["reward_daily"] = "addToItem*500?id=Gem",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "addToBoost*2?id=offlineCityTime",
        ["type"] = "subscription",
    },
    [202] = {
        ["id"] = 202,
        ["cost"] = {},
        ["double"] = false,
        ["duration_in_editor"] = 2592000,
        ["product_id"] = "test.fct.global.package002",
        ["reward"] = "addToItem*1000?id=Gem",
        ["reward_daily"] = "addToItem*1000?id=Gem",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "addToBoost*4?id=offlineCityTime",
        ["type"] = "subscription",
    },
    [21] = {
        ["id"] = 21,
        ["cost"] = {
            ["Gem"] = 40,
        },
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "",
        ["reward"] = "addToItemOverTime*600?guarantee=1",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [22] = {
        ["id"] = 22,
        ["cost"] = {
            ["Gem"] = 200,
        },
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "",
        ["reward"] = "addToItemOverTime*3600?guarantee=1",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [23] = {
        ["id"] = 23,
        ["cost"] = {
            ["Gem"] = 60,
        },
        ["double"] = false,
        ["duration_in_editor"] = 0,
        ["product_id"] = "",
        ["reward"] = "addToOverTime*3600?id=Heart",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [3] = {
        ["id"] = 3,
        ["cost"] = {},
        ["double"] = true,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.gems200",
        ["reward"] = "addToItem*110?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [4] = {
        ["id"] = 4,
        ["cost"] = {},
        ["double"] = true,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.gems400",
        ["reward"] = "addToItem*230?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [5] = {
        ["id"] = 5,
        ["cost"] = {},
        ["double"] = true,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.gems1000",
        ["reward"] = "addToItem*600?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
    [6] = {
        ["id"] = 6,
        ["cost"] = {},
        ["double"] = true,
        ["duration_in_editor"] = 0,
        ["product_id"] = "com.fct.global.gems2000",
        ["reward"] = "addToItem*1250?id=Gem",
        ["reward_daily"] = "",
        ["reward_daily_auto"] = "",
        ["reward_subscription"] = "",
        ["type"] = "",
    },
}
