return {
    [1] = {
        ["id"] = 1,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.gems20',
        ["duration_in_editor"] = 0,
        ["double"] = true,
        ["double_ratio"] = 0.25,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*80?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [2] = {
        ["id"] = 2,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.gems100',
        ["duration_in_editor"] = 0,
        ["double"] = true,
        ["double_ratio"] = 0.2,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*500?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [3] = {
        ["id"] = 3,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.gems200',
        ["duration_in_editor"] = 0,
        ["double"] = true,
        ["double_ratio"] = 0.3,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1100?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [4] = {
        ["id"] = 4,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.gems400',
        ["duration_in_editor"] = 0,
        ["double"] = true,
        ["double_ratio"] = 0.3,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*2300?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [5] = {
        ["id"] = 5,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.gems1000',
        ["duration_in_editor"] = 0,
        ["double"] = true,
        ["double_ratio"] = 0.2,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*6000?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [6] = {
        ["id"] = 6,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.gems2000',
        ["duration_in_editor"] = 0,
        ["double"] = true,
        ["double_ratio"] = 0.2,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*12500?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [8] = {
        ["id"] = 8,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = 'discord',
        ["reward"] = 'addToItem*20?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [9] = {
        ["id"] = 9,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = 'facebook',
        ["reward"] = 'addToItem*20?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [11] = {
        ["id"] = 11,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=box_blue',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [12] = {
        ["id"] = 12,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = 'ad',
        ["reward"] = 'addToBox*1?id=box_blue',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [13] = {
        ["id"] = 13,
        ["type"] = '',
        ["diamond_confirm_count"] = 100,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 350,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=box_purple',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [14] = {
        ["id"] = 14,
        ["type"] = '',
        ["diamond_confirm_count"] = 100,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 800,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=box_gold',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [21] = {
        ["id"] = 21,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 40,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItemOverTime*600?guarantee=1',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [22] = {
        ["id"] = 22,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 200,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItemOverTime*3600?guarantee=1',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [23] = {
        ["id"] = 23,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 60,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToOverTime*3600?id=Heart',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [24] = {
        ["id"] = 24,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 0,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*10?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [25] = {
        ["id"] = 25,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 30,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1?id=TimeSkip30',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [26] = {
        ["id"] = 26,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 110,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1?id=TimeSkip120',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [27] = {
        ["id"] = 27,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 270,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1?id=TimeSkip300',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [100] = {
        ["id"] = 100,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package012',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*1?id=street_box_yiyuan,addToItem*6000?id=Heart,addToItem*100?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [101] = {
        ["id"] = 101,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package299',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*1?id=street_box_new,addToItem*10800?id=Heart,addToItem*180?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [102] = {
        ["id"] = 102,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*1?id=14,addToItem*680?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [103] = {
        ["id"] = 103,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package699',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*1?id=street_box,addToCard*2?color=blue,addToItem*400?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [104] = {
        ["id"] = 104,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package4999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*500?id=BlackCoin,addToItem*3280?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [105] = {
        ["id"] = 105,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package499',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOverTime*18000?id=Heart,addToItem*300?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [106] = {
        ["id"] = 106,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1299',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*1?id=2,addToCard*1?id=9,addToOverTime*40800?id=Heart,addToItem*680?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [107] = {
        ["id"] = 107,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*1?id=1,addToCard*1?id=14,addToCard*1?id=11',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [111] = {
        ["id"] = 111,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package599',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*1?id=box_purple,addToItem*300?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [112] = {
        ["id"] = 112,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package4',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*1?id=box_gold,addToOpenBox*1?id=box_purple,addToItem*680?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [113] = {
        ["id"] = 113,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package5',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*1?id=box_gold,addToItem*400?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [114] = {
        ["id"] = 114,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package2999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*2?id=4,addToCard*2?id=3,addToCard*5?id=19,addToCard*5?id=23,addToItem*1680?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [115] = {
        ["id"] = 115,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1499',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*2?id=6,addToCard*2?id=14,addToItem*780?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [116] = {
        ["id"] = 116,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*3?id=box_purple,addToItem*150?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [201] = {
        ["id"] = 201,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.subscriptiondiamond',
        ["duration_in_editor"] = 2592000,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*800?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = 'addToItem*100?id=Gem',
    },
    [202] = {
        ["id"] = 202,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.subscriptionadweek',
        ["duration_in_editor"] = 604800,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = 'addToDailyItem*20?id=ADTicket',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [203] = {
        ["id"] = 203,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.subscriptionadmonth',
        ["duration_in_editor"] = 2592000,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = 'addToDailyItem*20?id=ADTicket',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [204] = {
        ["id"] = 204,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.subscriptioncity',
        ["duration_in_editor"] = 2592000,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*20?id=BuildTicket',
        ["reward_boost"] = 'increase_offline_time,people_fast_come,construction_queue2',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [205] = {
        ["id"] = 205,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.subscriptionfight',
        ["duration_in_editor"] = 2592000,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = 'battle_speed,offline_battle_time',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [206] = {
        ["id"] = 206,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.subscriptioncitynew',
        ["duration_in_editor"] = 2592000,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = 'increase_offline_time,people_fast_come,construction_queue2,battle_speed,offline_battle_time',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [207] = {
        ["id"] = 207,
        ["type"] = 'assist',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.assist599',
        ["duration_in_editor"] = 2592000,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [401] = {
        ["id"] = 401,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1004',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [402] = {
        ["id"] = 402,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1005',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [403] = {
        ["id"] = 403,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1006',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [404] = {
        ["id"] = 404,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1007',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [405] = {
        ["id"] = 405,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1008',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [406] = {
        ["id"] = 406,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1009',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [407] = {
        ["id"] = 407,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1010',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [408] = {
        ["id"] = 408,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1011',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [409] = {
        ["id"] = 409,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1012',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [410] = {
        ["id"] = 410,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1013',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [411] = {
        ["id"] = 411,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1014',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [412] = {
        ["id"] = 412,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1015',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [413] = {
        ["id"] = 413,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1016',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [414] = {
        ["id"] = 414,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1017',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [415] = {
        ["id"] = 415,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1018',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [416] = {
        ["id"] = 416,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1019',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [417] = {
        ["id"] = 417,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.casino1020',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = '',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [999] = {
        ["id"] = 999,
        ["type"] = 'subscription',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.firstcharge099',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=card_fix_box_12',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1001] = {
        ["id"] = 1001,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 0,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*15?id=PlayCoin1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1002] = {
        ["id"] = 1002,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 80,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*20?id=PlayCoin1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1003] = {
        ["id"] = 1003,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 350,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*100?id=PlayCoin1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1004] = {
        ["id"] = 1004,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 150,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*10?id=Trick1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1005] = {
        ["id"] = 1005,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1499',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBoost*0?id=cash_exp_double_event,addToBoost*0?id=increase_offline_time_event',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1006] = {
        ["id"] = 1006,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package299',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*100?id=PlayCoin1001,addToItem*100?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1007] = {
        ["id"] = 1007,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*250?id=PlayCoin1001,addToItem*20?id=Trick1001,addToOverTime*14400?id=Heart1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1008] = {
        ["id"] = 1008,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 60,
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToOverTime*7200?id=Heart1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1009] = {
        ["id"] = 1009,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*200?id=PlayCoin1001,addToItem*30?id=Trick1001,addToItem*200?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1010] = {
        ["id"] = 1010,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1299',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*300?id=PlayCoin1001,addToItem*40?id=Trick1001,addToOverTime*14400?id=Heart1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1011] = {
        ["id"] = 1011,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1499',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = true,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*350?id=PlayCoin1001,addToItem*40?id=Trick1001,addToItem*200?id=Gem',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1012] = {
        ["id"] = 1012,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*500?id=PlayCoin1001,addToItem*50?id=Trick1001,addToOverTime*28800?id=Heart1001',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1101] = {
        ["id"] = 1101,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1499',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBoost*0?id=cash_exp_double_event,addToBoost*0?id=increase_offline_time_event',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1102] = {
        ["id"] = 1102,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package499',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*3?id=event1002_box_purple,addToItem*100?id=Gem,addToItem*500?id=BlackCoin1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1103] = {
        ["id"] = 1103,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package599',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*6?id=100254,addToCard*5?id=100201,addToItem*200?id=BlackCoin1002,addToItem*1000000?id=Heart1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1104] = {
        ["id"] = 1104,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package599',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*6?id=100251,addToCard*5?id=100202,addToItem*250?id=BlackCoin1002,addToItem*1000000?id=Heart1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1105] = {
        ["id"] = 1105,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package799',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*10?id=100253,addToCard*5?id=100203,addToItem*250?id=BlackCoin1002,addToItem*1000000?id=Heart1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1106] = {
        ["id"] = 1106,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToCard*10?id=100252,addToCard*10?id=100204,addToItem*450?id=BlackCoin1002,addToItem*10000000?id=Heart1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1107] = {
        ["id"] = 1107,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*3?id=event1002_box_gold,addToCard*10?id=100205,addToItem*450?id=BlackCoin1002,addToItem*100000000?id=Heart1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1108] = {
        ["id"] = 1108,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package999',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*3?id=event1002_box_gold,addToCard*15?id=100206,addToItem*600?id=BlackCoin1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1109] = {
        ["id"] = 1109,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = 'com.fct.global.package1299',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToOpenBox*3?id=event1002_box_gold,addToCard*20?id=100207,addToItem*800?id=BlackCoin1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1110] = {
        ["id"] = 1110,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=event1002_box_blue',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1111] = {
        ["id"] = 1111,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = 'ad',
        ["reward"] = 'addToBox*1?id=event1002_box_blue',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1112] = {
        ["id"] = 1112,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 100,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=event1002_box_purple',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1113] = {
        ["id"] = 1113,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 300,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToBox*1?id=event1002_box_gold',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1114] = {
        ["id"] = 1114,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 30,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1?id=TimeSkip15_1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1115] = {
        ["id"] = 1115,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 90,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1?id=TimeSkip60_1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
    [1116] = {
        ["id"] = 1116,
        ["type"] = '',
        ["diamond_confirm_count"] = -1,
        ["product_id"] = '',
        ["duration_in_editor"] = 0,
        ["double"] = false,
        ["double_ratio"] = 0.0,
        ["reward_daily_auto"] = '',
        ["cost"] = {
            ["Gem"] = 180,
        },
        ["reward_confirm"] = false,
        ["extended_cost"] = '',
        ["reward"] = 'addToItem*1?id=TimeSkip120_1002',
        ["reward_boost"] = '',
        ["reward_backend"] = '',
        ["reward_daily"] = '',
    },
}
