return {
    {
        ["animation"] = "hammerwork",
        ["character_type"] = "Hero",
        ["grid_Type"] = "Special1ForIdle",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "Generator_Special1ForIdle",
        ["right_hand_id"] = 1,
        ["right_hand_name"] = "HandTool",
        ["usage_duration"] = 4,
        ["zone_type"] = "Generator",
    },
    {
        ["animation"] = "look",
        ["character_type"] = "Hero",
        ["grid_Type"] = "Special2ForIdle",
        ["left_hand_id"] = 1,
        ["left_hand_name"] = "HandConcentrator1",
        ["q"] = "Generator_Special2ForIdle",
        ["right_hand_id"] = 1,
        ["right_hand_name"] = "HandConcentrator",
        ["usage_duration"] = 3,
        ["zone_type"] = "Generator",
    },
    {
        ["animation"] = "heal",
        ["character_type"] = "Hero",
        ["grid_Type"] = "Special3ForIdle",
        ["left_hand_id"] = 1,
        ["left_hand_name"] = "HandDoctorTable",
        ["q"] = "Generator_Special3ForIdle",
        ["right_hand_id"] = 0,
        ["right_hand_name"] = "",
        ["usage_duration"] = 3,
        ["zone_type"] = "Generator",
    },
    {
        ["animation"] = "seeking",
        ["character_type"] = "Hero",
        ["grid_Type"] = "Special1ForIdle",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "Watchtower_Special1ForIdle",
        ["right_hand_id"] = 0,
        ["right_hand_name"] = "",
        ["usage_duration"] = 3,
        ["zone_type"] = "Watchtower",
    },
    {
        ["animation"] = "eattingsnack",
        ["character_type"] = "Hero",
        ["grid_Type"] = "Special2ForIdle",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "Watchtower_Special2ForIdle",
        ["right_hand_id"] = 0,
        ["right_hand_name"] = "",
        ["usage_duration"] = 3,
        ["zone_type"] = "Watchtower",
    },
    {
        ["animation"] = "speech",
        ["character_type"] = "Hero",
        ["grid_Type"] = "Speech",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "MainRoad_Speech",
        ["right_hand_id"] = 1,
        ["right_hand_name"] = "HandMicrophone",
        ["usage_duration"] = 5,
        ["zone_type"] = "MainRoad",
    },
    {
        ["animation"] = "protest",
        ["character_type"] = "people",
        ["grid_Type"] = "Protest",
        ["left_hand_id"] = 1,
        ["left_hand_name"] = "HandBrand",
        ["q"] = "MainRoad_Protest",
        ["right_hand_id"] = 0,
        ["right_hand_name"] = "",
        ["usage_duration"] = 5,
        ["zone_type"] = "MainRoad",
    },
    {
        ["animation"] = "protest2",
        ["character_type"] = "people",
        ["grid_Type"] = "Protest2",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "MainRoad_Protest2",
        ["right_hand_id"] = 0,
        ["right_hand_name"] = "",
        ["usage_duration"] = 5,
        ["zone_type"] = "MainRoad",
    },
    {
        ["animation"] = "sweep",
        ["character_type"] = "people",
        ["grid_Type"] = "Special1ForIdle",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "Kitchen_Special1ForIdle",
        ["right_hand_id"] = 1,
        ["right_hand_name"] = "HandBroom",
        ["usage_duration"] = 5,
        ["zone_type"] = "Kitchen",
    },
    {
        ["animation"] = "hammerwork",
        ["character_type"] = "people",
        ["grid_Type"] = "Hunt",
        ["left_hand_id"] = 0,
        ["left_hand_name"] = "",
        ["q"] = "MainRoad_Hunt",
        ["right_hand_id"] = 1,
        ["right_hand_name"] = "HandMeat",
        ["usage_duration"] = 13,
        ["zone_type"] = "MainRoad",
    },
    {
        ["animation"] = "cleanweapon",
        ["character_type"] = "people",
        ["grid_Type"] = "Special1ForIdle",
        ["left_hand_id"] = 1,
        ["left_hand_name"] = "HandKnife",
        ["q"] = "HunterCabin_Special1ForIdle",
        ["right_hand_id"] = 0,
        ["right_hand_name"] = "",
        ["usage_duration"] = 8,
        ["zone_type"] = "HunterCabin",
    },
}
