return {
    ["a11"] = {
        ["id"] = "a11",
        ["behavior"] = "Action",
        ["city_id"] = 1,
        ["next"] = "s11",
        ["p1"] = {
            ["zoneId"] = "C1_Dorm_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a13"] = {
        ["id"] = "a13",
        ["behavior"] = "Action",
        ["city_id"] = 1,
        ["next"] = "s13",
        ["p1"] = {
            ["zoneId"] = "C1_Sawmill_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a22"] = {
        ["id"] = "a22",
        ["behavior"] = "Action",
        ["city_id"] = 2,
        ["next"] = "s22",
        ["p1"] = {
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a23"] = {
        ["id"] = "a23",
        ["behavior"] = "Action",
        ["city_id"] = 2,
        ["next"] = "s23",
        ["p1"] = {
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a25"] = {
        ["id"] = "a25",
        ["behavior"] = "Action",
        ["city_id"] = 2,
        ["next"] = "s25",
        ["p1"] = {
            ["zoneId"] = "C2_Infirmary_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a31"] = {
        ["id"] = "a31",
        ["behavior"] = "Action",
        ["city_id"] = 3,
        ["next"] = "s31",
        ["p1"] = {
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a32"] = {
        ["id"] = "a32",
        ["behavior"] = "Action",
        ["city_id"] = 3,
        ["next"] = "s32",
        ["p1"] = {
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a34"] = {
        ["id"] = "a34",
        ["behavior"] = "Action",
        ["city_id"] = 3,
        ["next"] = "s34",
        ["p1"] = {
            ["zoneId"] = "C3_Generator_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a35"] = {
        ["id"] = "a35",
        ["behavior"] = "Action",
        ["city_id"] = 3,
        ["next"] = "s35",
        ["p1"] = {
            ["zoneId"] = "C3_Watchtower_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a41"] = {
        ["id"] = "a41",
        ["behavior"] = "Action",
        ["city_id"] = 4,
        ["next"] = "s41",
        ["p1"] = {
            ["zoneId"] = "C4_Kitchen_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a42"] = {
        ["id"] = "a42",
        ["behavior"] = "Action",
        ["city_id"] = 4,
        ["next"] = "s42",
        ["p1"] = {
            ["zoneId"] = "C4_CopperMine_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["a43"] = {
        ["id"] = "a43",
        ["behavior"] = "Action",
        ["city_id"] = 4,
        ["next"] = "s43",
        ["p1"] = {
            ["zoneId"] = "C4_Generator_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "ShowBuildIcon",
    },
    ["s11"] = {
        ["id"] = "s11",
        ["behavior"] = "Story",
        ["city_id"] = 1,
        ["next"] = "g11",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "1",
                ["peopleText"] = "Story_city3_dialog2_1",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city3_dialog2_2",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "1",
                ["peopleText"] = "Story_city3_dialog2_3",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city3_dialog2_4",
                ["right"] = "1",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s13"] = {
        ["id"] = "s13",
        ["behavior"] = "Story",
        ["city_id"] = 1,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "1",
                ["peopleText"] = "Story_city1_dialog4_1",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city1_dialog4_2",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city1_dialog4_3",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "1",
                ["peopleText"] = "Story_city1_dialog4_4",
                ["right"] = "0",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s22"] = {
        ["id"] = "s22",
        ["behavior"] = "Story",
        ["city_id"] = 2,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city1_dialog5_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_14_laura",
                ["name"] = "card_14_name",
                ["peopleText"] = "Story_city1_dialog5_2",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city1_dialog5_5",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_14_laura",
                ["name"] = "card_14_name",
                ["peopleText"] = "Story_city1_dialog5_6",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city1_dialog5_7",
                ["right"] = "0",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s23"] = {
        ["id"] = "s23",
        ["behavior"] = "Story",
        ["city_id"] = 2,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city1_dialog7_1",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city1_dialog7_2",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city1_dialog7_3",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city1_dialog7_4",
                ["right"] = "1",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s25"] = {
        ["id"] = "s25",
        ["behavior"] = "Story",
        ["city_id"] = 2,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city2_dialog3_1",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city2_dialog3_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city2_dialog3_3",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["pause"] = "1",
                ["peopleText"] = "Story_city2_dialog3_4",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city2_dialog3_5",
                ["right"] = "0",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city2_dialog3_6",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city2_dialog3_7",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city2_dialog3_8",
                ["right"] = "0",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s31"] = {
        ["id"] = "s31",
        ["behavior"] = "Story",
        ["city_id"] = 3,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_19_name",
                ["peopleText"] = "Story_city1_dialog6_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_14_laura",
                ["name"] = "card_14_name",
                ["peopleText"] = "Story_city1_dialog6_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_19_name",
                ["peopleText"] = "Story_city1_dialog6_3",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_14_laura",
                ["name"] = "card_14_name",
                ["peopleText"] = "Story_city1_dialog6_4",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_14_laura",
                ["name"] = "card_14_name",
                ["peopleText"] = "Story_city1_dialog6_5",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_19_name",
                ["peopleText"] = "Story_city1_dialog6_6",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_14_laura",
                ["name"] = "card_14_name",
                ["peopleText"] = "Story_city1_dialog6_7",
                ["right"] = "1",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s32"] = {
        ["id"] = "s32",
        ["behavior"] = "Story",
        ["city_id"] = 3,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city3_dialog3_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city3_dialog3_4",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_04_name",
                ["peopleText"] = "Story_city3_dialog3_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_09_medicsoldier",
                ["name"] = "card_09_name",
                ["peopleText"] = "Story_city3_dialog3_3",
                ["right"] = "0",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s34"] = {
        ["id"] = "s34",
        ["behavior"] = "Story",
        ["city_id"] = 3,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city3_dialog9_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_19_name",
                ["peopleText"] = "Story_city3_dialog9_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_19_name",
                ["peopleText"] = "Story_city3_dialog9_3",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city3_dialog9_4",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_19_keanu",
                ["name"] = "card_19_name",
                ["peopleText"] = "Story_city3_dialog9_5",
                ["right"] = "1",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s35"] = {
        ["id"] = "s35",
        ["behavior"] = "Story",
        ["city_id"] = 3,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city4_dialog7_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_17_mideast",
                ["name"] = "card_17_name",
                ["peopleText"] = "Story_city4_dialog7_2",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city4_dialog7_3",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_17_mideast",
                ["name"] = "card_17_name",
                ["peopleText"] = "Story_city4_dialog7_4",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "2",
                ["peopleText"] = "Story_city4_dialog7_5",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_17_mideast",
                ["name"] = "card_17_name",
                ["peopleText"] = "Story_city4_dialog7_6",
                ["right"] = "1",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s41"] = {
        ["id"] = "s41",
        ["behavior"] = "Story",
        ["city_id"] = 4,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["heroIcon"] = "card_half_15_chef",
                ["name"] = "card_15_name",
                ["peopleText"] = "Story_city4_dialog1_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_04_reinhardt",
                ["name"] = "card_04_name",
                ["peopleText"] = "Story_city4_dialog1_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_04_reinhardt",
                ["name"] = "card_04_name",
                ["peopleText"] = "Story_city4_dialog1_3",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_15_chef",
                ["name"] = "card_15_name",
                ["peopleText"] = "Story_city4_dialog1_4",
                ["right"] = "0",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s42"] = {
        ["id"] = "s42",
        ["behavior"] = "Story",
        ["city_id"] = 4,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["heroIcon"] = "card_half_04_reinhardt",
                ["name"] = "card_04_name",
                ["peopleText"] = "Story_city4_dialog2_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_15_chef",
                ["name"] = "card_15_name",
                ["peopleText"] = "Story_city4_dialog2_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_04_reinhardt",
                ["name"] = "card_04_name",
                ["peopleText"] = "Story_city4_dialog2_3",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_15_chef",
                ["name"] = "card_15_name",
                ["peopleText"] = "Story_city4_dialog2_4",
                ["right"] = "1",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["s43"] = {
        ["id"] = "s43",
        ["behavior"] = "Story",
        ["city_id"] = 4,
        ["next"] = "",
        ["p1"] = {},
        ["p2"] = {
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city4_dialog8_1",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_21_zhanluka",
                ["name"] = "card_21_name",
                ["peopleText"] = "Story_city4_dialog8_2",
                ["right"] = "1",
            },
            {
                ["heroIcon"] = "card_half_21_zhanluka",
                ["name"] = "card_21_name",
                ["peopleText"] = "Story_city4_dialog8_21",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city4_dialog8_3",
                ["right"] = "0",
            },
            {
                ["heroIcon"] = "card_half_21_zhanluka",
                ["name"] = "card_21_name",
                ["peopleText"] = "Story_city4_dialog8_4",
                ["right"] = "1",
            },
            {
                ["peopleId"] = "4",
                ["peopleText"] = "Story_city4_dialog8_5",
                ["right"] = "0",
            },
        },
        ["param_index"] = "p2",
        ["type"] = "MutualDialogue",
    },
    ["t11"] = {
        ["id"] = "t11",
        ["behavior"] = "Trigger",
        ["city_id"] = 1,
        ["next"] = "a11",
        ["p1"] = {
            ["level"] = "2",
            ["zoneId"] = "C1_Dorm_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t13"] = {
        ["id"] = "t13",
        ["behavior"] = "Trigger",
        ["city_id"] = 1,
        ["next"] = "a13",
        ["p1"] = {
            ["taskId"] = "10013002",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "TaskComplete",
    },
    ["t22"] = {
        ["id"] = "t22",
        ["behavior"] = "Trigger",
        ["city_id"] = 2,
        ["next"] = "a22",
        ["p1"] = {
            ["taskId"] = "20011009",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "TaskComplete",
    },
    ["t23"] = {
        ["id"] = "t23",
        ["behavior"] = "Trigger",
        ["city_id"] = 2,
        ["next"] = "a23",
        ["p1"] = {
            ["level"] = "2",
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t25"] = {
        ["id"] = "t25",
        ["behavior"] = "Trigger",
        ["city_id"] = 2,
        ["next"] = "a25",
        ["p1"] = {
            ["taskId"] = "20012007",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "TaskComplete",
    },
    ["t31"] = {
        ["id"] = "t31",
        ["behavior"] = "Trigger",
        ["city_id"] = 3,
        ["next"] = "a31",
        ["p1"] = {
            ["level"] = "2",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t32"] = {
        ["id"] = "t32",
        ["behavior"] = "Trigger",
        ["city_id"] = 3,
        ["next"] = "a32",
        ["p1"] = {
            ["level"] = "3",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t34"] = {
        ["id"] = "t34",
        ["behavior"] = "Trigger",
        ["city_id"] = 3,
        ["next"] = "a34",
        ["p1"] = {
            ["level"] = "1",
            ["zoneId"] = "C3_MachineryFactory_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t35"] = {
        ["id"] = "t35",
        ["behavior"] = "Trigger",
        ["city_id"] = 3,
        ["next"] = "a35",
        ["p1"] = {
            ["level"] = "2",
            ["zoneId"] = "C3_Watchtower_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t41"] = {
        ["id"] = "t41",
        ["behavior"] = "Trigger",
        ["city_id"] = 4,
        ["next"] = "a41",
        ["p1"] = {
            ["level"] = "2",
            ["zoneId"] = "C4_Kitchen_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t42"] = {
        ["id"] = "t42",
        ["behavior"] = "Trigger",
        ["city_id"] = 4,
        ["next"] = "a42",
        ["p1"] = {
            ["level"] = "1",
            ["zoneId"] = "C4_CopperMine_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
    ["t43"] = {
        ["id"] = "t43",
        ["behavior"] = "Trigger",
        ["city_id"] = 4,
        ["next"] = "a43",
        ["p1"] = {
            ["level"] = "3",
            ["zoneId"] = "C4_Generator_1",
        },
        ["p2"] = {},
        ["param_index"] = "p1",
        ["type"] = "BuildComplete",
    },
}
