return {
    ["survey1"] = {
        ["name"] = "survey1",
        ["functions_unlock"] = "SurveySoftLaunch1",
        ["hash"] = "99YF2DT",
        ["precondition"] = "none",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {},
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 1,
    },
    ["survey2"] = {
        ["name"] = "survey2",
        ["functions_unlock"] = "SurveySoftLaunch2",
        ["hash"] = "99WBQTV",
        ["precondition"] = "no",
        ["precondition_survey"] = "survey1",
        ["precondition_survey_list"] = {
            "survey1",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 2,
    },
    ["survey3"] = {
        ["name"] = "survey3",
        ["functions_unlock"] = "SurveySoftLaunch2",
        ["hash"] = "99RQVH8",
        ["precondition"] = "yes",
        ["precondition_survey"] = "survey1",
        ["precondition_survey_list"] = {
            "survey1",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 3,
    },
    ["survey4"] = {
        ["name"] = "survey4",
        ["functions_unlock"] = "SurveySoftLaunch3",
        ["hash"] = "99PXJW9",
        ["precondition"] = "no",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {
            "survey1",
            "survey2",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 4,
    },
    ["survey5"] = {
        ["name"] = "survey5",
        ["functions_unlock"] = "SurveySoftLaunch3",
        ["hash"] = "9DV5LZY",
        ["precondition"] = "yes",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {
            "survey1",
            "survey2",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 5,
    },
    ["survey6"] = {
        ["name"] = "survey6",
        ["functions_unlock"] = "SurveySoftLaunch4",
        ["hash"] = "7PSPDLW",
        ["precondition"] = "no",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {
            "survey1",
            "survey2",
            "survey4",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 6,
    },
    ["survey7"] = {
        ["name"] = "survey7",
        ["functions_unlock"] = "SurveySoftLaunch4",
        ["hash"] = "9DDFVBZ",
        ["precondition"] = "yes",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {
            "survey1",
            "survey2",
            "survey4",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "City",
        ["sort"] = 7,
    },
    ["surveyFarmSummer1"] = {
        ["name"] = "surveyFarmSummer1",
        ["functions_unlock"] = "SurveySoftLaunchCity1002",
        ["hash"] = "9DYBWQF",
        ["precondition"] = "no",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {
            "survey1",
            "survey2",
            "survey4",
            "survey6",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "Event",
        ["sort"] = 8,
    },
    ["surveyFarmSummer2"] = {
        ["name"] = "surveyFarmSummer2",
        ["functions_unlock"] = "SurveySoftLaunchCity1002",
        ["hash"] = "7PFVBXQ",
        ["precondition"] = "yes",
        ["precondition_survey"] = "",
        ["precondition_survey_list"] = {
            "survey1",
            "survey2",
            "survey4",
            "survey6",
        },
        ["rewards"] = "addToItem*100?id=Gem",
        ["scope"] = "Event",
        ["sort"] = 9,
    },
}
