return {
    ["50011001"] = {
        ["id"] = "50011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50011002"] = {
        ["id"] = "50011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50011003"] = {
        ["id"] = "50011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011004"] = {
        ["id"] = "50011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50011005"] = {
        ["id"] = "50011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50011006"] = {
        ["id"] = "50011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011007"] = {
        ["id"] = "50011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 11.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50011008"] = {
        ["id"] = "50011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50011009"] = {
        ["id"] = "50011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50011010"] = {
        ["id"] = "50011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50011011"] = {
        ["id"] = "50011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50011012"] = {
        ["id"] = "50011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011013"] = {
        ["id"] = "50011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50011014"] = {
        ["id"] = "50011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011015"] = {
        ["id"] = "50011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50011016"] = {
        ["id"] = "50011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50011017"] = {
        ["id"] = "50011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50011018"] = {
        ["id"] = "50011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50011019"] = {
        ["id"] = "50011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011020"] = {
        ["id"] = "50011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50011021"] = {
        ["id"] = "50011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50011022"] = {
        ["id"] = "50011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50011023"] = {
        ["id"] = "50011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011024"] = {
        ["id"] = "50011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50011025"] = {
        ["id"] = "50011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50011026"] = {
        ["id"] = "50011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50011027"] = {
        ["id"] = "50011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50011028"] = {
        ["id"] = "50011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50011029"] = {
        ["id"] = "50011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 18.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011030"] = {
        ["id"] = "50011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50011031"] = {
        ["id"] = "50011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50011032"] = {
        ["id"] = "50011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011033"] = {
        ["id"] = "50011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50011034"] = {
        ["id"] = "50011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Nails&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50011035"] = {
        ["id"] = "50011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50011036"] = {
        ["id"] = "50011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50011037"] = {
        ["id"] = "50011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cloth&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50011038"] = {
        ["id"] = "50011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50011039"] = {
        ["id"] = "50011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011040"] = {
        ["id"] = "50011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Clothing&guarantee=1",
        ["stage"] = 21.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50011041"] = {
        ["id"] = "50011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50011042"] = {
        ["id"] = "50011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011043"] = {
        ["id"] = "50011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 23.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50011044"] = {
        ["id"] = "50011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50011045"] = {
        ["id"] = "50011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011046"] = {
        ["id"] = "50011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Nails&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50011047"] = {
        ["id"] = "50011047",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50011048"] = {
        ["id"] = "50011048",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50011049"] = {
        ["id"] = "50011049",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cloth&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50011050"] = {
        ["id"] = "50011050",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50011051"] = {
        ["id"] = "50011051",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011052"] = {
        ["id"] = "50011052",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 26.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C5_Generator_1",
        },
    },
    ["50011053"] = {
        ["id"] = "50011053",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50011054"] = {
        ["id"] = "50011054",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50011055"] = {
        ["id"] = "50011055",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cloth&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50011056"] = {
        ["id"] = "50011056",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50011057"] = {
        ["id"] = "50011057",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50011058"] = {
        ["id"] = "50011058",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cotton&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50011059"] = {
        ["id"] = "50011059",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50011060"] = {
        ["id"] = "50011060",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50012001"] = {
        ["id"] = "50012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C5_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50012002"] = {
        ["id"] = "50012002",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Nails&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["furnitureId"] = "C5_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50012004"] = {
        ["id"] = "50012004",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9.8,
        ["task"] = {
            ["furnitureId"] = "C5_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50012005"] = {
        ["id"] = "50012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.2,
        ["task"] = {
            ["furnitureId"] = "C5_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50012006"] = {
        ["id"] = "50012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012007"] = {
        ["id"] = "50012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.9,
        ["task"] = {
            ["furnitureId"] = "C5_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50012008"] = {
        ["id"] = "50012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Nails&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C5_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50012009"] = {
        ["id"] = "50012009",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C5_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50012010"] = {
        ["id"] = "50012010",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C5_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50012011"] = {
        ["id"] = "50012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.5,
        ["task"] = {
            ["furnitureId"] = "C5_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50012013"] = {
        ["id"] = "50012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.5,
        ["task"] = {
            ["furnitureId"] = "C5_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50012014"] = {
        ["id"] = "50012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012015"] = {
        ["id"] = "50012015",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C5_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50012016"] = {
        ["id"] = "50012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C5_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50012017"] = {
        ["id"] = "50012017",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cotton&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C5_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50012018"] = {
        ["id"] = "50012018",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.3,
        ["task"] = {
            ["furnitureId"] = "C5_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50012020"] = {
        ["id"] = "50012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.6,
        ["task"] = {
            ["furnitureId"] = "C5_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50012021"] = {
        ["id"] = "50012021",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["furnitureId"] = "C5_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50012022"] = {
        ["id"] = "50012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.7,
        ["task"] = {
            ["furnitureId"] = "C5_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50012023"] = {
        ["id"] = "50012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012024"] = {
        ["id"] = "50012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C5_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50012025"] = {
        ["id"] = "50012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C5_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50012026"] = {
        ["id"] = "50012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cotton&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C5_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50012027"] = {
        ["id"] = "50012027",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50012028"] = {
        ["id"] = "50012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18.1,
        ["task"] = {
            ["furnitureId"] = "C5_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50012030"] = {
        ["id"] = "50012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.2,
        ["task"] = {
            ["furnitureId"] = "C5_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50012031"] = {
        ["id"] = "50012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.9,
        ["task"] = {
            ["furnitureId"] = "C5_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50012032"] = {
        ["id"] = "50012032",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012033"] = {
        ["id"] = "50012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.9,
        ["task"] = {
            ["furnitureId"] = "C5_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50012034"] = {
        ["id"] = "50012034",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C5_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50012035"] = {
        ["id"] = "50012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C5_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50012036"] = {
        ["id"] = "50012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C5_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50012037"] = {
        ["id"] = "50012037",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50012038"] = {
        ["id"] = "50012038",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Clothing&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50012040"] = {
        ["id"] = "50012040",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21.6,
        ["task"] = {
            ["furnitureId"] = "C5_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C5_Infirmary_1",
        },
    },
    ["50012041"] = {
        ["id"] = "50012041",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Clothing&guarantee=1",
        ["stage"] = 22.8,
        ["task"] = {
            ["furnitureId"] = "C5_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C5_Watchtower_1",
        },
    },
    ["50012042"] = {
        ["id"] = "50012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012043"] = {
        ["id"] = "50012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.2,
        ["task"] = {
            ["furnitureId"] = "C5_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_Kitchen_1",
        },
    },
    ["50012044"] = {
        ["id"] = "50012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.6,
        ["task"] = {
            ["furnitureId"] = "C5_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "70",
            ["zoneId"] = "C5_HunterCabin_1",
        },
    },
    ["50012046"] = {
        ["id"] = "50012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C5_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C5_Metal_1",
        },
    },
    ["50012047"] = {
        ["id"] = "50012047",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C5_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50012048"] = {
        ["id"] = "50012048",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C5_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50012049"] = {
        ["id"] = "50012049",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50012050"] = {
        ["id"] = "50012050",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Clothing&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50012051"] = {
        ["id"] = "50012051",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012053"] = {
        ["id"] = "50012053",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C5_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C5_Metal2_1",
        },
    },
    ["50012054"] = {
        ["id"] = "50012054",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C5_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50012055"] = {
        ["id"] = "50012055",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50012056"] = {
        ["id"] = "50012056",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Clothing&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50012057"] = {
        ["id"] = "50012057",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 29,
        ["task"] = {
            ["furnitureId"] = "C5_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C5_CoalMine_1",
        },
    },
    ["50012058"] = {
        ["id"] = "50012058",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C5_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C5_Greenhouse2_1",
        },
    },
    ["50012059"] = {
        ["id"] = "50012059",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cloth&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C5_Carpentry_1",
        },
    },
    ["50012060"] = {
        ["id"] = "50012060",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C5_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C5_Carpentry2_1",
        },
    },
    ["50013001"] = {
        ["id"] = "50013001",
        ["action"] = "EAT_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["50013002"] = {
        ["id"] = "50013002",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "540",
            ["itemType"] = "Nails",
        },
    },
    ["50013003"] = {
        ["id"] = "50013003",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C5_Dorm_4",
        },
    },
    ["50013004"] = {
        ["id"] = "50013004",
        ["action"] = "SLEEP_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "8",
            ["hunger"] = "0",
        },
    },
    ["50013005"] = {
        ["id"] = "50013005",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 10.2,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C5_Dorm_1",
        },
    },
    ["50013006"] = {
        ["id"] = "50013006",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "660",
            ["itemType"] = "Coal",
        },
    },
    ["50013007"] = {
        ["id"] = "50013007",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.9,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C5_Dorm_3",
        },
    },
    ["50013008"] = {
        ["id"] = "50013008",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "720",
            ["itemType"] = "Nails",
        },
    },
    ["50013009"] = {
        ["id"] = "50013009",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperTube&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "2160",
            ["countByTime"] = "720",
            ["itemType"] = "CopperTube",
        },
    },
    ["50013010"] = {
        ["id"] = "50013010",
        ["action"] = "EAT_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "28",
        },
    },
    ["50013011"] = {
        ["id"] = "50013011",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12.5,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C5_Dorm_5",
        },
    },
    ["50013012"] = {
        ["id"] = "50013012",
        ["action"] = "SLEEP_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "18",
            ["hunger"] = "0",
        },
    },
    ["50013013"] = {
        ["id"] = "50013013",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.5,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C5_Dorm_6",
        },
    },
    ["50013014"] = {
        ["id"] = "50013014",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "840",
            ["itemType"] = "Coal",
        },
    },
    ["50013015"] = {
        ["id"] = "50013015",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Nails&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "900",
            ["itemType"] = "Nails",
        },
    },
    ["50013016"] = {
        ["id"] = "50013016",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "2160",
            ["countByTime"] = "900",
            ["itemType"] = "CopperTube",
        },
    },
    ["50013017"] = {
        ["id"] = "50013017",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "6480",
            ["countByTime"] = "900",
            ["itemType"] = "Cotton",
        },
    },
    ["50013018"] = {
        ["id"] = "50013018",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.3,
        ["task"] = {
            ["count"] = "26",
            ["zoneId"] = "C5_Dorm_5",
        },
    },
    ["50013019"] = {
        ["id"] = "50013019",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C5_Dorm_9",
        },
    },
    ["50013020"] = {
        ["id"] = "50013020",
        ["action"] = "EAT_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.6,
        ["task"] = {
            ["count"] = "56",
        },
    },
    ["50013021"] = {
        ["id"] = "50013021",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "32",
            ["zoneId"] = "C5_Dorm_10",
        },
    },
    ["50013022"] = {
        ["id"] = "50013022",
        ["action"] = "SLEEP_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "32",
            ["hunger"] = "0",
        },
    },
    ["50013023"] = {
        ["id"] = "50013023",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "1020",
            ["itemType"] = "Coal",
        },
    },
    ["50013024"] = {
        ["id"] = "50013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Nails&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1080",
            ["itemType"] = "Nails",
        },
    },
    ["50013025"] = {
        ["id"] = "50013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "2160",
            ["countByTime"] = "1080",
            ["itemType"] = "CopperTube",
        },
    },
    ["50013026"] = {
        ["id"] = "50013026",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "6480",
            ["countByTime"] = "1080",
            ["itemType"] = "Cotton",
        },
    },
    ["50013027"] = {
        ["id"] = "50013027",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cloth&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "2250",
            ["countByTime"] = "1080",
            ["itemType"] = "Cloth",
        },
    },
    ["50013028"] = {
        ["id"] = "50013028",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18.1,
        ["task"] = {
            ["count"] = "38",
            ["zoneId"] = "C5_Dorm_12",
        },
    },
    ["50013029"] = {
        ["id"] = "50013029",
        ["action"] = "EAT_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 18.4,
        ["task"] = {
            ["count"] = "76",
        },
    },
    ["50013030"] = {
        ["id"] = "50013030",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.2,
        ["task"] = {
            ["count"] = "40",
            ["zoneId"] = "C5_Dorm_8",
        },
    },
    ["50013031"] = {
        ["id"] = "50013031",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "42",
            ["zoneId"] = "C5_Dorm_9",
        },
    },
    ["50013032"] = {
        ["id"] = "50013032",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "1200",
            ["itemType"] = "Coal",
        },
    },
    ["50013033"] = {
        ["id"] = "50013033",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.9,
        ["task"] = {
            ["count"] = "44",
            ["zoneId"] = "C5_Dorm_10",
        },
    },
    ["50013034"] = {
        ["id"] = "50013034",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1260",
            ["itemType"] = "Nails",
        },
    },
    ["50013035"] = {
        ["id"] = "50013035",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "2160",
            ["countByTime"] = "1260",
            ["itemType"] = "CopperTube",
        },
    },
    ["50013036"] = {
        ["id"] = "50013036",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cotton&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "6480",
            ["countByTime"] = "1260",
            ["itemType"] = "Cotton",
        },
    },
    ["50013037"] = {
        ["id"] = "50013037",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "2250",
            ["countByTime"] = "1260",
            ["itemType"] = "Cloth",
        },
    },
    ["50013038"] = {
        ["id"] = "50013038",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "360",
            ["countByTime"] = "1260",
            ["itemType"] = "Clothing",
        },
    },
    ["50013039"] = {
        ["id"] = "50013039",
        ["action"] = "SLEEP_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "44",
            ["hunger"] = "0",
        },
    },
    ["50013040"] = {
        ["id"] = "50013040",
        ["action"] = "EAT_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.6,
        ["task"] = {
            ["count"] = "88",
        },
    },
    ["50013041"] = {
        ["id"] = "50013041",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22.8,
        ["task"] = {
            ["count"] = "46",
            ["zoneId"] = "C5_Dorm_11",
        },
    },
    ["50013042"] = {
        ["id"] = "50013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "1380",
            ["itemType"] = "Coal",
        },
    },
    ["50013043"] = {
        ["id"] = "50013043",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.2,
        ["task"] = {
            ["count"] = "48",
            ["zoneId"] = "C5_Dorm_12",
        },
    },
    ["50013044"] = {
        ["id"] = "50013044",
        ["action"] = "SLEEP_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.6,
        ["task"] = {
            ["count"] = "48",
            ["hunger"] = "0",
        },
    },
    ["50013045"] = {
        ["id"] = "50013045",
        ["action"] = "EAT_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "96",
        },
    },
    ["50013046"] = {
        ["id"] = "50013046",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1440",
            ["itemType"] = "Nails",
        },
    },
    ["50013047"] = {
        ["id"] = "50013047",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "2160",
            ["countByTime"] = "1440",
            ["itemType"] = "CopperTube",
        },
    },
    ["50013048"] = {
        ["id"] = "50013048",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cotton&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "6480",
            ["countByTime"] = "1440",
            ["itemType"] = "Cotton",
        },
    },
    ["50013049"] = {
        ["id"] = "50013049",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "2250",
            ["countByTime"] = "1440",
            ["itemType"] = "Cloth",
        },
    },
    ["50013050"] = {
        ["id"] = "50013050",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "360",
            ["countByTime"] = "1440",
            ["itemType"] = "Clothing",
        },
    },
    ["50013051"] = {
        ["id"] = "50013051",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "1560",
            ["itemType"] = "Coal",
        },
    },
    ["50013052"] = {
        ["id"] = "50013052",
        ["action"] = "SLEEP_WELL",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 26.9,
        ["task"] = {
            ["count"] = "48",
            ["hunger"] = "0",
        },
    },
    ["50013053"] = {
        ["id"] = "50013053",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "2160",
            ["countByTime"] = "1620",
            ["itemType"] = "CopperTube",
        },
    },
    ["50013054"] = {
        ["id"] = "50013054",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cotton&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "6480",
            ["countByTime"] = "1620",
            ["itemType"] = "Cotton",
        },
    },
    ["50013055"] = {
        ["id"] = "50013055",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "2250",
            ["countByTime"] = "1620",
            ["itemType"] = "Cloth",
        },
    },
    ["50013056"] = {
        ["id"] = "50013056",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "360",
            ["countByTime"] = "1620",
            ["itemType"] = "Clothing",
        },
    },
    ["50013057"] = {
        ["id"] = "50013057",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal5&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "12000",
            ["countByTime"] = "1740",
            ["itemType"] = "Coal",
        },
    },
    ["50013058"] = {
        ["id"] = "50013058",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "6480",
            ["countByTime"] = "1800",
            ["itemType"] = "Cotton",
        },
    },
    ["50013059"] = {
        ["id"] = "50013059",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "2250",
            ["countByTime"] = "1800",
            ["itemType"] = "Cloth",
        },
    },
    ["50013060"] = {
        ["id"] = "50013060",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 5,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Clothing&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "360",
            ["countByTime"] = "1800",
            ["itemType"] = "Clothing",
        },
    },
} 
