return {
    ["60011001"] = {
        ["id"] = "60011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60011002"] = {
        ["id"] = "60011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60011003"] = {
        ["id"] = "60011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011004"] = {
        ["id"] = "60011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60011005"] = {
        ["id"] = "60011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60011006"] = {
        ["id"] = "60011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011007"] = {
        ["id"] = "60011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 11.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60011008"] = {
        ["id"] = "60011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60011009"] = {
        ["id"] = "60011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60011010"] = {
        ["id"] = "60011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=card_fix_box_7",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60011011"] = {
        ["id"] = "60011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60011012"] = {
        ["id"] = "60011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011013"] = {
        ["id"] = "60011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60011014"] = {
        ["id"] = "60011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011015"] = {
        ["id"] = "60011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60011016"] = {
        ["id"] = "60011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60011017"] = {
        ["id"] = "60011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60011018"] = {
        ["id"] = "60011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60011019"] = {
        ["id"] = "60011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011020"] = {
        ["id"] = "60011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60011021"] = {
        ["id"] = "60011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60011022"] = {
        ["id"] = "60011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60011023"] = {
        ["id"] = "60011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011024"] = {
        ["id"] = "60011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60011025"] = {
        ["id"] = "60011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60011026"] = {
        ["id"] = "60011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60011027"] = {
        ["id"] = "60011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60011028"] = {
        ["id"] = "60011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60011029"] = {
        ["id"] = "60011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 18.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011030"] = {
        ["id"] = "60011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60011031"] = {
        ["id"] = "60011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60011032"] = {
        ["id"] = "60011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011033"] = {
        ["id"] = "60011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60011034"] = {
        ["id"] = "60011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Mat&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60011035"] = {
        ["id"] = "60011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60011036"] = {
        ["id"] = "60011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60011037"] = {
        ["id"] = "60011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelFrame&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60011038"] = {
        ["id"] = "60011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60011039"] = {
        ["id"] = "60011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011040"] = {
        ["id"] = "60011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerSteamFurnace&guarantee=1",
        ["stage"] = 21.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60011041"] = {
        ["id"] = "60011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60011042"] = {
        ["id"] = "60011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011043"] = {
        ["id"] = "60011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 23.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60011044"] = {
        ["id"] = "60011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60011045"] = {
        ["id"] = "60011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011046"] = {
        ["id"] = "60011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Mat&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60011047"] = {
        ["id"] = "60011047",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60011048"] = {
        ["id"] = "60011048",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60011049"] = {
        ["id"] = "60011049",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelFrame&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60011050"] = {
        ["id"] = "60011050",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60011051"] = {
        ["id"] = "60011051",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011052"] = {
        ["id"] = "60011052",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 26.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C6_Generator_1",
        },
    },
    ["60011053"] = {
        ["id"] = "60011053",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60011054"] = {
        ["id"] = "60011054",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60011055"] = {
        ["id"] = "60011055",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelFrame&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60011056"] = {
        ["id"] = "60011056",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60011057"] = {
        ["id"] = "60011057",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60011058"] = {
        ["id"] = "60011058",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelFrame&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60011059"] = {
        ["id"] = "60011059",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60012001"] = {
        ["id"] = "60012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C6_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60012002"] = {
        ["id"] = "60012002",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Mat&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60012004"] = {
        ["id"] = "60012004",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9.8,
        ["task"] = {
            ["furnitureId"] = "C6_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60012005"] = {
        ["id"] = "60012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.2,
        ["task"] = {
            ["furnitureId"] = "C6_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60012006"] = {
        ["id"] = "60012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012007"] = {
        ["id"] = "60012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.9,
        ["task"] = {
            ["furnitureId"] = "C6_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60012008"] = {
        ["id"] = "60012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Mat&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60012009"] = {
        ["id"] = "60012009",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C6_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60012010"] = {
        ["id"] = "60012010",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C6_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60012011"] = {
        ["id"] = "60012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.5,
        ["task"] = {
            ["furnitureId"] = "C6_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60012013"] = {
        ["id"] = "60012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.5,
        ["task"] = {
            ["furnitureId"] = "C6_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60012014"] = {
        ["id"] = "60012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012015"] = {
        ["id"] = "60012015",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60012016"] = {
        ["id"] = "60012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C6_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60012017"] = {
        ["id"] = "60012017",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GasSteelFurnace&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60012018"] = {
        ["id"] = "60012018",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.3,
        ["task"] = {
            ["furnitureId"] = "C6_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60012020"] = {
        ["id"] = "60012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.6,
        ["task"] = {
            ["furnitureId"] = "C6_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60012021"] = {
        ["id"] = "60012021",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["furnitureId"] = "C6_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60012022"] = {
        ["id"] = "60012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.7,
        ["task"] = {
            ["furnitureId"] = "C6_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60012023"] = {
        ["id"] = "60012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012024"] = {
        ["id"] = "60012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60012025"] = {
        ["id"] = "60012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C6_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60012026"] = {
        ["id"] = "60012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GasSteelFurnace&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60012027"] = {
        ["id"] = "60012027",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C6_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60012028"] = {
        ["id"] = "60012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18.1,
        ["task"] = {
            ["furnitureId"] = "C6_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60012030"] = {
        ["id"] = "60012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.2,
        ["task"] = {
            ["furnitureId"] = "C6_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60012031"] = {
        ["id"] = "60012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.9,
        ["task"] = {
            ["furnitureId"] = "C6_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60012032"] = {
        ["id"] = "60012032",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012033"] = {
        ["id"] = "60012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.9,
        ["task"] = {
            ["furnitureId"] = "C6_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60012034"] = {
        ["id"] = "60012034",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60012035"] = {
        ["id"] = "60012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C6_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60012036"] = {
        ["id"] = "60012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60012037"] = {
        ["id"] = "60012037",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C6_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60012038"] = {
        ["id"] = "60012038",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerSteamFurnace&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C6_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60012040"] = {
        ["id"] = "60012040",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21.6,
        ["task"] = {
            ["furnitureId"] = "C6_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C6_Infirmary_1",
        },
    },
    ["60012041"] = {
        ["id"] = "60012041",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerSteamFurnace&guarantee=1",
        ["stage"] = 22.8,
        ["task"] = {
            ["furnitureId"] = "C6_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C6_Watchtower_1",
        },
    },
    ["60012042"] = {
        ["id"] = "60012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012043"] = {
        ["id"] = "60012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.2,
        ["task"] = {
            ["furnitureId"] = "C6_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_Kitchen_1",
        },
    },
    ["60012044"] = {
        ["id"] = "60012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.6,
        ["task"] = {
            ["furnitureId"] = "C6_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "70",
            ["zoneId"] = "C6_Greenhouse_1",
        },
    },
    ["60012046"] = {
        ["id"] = "60012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C6_Carpentry_1",
        },
    },
    ["60012047"] = {
        ["id"] = "60012047",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C6_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60012048"] = {
        ["id"] = "60012048",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60012049"] = {
        ["id"] = "60012049",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C6_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60012050"] = {
        ["id"] = "60012050",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerSteamFurnace&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C6_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60012051"] = {
        ["id"] = "60012051",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012053"] = {
        ["id"] = "60012053",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C6_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C6_Metal_1",
        },
    },
    ["60012054"] = {
        ["id"] = "60012054",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C6_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C6_Carpentry2_1",
        },
    },
    ["60012055"] = {
        ["id"] = "60012055",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C6_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60012056"] = {
        ["id"] = "60012056",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerSteamFurnace&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C6_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60012057"] = {
        ["id"] = "60012057",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 29,
        ["task"] = {
            ["furnitureId"] = "C6_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C6_CoalMine_1",
        },
    },
    ["60012058"] = {
        ["id"] = "60012058",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C6_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C6_Metal2_1",
        },
    },
    ["60012059"] = {
        ["id"] = "60012059",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerSteamFurnace&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C6_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C6_MachineryFactory_1",
        },
    },
    ["60013001"] = {
        ["id"] = "60013001",
        ["action"] = "EAT_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["60013002"] = {
        ["id"] = "60013002",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "15120",
            ["countByTime"] = "540",
            ["itemType"] = "Mat",
        },
    },
    ["60013003"] = {
        ["id"] = "60013003",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C6_Dorm_4",
        },
    },
    ["60013004"] = {
        ["id"] = "60013004",
        ["action"] = "SLEEP_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "8",
            ["hunger"] = "0",
        },
    },
    ["60013005"] = {
        ["id"] = "60013005",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 10.2,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C6_Dorm_1",
        },
    },
    ["60013006"] = {
        ["id"] = "60013006",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "660",
            ["itemType"] = "Coal",
        },
    },
    ["60013007"] = {
        ["id"] = "60013007",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.9,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C6_Dorm_3",
        },
    },
    ["60013008"] = {
        ["id"] = "60013008",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "15120",
            ["countByTime"] = "720",
            ["itemType"] = "Mat",
        },
    },
    ["60013009"] = {
        ["id"] = "60013009",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "12600",
            ["countByTime"] = "720",
            ["itemType"] = "SteelBlock",
        },
    },
    ["60013010"] = {
        ["id"] = "60013010",
        ["action"] = "EAT_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "28",
        },
    },
    ["60013011"] = {
        ["id"] = "60013011",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12.5,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C6_Dorm_5",
        },
    },
    ["60013012"] = {
        ["id"] = "60013012",
        ["action"] = "SLEEP_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "18",
            ["hunger"] = "0",
        },
    },
    ["60013013"] = {
        ["id"] = "60013013",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.5,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C6_Dorm_6",
        },
    },
    ["60013014"] = {
        ["id"] = "60013014",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "840",
            ["itemType"] = "Coal",
        },
    },
    ["60013015"] = {
        ["id"] = "60013015",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Mat&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "15120",
            ["countByTime"] = "900",
            ["itemType"] = "Mat",
        },
    },
    ["60013016"] = {
        ["id"] = "60013016",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "12600",
            ["countByTime"] = "900",
            ["itemType"] = "SteelBlock",
        },
    },
    ["60013017"] = {
        ["id"] = "60013017",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "690",
            ["countByTime"] = "900",
            ["itemType"] = "GasSteelFurnace",
        },
    },
    ["60013018"] = {
        ["id"] = "60013018",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.3,
        ["task"] = {
            ["count"] = "26",
            ["zoneId"] = "C6_Dorm_5",
        },
    },
    ["60013019"] = {
        ["id"] = "60013019",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C6_Dorm_9",
        },
    },
    ["60013020"] = {
        ["id"] = "60013020",
        ["action"] = "EAT_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.6,
        ["task"] = {
            ["count"] = "56",
        },
    },
    ["60013021"] = {
        ["id"] = "60013021",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "32",
            ["zoneId"] = "C6_Dorm_10",
        },
    },
    ["60013022"] = {
        ["id"] = "60013022",
        ["action"] = "SLEEP_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "32",
            ["hunger"] = "0",
        },
    },
    ["60013023"] = {
        ["id"] = "60013023",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "1020",
            ["itemType"] = "Coal",
        },
    },
    ["60013024"] = {
        ["id"] = "60013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Mat&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "15120",
            ["countByTime"] = "1080",
            ["itemType"] = "Mat",
        },
    },
    ["60013025"] = {
        ["id"] = "60013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "12600",
            ["countByTime"] = "1080",
            ["itemType"] = "SteelBlock",
        },
    },
    ["60013026"] = {
        ["id"] = "60013026",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "690",
            ["countByTime"] = "1080",
            ["itemType"] = "GasSteelFurnace",
        },
    },
    ["60013027"] = {
        ["id"] = "60013027",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelFrame&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1730",
            ["countByTime"] = "1080",
            ["itemType"] = "SteelFrame",
        },
    },
    ["60013028"] = {
        ["id"] = "60013028",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18.1,
        ["task"] = {
            ["count"] = "38",
            ["zoneId"] = "C6_Dorm_12",
        },
    },
    ["60013029"] = {
        ["id"] = "60013029",
        ["action"] = "EAT_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 18.4,
        ["task"] = {
            ["count"] = "76",
        },
    },
    ["60013030"] = {
        ["id"] = "60013030",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.2,
        ["task"] = {
            ["count"] = "40",
            ["zoneId"] = "C6_Dorm_8",
        },
    },
    ["60013031"] = {
        ["id"] = "60013031",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "42",
            ["zoneId"] = "C6_Dorm_9",
        },
    },
    ["60013032"] = {
        ["id"] = "60013032",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "1200",
            ["itemType"] = "Coal",
        },
    },
    ["60013033"] = {
        ["id"] = "60013033",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.9,
        ["task"] = {
            ["count"] = "44",
            ["zoneId"] = "C6_Dorm_10",
        },
    },
    ["60013034"] = {
        ["id"] = "60013034",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "15120",
            ["countByTime"] = "1260",
            ["itemType"] = "Mat",
        },
    },
    ["60013035"] = {
        ["id"] = "60013035",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "12600",
            ["countByTime"] = "1260",
            ["itemType"] = "SteelBlock",
        },
    },
    ["60013036"] = {
        ["id"] = "60013036",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GasSteelFurnace&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "690",
            ["countByTime"] = "1260",
            ["itemType"] = "GasSteelFurnace",
        },
    },
    ["60013037"] = {
        ["id"] = "60013037",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1730",
            ["countByTime"] = "1260",
            ["itemType"] = "SteelFrame",
        },
    },
    ["60013038"] = {
        ["id"] = "60013038",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "840",
            ["countByTime"] = "1260",
            ["itemType"] = "PowerSteamFurnace",
        },
    },
    ["60013039"] = {
        ["id"] = "60013039",
        ["action"] = "SLEEP_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "44",
            ["hunger"] = "0",
        },
    },
    ["60013040"] = {
        ["id"] = "60013040",
        ["action"] = "EAT_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.6,
        ["task"] = {
            ["count"] = "88",
        },
    },
    ["60013041"] = {
        ["id"] = "60013041",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22.8,
        ["task"] = {
            ["count"] = "46",
            ["zoneId"] = "C6_Dorm_11",
        },
    },
    ["60013042"] = {
        ["id"] = "60013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "1380",
            ["itemType"] = "Coal",
        },
    },
    ["60013043"] = {
        ["id"] = "60013043",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.2,
        ["task"] = {
            ["count"] = "48",
            ["zoneId"] = "C6_Dorm_12",
        },
    },
    ["60013044"] = {
        ["id"] = "60013044",
        ["action"] = "SLEEP_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.6,
        ["task"] = {
            ["count"] = "48",
            ["hunger"] = "0",
        },
    },
    ["60013045"] = {
        ["id"] = "60013045",
        ["action"] = "EAT_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "96",
        },
    },
    ["60013046"] = {
        ["id"] = "60013046",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "15120",
            ["countByTime"] = "1440",
            ["itemType"] = "Mat",
        },
    },
    ["60013047"] = {
        ["id"] = "60013047",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "12600",
            ["countByTime"] = "1440",
            ["itemType"] = "SteelBlock",
        },
    },
    ["60013048"] = {
        ["id"] = "60013048",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GasSteelFurnace&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "690",
            ["countByTime"] = "1440",
            ["itemType"] = "GasSteelFurnace",
        },
    },
    ["60013049"] = {
        ["id"] = "60013049",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1730",
            ["countByTime"] = "1440",
            ["itemType"] = "SteelFrame",
        },
    },
    ["60013050"] = {
        ["id"] = "60013050",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "840",
            ["countByTime"] = "1440",
            ["itemType"] = "PowerSteamFurnace",
        },
    },
    ["60013051"] = {
        ["id"] = "60013051",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "1560",
            ["itemType"] = "Coal",
        },
    },
    ["60013052"] = {
        ["id"] = "60013052",
        ["action"] = "SLEEP_WELL",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 26.9,
        ["task"] = {
            ["count"] = "48",
            ["hunger"] = "0",
        },
    },
    ["60013053"] = {
        ["id"] = "60013053",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "12600",
            ["countByTime"] = "1620",
            ["itemType"] = "SteelBlock",
        },
    },
    ["60013054"] = {
        ["id"] = "60013054",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GasSteelFurnace&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "690",
            ["countByTime"] = "1620",
            ["itemType"] = "GasSteelFurnace",
        },
    },
    ["60013055"] = {
        ["id"] = "60013055",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1730",
            ["countByTime"] = "1620",
            ["itemType"] = "SteelFrame",
        },
    },
    ["60013056"] = {
        ["id"] = "60013056",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "840",
            ["countByTime"] = "1620",
            ["itemType"] = "PowerSteamFurnace",
        },
    },
    ["60013057"] = {
        ["id"] = "60013057",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal6&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "9200",
            ["countByTime"] = "1740",
            ["itemType"] = "Coal",
        },
    },
    ["60013058"] = {
        ["id"] = "60013058",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1730",
            ["countByTime"] = "1800",
            ["itemType"] = "SteelFrame",
        },
    },
    ["60013059"] = {
        ["id"] = "60013059",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 6,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "840",
            ["countByTime"] = "1800",
            ["itemType"] = "PowerSteamFurnace",
        },
    },
} 
