return {
    ["80011001"] = {
        ["id"] = "80011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80011002"] = {
        ["id"] = "80011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 10.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011003"] = {
        ["id"] = "80011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011004"] = {
        ["id"] = "80011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80011005"] = {
        ["id"] = "80011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011006"] = {
        ["id"] = "80011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80011007"] = {
        ["id"] = "80011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 12.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80011008"] = {
        ["id"] = "80011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80011009"] = {
        ["id"] = "80011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80011010"] = {
        ["id"] = "80011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 13.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011011"] = {
        ["id"] = "80011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011012"] = {
        ["id"] = "80011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80011013"] = {
        ["id"] = "80011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011014"] = {
        ["id"] = "80011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80011015"] = {
        ["id"] = "80011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80011016"] = {
        ["id"] = "80011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 16.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80011017"] = {
        ["id"] = "80011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80011018"] = {
        ["id"] = "80011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 16.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011019"] = {
        ["id"] = "80011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011020"] = {
        ["id"] = "80011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80011021"] = {
        ["id"] = "80011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011022"] = {
        ["id"] = "80011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 18.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80011023"] = {
        ["id"] = "80011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80011024"] = {
        ["id"] = "80011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80011025"] = {
        ["id"] = "80011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CornBroth&guarantee=1",
        ["stage"] = 19,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80011026"] = {
        ["id"] = "80011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011027"] = {
        ["id"] = "80011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 20.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011028"] = {
        ["id"] = "80011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80011029"] = {
        ["id"] = "80011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80011030"] = {
        ["id"] = "80011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80011031"] = {
        ["id"] = "80011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011032"] = {
        ["id"] = "80011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80011033"] = {
        ["id"] = "80011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80011034"] = {
        ["id"] = "80011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CornBroth&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80011035"] = {
        ["id"] = "80011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80011036"] = {
        ["id"] = "80011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011037"] = {
        ["id"] = "80011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 23.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011038"] = {
        ["id"] = "80011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80011039"] = {
        ["id"] = "80011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011040"] = {
        ["id"] = "80011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80011041"] = {
        ["id"] = "80011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80011042"] = {
        ["id"] = "80011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80011043"] = {
        ["id"] = "80011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CornBroth&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80011044"] = {
        ["id"] = "80011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80011045"] = {
        ["id"] = "80011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80011046"] = {
        ["id"] = "80011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Penicillin&guarantee=1",
        ["stage"] = 25.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80011047"] = {
        ["id"] = "80011047",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80011048"] = {
        ["id"] = "80011048",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011049"] = {
        ["id"] = "80011049",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80011050"] = {
        ["id"] = "80011050",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 26.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011051"] = {
        ["id"] = "80011051",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011052"] = {
        ["id"] = "80011052",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GlassPlate&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80011053"] = {
        ["id"] = "80011053",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80011054"] = {
        ["id"] = "80011054",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80011055"] = {
        ["id"] = "80011055",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Flask&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80011056"] = {
        ["id"] = "80011056",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80011057"] = {
        ["id"] = "80011057",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011058"] = {
        ["id"] = "80011058",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C8_Generator_1",
        },
    },
    ["80011059"] = {
        ["id"] = "80011059",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80011060"] = {
        ["id"] = "80011060",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80011061"] = {
        ["id"] = "80011061",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CornBroth&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80011062"] = {
        ["id"] = "80011062",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80011063"] = {
        ["id"] = "80011063",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80011064"] = {
        ["id"] = "80011064",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 32,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80011065"] = {
        ["id"] = "80011065",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 34,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80011066"] = {
        ["id"] = "80011066",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 66,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 34,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80012001"] = {
        ["id"] = "80012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C8_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80012003"] = {
        ["id"] = "80012003",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012004"] = {
        ["id"] = "80012004",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.1,
        ["task"] = {
            ["furnitureId"] = "C8_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80012005"] = {
        ["id"] = "80012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012006"] = {
        ["id"] = "80012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C8_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80012007"] = {
        ["id"] = "80012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12.3,
        ["task"] = {
            ["furnitureId"] = "C8_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80012008"] = {
        ["id"] = "80012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 12.7,
        ["task"] = {
            ["furnitureId"] = "C8_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80012009"] = {
        ["id"] = "80012009",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13,
        ["task"] = {
            ["furnitureId"] = "C8_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80012011"] = {
        ["id"] = "80012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012012"] = {
        ["id"] = "80012012",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14.2,
        ["task"] = {
            ["furnitureId"] = "C8_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80012013"] = {
        ["id"] = "80012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012014"] = {
        ["id"] = "80012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GlassPlate&guarantee=1",
        ["stage"] = 16,
        ["task"] = {
            ["furnitureId"] = "C8_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80012015"] = {
        ["id"] = "80012015",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16,
        ["task"] = {
            ["furnitureId"] = "C8_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80012016"] = {
        ["id"] = "80012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.4,
        ["task"] = {
            ["furnitureId"] = "C8_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80012017"] = {
        ["id"] = "80012017",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 16.6,
        ["task"] = {
            ["furnitureId"] = "C8_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80012019"] = {
        ["id"] = "80012019",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012020"] = {
        ["id"] = "80012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.3,
        ["task"] = {
            ["furnitureId"] = "C8_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80012021"] = {
        ["id"] = "80012021",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012022"] = {
        ["id"] = "80012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18.3,
        ["task"] = {
            ["furnitureId"] = "C8_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80012023"] = {
        ["id"] = "80012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GlassPlate&guarantee=1",
        ["stage"] = 19,
        ["task"] = {
            ["furnitureId"] = "C8_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80012024"] = {
        ["id"] = "80012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19,
        ["task"] = {
            ["furnitureId"] = "C8_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80012025"] = {
        ["id"] = "80012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80012026"] = {
        ["id"] = "80012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012028"] = {
        ["id"] = "80012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.3,
        ["task"] = {
            ["furnitureId"] = "C8_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80012029"] = {
        ["id"] = "80012029",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.8,
        ["task"] = {
            ["furnitureId"] = "C8_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80012030"] = {
        ["id"] = "80012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C8_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80012031"] = {
        ["id"] = "80012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012032"] = {
        ["id"] = "80012032",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GlassPlate&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["furnitureId"] = "C8_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80012033"] = {
        ["id"] = "80012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22,
        ["task"] = {
            ["furnitureId"] = "C8_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80012034"] = {
        ["id"] = "80012034",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80012035"] = {
        ["id"] = "80012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Flask&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80012036"] = {
        ["id"] = "80012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012038"] = {
        ["id"] = "80012038",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.4,
        ["task"] = {
            ["furnitureId"] = "C8_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80012039"] = {
        ["id"] = "80012039",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012040"] = {
        ["id"] = "80012040",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C8_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C8_Infirmary_1",
        },
    },
    ["80012041"] = {
        ["id"] = "80012041",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GlassPlate&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["furnitureId"] = "C8_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80012042"] = {
        ["id"] = "80012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25,
        ["task"] = {
            ["furnitureId"] = "C8_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80012043"] = {
        ["id"] = "80012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80012044"] = {
        ["id"] = "80012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Flask&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80012045"] = {
        ["id"] = "80012045",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25,
        ["task"] = {
            ["furnitureId"] = "C8_Laboratory_Tool1ForLaboratory",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80012046"] = {
        ["id"] = "80012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25.2,
        ["task"] = {
            ["furnitureId"] = "C8_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C8_Watchtower_1",
        },
    },
    ["80012047"] = {
        ["id"] = "80012047",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Penicillin&guarantee=1",
        ["stage"] = 25.3,
        ["task"] = {
            ["furnitureId"] = "C8_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C8_Kitchen_1",
        },
    },
    ["80012048"] = {
        ["id"] = "80012048",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012049"] = {
        ["id"] = "80012049",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26.5,
        ["task"] = {
            ["furnitureId"] = "C8_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "70",
            ["zoneId"] = "C8_HunterCabin_1",
        },
    },
    ["80012051"] = {
        ["id"] = "80012051",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012052"] = {
        ["id"] = "80012052",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["furnitureId"] = "C8_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C8_Metal_1",
        },
    },
    ["80012053"] = {
        ["id"] = "80012053",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["furnitureId"] = "C8_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80012054"] = {
        ["id"] = "80012054",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 28,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80012055"] = {
        ["id"] = "80012055",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80012056"] = {
        ["id"] = "80012056",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Penicillin&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["furnitureId"] = "C8_Laboratory_Tool1ForLaboratory",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80012057"] = {
        ["id"] = "80012057",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 29,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012059"] = {
        ["id"] = "80012059",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C8_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C8_CoalMine_1",
        },
    },
    ["80012060"] = {
        ["id"] = "80012060",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 31,
        ["task"] = {
            ["furnitureId"] = "C8_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C8_Greenhouse2_1",
        },
    },
    ["80012061"] = {
        ["id"] = "80012061",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C8_Carpentry_1",
        },
    },
    ["80012062"] = {
        ["id"] = "80012062",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Flask&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80012063"] = {
        ["id"] = "80012063",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 31,
        ["task"] = {
            ["furnitureId"] = "C8_Laboratory_Tool1ForLaboratory",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80012064"] = {
        ["id"] = "80012064",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 32,
        ["task"] = {
            ["furnitureId"] = "C8_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C8_CollectionStation_1",
        },
    },
    ["80012065"] = {
        ["id"] = "80012065",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Flask&guarantee=1",
        ["stage"] = 34,
        ["task"] = {
            ["furnitureId"] = "C8_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C8_Carpentry2_1",
        },
    },
    ["80012066"] = {
        ["id"] = "80012066",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 66,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 34,
        ["task"] = {
            ["furnitureId"] = "C8_Laboratory_Tool1ForLaboratory",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C8_Laboratory_1",
        },
    },
    ["80013001"] = {
        ["id"] = "80013001",
        ["action"] = "EAT_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["80013002"] = {
        ["id"] = "80013002",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 10.3,
        ["task"] = {
            ["count"] = "4",
            ["zoneId"] = "C8_Dorm_2",
        },
    },
    ["80013003"] = {
        ["id"] = "80013003",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "660",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013004"] = {
        ["id"] = "80013004",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.1,
        ["task"] = {
            ["count"] = "6",
            ["zoneId"] = "C8_Dorm_3",
        },
    },
    ["80013005"] = {
        ["id"] = "80013005",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "720",
            ["itemType"] = "Coal",
        },
    },
    ["80013006"] = {
        ["id"] = "80013006",
        ["action"] = "SLEEP_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "6",
            ["hunger"] = "0",
        },
    },
    ["80013007"] = {
        ["id"] = "80013007",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.3,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C8_Dorm_2",
        },
    },
    ["80013008"] = {
        ["id"] = "80013008",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C8_Dorm_1",
        },
    },
    ["80013009"] = {
        ["id"] = "80013009",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=GlassPlate&guarantee=1",
        ["stage"] = 13,
        ["task"] = {
            ["count"] = "1050",
            ["countByTime"] = "780",
            ["itemType"] = "GlassPlate",
        },
    },
    ["80013010"] = {
        ["id"] = "80013010",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 13.6,
        ["task"] = {
            ["count"] = "12",
            ["zoneId"] = "C8_Dorm_4",
        },
    },
    ["80013011"] = {
        ["id"] = "80013011",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "840",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013012"] = {
        ["id"] = "80013012",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14.2,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C8_Dorm_3",
        },
    },
    ["80013013"] = {
        ["id"] = "80013013",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "900",
            ["itemType"] = "Coal",
        },
    },
    ["80013014"] = {
        ["id"] = "80013014",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16,
        ["task"] = {
            ["count"] = "1050",
            ["countByTime"] = "960",
            ["itemType"] = "GlassPlate",
        },
    },
    ["80013015"] = {
        ["id"] = "80013015",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 16,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "960",
            ["itemType"] = "Corn",
        },
    },
    ["80013016"] = {
        ["id"] = "80013016",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.4,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C8_Dorm_5",
        },
    },
    ["80013017"] = {
        ["id"] = "80013017",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.6,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C8_Dorm_6",
        },
    },
    ["80013018"] = {
        ["id"] = "80013018",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 16.9,
        ["task"] = {
            ["count"] = "22",
            ["zoneId"] = "C8_Dorm_7",
        },
    },
    ["80013019"] = {
        ["id"] = "80013019",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1020",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013020"] = {
        ["id"] = "80013020",
        ["action"] = "EAT_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17.3,
        ["task"] = {
            ["count"] = "44",
        },
    },
    ["80013021"] = {
        ["id"] = "80013021",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1080",
            ["itemType"] = "Coal",
        },
    },
    ["80013022"] = {
        ["id"] = "80013022",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18.3,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C8_Dorm_10",
        },
    },
    ["80013023"] = {
        ["id"] = "80013023",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19,
        ["task"] = {
            ["count"] = "1050",
            ["countByTime"] = "1140",
            ["itemType"] = "GlassPlate",
        },
    },
    ["80013024"] = {
        ["id"] = "80013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 19,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1140",
            ["itemType"] = "Corn",
        },
    },
    ["80013025"] = {
        ["id"] = "80013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19,
        ["task"] = {
            ["count"] = "280",
            ["countByTime"] = "1140",
            ["itemType"] = "CornBroth",
        },
    },
    ["80013026"] = {
        ["id"] = "80013026",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1200",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013027"] = {
        ["id"] = "80013027",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 20.2,
        ["task"] = {
            ["count"] = "40",
            ["zoneId"] = "C8_Dorm_14",
        },
    },
    ["80013028"] = {
        ["id"] = "80013028",
        ["action"] = "SLEEP_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.3,
        ["task"] = {
            ["count"] = "40",
            ["hunger"] = "0",
        },
    },
    ["80013029"] = {
        ["id"] = "80013029",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.8,
        ["task"] = {
            ["count"] = "42",
            ["zoneId"] = "C8_Dorm_7",
        },
    },
    ["80013030"] = {
        ["id"] = "80013030",
        ["action"] = "EAT_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "84",
        },
    },
    ["80013031"] = {
        ["id"] = "80013031",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1260",
            ["itemType"] = "Coal",
        },
    },
    ["80013032"] = {
        ["id"] = "80013032",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "1050",
            ["countByTime"] = "1320",
            ["itemType"] = "GlassPlate",
        },
    },
    ["80013033"] = {
        ["id"] = "80013033",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1320",
            ["itemType"] = "Corn",
        },
    },
    ["80013034"] = {
        ["id"] = "80013034",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "280",
            ["countByTime"] = "1320",
            ["itemType"] = "CornBroth",
        },
    },
    ["80013035"] = {
        ["id"] = "80013035",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1320",
            ["itemType"] = "Flask",
        },
    },
    ["80013036"] = {
        ["id"] = "80013036",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1380",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013037"] = {
        ["id"] = "80013037",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 23.4,
        ["task"] = {
            ["count"] = "50",
            ["zoneId"] = "C8_Dorm_11",
        },
    },
    ["80013038"] = {
        ["id"] = "80013038",
        ["action"] = "SLEEP_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.4,
        ["task"] = {
            ["count"] = "50",
            ["hunger"] = "0",
        },
    },
    ["80013039"] = {
        ["id"] = "80013039",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1440",
            ["itemType"] = "Coal",
        },
    },
    ["80013040"] = {
        ["id"] = "80013040",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "52",
            ["zoneId"] = "C8_Dorm_12",
        },
    },
    ["80013041"] = {
        ["id"] = "80013041",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "1050",
            ["countByTime"] = "1500",
            ["itemType"] = "GlassPlate",
        },
    },
    ["80013042"] = {
        ["id"] = "80013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1500",
            ["itemType"] = "Corn",
        },
    },
    ["80013043"] = {
        ["id"] = "80013043",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "280",
            ["countByTime"] = "1500",
            ["itemType"] = "CornBroth",
        },
    },
    ["80013044"] = {
        ["id"] = "80013044",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1500",
            ["itemType"] = "Flask",
        },
    },
    ["80013045"] = {
        ["id"] = "80013045",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Penicillin&guarantee=1",
        ["stage"] = 25,
        ["task"] = {
            ["count"] = "150",
            ["countByTime"] = "1500",
            ["itemType"] = "Penicillin",
        },
    },
    ["80013046"] = {
        ["id"] = "80013046",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.2,
        ["task"] = {
            ["count"] = "56",
            ["zoneId"] = "C8_Dorm_14",
        },
    },
    ["80013047"] = {
        ["id"] = "80013047",
        ["action"] = "EAT_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25.3,
        ["task"] = {
            ["count"] = "112",
        },
    },
    ["80013048"] = {
        ["id"] = "80013048",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1560",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013049"] = {
        ["id"] = "80013049",
        ["action"] = "SLEEP_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26.5,
        ["task"] = {
            ["count"] = "56",
            ["hunger"] = "0",
        },
    },
    ["80013050"] = {
        ["id"] = "80013050",
        ["action"] = "EAT_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 26.7,
        ["task"] = {
            ["count"] = "112",
        },
    },
    ["80013051"] = {
        ["id"] = "80013051",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal8&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1620",
            ["itemType"] = "Coal",
        },
    },
    ["80013052"] = {
        ["id"] = "80013052",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "1050",
            ["countByTime"] = "1680",
            ["itemType"] = "GlassPlate",
        },
    },
    ["80013053"] = {
        ["id"] = "80013053",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1680",
            ["itemType"] = "Corn",
        },
    },
    ["80013054"] = {
        ["id"] = "80013054",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CornBroth&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "280",
            ["countByTime"] = "1680",
            ["itemType"] = "CornBroth",
        },
    },
    ["80013055"] = {
        ["id"] = "80013055",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1680",
            ["itemType"] = "Flask",
        },
    },
    ["80013056"] = {
        ["id"] = "80013056",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 28,
        ["task"] = {
            ["count"] = "150",
            ["countByTime"] = "1680",
            ["itemType"] = "Penicillin",
        },
    },
    ["80013057"] = {
        ["id"] = "80013057",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass8&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1740",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013058"] = {
        ["id"] = "80013058",
        ["action"] = "SLEEP_WELL",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "56",
            ["hunger"] = "0",
        },
    },
    ["80013059"] = {
        ["id"] = "80013059",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1800",
            ["itemType"] = "Coal",
        },
    },
    ["80013060"] = {
        ["id"] = "80013060",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Corn&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1860",
            ["itemType"] = "Corn",
        },
    },
    ["80013061"] = {
        ["id"] = "80013061",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "280",
            ["countByTime"] = "1860",
            ["itemType"] = "CornBroth",
        },
    },
    ["80013062"] = {
        ["id"] = "80013062",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1860",
            ["itemType"] = "Flask",
        },
    },
    ["80013063"] = {
        ["id"] = "80013063",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Penicillin&guarantee=1",
        ["stage"] = 31,
        ["task"] = {
            ["count"] = "150",
            ["countByTime"] = "1860",
            ["itemType"] = "Penicillin",
        },
    },
    ["80013064"] = {
        ["id"] = "80013064",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 32,
        ["task"] = {
            ["count"] = "2520",
            ["countByTime"] = "1920",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["80013065"] = {
        ["id"] = "80013065",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 34,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "2040",
            ["itemType"] = "Flask",
        },
    },
    ["80013066"] = {
        ["id"] = "80013066",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 8,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 66,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Penicillin&guarantee=1",
        ["stage"] = 34,
        ["task"] = {
            ["count"] = "150",
            ["countByTime"] = "2040",
            ["itemType"] = "Penicillin",
        },
    },
} 
