return {
    ["30011010"] = {
        ["id"] = 30011010,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=IronBlock2&guarantee=1',
        ["group"] = 1,
        ["index"] = 10,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30011012"] = {
        ["id"] = 30011012,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_17',
        ["group"] = 1,
        ["index"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_Watchtower_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30011014"] = {
        ["id"] = 30011014,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["30011018"] = {
        ["id"] = 30011018,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_Metal2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30011019"] = {
        ["id"] = 30011019,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Cylinder&guarantee=1',
        ["group"] = 1,
        ["index"] = 19,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 15.8,
        ["desc"] = '',
    },
    ["30011037"] = {
        ["id"] = 30011037,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=SteamEngine&guarantee=1',
        ["group"] = 1,
        ["index"] = 37,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_MachineryFactory_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30012039"] = {
        ["id"] = 30012039,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 39,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C3_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 24.0,
        ["desc"] = '',
    },
    ["30012038"] = {
        ["id"] = 30012038,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Coal3&guarantee=1',
        ["group"] = 2,
        ["index"] = 38,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "150",
            ["furnitureId"] = "C3_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 23.0,
        ["desc"] = '',
    },
    ["30011032"] = {
        ["id"] = 30011032,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_blue',
        ["group"] = 1,
        ["index"] = 32,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C3_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 20.6,
        ["desc"] = '',
    },
    ["30012035"] = {
        ["id"] = 30012035,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Cylinder&guarantee=1',
        ["group"] = 2,
        ["index"] = 35,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C3_Metal2_Tool1ForMetal2",
            ["zoneId"] = "C3_Metal2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30012034"] = {
        ["id"] = 30012034,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 34,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "90",
            ["furnitureId"] = "C3_Metal_Tool1ForMetal",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011003"] = {
        ["id"] = 30011003,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 9.4,
        ["desc"] = '',
    },
    ["30012029"] = {
        ["id"] = 30012029,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Link&guarantee=1',
        ["group"] = 2,
        ["index"] = 29,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "50",
            ["furnitureId"] = "C3_Kitchen_Burner",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 18.7,
        ["desc"] = '',
    },
    ["30011007"] = {
        ["id"] = 30011007,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.9,
        ["desc"] = '',
    },
    ["30011006"] = {
        ["id"] = 30011006,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["30011005"] = {
        ["id"] = 30011005,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 9.9,
        ["desc"] = '',
    },
    ["30011004"] = {
        ["id"] = 30011004,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_blue',
        ["group"] = 1,
        ["index"] = 4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 9.7,
        ["desc"] = '',
    },
    ["30012020"] = {
        ["id"] = 30012020,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 20,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "50",
            ["furnitureId"] = "C3_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 16.7,
        ["desc"] = '',
    },
    ["30011009"] = {
        ["id"] = 30011009,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["30012025"] = {
        ["id"] = 30012025,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 25,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "90",
            ["furnitureId"] = "C3_IronMine_Tool1ForIronMine",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30012026"] = {
        ["id"] = 30012026,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=IronBlock2&guarantee=1',
        ["group"] = 2,
        ["index"] = 26,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C3_Metal_Tool1ForMetal",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30012027"] = {
        ["id"] = 30012027,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 27,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_Metal2_Tool1ForMetal2",
            ["zoneId"] = "C3_Metal2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30011034"] = {
        ["id"] = 30011034,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=IronBlock2&guarantee=1',
        ["group"] = 1,
        ["index"] = 34,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011036"] = {
        ["id"] = 30011036,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 36,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011033"] = {
        ["id"] = 30011033,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011031"] = {
        ["id"] = 30011031,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Coal3&guarantee=1',
        ["group"] = 1,
        ["index"] = 31,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 20.0,
        ["desc"] = '',
    },
    ["30012033"] = {
        ["id"] = 30012033,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 33,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "120",
            ["furnitureId"] = "C3_IronMine_Tool1ForIronMine",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30012031"] = {
        ["id"] = 30012031,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 31,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "120",
            ["furnitureId"] = "C3_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 20.0,
        ["desc"] = '',
    },
    ["30012030"] = {
        ["id"] = 30012030,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 30,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C3_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 19.2,
        ["desc"] = '',
    },
    ["30012037"] = {
        ["id"] = 30012037,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 37,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_MachineryFactory_Tool1ForMachineryFactory",
            ["zoneId"] = "C3_MachineryFactory_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30012036"] = {
        ["id"] = 30012036,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 36,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011038"] = {
        ["id"] = 30011038,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 38,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 23.0,
        ["desc"] = '',
    },
    ["30011039"] = {
        ["id"] = 30011039,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 39,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 24.0,
        ["desc"] = '',
    },
    ["30013012"] = {
        ["id"] = 30013012,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=IronBlock2&guarantee=1',
        ["group"] = 3,
        ["index"] = 12,
        ["task"] = {
            ["count"] = "18",
            ["hunger"] = "0",
        },
        ["part"] = 1,
        ["action"] = 'SLEEP_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["30011030"] = {
        ["id"] = 30011030,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 19.2,
        ["desc"] = '',
    },
    ["30011011"] = {
        ["id"] = 30011011,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 12.8,
        ["desc"] = '',
    },
    ["30011015"] = {
        ["id"] = 30011015,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 14.3,
        ["desc"] = '',
    },
    ["30012008"] = {
        ["id"] = 30012008,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 8,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C3_Infirmary_MedicalBed",
            ["zoneId"] = "C3_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 11.9,
        ["desc"] = '',
    },
    ["30012009"] = {
        ["id"] = 30012009,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 9,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_IronMine_Tool1ForIronMine",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["30012006"] = {
        ["id"] = 30012006,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 6,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["30012007"] = {
        ["id"] = 30012007,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 7,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 11.9,
        ["desc"] = '',
    },
    ["30012005"] = {
        ["id"] = 30012005,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 5,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C3_Kitchen_Burner",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 9.9,
        ["desc"] = '',
    },
    ["30012002"] = {
        ["id"] = 30012002,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Iron&guarantee=1',
        ["group"] = 2,
        ["index"] = 2,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_IronMine_Tool1ForIronMine",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 9.0,
        ["desc"] = '',
    },
    ["30012003"] = {
        ["id"] = 30012003,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 3,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C3_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 9.4,
        ["desc"] = '',
    },
    ["30012001"] = {
        ["id"] = 30012001,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 1,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_Infirmary_MedicalBed",
            ["zoneId"] = "C3_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["30011029"] = {
        ["id"] = 30011029,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 29,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 18.7,
        ["desc"] = '',
    },
    ["30011028"] = {
        ["id"] = 30011028,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Link&guarantee=1',
        ["group"] = 1,
        ["index"] = 28,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30011020"] = {
        ["id"] = 30011020,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 16.7,
        ["desc"] = '',
    },
    ["30011023"] = {
        ["id"] = 30011023,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 23,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["30011022"] = {
        ["id"] = 30011022,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_blue',
        ["group"] = 1,
        ["index"] = 22,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C3_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["30011025"] = {
        ["id"] = 30011025,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Iron&guarantee=1',
        ["group"] = 1,
        ["index"] = 25,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30011024"] = {
        ["id"] = 30011024,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Watchtower_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.3,
        ["desc"] = '',
    },
    ["30011027"] = {
        ["id"] = 30011027,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Metal2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30011026"] = {
        ["id"] = 30011026,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 26,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30012011"] = {
        ["id"] = 30012011,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=IronBlock2&guarantee=1',
        ["group"] = 2,
        ["index"] = 11,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_Kitchen_Burner",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 12.8,
        ["desc"] = '',
    },
    ["30012015"] = {
        ["id"] = 30012015,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 15,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "40",
            ["furnitureId"] = "C3_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C3_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 14.3,
        ["desc"] = '',
    },
    ["30012014"] = {
        ["id"] = 30012014,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Coal3&guarantee=1',
        ["group"] = 2,
        ["index"] = 14,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C3_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["30012017"] = {
        ["id"] = 30012017,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=IronBlock2&guarantee=1',
        ["group"] = 2,
        ["index"] = 17,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_Metal_Tool1ForMetal",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30012019"] = {
        ["id"] = 30012019,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 19,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "40",
            ["furnitureId"] = "C3_Kitchen_Burner",
            ["zoneId"] = "C3_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 15.8,
        ["desc"] = '',
    },
    ["30013031"] = {
        ["id"] = 30013031,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 31,
        ["task"] = {
            ["count"] = "2640",
            ["countByTime"] = "1200",
            ["itemType"] = "Coal",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 20.0,
        ["desc"] = '',
    },
    ["30013033"] = {
        ["id"] = 30013033,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Iron&guarantee=1',
        ["group"] = 3,
        ["index"] = 33,
        ["task"] = {
            ["count"] = "4950",
            ["countByTime"] = "1260",
            ["itemType"] = "Iron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30013034"] = {
        ["id"] = 30013034,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 34,
        ["task"] = {
            ["count"] = "1320",
            ["countByTime"] = "1260",
            ["itemType"] = "IronBlock",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011001"] = {
        ["id"] = 30011001,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30013030"] = {
        ["id"] = 30013030,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 30,
        ["task"] = {
            ["count"] = "36",
            ["zoneId"] = "C3_Dorm_8",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 19.2,
        ["desc"] = '',
    },
    ["30013035"] = {
        ["id"] = 30013035,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 35,
        ["task"] = {
            ["count"] = "660",
            ["countByTime"] = "1260",
            ["itemType"] = "Cylinder",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30013037"] = {
        ["id"] = 30013037,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 37,
        ["task"] = {
            ["count"] = "110",
            ["countByTime"] = "1260",
            ["itemType"] = "SteamEngine",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30013039"] = {
        ["id"] = 30013039,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Link&guarantee=1',
        ["group"] = 3,
        ["index"] = 39,
        ["task"] = {
            ["count"] = "830",
            ["countByTime"] = "1440",
            ["itemType"] = "Link",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 24.0,
        ["desc"] = '',
    },
    ["30012028"] = {
        ["id"] = 30012028,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 28,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C3_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30013023"] = {
        ["id"] = 30013023,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 23,
        ["task"] = {
            ["count"] = "2640",
            ["countByTime"] = "1020",
            ["itemType"] = "Coal",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["30013022"] = {
        ["id"] = 30013022,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 3,
        ["index"] = 22,
        ["task"] = {
            ["count"] = "56",
        },
        ["part"] = 1,
        ["action"] = 'EAT_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["30013021"] = {
        ["id"] = 30013021,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 21,
        ["task"] = {
            ["count"] = "28",
            ["hunger"] = "0",
        },
        ["part"] = 1,
        ["action"] = 'SLEEP_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 16.7,
        ["desc"] = '',
    },
    ["30013020"] = {
        ["id"] = 30013020,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 20,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C3_Dorm_6",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 16.7,
        ["desc"] = '',
    },
    ["30013027"] = {
        ["id"] = 30013027,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Cylinder&guarantee=1',
        ["group"] = 3,
        ["index"] = 27,
        ["task"] = {
            ["count"] = "660",
            ["countByTime"] = "1080",
            ["itemType"] = "Cylinder",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30013026"] = {
        ["id"] = 30013026,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 26,
        ["task"] = {
            ["count"] = "1320",
            ["countByTime"] = "1080",
            ["itemType"] = "IronBlock",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30013025"] = {
        ["id"] = 30013025,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 25,
        ["task"] = {
            ["count"] = "4950",
            ["countByTime"] = "1080",
            ["itemType"] = "Iron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30013024"] = {
        ["id"] = 30013024,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Coal3&guarantee=1',
        ["group"] = 3,
        ["index"] = 24,
        ["task"] = {
            ["count"] = "30",
            ["zoneId"] = "C3_Dorm_9",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 17.3,
        ["desc"] = '',
    },
    ["30013029"] = {
        ["id"] = 30013029,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 29,
        ["task"] = {
            ["count"] = "34",
            ["zoneId"] = "C3_Dorm_10",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 18.7,
        ["desc"] = '',
    },
    ["30013028"] = {
        ["id"] = 30013028,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 28,
        ["task"] = {
            ["count"] = "830",
            ["countByTime"] = "1080",
            ["itemType"] = "Link",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 18.0,
        ["desc"] = '',
    },
    ["30012040"] = {
        ["id"] = 30012040,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 40,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_MachineryFactory_Tool1ForMachineryFactory",
            ["zoneId"] = "C3_MachineryFactory_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 24.0,
        ["desc"] = '',
    },
    ["30011021"] = {
        ["id"] = 30011021,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 16.7,
        ["desc"] = '',
    },
    ["30013016"] = {
        ["id"] = 30013016,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 16,
        ["task"] = {
            ["count"] = "4950",
            ["countByTime"] = "900",
            ["itemType"] = "Iron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30013017"] = {
        ["id"] = 30013017,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 17,
        ["task"] = {
            ["count"] = "1320",
            ["countByTime"] = "900",
            ["itemType"] = "IronBlock",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30013014"] = {
        ["id"] = 30013014,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 14,
        ["task"] = {
            ["count"] = "2640",
            ["countByTime"] = "840",
            ["itemType"] = "Coal",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["30013015"] = {
        ["id"] = 30013015,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 15,
        ["task"] = {
            ["count"] = "40",
        },
        ["part"] = 1,
        ["action"] = 'EAT_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 14.3,
        ["desc"] = '',
    },
    ["30013013"] = {
        ["id"] = 30013013,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 3,
        ["index"] = 13,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C3_Dorm_6",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 13.3,
        ["desc"] = '',
    },
    ["30013010"] = {
        ["id"] = 30013010,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 10,
        ["task"] = {
            ["count"] = "1320",
            ["countByTime"] = "720",
            ["itemType"] = "IronBlock",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["30013011"] = {
        ["id"] = 30013011,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 11,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C3_Dorm_5",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 12.8,
        ["desc"] = '',
    },
    ["30013018"] = {
        ["id"] = 30013018,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Cylinder&guarantee=1',
        ["group"] = 3,
        ["index"] = 18,
        ["task"] = {
            ["count"] = "660",
            ["countByTime"] = "900",
            ["itemType"] = "Cylinder",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30013019"] = {
        ["id"] = 30013019,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 19,
        ["task"] = {
            ["count"] = "24",
            ["zoneId"] = "C3_Dorm_5",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 15.8,
        ["desc"] = '',
    },
    ["30011002"] = {
        ["id"] = 30011002,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 9.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["30013009"] = {
        ["id"] = 30013009,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Iron&guarantee=1',
        ["group"] = 3,
        ["index"] = 9,
        ["task"] = {
            ["count"] = "4950",
            ["countByTime"] = "720",
            ["itemType"] = "Iron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["30013003"] = {
        ["id"] = 30013003,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 3,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C3_Dorm_4",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 9.4,
        ["desc"] = '',
    },
    ["30013005"] = {
        ["id"] = 30013005,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 5,
        ["task"] = {
            ["count"] = "10",
            ["hunger"] = "0",
        },
        ["part"] = 1,
        ["action"] = 'SLEEP_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 9.9,
        ["desc"] = '',
    },
    ["30013004"] = {
        ["id"] = 30013004,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 3,
        ["index"] = 4,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C3_Dorm_8",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 9.7,
        ["desc"] = '',
    },
    ["30013007"] = {
        ["id"] = 30013007,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 7,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C3_Dorm_3",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 11.9,
        ["desc"] = '',
    },
    ["30013006"] = {
        ["id"] = 30013006,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Coal3&guarantee=1',
        ["group"] = 3,
        ["index"] = 6,
        ["task"] = {
            ["count"] = "2640",
            ["countByTime"] = "660",
            ["itemType"] = "Coal",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["30012021"] = {
        ["id"] = 30012021,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 21,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C3_Infirmary_MedicalBed",
            ["zoneId"] = "C3_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 16.7,
        ["desc"] = '',
    },
    ["30012023"] = {
        ["id"] = 30012023,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Coal3&guarantee=1',
        ["group"] = 2,
        ["index"] = 23,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "90",
            ["furnitureId"] = "C3_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C3_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["30012024"] = {
        ["id"] = 30012024,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 24,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C3_Watchtower_Boost1ForWatchtower",
            ["zoneId"] = "C3_Watchtower_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 17.3,
        ["desc"] = '',
    },
    ["30011013"] = {
        ["id"] = 30011013,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_blue',
        ["group"] = 1,
        ["index"] = 13,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 13.3,
        ["desc"] = '',
    },
    ["30013036"] = {
        ["id"] = 30013036,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Link&guarantee=1',
        ["group"] = 3,
        ["index"] = 36,
        ["task"] = {
            ["count"] = "830",
            ["countByTime"] = "1260",
            ["itemType"] = "Link",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30013038"] = {
        ["id"] = 30013038,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 38,
        ["task"] = {
            ["count"] = "2640",
            ["countByTime"] = "1380",
            ["itemType"] = "Coal",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 23.0,
        ["desc"] = '',
    },
    ["30011035"] = {
        ["id"] = 30011035,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 35,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_Metal2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 21.0,
        ["desc"] = '',
    },
    ["30011008"] = {
        ["id"] = 30011008,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.9,
        ["desc"] = '',
    },
    ["30011016"] = {
        ["id"] = 30011016,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=Iron&guarantee=1',
        ["group"] = 1,
        ["index"] = 16,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30011017"] = {
        ["id"] = 30011017,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30012010"] = {
        ["id"] = 30012010,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 10,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_Metal_Tool1ForMetal",
            ["zoneId"] = "C3_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["30012012"] = {
        ["id"] = 30012012,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 12,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_Watchtower_Boost1ForWatchtower",
            ["zoneId"] = "C3_Watchtower_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["30012016"] = {
        ["id"] = 30012016,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 16,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C3_IronMine_Tool1ForIronMine",
            ["zoneId"] = "C3_IronMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30012018"] = {
        ["id"] = 30012018,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 18,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C3_Metal2_Tool1ForMetal2",
            ["zoneId"] = "C3_Metal2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 15.0,
        ["desc"] = '',
    },
    ["30013040"] = {
        ["id"] = 30013040,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 40,
        ["task"] = {
            ["count"] = "110",
            ["countByTime"] = "1440",
            ["itemType"] = "SteamEngine",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 24.0,
        ["desc"] = '',
    },
    ["30013008"] = {
        ["id"] = 30013008,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 8,
        ["task"] = {
            ["count"] = "28",
        },
        ["part"] = 1,
        ["action"] = 'EAT_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 11.9,
        ["desc"] = '',
    },
    ["30013001"] = {
        ["id"] = 30013001,
        ["city"] = 3,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 1,
        ["task"] = {
            ["count"] = "8",
        },
        ["part"] = 1,
        ["action"] = 'EAT_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["30013002"] = {
        ["id"] = 30013002,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*1200?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 2,
        ["task"] = {
            ["count"] = "4950",
            ["countByTime"] = "540",
            ["itemType"] = "Iron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 9.0,
        ["desc"] = '',
    },
    ["30011040"] = {
        ["id"] = 30011040,
        ["city"] = 3,
        ["rewards"] = 'addToOverTime*900?id=SteamEngine&guarantee=1',
        ["group"] = 1,
        ["index"] = 40,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C3_MachineryFactory_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 24.0,
        ["desc"] = '',
    },
    ["30013032"] = {
        ["id"] = 30013032,
        ["city"] = 3,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 3,
        ["index"] = 32,
        ["task"] = {
            ["count"] = "40",
            ["zoneId"] = "C3_Dorm_9",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 20.6,
        ["desc"] = '',
    },
} 
