return {
    ["100011001"] = {
        ["id"] = "100011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100011002"] = {
        ["id"] = "100011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 10.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011003"] = {
        ["id"] = "100011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100011004"] = {
        ["id"] = "100011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100011005"] = {
        ["id"] = "100011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011006"] = {
        ["id"] = "100011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100011007"] = {
        ["id"] = "100011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 13,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100011008"] = {
        ["id"] = "100011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100011009"] = {
        ["id"] = "100011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011010"] = {
        ["id"] = "100011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100011011"] = {
        ["id"] = "100011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011012"] = {
        ["id"] = "100011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100011013"] = {
        ["id"] = "100011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100011014"] = {
        ["id"] = "100011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100011015"] = {
        ["id"] = "100011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 17.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011016"] = {
        ["id"] = "100011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100011017"] = {
        ["id"] = "100011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011018"] = {
        ["id"] = "100011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100011019"] = {
        ["id"] = "100011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100011020"] = {
        ["id"] = "100011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100011021"] = {
        ["id"] = "100011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100011022"] = {
        ["id"] = "100011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 19.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100011023"] = {
        ["id"] = "100011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100011024"] = {
        ["id"] = "100011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011025"] = {
        ["id"] = "100011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100011026"] = {
        ["id"] = "100011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100011027"] = {
        ["id"] = "100011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100011028"] = {
        ["id"] = "100011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Drum&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100011029"] = {
        ["id"] = "100011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 21.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011030"] = {
        ["id"] = "100011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100011031"] = {
        ["id"] = "100011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100011032"] = {
        ["id"] = "100011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011033"] = {
        ["id"] = "100011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100011034"] = {
        ["id"] = "100011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100011035"] = {
        ["id"] = "100011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100011036"] = {
        ["id"] = "100011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100011037"] = {
        ["id"] = "100011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Motor&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100011038"] = {
        ["id"] = "100011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 24.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011039"] = {
        ["id"] = "100011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100011040"] = {
        ["id"] = "100011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100011041"] = {
        ["id"] = "100011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011042"] = {
        ["id"] = "100011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100011043"] = {
        ["id"] = "100011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100011044"] = {
        ["id"] = "100011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100011045"] = {
        ["id"] = "100011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100011046"] = {
        ["id"] = "100011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Motor&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100011047"] = {
        ["id"] = "100011047",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100011048"] = {
        ["id"] = "100011048",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100011049"] = {
        ["id"] = "100011049",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 27.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100011050"] = {
        ["id"] = "100011050",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100011051"] = {
        ["id"] = "100011051",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 28.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011052"] = {
        ["id"] = "100011052",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100011053"] = {
        ["id"] = "100011053",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100011054"] = {
        ["id"] = "100011054",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100011055"] = {
        ["id"] = "100011055",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Drum&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100011056"] = {
        ["id"] = "100011056",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100011057"] = {
        ["id"] = "100011057",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100011058"] = {
        ["id"] = "100011058",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 31.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C10_Generator_1",
        },
    },
    ["100011059"] = {
        ["id"] = "100011059",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100011060"] = {
        ["id"] = "100011060",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100011061"] = {
        ["id"] = "100011061",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Motor&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100011062"] = {
        ["id"] = "100011062",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100011063"] = {
        ["id"] = "100011063",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 34.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100011064"] = {
        ["id"] = "100011064",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Motor&guarantee=1",
        ["stage"] = 36,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100011065"] = {
        ["id"] = "100011065",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 36,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100012001"] = {
        ["id"] = "100012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C10_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100012003"] = {
        ["id"] = "100012003",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.3,
        ["task"] = {
            ["furnitureId"] = "C10_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100012004"] = {
        ["id"] = "100012004",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.9,
        ["task"] = {
            ["furnitureId"] = "C10_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100012005"] = {
        ["id"] = "100012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012006"] = {
        ["id"] = "100012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100012007"] = {
        ["id"] = "100012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13,
        ["task"] = {
            ["furnitureId"] = "C10_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100012008"] = {
        ["id"] = "100012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 13.1,
        ["task"] = {
            ["furnitureId"] = "C10_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100012010"] = {
        ["id"] = "100012010",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14.6,
        ["task"] = {
            ["furnitureId"] = "C10_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100012011"] = {
        ["id"] = "100012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012012"] = {
        ["id"] = "100012012",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100012013"] = {
        ["id"] = "100012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C10_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100012014"] = {
        ["id"] = "100012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 15.7,
        ["task"] = {
            ["furnitureId"] = "C10_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100012016"] = {
        ["id"] = "100012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17.9,
        ["task"] = {
            ["furnitureId"] = "C10_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100012017"] = {
        ["id"] = "100012017",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012018"] = {
        ["id"] = "100012018",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100012019"] = {
        ["id"] = "100012019",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C10_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100012020"] = {
        ["id"] = "100012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C10_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100012021"] = {
        ["id"] = "100012021",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.1,
        ["task"] = {
            ["furnitureId"] = "C10_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100012022"] = {
        ["id"] = "100012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.6,
        ["task"] = {
            ["furnitureId"] = "C10_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100012023"] = {
        ["id"] = "100012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 20.3,
        ["task"] = {
            ["furnitureId"] = "C10_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100012024"] = {
        ["id"] = "100012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012025"] = {
        ["id"] = "100012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100012026"] = {
        ["id"] = "100012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C10_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100012027"] = {
        ["id"] = "100012027",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C10_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100012028"] = {
        ["id"] = "100012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100012030"] = {
        ["id"] = "100012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.3,
        ["task"] = {
            ["furnitureId"] = "C10_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100012031"] = {
        ["id"] = "100012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.5,
        ["task"] = {
            ["furnitureId"] = "C10_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100012032"] = {
        ["id"] = "100012032",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012033"] = {
        ["id"] = "100012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100012034"] = {
        ["id"] = "100012034",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C10_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100012035"] = {
        ["id"] = "100012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C10_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100012036"] = {
        ["id"] = "100012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100012037"] = {
        ["id"] = "100012037",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C10_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100012039"] = {
        ["id"] = "100012039",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24.6,
        ["task"] = {
            ["furnitureId"] = "C10_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100012040"] = {
        ["id"] = "100012040",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25.2,
        ["task"] = {
            ["furnitureId"] = "C10_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C10_Infirmary_1",
        },
    },
    ["100012041"] = {
        ["id"] = "100012041",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012042"] = {
        ["id"] = "100012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C10_Carpentry_1",
        },
    },
    ["100012043"] = {
        ["id"] = "100012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100012044"] = {
        ["id"] = "100012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100012045"] = {
        ["id"] = "100012045",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100012046"] = {
        ["id"] = "100012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100012047"] = {
        ["id"] = "100012047",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C10_OilWell_Tool1ForOilWell",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100012048"] = {
        ["id"] = "100012048",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27.3,
        ["task"] = {
            ["furnitureId"] = "C10_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_Kitchen_1",
        },
    },
    ["100012049"] = {
        ["id"] = "100012049",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27.5,
        ["task"] = {
            ["furnitureId"] = "C10_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100012050"] = {
        ["id"] = "100012050",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27.9,
        ["task"] = {
            ["furnitureId"] = "C10_HunterCabin_Tool1ForHunterCabin",
            ["index"] = "1",
            ["level"] = "70",
            ["zoneId"] = "C10_HunterCabin_1",
        },
    },
    ["100012052"] = {
        ["id"] = "100012052",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C10_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C10_CoalMine_1",
        },
    },
    ["100012053"] = {
        ["id"] = "100012053",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronSheet&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C10_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C10_Metal_1",
        },
    },
    ["100012054"] = {
        ["id"] = "100012054",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C10_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100012055"] = {
        ["id"] = "100012055",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100012056"] = {
        ["id"] = "100012056",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Motor&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C10_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100012057"] = {
        ["id"] = "100012057",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C10_OilWell_Tool1ForOilWell",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100012059"] = {
        ["id"] = "100012059",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C10_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C10_Metal2_1",
        },
    },
    ["100012060"] = {
        ["id"] = "100012060",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C10_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C10_Carpentry2_1",
        },
    },
    ["100012061"] = {
        ["id"] = "100012061",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C10_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100012062"] = {
        ["id"] = "100012062",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C10_OilWell_Tool1ForOilWell",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100012063"] = {
        ["id"] = "100012063",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 34.8,
        ["task"] = {
            ["furnitureId"] = "C10_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C10_Watchtower_1",
        },
    },
    ["100012064"] = {
        ["id"] = "100012064",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 36,
        ["task"] = {
            ["furnitureId"] = "C10_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C10_MachineryFactory_1",
        },
    },
    ["100012065"] = {
        ["id"] = "100012065",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 36,
        ["task"] = {
            ["furnitureId"] = "C10_OilWell_Tool1ForOilWell",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C10_OilWell_1",
        },
    },
    ["100013001"] = {
        ["id"] = "100013001",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["100013002"] = {
        ["id"] = "100013002",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 10.5,
        ["task"] = {
            ["count"] = "4",
            ["zoneId"] = "C10_Dorm_2",
        },
    },
    ["100013003"] = {
        ["id"] = "100013003",
        ["action"] = "SLEEP_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.3,
        ["task"] = {
            ["count"] = "4",
            ["hunger"] = "0",
        },
    },
    ["100013004"] = {
        ["id"] = "100013004",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.9,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["100013005"] = {
        ["id"] = "100013005",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "720",
            ["itemType"] = "Coal",
        },
    },
    ["100013006"] = {
        ["id"] = "100013006",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "7650",
            ["countByTime"] = "720",
            ["itemType"] = "CopperWire",
        },
    },
    ["100013007"] = {
        ["id"] = "100013007",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C10_Dorm_3",
        },
    },
    ["100013008"] = {
        ["id"] = "100013008",
        ["action"] = "SLEEP_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.1,
        ["task"] = {
            ["count"] = "10",
            ["hunger"] = "0",
        },
    },
    ["100013009"] = {
        ["id"] = "100013009",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "20",
        },
    },
    ["100013010"] = {
        ["id"] = "100013010",
        ["action"] = "SLEEP_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14.6,
        ["task"] = {
            ["count"] = "10",
            ["hunger"] = "0",
        },
    },
    ["100013011"] = {
        ["id"] = "100013011",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "900",
            ["itemType"] = "Coal",
        },
    },
    ["100013012"] = {
        ["id"] = "100013012",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "7650",
            ["countByTime"] = "900",
            ["itemType"] = "CopperWire",
        },
    },
    ["100013013"] = {
        ["id"] = "100013013",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "9240",
            ["countByTime"] = "900",
            ["itemType"] = "IronSheet",
        },
    },
    ["100013014"] = {
        ["id"] = "100013014",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.7,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C10_Dorm_4",
        },
    },
    ["100013015"] = {
        ["id"] = "100013015",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 17.5,
        ["task"] = {
            ["count"] = "28",
        },
    },
    ["100013016"] = {
        ["id"] = "100013016",
        ["action"] = "SLEEP_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.9,
        ["task"] = {
            ["count"] = "14",
            ["hunger"] = "0",
        },
    },
    ["100013017"] = {
        ["id"] = "100013017",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "1080",
            ["itemType"] = "Coal",
        },
    },
    ["100013018"] = {
        ["id"] = "100013018",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "7650",
            ["countByTime"] = "1080",
            ["itemType"] = "CopperWire",
        },
    },
    ["100013019"] = {
        ["id"] = "100013019",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "9240",
            ["countByTime"] = "1080",
            ["itemType"] = "IronSheet",
        },
    },
    ["100013020"] = {
        ["id"] = "100013020",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "10200",
            ["countByTime"] = "1080",
            ["itemType"] = "CopperCoil",
        },
    },
    ["100013021"] = {
        ["id"] = "100013021",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 19.1,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C10_Dorm_5",
        },
    },
    ["100013022"] = {
        ["id"] = "100013022",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.6,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C10_Dorm_6",
        },
    },
    ["100013023"] = {
        ["id"] = "100013023",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.3,
        ["task"] = {
            ["count"] = "40",
        },
    },
    ["100013024"] = {
        ["id"] = "100013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal10&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "1260",
            ["itemType"] = "Coal",
        },
    },
    ["100013025"] = {
        ["id"] = "100013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "7650",
            ["countByTime"] = "1260",
            ["itemType"] = "CopperWire",
        },
    },
    ["100013026"] = {
        ["id"] = "100013026",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "9240",
            ["countByTime"] = "1260",
            ["itemType"] = "IronSheet",
        },
    },
    ["100013027"] = {
        ["id"] = "100013027",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "10200",
            ["countByTime"] = "1260",
            ["itemType"] = "CopperCoil",
        },
    },
    ["100013028"] = {
        ["id"] = "100013028",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "770",
            ["countByTime"] = "1260",
            ["itemType"] = "Drum",
        },
    },
    ["100013029"] = {
        ["id"] = "100013029",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 21.1,
        ["task"] = {
            ["count"] = "24",
            ["zoneId"] = "C10_Dorm_5",
        },
    },
    ["100013030"] = {
        ["id"] = "100013030",
        ["action"] = "SLEEP_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.3,
        ["task"] = {
            ["count"] = "24",
            ["hunger"] = "0",
        },
    },
    ["100013031"] = {
        ["id"] = "100013031",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.5,
        ["task"] = {
            ["count"] = "30",
            ["zoneId"] = "C10_Dorm_9",
        },
    },
    ["100013032"] = {
        ["id"] = "100013032",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "1440",
            ["itemType"] = "Coal",
        },
    },
    ["100013033"] = {
        ["id"] = "100013033",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "7650",
            ["countByTime"] = "1440",
            ["itemType"] = "CopperWire",
        },
    },
    ["100013034"] = {
        ["id"] = "100013034",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "9240",
            ["countByTime"] = "1440",
            ["itemType"] = "IronSheet",
        },
    },
    ["100013035"] = {
        ["id"] = "100013035",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "10200",
            ["countByTime"] = "1440",
            ["itemType"] = "CopperCoil",
        },
    },
    ["100013036"] = {
        ["id"] = "100013036",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Drum&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "770",
            ["countByTime"] = "1440",
            ["itemType"] = "Drum",
        },
    },
    ["100013037"] = {
        ["id"] = "100013037",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "3400",
            ["countByTime"] = "1440",
            ["itemType"] = "Motor",
        },
    },
    ["100013038"] = {
        ["id"] = "100013038",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 24.6,
        ["task"] = {
            ["count"] = "32",
            ["zoneId"] = "C10_Dorm_7",
        },
    },
    ["100013039"] = {
        ["id"] = "100013039",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24.6,
        ["task"] = {
            ["count"] = "64",
        },
    },
    ["100013040"] = {
        ["id"] = "100013040",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.2,
        ["task"] = {
            ["count"] = "34",
            ["zoneId"] = "C10_Dorm_10",
        },
    },
    ["100013041"] = {
        ["id"] = "100013041",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "1620",
            ["itemType"] = "Coal",
        },
    },
    ["100013042"] = {
        ["id"] = "100013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire10&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "7650",
            ["countByTime"] = "1620",
            ["itemType"] = "CopperWire",
        },
    },
    ["100013043"] = {
        ["id"] = "100013043",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "9240",
            ["countByTime"] = "1620",
            ["itemType"] = "IronSheet",
        },
    },
    ["100013044"] = {
        ["id"] = "100013044",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "10200",
            ["countByTime"] = "1620",
            ["itemType"] = "CopperCoil",
        },
    },
    ["100013045"] = {
        ["id"] = "100013045",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Drum&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "770",
            ["countByTime"] = "1620",
            ["itemType"] = "Drum",
        },
    },
    ["100013046"] = {
        ["id"] = "100013046",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "3400",
            ["countByTime"] = "1620",
            ["itemType"] = "Motor",
        },
    },
    ["100013047"] = {
        ["id"] = "100013047",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "600",
            ["countByTime"] = "1620",
            ["itemType"] = "Oil",
        },
    },
    ["100013048"] = {
        ["id"] = "100013048",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 27.3,
        ["task"] = {
            ["count"] = "38",
            ["zoneId"] = "C10_Dorm_8",
        },
    },
    ["100013049"] = {
        ["id"] = "100013049",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27.5,
        ["task"] = {
            ["count"] = "40",
            ["zoneId"] = "C10_Dorm_12",
        },
    },
    ["100013050"] = {
        ["id"] = "100013050",
        ["action"] = "SLEEP_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27.9,
        ["task"] = {
            ["count"] = "40",
            ["hunger"] = "0",
        },
    },
    ["100013051"] = {
        ["id"] = "100013051",
        ["action"] = "EAT_WELL",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 28.1,
        ["task"] = {
            ["count"] = "80",
        },
    },
    ["100013052"] = {
        ["id"] = "100013052",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "30800",
            ["countByTime"] = "1800",
            ["itemType"] = "Coal",
        },
    },
    ["100013053"] = {
        ["id"] = "100013053",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "9240",
            ["countByTime"] = "1800",
            ["itemType"] = "IronSheet",
        },
    },
    ["100013054"] = {
        ["id"] = "100013054",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperCoil&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "10200",
            ["countByTime"] = "1800",
            ["itemType"] = "CopperCoil",
        },
    },
    ["100013055"] = {
        ["id"] = "100013055",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "770",
            ["countByTime"] = "1800",
            ["itemType"] = "Drum",
        },
    },
    ["100013056"] = {
        ["id"] = "100013056",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "3400",
            ["countByTime"] = "1800",
            ["itemType"] = "Motor",
        },
    },
    ["100013057"] = {
        ["id"] = "100013057",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "600",
            ["countByTime"] = "1800",
            ["itemType"] = "Oil",
        },
    },
    ["100013058"] = {
        ["id"] = "100013058",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 31.6,
        ["task"] = {
            ["count"] = "48",
            ["zoneId"] = "C10_Dorm_14",
        },
    },
    ["100013059"] = {
        ["id"] = "100013059",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "10200",
            ["countByTime"] = "1980",
            ["itemType"] = "CopperCoil",
        },
    },
    ["100013060"] = {
        ["id"] = "100013060",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Drum&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "770",
            ["countByTime"] = "1980",
            ["itemType"] = "Drum",
        },
    },
    ["100013061"] = {
        ["id"] = "100013061",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "3400",
            ["countByTime"] = "1980",
            ["itemType"] = "Motor",
        },
    },
    ["100013062"] = {
        ["id"] = "100013062",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "600",
            ["countByTime"] = "1980",
            ["itemType"] = "Oil",
        },
    },
    ["100013063"] = {
        ["id"] = "100013063",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Oil&guarantee=1",
        ["stage"] = 34.8,
        ["task"] = {
            ["count"] = "52",
            ["zoneId"] = "C10_Dorm_12",
        },
    },
    ["100013064"] = {
        ["id"] = "100013064",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 10,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 36,
        ["task"] = {
            ["count"] = "3400",
            ["countByTime"] = "2160",
            ["itemType"] = "Motor",
        },
    },
} 
