return {
    ["90011001"] = {
        ["id"] = "90011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90011002"] = {
        ["id"] = "90011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011003"] = {
        ["id"] = "90011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011004"] = {
        ["id"] = "90011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90011005"] = {
        ["id"] = "90011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011006"] = {
        ["id"] = "90011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90011007"] = {
        ["id"] = "90011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011008"] = {
        ["id"] = "90011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90011009"] = {
        ["id"] = "90011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90011010"] = {
        ["id"] = "90011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011011"] = {
        ["id"] = "90011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90011012"] = {
        ["id"] = "90011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90011013"] = {
        ["id"] = "90011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011014"] = {
        ["id"] = "90011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011015"] = {
        ["id"] = "90011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90011016"] = {
        ["id"] = "90011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Distiller&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90011017"] = {
        ["id"] = "90011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011018"] = {
        ["id"] = "90011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90011019"] = {
        ["id"] = "90011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90011020"] = {
        ["id"] = "90011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90011021"] = {
        ["id"] = "90011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011022"] = {
        ["id"] = "90011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 17.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90011023"] = {
        ["id"] = "90011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011024"] = {
        ["id"] = "90011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90011025"] = {
        ["id"] = "90011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Distiller&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90011026"] = {
        ["id"] = "90011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90011027"] = {
        ["id"] = "90011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 18.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011028"] = {
        ["id"] = "90011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90011029"] = {
        ["id"] = "90011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90011030"] = {
        ["id"] = "90011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011031"] = {
        ["id"] = "90011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 20.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90011032"] = {
        ["id"] = "90011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011033"] = {
        ["id"] = "90011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90011034"] = {
        ["id"] = "90011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Distiller&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90011035"] = {
        ["id"] = "90011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90011036"] = {
        ["id"] = "90011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90011037"] = {
        ["id"] = "90011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011038"] = {
        ["id"] = "90011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90011039"] = {
        ["id"] = "90011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011040"] = {
        ["id"] = "90011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 23.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90011041"] = {
        ["id"] = "90011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011042"] = {
        ["id"] = "90011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011043"] = {
        ["id"] = "90011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90011044"] = {
        ["id"] = "90011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90011045"] = {
        ["id"] = "90011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90011046"] = {
        ["id"] = "90011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Grape&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90011047"] = {
        ["id"] = "90011047",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90011048"] = {
        ["id"] = "90011048",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90011049"] = {
        ["id"] = "90011049",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Liquor&guarantee=1",
        ["stage"] = 24.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90011050"] = {
        ["id"] = "90011050",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90011051"] = {
        ["id"] = "90011051",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011052"] = {
        ["id"] = "90011052",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 26.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C9_Generator_1",
        },
    },
    ["90011053"] = {
        ["id"] = "90011053",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011054"] = {
        ["id"] = "90011054",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90011055"] = {
        ["id"] = "90011055",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Distiller&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90011056"] = {
        ["id"] = "90011056",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90011057"] = {
        ["id"] = "90011057",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90011058"] = {
        ["id"] = "90011058",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Liquor&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90011059"] = {
        ["id"] = "90011059",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90011060"] = {
        ["id"] = "90011060",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90011061"] = {
        ["id"] = "90011061",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Grape&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90011062"] = {
        ["id"] = "90011062",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90011063"] = {
        ["id"] = "90011063",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90012001"] = {
        ["id"] = "90012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C9_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90012002"] = {
        ["id"] = "90012002",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012004"] = {
        ["id"] = "90012004",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90012005"] = {
        ["id"] = "90012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012006"] = {
        ["id"] = "90012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C9_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90012007"] = {
        ["id"] = "90012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012008"] = {
        ["id"] = "90012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C9_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90012009"] = {
        ["id"] = "90012009",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.5,
        ["task"] = {
            ["furnitureId"] = "C9_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90012011"] = {
        ["id"] = "90012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 13,
        ["task"] = {
            ["furnitureId"] = "C9_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90012012"] = {
        ["id"] = "90012012",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.9,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90012013"] = {
        ["id"] = "90012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012014"] = {
        ["id"] = "90012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012015"] = {
        ["id"] = "90012015",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C9_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90012016"] = {
        ["id"] = "90012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90012018"] = {
        ["id"] = "90012018",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.5,
        ["task"] = {
            ["furnitureId"] = "C9_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90012019"] = {
        ["id"] = "90012019",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.9,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90012020"] = {
        ["id"] = "90012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.9,
        ["task"] = {
            ["furnitureId"] = "C9_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90012021"] = {
        ["id"] = "90012021",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012022"] = {
        ["id"] = "90012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17.9,
        ["task"] = {
            ["furnitureId"] = "C9_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90012023"] = {
        ["id"] = "90012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012024"] = {
        ["id"] = "90012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C9_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90012025"] = {
        ["id"] = "90012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90012026"] = {
        ["id"] = "90012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=WoodenBarrel&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90012028"] = {
        ["id"] = "90012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.9,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90012029"] = {
        ["id"] = "90012029",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["furnitureId"] = "C9_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90012030"] = {
        ["id"] = "90012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012031"] = {
        ["id"] = "90012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.9,
        ["task"] = {
            ["furnitureId"] = "C9_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90012032"] = {
        ["id"] = "90012032",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012033"] = {
        ["id"] = "90012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C9_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90012034"] = {
        ["id"] = "90012034",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90012035"] = {
        ["id"] = "90012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=WoodenBarrel&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90012036"] = {
        ["id"] = "90012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90012038"] = {
        ["id"] = "90012038",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 22.9,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90012039"] = {
        ["id"] = "90012039",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012040"] = {
        ["id"] = "90012040",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23.4,
        ["task"] = {
            ["furnitureId"] = "C9_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C9_Infirmary_1",
        },
    },
    ["90012042"] = {
        ["id"] = "90012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012043"] = {
        ["id"] = "90012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C9_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90012044"] = {
        ["id"] = "90012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Distiller&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90012045"] = {
        ["id"] = "90012045",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90012046"] = {
        ["id"] = "90012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90012047"] = {
        ["id"] = "90012047",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Liquor&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C9_FoodFactory_Tool1ForFoodFactory",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90012048"] = {
        ["id"] = "90012048",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24.4,
        ["task"] = {
            ["furnitureId"] = "C9_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C9_Watchtower_1",
        },
    },
    ["90012049"] = {
        ["id"] = "90012049",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24.8,
        ["task"] = {
            ["furnitureId"] = "C9_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C9_Kitchen_1",
        },
    },
    ["90012050"] = {
        ["id"] = "90012050",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.8,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "70",
            ["zoneId"] = "C9_Greenhouse_1",
        },
    },
    ["90012051"] = {
        ["id"] = "90012051",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012053"] = {
        ["id"] = "90012053",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012054"] = {
        ["id"] = "90012054",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C9_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C9_Metal_1",
        },
    },
    ["90012055"] = {
        ["id"] = "90012055",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C9_Carpentry_1",
        },
    },
    ["90012056"] = {
        ["id"] = "90012056",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=WoodenBarrel&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C9_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_Carpentry2_1",
        },
    },
    ["90012057"] = {
        ["id"] = "90012057",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90012058"] = {
        ["id"] = "90012058",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C9_FoodFactory_Tool1ForFoodFactory",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90012059"] = {
        ["id"] = "90012059",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["furnitureId"] = "C9_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C9_CoalMine_1",
        },
    },
    ["90012060"] = {
        ["id"] = "90012060",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C9_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C9_CollectionStation_1",
        },
    },
    ["90012061"] = {
        ["id"] = "90012061",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C9_Greenhouse2_Tool1ForGreenhouse2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_Greenhouse2_1",
        },
    },
    ["90012062"] = {
        ["id"] = "90012062",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Liquor&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C9_FoodFactory_Tool1ForFoodFactory",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90012063"] = {
        ["id"] = "90012063",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C9_FoodFactory_Tool1ForFoodFactory",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C9_FoodFactory_1",
        },
    },
    ["90013001"] = {
        ["id"] = "90013001",
        ["action"] = "EAT_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["90013002"] = {
        ["id"] = "90013002",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "540",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013003"] = {
        ["id"] = "90013003",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "6",
            ["zoneId"] = "C9_Dorm_3",
        },
    },
    ["90013004"] = {
        ["id"] = "90013004",
        ["action"] = "SLEEP_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "6",
            ["hunger"] = "0",
        },
    },
    ["90013005"] = {
        ["id"] = "90013005",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "660",
            ["itemType"] = "Coal",
        },
    },
    ["90013006"] = {
        ["id"] = "90013006",
        ["action"] = "EAT_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "12",
        },
    },
    ["90013007"] = {
        ["id"] = "90013007",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "720",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013008"] = {
        ["id"] = "90013008",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "720",
            ["itemType"] = "IronWire",
        },
    },
    ["90013009"] = {
        ["id"] = "90013009",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 12.5,
        ["task"] = {
            ["count"] = "12",
            ["zoneId"] = "C9_Dorm_4",
        },
    },
    ["90013010"] = {
        ["id"] = "90013010",
        ["action"] = "SLEEP_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "12",
            ["hunger"] = "0",
        },
    },
    ["90013011"] = {
        ["id"] = "90013011",
        ["action"] = "EAT_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13,
        ["task"] = {
            ["count"] = "24",
        },
    },
    ["90013012"] = {
        ["id"] = "90013012",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.9,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C9_Dorm_1",
        },
    },
    ["90013013"] = {
        ["id"] = "90013013",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "840",
            ["itemType"] = "Coal",
        },
    },
    ["90013014"] = {
        ["id"] = "90013014",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "900",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013015"] = {
        ["id"] = "90013015",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "900",
            ["itemType"] = "IronWire",
        },
    },
    ["90013016"] = {
        ["id"] = "90013016",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1200",
            ["countByTime"] = "900",
            ["itemType"] = "Distiller",
        },
    },
    ["90013017"] = {
        ["id"] = "90013017",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C9_Dorm_5",
        },
    },
    ["90013018"] = {
        ["id"] = "90013018",
        ["action"] = "SLEEP_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Distiller&guarantee=1",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "18",
            ["hunger"] = "0",
        },
    },
    ["90013019"] = {
        ["id"] = "90013019",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.9,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C9_Dorm_6",
        },
    },
    ["90013020"] = {
        ["id"] = "90013020",
        ["action"] = "EAT_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.9,
        ["task"] = {
            ["count"] = "40",
        },
    },
    ["90013021"] = {
        ["id"] = "90013021",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "1020",
            ["itemType"] = "Coal",
        },
    },
    ["90013022"] = {
        ["id"] = "90013022",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.9,
        ["task"] = {
            ["count"] = "22",
            ["zoneId"] = "C9_Dorm_7",
        },
    },
    ["90013023"] = {
        ["id"] = "90013023",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "1080",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013024"] = {
        ["id"] = "90013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1080",
            ["itemType"] = "IronWire",
        },
    },
    ["90013025"] = {
        ["id"] = "90013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1200",
            ["countByTime"] = "1080",
            ["itemType"] = "Distiller",
        },
    },
    ["90013026"] = {
        ["id"] = "90013026",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1140",
            ["countByTime"] = "1080",
            ["itemType"] = "WoodenBarrel",
        },
    },
    ["90013027"] = {
        ["id"] = "90013027",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 18.4,
        ["task"] = {
            ["count"] = "24",
            ["zoneId"] = "C9_Dorm_5",
        },
    },
    ["90013028"] = {
        ["id"] = "90013028",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C9_Dorm_6",
        },
    },
    ["90013029"] = {
        ["id"] = "90013029",
        ["action"] = "SLEEP_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.9,
        ["task"] = {
            ["count"] = "28",
            ["hunger"] = "0",
        },
    },
    ["90013030"] = {
        ["id"] = "90013030",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "1200",
            ["itemType"] = "Coal",
        },
    },
    ["90013031"] = {
        ["id"] = "90013031",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.9,
        ["task"] = {
            ["count"] = "30",
            ["zoneId"] = "C9_Dorm_9",
        },
    },
    ["90013032"] = {
        ["id"] = "90013032",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "1260",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013033"] = {
        ["id"] = "90013033",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1260",
            ["itemType"] = "IronWire",
        },
    },
    ["90013034"] = {
        ["id"] = "90013034",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1200",
            ["countByTime"] = "1260",
            ["itemType"] = "Distiller",
        },
    },
    ["90013035"] = {
        ["id"] = "90013035",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1140",
            ["countByTime"] = "1260",
            ["itemType"] = "WoodenBarrel",
        },
    },
    ["90013036"] = {
        ["id"] = "90013036",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Grape&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "11400",
            ["countByTime"] = "1260",
            ["itemType"] = "Grape",
        },
    },
    ["90013037"] = {
        ["id"] = "90013037",
        ["action"] = "EAT_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "60",
        },
    },
    ["90013038"] = {
        ["id"] = "90013038",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 22.9,
        ["task"] = {
            ["count"] = "34",
            ["zoneId"] = "C9_Dorm_10",
        },
    },
    ["90013039"] = {
        ["id"] = "90013039",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "1380",
            ["itemType"] = "Coal",
        },
    },
    ["90013040"] = {
        ["id"] = "90013040",
        ["action"] = "SLEEP_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23.4,
        ["task"] = {
            ["count"] = "34",
            ["hunger"] = "0",
        },
    },
    ["90013041"] = {
        ["id"] = "90013041",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "38",
            ["zoneId"] = "C9_Dorm_8",
        },
    },
    ["90013042"] = {
        ["id"] = "90013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "1440",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013043"] = {
        ["id"] = "90013043",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1440",
            ["itemType"] = "IronWire",
        },
    },
    ["90013044"] = {
        ["id"] = "90013044",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1200",
            ["countByTime"] = "1440",
            ["itemType"] = "Distiller",
        },
    },
    ["90013045"] = {
        ["id"] = "90013045",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=WoodenBarrel&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1140",
            ["countByTime"] = "1440",
            ["itemType"] = "WoodenBarrel",
        },
    },
    ["90013046"] = {
        ["id"] = "90013046",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "11400",
            ["countByTime"] = "1440",
            ["itemType"] = "Grape",
        },
    },
    ["90013047"] = {
        ["id"] = "90013047",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1440",
            ["itemType"] = "Liquor",
        },
    },
    ["90013048"] = {
        ["id"] = "90013048",
        ["action"] = "EAT_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Liquor&guarantee=1",
        ["stage"] = 24.4,
        ["task"] = {
            ["count"] = "76",
        },
    },
    ["90013049"] = {
        ["id"] = "90013049",
        ["action"] = "SLEEP_WELL",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24.8,
        ["task"] = {
            ["count"] = "38",
            ["hunger"] = "0",
        },
    },
    ["90013050"] = {
        ["id"] = "90013050",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25.8,
        ["task"] = {
            ["count"] = "42",
            ["zoneId"] = "C9_Dorm_9",
        },
    },
    ["90013051"] = {
        ["id"] = "90013051",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal9&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "1560",
            ["itemType"] = "Coal",
        },
    },
    ["90013052"] = {
        ["id"] = "90013052",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 26.9,
        ["task"] = {
            ["count"] = "44",
            ["zoneId"] = "C9_Dorm_13",
        },
    },
    ["90013053"] = {
        ["id"] = "90013053",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "1620",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013054"] = {
        ["id"] = "90013054",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=IronWire&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "16800",
            ["countByTime"] = "1620",
            ["itemType"] = "IronWire",
        },
    },
    ["90013055"] = {
        ["id"] = "90013055",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1200",
            ["countByTime"] = "1620",
            ["itemType"] = "Distiller",
        },
    },
    ["90013056"] = {
        ["id"] = "90013056",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1140",
            ["countByTime"] = "1620",
            ["itemType"] = "WoodenBarrel",
        },
    },
    ["90013057"] = {
        ["id"] = "90013057",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Grape&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "11400",
            ["countByTime"] = "1620",
            ["itemType"] = "Grape",
        },
    },
    ["90013058"] = {
        ["id"] = "90013058",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1620",
            ["itemType"] = "Liquor",
        },
    },
    ["90013059"] = {
        ["id"] = "90013059",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "48000",
            ["countByTime"] = "1740",
            ["itemType"] = "Coal",
        },
    },
    ["90013060"] = {
        ["id"] = "90013060",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass9&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "14400",
            ["countByTime"] = "1800",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["90013061"] = {
        ["id"] = "90013061",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "11400",
            ["countByTime"] = "1800",
            ["itemType"] = "Grape",
        },
    },
    ["90013062"] = {
        ["id"] = "90013062",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1800",
            ["itemType"] = "Liquor",
        },
    },
    ["90013063"] = {
        ["id"] = "90013063",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 9,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Liquor&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1980",
            ["itemType"] = "Liquor",
        },
    },  
} 
