return {
    ["40011001"] = {
        ["id"] = "40011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40011002"] = {
        ["id"] = "40011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40011003"] = {
        ["id"] = "40011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40011004"] = {
        ["id"] = "40011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 10.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Generator_1",
        },
    },
    ["40011005"] = {
        ["id"] = "40011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40011006"] = {
        ["id"] = "40011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40011007"] = {
        ["id"] = "40011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal4&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_Watchtower_1",
        },
    },
    ["40011008"] = {
        ["id"] = "40011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40011009"] = {
        ["id"] = "40011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40011010"] = {
        ["id"] = "40011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperBlock&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40011011"] = {
        ["id"] = "40011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40011012"] = {
        ["id"] = "40011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 13.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Generator_1",
        },
    },
    ["40011013"] = {
        ["id"] = "40011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40011014"] = {
        ["id"] = "40011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40011015"] = {
        ["id"] = "40011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40011016"] = {
        ["id"] = "40011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperBlock&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40011017"] = {
        ["id"] = "40011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40011018"] = {
        ["id"] = "40011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Watchtower_1",
        },
    },
    ["40011019"] = {
        ["id"] = "40011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40011020"] = {
        ["id"] = "40011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40011021"] = {
        ["id"] = "40011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_Generator_1",
        },
    },
    ["40011022"] = {
        ["id"] = "40011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal4&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40011023"] = {
        ["id"] = "40011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40011024"] = {
        ["id"] = "40011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40011025"] = {
        ["id"] = "40011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperBlock&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40011026"] = {
        ["id"] = "40011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40011027"] = {
        ["id"] = "40011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_CollectionStation_1",
        },
    },
    ["40011028"] = {
        ["id"] = "40011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass&guarantee=1",
        ["stage"] = 18.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40011029"] = {
        ["id"] = "40011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Watchtower_1",
        },
    },
    ["40011030"] = {
        ["id"] = "40011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40011031"] = {
        ["id"] = "40011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal4&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40011032"] = {
        ["id"] = "40011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 20.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C4_Generator_1",
        },
    },
    ["40011033"] = {
        ["id"] = "40011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40011034"] = {
        ["id"] = "40011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40011035"] = {
        ["id"] = "40011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40011036"] = {
        ["id"] = "40011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40011037"] = {
        ["id"] = "40011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_CollectionStation_1",
        },
    },
    ["40011038"] = {
        ["id"] = "40011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C4_Carpentry_1",
        },
    },
    ["40011039"] = {
        ["id"] = "40011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40011040"] = {
        ["id"] = "40011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 23.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C4_Generator_1",
        },
    },
    ["40011041"] = {
        ["id"] = "40011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40011042"] = {
        ["id"] = "40011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40011043"] = {
        ["id"] = "40011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40011044"] = {
        ["id"] = "40011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_CollectionStation_1",
        },
    },
    ["40011045"] = {
        ["id"] = "40011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C4_Carpentry_1",
        },
    },
    ["40011046"] = {
        ["id"] = "40011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ElectricLight&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C4_Carpentry_1",
        },
    },
    ["40012001"] = {
        ["id"] = "40012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C4_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40012002"] = {
        ["id"] = "40012002",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["furnitureId"] = "C4_CopperMine_Tool1ForCopperMine",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40012003"] = {
        ["id"] = "40012003",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9.8,
        ["task"] = {
            ["furnitureId"] = "C4_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40012005"] = {
        ["id"] = "40012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.4,
        ["task"] = {
            ["furnitureId"] = "C4_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40012006"] = {
        ["id"] = "40012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C4_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40012007"] = {
        ["id"] = "40012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C4_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_Watchtower_1",
        },
    },
    ["40012008"] = {
        ["id"] = "40012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal4&guarantee=1",
        ["stage"] = 11.3,
        ["task"] = {
            ["furnitureId"] = "C4_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40012009"] = {
        ["id"] = "40012009",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C4_CopperMine_Tool1ForCopperMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40012010"] = {
        ["id"] = "40012010",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C4_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40012011"] = {
        ["id"] = "40012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperBlock&guarantee=1",
        ["stage"] = 12.7,
        ["task"] = {
            ["furnitureId"] = "C4_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40012013"] = {
        ["id"] = "40012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.8,
        ["task"] = {
            ["furnitureId"] = "C4_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40012014"] = {
        ["id"] = "40012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal4&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["furnitureId"] = "C4_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40012015"] = {
        ["id"] = "40012015",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C4_CopperMine_Tool1ForCopperMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40012016"] = {
        ["id"] = "40012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C4_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40012017"] = {
        ["id"] = "40012017",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C4_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40012018"] = {
        ["id"] = "40012018",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.3,
        ["task"] = {
            ["furnitureId"] = "C4_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C4_Watchtower_1",
        },
    },
    ["40012019"] = {
        ["id"] = "40012019",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.5,
        ["task"] = {
            ["furnitureId"] = "C4_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40012020"] = {
        ["id"] = "40012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 15.5,
        ["task"] = {
            ["furnitureId"] = "C4_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40012022"] = {
        ["id"] = "40012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["furnitureId"] = "C4_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40012023"] = {
        ["id"] = "40012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.2,
        ["task"] = {
            ["furnitureId"] = "C4_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40012024"] = {
        ["id"] = "40012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C4_CopperMine_Tool1ForCopperMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40012025"] = {
        ["id"] = "40012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C4_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40012026"] = {
        ["id"] = "40012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C4_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40012027"] = {
        ["id"] = "40012027",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C4_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_CollectionStation_1",
        },
    },
    ["40012028"] = {
        ["id"] = "40012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18.3,
        ["task"] = {
            ["furnitureId"] = "C4_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40012029"] = {
        ["id"] = "40012029",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass&guarantee=1",
        ["stage"] = 19.7,
        ["task"] = {
            ["furnitureId"] = "C4_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Watchtower_1",
        },
    },
    ["40012030"] = {
        ["id"] = "40012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.8,
        ["task"] = {
            ["furnitureId"] = "C4_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C4_Infirmary_1",
        },
    },
    ["40012031"] = {
        ["id"] = "40012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["furnitureId"] = "C4_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C4_CoalMine_1",
        },
    },
    ["40012033"] = {
        ["id"] = "40012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.6,
        ["task"] = {
            ["furnitureId"] = "C4_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C4_Greenhouse_1",
        },
    },
    ["40012034"] = {
        ["id"] = "40012034",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C4_CopperMine_Tool1ForCopperMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40012035"] = {
        ["id"] = "40012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperBlock&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C4_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40012036"] = {
        ["id"] = "40012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C4_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40012037"] = {
        ["id"] = "40012037",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C4_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_CollectionStation_1",
        },
    },
    ["40012038"] = {
        ["id"] = "40012038",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ElectricLight&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C4_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C4_Carpentry_1",
        },
    },
    ["40012039"] = {
        ["id"] = "40012039",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.2,
        ["task"] = {
            ["furnitureId"] = "C4_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_Kitchen_1",
        },
    },
    ["40012041"] = {
        ["id"] = "40012041",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C4_CopperMine_Tool1ForCopperMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C4_CopperMine_1",
        },
    },
    ["40012042"] = {
        ["id"] = "40012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C4_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C4_Metal_1",
        },
    },
    ["40012043"] = {
        ["id"] = "40012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C4_Metal2_Tool1ForMetal2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C4_Metal2_1",
        },
    },
    ["40012044"] = {
        ["id"] = "40012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C4_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_CollectionStation_1",
        },
    },
    ["40012045"] = {
        ["id"] = "40012045",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C4_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C4_Carpentry_1",
        },
    },
    ["40012046"] = {
        ["id"] = "40012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C4_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C4_Carpentry_1",
        },
    },
    ["40013001"] = {
        ["id"] = "40013001",
        ["action"] = "SLEEP_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "4",
            ["hunger"] = "0",
        },
    },
    ["40013002"] = {
        ["id"] = "40013002",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "6300",
            ["countByTime"] = "540",
            ["itemType"] = "Copper",
        },
    },
    ["40013003"] = {
        ["id"] = "40013003",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 9.8,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C4_Dorm_4",
        },
    },
    ["40013004"] = {
        ["id"] = "40013004",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 10.3,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C4_Dorm_2",
        },
    },
    ["40013005"] = {
        ["id"] = "40013005",
        ["action"] = "EAT_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 10.4,
        ["task"] = {
            ["count"] = "20",
        },
    },
    ["40013006"] = {
        ["id"] = "40013006",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal4&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "5200",
            ["countByTime"] = "660",
            ["itemType"] = "Coal",
        },
    },
    ["40013007"] = {
        ["id"] = "40013007",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "12",
            ["zoneId"] = "C4_Dorm_1",
        },
    },
    ["40013008"] = {
        ["id"] = "40013008",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.3,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C4_Dorm_3",
        },
    },
    ["40013009"] = {
        ["id"] = "40013009",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "6300",
            ["countByTime"] = "720",
            ["itemType"] = "Copper",
        },
    },
    ["40013010"] = {
        ["id"] = "40013010",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "4200",
            ["countByTime"] = "720",
            ["itemType"] = "CopperBlock",
        },
    },
    ["40013011"] = {
        ["id"] = "40013011",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12.7,
        ["task"] = {
            ["count"] = "18",
            ["zoneId"] = "C4_Dorm_5",
        },
    },
    ["40013012"] = {
        ["id"] = "40013012",
        ["action"] = "SLEEP_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 13.7,
        ["task"] = {
            ["count"] = "18",
            ["hunger"] = "0",
        },
    },
    ["40013013"] = {
        ["id"] = "40013013",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.8,
        ["task"] = {
            ["count"] = "20",
            ["zoneId"] = "C4_Dorm_6",
        },
    },
    ["40013014"] = {
        ["id"] = "40013014",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "5200",
            ["countByTime"] = "840",
            ["itemType"] = "Coal",
        },
    },
    ["40013015"] = {
        ["id"] = "40013015",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "6300",
            ["countByTime"] = "900",
            ["itemType"] = "Copper",
        },
    },
    ["40013016"] = {
        ["id"] = "40013016",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "4200",
            ["countByTime"] = "900",
            ["itemType"] = "CopperBlock",
        },
    },
    ["40013017"] = {
        ["id"] = "40013017",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "980",
            ["countByTime"] = "900",
            ["itemType"] = "CopperWire",
        },
    },
    ["40013018"] = {
        ["id"] = "40013018",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 15.3,
        ["task"] = {
            ["count"] = "22",
            ["zoneId"] = "C4_Dorm_5",
        },
    },
    ["40013019"] = {
        ["id"] = "40013019",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "24",
            ["zoneId"] = "C4_Dorm_7",
        },
    },
    ["40013020"] = {
        ["id"] = "40013020",
        ["action"] = "EAT_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15.5,
        ["task"] = {
            ["count"] = "48",
        },
    },
    ["40013021"] = {
        ["id"] = "40013021",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "26",
            ["zoneId"] = "C4_Dorm_6",
        },
    },
    ["40013022"] = {
        ["id"] = "40013022",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "5200",
            ["countByTime"] = "1020",
            ["itemType"] = "Coal",
        },
    },
    ["40013023"] = {
        ["id"] = "40013023",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17.2,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C4_Dorm_8",
        },
    },
    ["40013024"] = {
        ["id"] = "40013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Copper&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "6300",
            ["countByTime"] = "1080",
            ["itemType"] = "Copper",
        },
    },
    ["40013025"] = {
        ["id"] = "40013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "4200",
            ["countByTime"] = "1080",
            ["itemType"] = "CopperBlock",
        },
    },
    ["40013026"] = {
        ["id"] = "40013026",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "980",
            ["countByTime"] = "1080",
            ["itemType"] = "CopperWire",
        },
    },
    ["40013027"] = {
        ["id"] = "40013027",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "18900",
            ["countByTime"] = "1080",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["40013028"] = {
        ["id"] = "40013028",
        ["action"] = "SLEEP_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18.3,
        ["task"] = {
            ["count"] = "28",
            ["hunger"] = "0",
        },
    },
    ["40013029"] = {
        ["id"] = "40013029",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.7,
        ["task"] = {
            ["count"] = "32",
            ["zoneId"] = "C4_Dorm_9",
        },
    },
    ["40013030"] = {
        ["id"] = "40013030",
        ["action"] = "EAT_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ShatteredGlass&guarantee=1",
        ["stage"] = 19.8,
        ["task"] = {
            ["count"] = "64",
        },
    },
    ["40013031"] = {
        ["id"] = "40013031",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "5200",
            ["countByTime"] = "1200",
            ["itemType"] = "Coal",
        },
    },
    ["40013032"] = {
        ["id"] = "40013032",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 20.3,
        ["task"] = {
            ["count"] = "34",
            ["zoneId"] = "C4_Dorm_8",
        },
    },
    ["40013033"] = {
        ["id"] = "40013033",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.6,
        ["task"] = {
            ["count"] = "36",
            ["zoneId"] = "C4_Dorm_10",
        },
    },
    ["40013034"] = {
        ["id"] = "40013034",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "6300",
            ["countByTime"] = "1260",
            ["itemType"] = "Copper",
        },
    },
    ["40013035"] = {
        ["id"] = "40013035",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "4200",
            ["countByTime"] = "1260",
            ["itemType"] = "CopperBlock",
        },
    },
    ["40013036"] = {
        ["id"] = "40013036",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "980",
            ["countByTime"] = "1260",
            ["itemType"] = "CopperWire",
        },
    },
    ["40013037"] = {
        ["id"] = "40013037",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "18900",
            ["countByTime"] = "1260",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["40013038"] = {
        ["id"] = "40013038",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "670",
            ["countByTime"] = "1260",
            ["itemType"] = "ElectricLight",
        },
    },
    ["40013039"] = {
        ["id"] = "40013039",
        ["action"] = "SLEEP_WELL",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ElectricLight&guarantee=1",
        ["stage"] = 21.2,
        ["task"] = {
            ["count"] = "36",
            ["hunger"] = "0",
        },
    },
    ["40013040"] = {
        ["id"] = "40013040",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 23.7,
        ["task"] = {
            ["count"] = "42",
            ["zoneId"] = "C4_Dorm_10",
        },
    },
    ["40013041"] = {
        ["id"] = "40013041",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "6300",
            ["countByTime"] = "1440",
            ["itemType"] = "Copper",
        },
    },
    ["40013042"] = {
        ["id"] = "40013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperBlock&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "4200",
            ["countByTime"] = "1440",
            ["itemType"] = "CopperBlock",
        },
    },
    ["40013043"] = {
        ["id"] = "40013043",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "980",
            ["countByTime"] = "1440",
            ["itemType"] = "CopperWire",
        },
    },
    ["40013044"] = {
        ["id"] = "40013044",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "18900",
            ["countByTime"] = "1440",
            ["itemType"] = "ShatteredGlass",
        },
    },
    ["40013045"] = {
        ["id"] = "40013045",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=ElectricLight&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "670",
            ["countByTime"] = "1440",
            ["itemType"] = "ElectricLight",
        },
    },
    ["40013046"] = {
        ["id"] = "40013046",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 4,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "670",
            ["countByTime"] = "1620",
            ["itemType"] = "ElectricLight",
        },
    },
} 
