return {
    [10001] = {
        ["id"] = 10001,
        ["availableTaskCount"] = 3,
        ["city"] = 10,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [1001] = {
        ["id"] = 1001,
        ["availableTaskCount"] = 3,
        ["city"] = 1,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToItem*100?id=Gem",
        ["title"] = "",
    },
    [1001001] = {
        ["id"] = 1001001,
        ["availableTaskCount"] = 3,
        ["city"] = 1001,
        ["part"] = 1,
        ["requiredTaskCount"] = 1000,
        ["rewards"] = "addToItem*30?id=Gem",
        ["title"] = "task_milestone_C1_1",
    },
    [1002001] = {
        ["id"] = 1002001,
        ["availableTaskCount"] = 3,
        ["city"] = 1002,
        ["part"] = 1,
        ["requiredTaskCount"] = 1000,
        ["rewards"] = "addToItem*30?id=Gem",
        ["title"] = "task_milestone_C1_1",
    },
    [11001] = {
        ["id"] = 11001,
        ["availableTaskCount"] = 3,
        ["city"] = 11,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [12001] = {
        ["id"] = 12001,
        ["availableTaskCount"] = 3,
        ["city"] = 12,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [13001] = {
        ["id"] = 13001,
        ["availableTaskCount"] = 3,
        ["city"] = 13,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [14001] = {
        ["id"] = 14001,
        ["availableTaskCount"] = 3,
        ["city"] = 14,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [15001] = {
        ["id"] = 15001,
        ["availableTaskCount"] = 3,
        ["city"] = 15,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [16001] = {
        ["id"] = 16001,
        ["availableTaskCount"] = 3,
        ["city"] = 16,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [17001] = {
        ["id"] = 17001,
        ["availableTaskCount"] = 3,
        ["city"] = 17,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [18001] = {
        ["id"] = 18001,
        ["availableTaskCount"] = 3,
        ["city"] = 18,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [19001] = {
        ["id"] = 19001,
        ["availableTaskCount"] = 3,
        ["city"] = 19,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [20001] = {
        ["id"] = 20001,
        ["availableTaskCount"] = 3,
        ["city"] = 20,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [2003] = {
        ["id"] = 2003,
        ["availableTaskCount"] = 3,
        ["city"] = 2,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [3001] = {
        ["id"] = 3001,
        ["availableTaskCount"] = 3,
        ["city"] = 3,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [4001] = {
        ["id"] = 4001,
        ["availableTaskCount"] = 3,
        ["city"] = 4,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [5001] = {
        ["id"] = 5001,
        ["availableTaskCount"] = 3,
        ["city"] = 5,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [6001] = {
        ["id"] = 6001,
        ["availableTaskCount"] = 3,
        ["city"] = 6,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [7001] = {
        ["id"] = 7001,
        ["availableTaskCount"] = 3,
        ["city"] = 7,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [8001] = {
        ["id"] = 8001,
        ["availableTaskCount"] = 3,
        ["city"] = 8,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
    [9001] = {
        ["id"] = 9001,
        ["availableTaskCount"] = 3,
        ["city"] = 9,
        ["part"] = 1,
        ["requiredTaskCount"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_purple",
        ["title"] = "",
    },
}
