return {
    ["20012016"] = {
        ["id"] = 20012016,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*240?id=SmallIronFurnace&guarantee=1',
        ["group"] = 2,
        ["index"] = 16,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C2_Carpentry2_Tool1ForCarpentry2",
            ["zoneId"] = "C2_Carpentry2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 20.0,
        ["desc"] = '',
    },
    ["20011004"] = {
        ["id"] = 20011004,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=ScrapIron&guarantee=1',
        ["group"] = 1,
        ["index"] = 4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_CollectionStation_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20011005"] = {
        ["id"] = 20011005,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_9',
        ["group"] = 1,
        ["index"] = 5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C2_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["20011006"] = {
        ["id"] = 20011006,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_21',
        ["group"] = 1,
        ["index"] = 6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 10.5,
        ["desc"] = '',
    },
    ["20011007"] = {
        ["id"] = 20011007,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C2_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["20011001"] = {
        ["id"] = 20011001,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=Coal',
        ["group"] = 1,
        ["index"] = 1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C2_CollectionStation_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["20011002"] = {
        ["id"] = 20011002,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=ScrapIron',
        ["group"] = 1,
        ["index"] = 2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 8.5,
        ["desc"] = '',
    },
    ["20011003"] = {
        ["id"] = 20011003,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 9.0,
        ["desc"] = '',
    },
    ["20011008"] = {
        ["id"] = 20011008,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["20011009"] = {
        ["id"] = 20011009,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_14',
        ["group"] = 1,
        ["index"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["20012010"] = {
        ["id"] = 20012010,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_19',
        ["group"] = 2,
        ["index"] = 10,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C2_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C2_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["20012011"] = {
        ["id"] = 20012011,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=Coal&guarantee=1',
        ["group"] = 2,
        ["index"] = 11,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "60",
            ["furnitureId"] = "C2_CollectionStation_Tool1ForCollectionStation",
            ["zoneId"] = "C2_CollectionStation_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["20011017"] = {
        ["id"] = 20011017,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["20011016"] = {
        ["id"] = 20011016,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 1,
        ["index"] = 16,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C2_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["20011015"] = {
        ["id"] = 20011015,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_23',
        ["group"] = 1,
        ["index"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C2_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["20011014"] = {
        ["id"] = 20011014,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=PrimaryMold&guarantee=1',
        ["group"] = 1,
        ["index"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["20011013"] = {
        ["id"] = 20011013,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 1,
        ["index"] = 13,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C2_Generator_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["20011012"] = {
        ["id"] = 20011012,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=ScrapIron&guarantee=1',
        ["group"] = 1,
        ["index"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C2_CollectionStation_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["20011011"] = {
        ["id"] = 20011011,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_19',
        ["group"] = 1,
        ["index"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C2_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["20011010"] = {
        ["id"] = 20011010,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*600?id=Heart&guarantee=1',
        ["group"] = 1,
        ["index"] = 10,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 11.5,
        ["desc"] = '',
    },
    ["20011019"] = {
        ["id"] = 20011019,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 19,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C2_Carpentry2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["20011018"] = {
        ["id"] = 20011018,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_20',
        ["group"] = 1,
        ["index"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C2_Carpentry2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["20012005"] = {
        ["id"] = 20012005,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=ScrapIron',
        ["group"] = 2,
        ["index"] = 5,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C2_CollectionStation_Tool1ForCollectionStation",
            ["zoneId"] = "C2_CollectionStation_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20012004"] = {
        ["id"] = 20012004,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 4,
        ["task"] = {
            ["id"] = "19",
            ["level"] = "6",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_CARD_LEVEL',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20012007"] = {
        ["id"] = 20012007,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 7,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C2_Kitchen_Burner",
            ["zoneId"] = "C2_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["20012006"] = {
        ["id"] = 20012006,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=ScrapIron&guarantee=1',
        ["group"] = 2,
        ["index"] = 6,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C2_Infirmary_MedicalBed",
            ["zoneId"] = "C2_Infirmary_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20012001"] = {
        ["id"] = 20012001,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=Coal',
        ["group"] = 2,
        ["index"] = 1,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C2_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C2_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["20012003"] = {
        ["id"] = 20012003,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=card_fix_box_19',
        ["group"] = 2,
        ["index"] = 3,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C2_CoalMine_Tool1ForCoalMine",
            ["zoneId"] = "C2_CoalMine_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20012002"] = {
        ["id"] = 20012002,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=ScrapIron',
        ["group"] = 2,
        ["index"] = 2,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C2_CollectionStation_Tool1ForCollectionStation",
            ["zoneId"] = "C2_CollectionStation_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 8.5,
        ["desc"] = '',
    },
    ["20012009"] = {
        ["id"] = 20012009,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 9,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C2_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 11.5,
        ["desc"] = '',
    },
    ["20012008"] = {
        ["id"] = 20012008,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*600?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 8,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C2_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["20013008"] = {
        ["id"] = 20013008,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 3,
        ["index"] = 8,
        ["task"] = {
            ["count"] = "16",
            ["zoneId"] = "C2_Dorm_5",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 10.5,
        ["desc"] = '',
    },
    ["20013003"] = {
        ["id"] = 20013003,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=Coal',
        ["group"] = 3,
        ["index"] = 3,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C2_Dorm_2",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["20013006"] = {
        ["id"] = 20013006,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 6,
        ["task"] = {
            ["count"] = "28",
        },
        ["part"] = 1,
        ["action"] = 'EAT_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20013012"] = {
        ["id"] = 20013012,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=Coal&guarantee=1',
        ["group"] = 3,
        ["index"] = 12,
        ["task"] = {
            ["count"] = "620",
            ["countByTime"] = "840",
            ["itemType"] = "PrimaryMold",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["20012013"] = {
        ["id"] = 20012013,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 2,
        ["index"] = 13,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C2_Metal_Tool1ForMetal",
            ["zoneId"] = "C2_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["20012014"] = {
        ["id"] = 20012014,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*600?id=Heart&guarantee=1',
        ["group"] = 2,
        ["index"] = 14,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C2_Metal_Tool1ForMetal",
            ["zoneId"] = "C2_Metal_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["20012015"] = {
        ["id"] = 20012015,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 15,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C2_Carpentry2_Tool1ForCarpentry2",
            ["zoneId"] = "C2_Carpentry2_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 17.0,
        ["desc"] = '',
    },
    ["20013002"] = {
        ["id"] = 20013002,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=Coal',
        ["group"] = 3,
        ["index"] = 2,
        ["task"] = {
            ["count"] = "500",
            ["countByTime"] = "0",
            ["itemType"] = "ScrapIron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["20013001"] = {
        ["id"] = 20013001,
        ["city"] = 2,
        ["rewards"] = 'addToItem*100?id=Coal',
        ["group"] = 3,
        ["index"] = 1,
        ["task"] = {
            ["count"] = "6",
            ["zoneId"] = "C2_Dorm_1",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["20013007"] = {
        ["id"] = 20013007,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*300?id=PrimaryMold&guarantee=1',
        ["group"] = 3,
        ["index"] = 7,
        ["task"] = {
            ["count"] = "620",
            ["countByTime"] = "660",
            ["itemType"] = "PrimaryMold",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 10.0,
        ["desc"] = '',
    },
    ["20013004"] = {
        ["id"] = 20013004,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 4,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C2_Dorm_3",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 7.0,
        ["desc"] = '',
    },
    ["20013005"] = {
        ["id"] = 20013005,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 5,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C2_Dorm_4",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 9.5,
        ["desc"] = '',
    },
    ["20013009"] = {
        ["id"] = 20013009,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 9,
        ["task"] = {
            ["count"] = "1040",
            ["countByTime"] = "720",
            ["itemType"] = "Coal",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 11.0,
        ["desc"] = '',
    },
    ["20013015"] = {
        ["id"] = 20013015,
        ["city"] = 2,
        ["rewards"] = 'addToOpenBox*1?id=box_task_wood',
        ["group"] = 3,
        ["index"] = 15,
        ["task"] = {
            ["count"] = "28",
            ["zoneId"] = "C2_Dorm_8",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 15.1,
        ["desc"] = '',
    },
    ["20013017"] = {
        ["id"] = 20013017,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*1000?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 17,
        ["task"] = {
            ["count"] = "120",
            ["countByTime"] = "1200",
            ["itemType"] = "SmallIronFurnace",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 20.0,
        ["desc"] = '',
    },
    ["20013016"] = {
        ["id"] = 20013016,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 16,
        ["task"] = {
            ["count"] = "90",
            ["countByTime"] = "1020",
            ["itemType"] = "SmallIronFurnace",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 16.5,
        ["desc"] = '',
    },
    ["20013010"] = {
        ["id"] = 20013010,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*600?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 10,
        ["task"] = {
            ["count"] = "1850",
            ["countByTime"] = "780",
            ["itemType"] = "ScrapIron",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 11.5,
        ["desc"] = '',
    },
    ["20013013"] = {
        ["id"] = 20013013,
        ["city"] = 2,
        ["rewards"] = 'addToOverTime*600?id=Heart&guarantee=1',
        ["group"] = 3,
        ["index"] = 13,
        ["task"] = {
            ["count"] = "24",
            ["zoneId"] = "C2_Dorm_7",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 13.7,
        ["desc"] = '',
    },
    ["20013014"] = {
        ["id"] = 20013014,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 14,
        ["task"] = {
            ["count"] = "230",
            ["countByTime"] = "840",
            ["itemType"] = "IronBlock",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 14.4,
        ["desc"] = '',
    },
    ["20013011"] = {
        ["id"] = 20013011,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 11,
        ["task"] = {
            ["count"] = "22",
            ["zoneId"] = "C2_Dorm_6",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 12.3,
        ["desc"] = '',
    },
    ["20012012"] = {
        ["id"] = 20012012,
        ["city"] = 2,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 12,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "30",
            ["furnitureId"] = "C2_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C2_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
} 
