return {
    ["10011006"] = {
        ["id"] = 10011006,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 6,
        ["task"] = {
            ["count"] = "2",
            ["professionType"] = "Hunter",
            ["zoneId"] = "C1_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'CHARACTER_PROFESSION_CHANGE',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["10013002"] = {
        ["id"] = 10013002,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 2,
        ["task"] = {
            ["count"] = "10",
            ["countByTime"] = "0",
            ["itemType"] = "RawFood",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 4.0,
        ["desc"] = '',
    },
    ["10011009"] = {
        ["id"] = 10011009,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 9,
        ["task"] = {
            ["count"] = "2",
            ["professionType"] = "Worker",
            ["zoneId"] = "C1_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'CHARACTER_PROFESSION_CHANGE',
        ["isAvailable"] = 1,
        ["stage"] = 16.0,
        ["desc"] = '',
    },
    ["10011008"] = {
        ["id"] = 10011008,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C1_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 16.0,
        ["desc"] = 'task_desc_upgrade_zone_lv1',
    },
    ["10011005"] = {
        ["id"] = 10011005,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C1_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["10011004"] = {
        ["id"] = 10011004,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 4,
        ["task"] = {
            ["count"] = "3",
            ["professionType"] = "FarmerWood",
            ["zoneId"] = "C1_Sawmill_1",
        },
        ["part"] = 1,
        ["action"] = 'CHARACTER_PROFESSION_CHANGE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["10011007"] = {
        ["id"] = 10011007,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 7,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C1_Dorm_3",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 14.0,
        ["desc"] = '',
    },
    ["10011001"] = {
        ["id"] = 10011001,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C1_Dorm_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 4.0,
        ["desc"] = '',
    },
    ["10011003"] = {
        ["id"] = 10011003,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C1_Sawmill_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_ZONE',
        ["isAvailable"] = 1,
        ["stage"] = 4.0,
        ["desc"] = '',
    },
    ["10011002"] = {
        ["id"] = 10011002,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 1,
        ["index"] = 2,
        ["task"] = {
            ["count"] = "6",
            ["zoneId"] = "C1_Dorm_1",
        },
        ["part"] = 1,
        ["action"] = 'SURVIVOR_COUNT',
        ["isAvailable"] = 1,
        ["stage"] = 5.0,
        ["desc"] = '',
    },
    ["10012005"] = {
        ["id"] = 10012005,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 5,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "40",
            ["furnitureId"] = "C1_Sawmill_Tool1ForSawmill",
            ["zoneId"] = "C1_Sawmill_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 13.0,
        ["desc"] = '',
    },
    ["10012006"] = {
        ["id"] = 10012006,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 6,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C1_Carpentry_Boost1ForCarpentry",
            ["zoneId"] = "C1_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 16.0,
        ["desc"] = '',
    },
    ["10012002"] = {
        ["id"] = 10012002,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 2,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C1_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C1_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 4.0,
        ["desc"] = '',
    },
    ["10013004"] = {
        ["id"] = 10013004,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 4,
        ["task"] = {
            ["count"] = "150",
            ["countByTime"] = "0",
            ["itemType"] = "WoodenBoard",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 16.0,
        ["desc"] = '',
    },
    ["10013003"] = {
        ["id"] = 10013003,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 3,
        ["task"] = {
            ["count"] = "1500",
            ["countByTime"] = "0",
            ["itemType"] = "Wood",
        },
        ["part"] = 1,
        ["action"] = 'COLLECT_ITEM',
        ["isAvailable"] = 1,
        ["stage"] = 5.0,
        ["desc"] = '',
    },
    ["10013001"] = {
        ["id"] = 10013001,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 3,
        ["index"] = 1,
        ["task"] = {
            ["count"] = "8",
        },
        ["part"] = 1,
        ["action"] = 'EAT_WELL',
        ["isAvailable"] = 1,
        ["stage"] = 4.0,
        ["desc"] = '',
    },
    ["10012004"] = {
        ["id"] = 10012004,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 4,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C1_HunterCabin_Tool1ForHunterCabin",
            ["zoneId"] = "C1_HunterCabin_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 12.0,
        ["desc"] = '',
    },
    ["10012001"] = {
        ["id"] = 10012001,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 1,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C1_Sawmill_Tool1ForSawmill",
            ["zoneId"] = "C1_Sawmill_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 4.0,
        ["desc"] = '',
    },
    ["10012003"] = {
        ["id"] = 10012003,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 3,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "10",
            ["furnitureId"] = "C1_Kitchen_Burner",
            ["zoneId"] = "C1_Kitchen_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 5.0,
        ["desc"] = '',
    },
    ["10012007"] = {
        ["id"] = 10012007,
        ["city"] = 1,
        ["rewards"] = 'addToItem*10?id=Gem',
        ["group"] = 2,
        ["index"] = 7,
        ["task"] = {
            ["index"] = "1",
            ["level"] = "20",
            ["furnitureId"] = "C1_Carpentry_Tool1ForCarpentry",
            ["zoneId"] = "C1_Carpentry_1",
        },
        ["part"] = 1,
        ["action"] = 'UPGRADE_TARGET_FURNITURE',
        ["isAvailable"] = 1,
        ["stage"] = 16.0,
        ["desc"] = '',
    },
} 
