return {
    ["70011001"] = {
        ["id"] = "70011001",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70011002"] = {
        ["id"] = "70011002",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011003"] = {
        ["id"] = "70011003",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 10.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011004"] = {
        ["id"] = "70011004",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70011005"] = {
        ["id"] = "70011005",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011006"] = {
        ["id"] = "70011006",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70011007"] = {
        ["id"] = "70011007",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011008"] = {
        ["id"] = "70011008",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70011009"] = {
        ["id"] = "70011009",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70011010"] = {
        ["id"] = "70011010",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 13.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70011011"] = {
        ["id"] = "70011011",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.9,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70011012"] = {
        ["id"] = "70011012",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011013"] = {
        ["id"] = "70011013",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011014"] = {
        ["id"] = "70011014",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011015"] = {
        ["id"] = "70011015",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70011016"] = {
        ["id"] = "70011016",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011017"] = {
        ["id"] = "70011017",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70011018"] = {
        ["id"] = "70011018",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70011019"] = {
        ["id"] = "70011019",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011020"] = {
        ["id"] = "70011020",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70011021"] = {
        ["id"] = "70011021",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 17.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011022"] = {
        ["id"] = "70011022",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011023"] = {
        ["id"] = "70011023",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70011024"] = {
        ["id"] = "70011024",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011025"] = {
        ["id"] = "70011025",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70011026"] = {
        ["id"] = "70011026",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 19.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70011027"] = {
        ["id"] = "70011027",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011028"] = {
        ["id"] = "70011028",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.8,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70011029"] = {
        ["id"] = "70011029",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011030"] = {
        ["id"] = "70011030",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70011031"] = {
        ["id"] = "70011031",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011032"] = {
        ["id"] = "70011032",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70011033"] = {
        ["id"] = "70011033",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70011034"] = {
        ["id"] = "70011034",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 21.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011035"] = {
        ["id"] = "70011035",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.5,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70011036"] = {
        ["id"] = "70011036",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70011037"] = {
        ["id"] = "70011037",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011038"] = {
        ["id"] = "70011038",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011039"] = {
        ["id"] = "70011039",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70011040"] = {
        ["id"] = "70011040",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011041"] = {
        ["id"] = "70011041",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70011042"] = {
        ["id"] = "70011042",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70011043"] = {
        ["id"] = "70011043",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "task_desc_upgrade_zone_lv1",
        ["group"] = 1,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerArm&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "1",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70011044"] = {
        ["id"] = "70011044",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24.3,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70011045"] = {
        ["id"] = "70011045",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 24.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011046"] = {
        ["id"] = "70011046",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.2,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70011047"] = {
        ["id"] = "70011047",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011048"] = {
        ["id"] = "70011048",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70011049"] = {
        ["id"] = "70011049",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 26.4,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70011050"] = {
        ["id"] = "70011050",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011051"] = {
        ["id"] = "70011051",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70011052"] = {
        ["id"] = "70011052",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011053"] = {
        ["id"] = "70011053",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70011054"] = {
        ["id"] = "70011054",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70011055"] = {
        ["id"] = "70011055",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerArm&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "2",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70011056"] = {
        ["id"] = "70011056",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27.7,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70011057"] = {
        ["id"] = "70011057",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 28.1,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011058"] = {
        ["id"] = "70011058",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70011059"] = {
        ["id"] = "70011059",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70011060"] = {
        ["id"] = "70011060",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011061"] = {
        ["id"] = "70011061",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70011062"] = {
        ["id"] = "70011062",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70011063"] = {
        ["id"] = "70011063",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "3",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70011064"] = {
        ["id"] = "70011064",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_blue",
        ["stage"] = 31.6,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C7_Generator_1",
        },
    },
    ["70011065"] = {
        ["id"] = "70011065",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "7",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70011066"] = {
        ["id"] = "70011066",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 66,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "6",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70011067"] = {
        ["id"] = "70011067",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 67,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "5",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70011068"] = {
        ["id"] = "70011068",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 68,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "4",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70011069"] = {
        ["id"] = "70011069",
        ["action"] = "UPGRADE_ZONE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 1,
        ["index"] = 69,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 36,
        ["task"] = {
            ["count"] = "1",
            ["level"] = "8",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012001"] = {
        ["id"] = "70012001",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 7,
        ["task"] = {
            ["furnitureId"] = "C7_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70012002"] = {
        ["id"] = "70012002",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012004"] = {
        ["id"] = "70012004",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 10.5,
        ["task"] = {
            ["furnitureId"] = "C7_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70012005"] = {
        ["id"] = "70012005",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012006"] = {
        ["id"] = "70012006",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 11.8,
        ["task"] = {
            ["furnitureId"] = "C7_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70012007"] = {
        ["id"] = "70012007",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012008"] = {
        ["id"] = "70012008",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C7_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70012009"] = {
        ["id"] = "70012009",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["furnitureId"] = "C7_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70012010"] = {
        ["id"] = "70012010",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.1,
        ["task"] = {
            ["furnitureId"] = "C7_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70012011"] = {
        ["id"] = "70012011",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.9,
        ["task"] = {
            ["furnitureId"] = "C7_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70012013"] = {
        ["id"] = "70012013",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 14,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012014"] = {
        ["id"] = "70012014",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012015"] = {
        ["id"] = "70012015",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C7_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70012016"] = {
        ["id"] = "70012016",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012017"] = {
        ["id"] = "70012017",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 16.7,
        ["task"] = {
            ["furnitureId"] = "C7_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70012018"] = {
        ["id"] = "70012018",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 16.8,
        ["task"] = {
            ["furnitureId"] = "C7_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "20",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70012019"] = {
        ["id"] = "70012019",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012020"] = {
        ["id"] = "70012020",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17.4,
        ["task"] = {
            ["furnitureId"] = "C7_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70012022"] = {
        ["id"] = "70012022",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012023"] = {
        ["id"] = "70012023",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C7_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70012024"] = {
        ["id"] = "70012024",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012025"] = {
        ["id"] = "70012025",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["furnitureId"] = "C7_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70012026"] = {
        ["id"] = "70012026",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 19.1,
        ["task"] = {
            ["furnitureId"] = "C7_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70012027"] = {
        ["id"] = "70012027",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012028"] = {
        ["id"] = "70012028",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 20.8,
        ["task"] = {
            ["furnitureId"] = "C7_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70012029"] = {
        ["id"] = "70012029",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012030"] = {
        ["id"] = "70012030",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C7_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70012031"] = {
        ["id"] = "70012031",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012032"] = {
        ["id"] = "70012032",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C7_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70012033"] = {
        ["id"] = "70012033",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70012035"] = {
        ["id"] = "70012035",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 21.5,
        ["task"] = {
            ["furnitureId"] = "C7_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70012036"] = {
        ["id"] = "70012036",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21.6,
        ["task"] = {
            ["furnitureId"] = "C7_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70012037"] = {
        ["id"] = "70012037",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 23,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012038"] = {
        ["id"] = "70012038",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012039"] = {
        ["id"] = "70012039",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C7_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70012040"] = {
        ["id"] = "70012040",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012041"] = {
        ["id"] = "70012041",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C7_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70012042"] = {
        ["id"] = "70012042",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70012043"] = {
        ["id"] = "70012043",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory2_Tool1ForMachineryFactory2",
            ["index"] = "1",
            ["level"] = "10",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70012044"] = {
        ["id"] = "70012044",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24.3,
        ["task"] = {
            ["furnitureId"] = "C7_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70012046"] = {
        ["id"] = "70012046",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 25.2,
        ["task"] = {
            ["furnitureId"] = "C7_Infirmary_MedicalBed",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C7_Infirmary_1",
        },
    },
    ["70012047"] = {
        ["id"] = "70012047",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012048"] = {
        ["id"] = "70012048",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26.4,
        ["task"] = {
            ["furnitureId"] = "C7_Kitchen_Burner",
            ["index"] = "1",
            ["level"] = "50",
            ["zoneId"] = "C7_Kitchen_1",
        },
    },
    ["70012049"] = {
        ["id"] = "70012049",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26.4,
        ["task"] = {
            ["furnitureId"] = "C7_Watchtower_Boost1ForWatchtower",
            ["index"] = "1",
            ["level"] = "40",
            ["zoneId"] = "C7_Watchtower_1",
        },
    },
    ["70012050"] = {
        ["id"] = "70012050",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012051"] = {
        ["id"] = "70012051",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C7_CollectionStation_Tool1ForCollectionStation",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C7_CollectionStation_1",
        },
    },
    ["70012052"] = {
        ["id"] = "70012052",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012053"] = {
        ["id"] = "70012053",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C7_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70012054"] = {
        ["id"] = "70012054",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70012055"] = {
        ["id"] = "70012055",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory2_Tool1ForMachineryFactory2",
            ["index"] = "1",
            ["level"] = "30",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70012056"] = {
        ["id"] = "70012056",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27.7,
        ["task"] = {
            ["furnitureId"] = "C7_Greenhouse_Tool1ForGreenhouse",
            ["index"] = "1",
            ["level"] = "70",
            ["zoneId"] = "C7_Greenhouse_1",
        },
    },
    ["70012058"] = {
        ["id"] = "70012058",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 29,
        ["task"] = {
            ["furnitureId"] = "C7_CoalMine_Tool1ForCoalMine",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C7_CoalMine_1",
        },
    },
    ["70012059"] = {
        ["id"] = "70012059",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=CopperWire2&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry_Tool1ForCarpentry",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C7_Carpentry_1",
        },
    },
    ["70012060"] = {
        ["id"] = "70012060",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012061"] = {
        ["id"] = "70012061",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C7_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70012062"] = {
        ["id"] = "70012062",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70012063"] = {
        ["id"] = "70012063",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory2_Tool1ForMachineryFactory2",
            ["index"] = "1",
            ["level"] = "60",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70012065"] = {
        ["id"] = "70012065",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "180",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70012066"] = {
        ["id"] = "70012066",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 66,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C7_Metal_Tool1ForMetal",
            ["index"] = "1",
            ["level"] = "150",
            ["zoneId"] = "C7_Metal_1",
        },
    },
    ["70012067"] = {
        ["id"] = "70012067",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 67,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory_Tool1ForMachineryFactory",
            ["index"] = "1",
            ["level"] = "120",
            ["zoneId"] = "C7_MachineryFactory_1",
        },
    },
    ["70012068"] = {
        ["id"] = "70012068",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 68,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerArm&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["furnitureId"] = "C7_MachineryFactory2_Tool1ForMachineryFactory2",
            ["index"] = "1",
            ["level"] = "90",
            ["zoneId"] = "C7_MachineryFactory2_1",
        },
    },
    ["70012069"] = {
        ["id"] = "70012069",
        ["action"] = "UPGRADE_TARGET_FURNITURE",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 2,
        ["index"] = 69,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 36,
        ["task"] = {
            ["furnitureId"] = "C7_Carpentry2_Tool1ForCarpentry2",
            ["index"] = "1",
            ["level"] = "210",
            ["zoneId"] = "C7_Carpentry2_1",
        },
    },
    ["70013001"] = {
        ["id"] = "70013001",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 1,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 7,
        ["task"] = {
            ["count"] = "8",
        },
    },
    ["70013002"] = {
        ["id"] = "70013002",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 2,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 9,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "540",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013003"] = {
        ["id"] = "70013003",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 3,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 10.5,
        ["task"] = {
            ["count"] = "6",
            ["zoneId"] = "C7_Dorm_3",
        },
    },
    ["70013004"] = {
        ["id"] = "70013004",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 4,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 10.5,
        ["task"] = {
            ["count"] = "6",
            ["hunger"] = "0",
        },
    },
    ["70013005"] = {
        ["id"] = "70013005",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 5,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 11,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "660",
            ["itemType"] = "Coal",
        },
    },
    ["70013006"] = {
        ["id"] = "70013006",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 6,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 11.8,
        ["task"] = {
            ["count"] = "8",
            ["zoneId"] = "C7_Dorm_2",
        },
    },
    ["70013007"] = {
        ["id"] = "70013007",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 7,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "720",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013008"] = {
        ["id"] = "70013008",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 8,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "2700",
            ["countByTime"] = "720",
            ["itemType"] = "Plastic",
        },
    },
    ["70013009"] = {
        ["id"] = "70013009",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 9,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 12,
        ["task"] = {
            ["count"] = "10",
            ["zoneId"] = "C7_Dorm_1",
        },
    },
    ["70013010"] = {
        ["id"] = "70013010",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 10,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 13.1,
        ["task"] = {
            ["count"] = "14",
            ["zoneId"] = "C7_Dorm_4",
        },
    },
    ["70013011"] = {
        ["id"] = "70013011",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 11,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 13.9,
        ["task"] = {
            ["count"] = "28",
        },
    },
    ["70013012"] = {
        ["id"] = "70013012",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 12,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "14",
            ["hunger"] = "0",
        },
    },
    ["70013013"] = {
        ["id"] = "70013013",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 13,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 14,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "840",
            ["itemType"] = "Coal",
        },
    },
    ["70013014"] = {
        ["id"] = "70013014",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 14,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "900",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013015"] = {
        ["id"] = "70013015",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 15,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "2700",
            ["countByTime"] = "900",
            ["itemType"] = "Plastic",
        },
    },
    ["70013016"] = {
        ["id"] = "70013016",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 16,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 15,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "900",
            ["itemType"] = "Cable",
        },
    },
    ["70013017"] = {
        ["id"] = "70013017",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 17,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 16.7,
        ["task"] = {
            ["count"] = "24",
            ["zoneId"] = "C7_Dorm_8",
        },
    },
    ["70013018"] = {
        ["id"] = "70013018",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 18,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 16.8,
        ["task"] = {
            ["count"] = "48",
        },
    },
    ["70013019"] = {
        ["id"] = "70013019",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 19,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 17,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "1020",
            ["itemType"] = "Coal",
        },
    },
    ["70013020"] = {
        ["id"] = "70013020",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 20,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 17.4,
        ["task"] = {
            ["count"] = "26",
            ["zoneId"] = "C7_Dorm_9",
        },
    },
    ["70013021"] = {
        ["id"] = "70013021",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 21,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 17.5,
        ["task"] = {
            ["count"] = "26",
            ["hunger"] = "0",
        },
    },
    ["70013022"] = {
        ["id"] = "70013022",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 22,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "1080",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013023"] = {
        ["id"] = "70013023",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 23,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "2700",
            ["countByTime"] = "1080",
            ["itemType"] = "Plastic",
        },
    },
    ["70013024"] = {
        ["id"] = "70013024",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 24,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "1080",
            ["itemType"] = "Cable",
        },
    },
    ["70013025"] = {
        ["id"] = "70013025",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 25,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 18,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1080",
            ["itemType"] = "SteelBlock",
        },
    },
    ["70013026"] = {
        ["id"] = "70013026",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 26,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 19.1,
        ["task"] = {
            ["count"] = "36",
            ["zoneId"] = "C7_Dorm_12",
        },
    },
    ["70013027"] = {
        ["id"] = "70013027",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 27,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 20,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "1200",
            ["itemType"] = "Coal",
        },
    },
    ["70013028"] = {
        ["id"] = "70013028",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 28,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 20.8,
        ["task"] = {
            ["count"] = "44",
            ["zoneId"] = "C7_Dorm_8",
        },
    },
    ["70013029"] = {
        ["id"] = "70013029",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 29,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "1260",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013030"] = {
        ["id"] = "70013030",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 30,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "2700",
            ["countByTime"] = "1260",
            ["itemType"] = "Plastic",
        },
    },
    ["70013031"] = {
        ["id"] = "70013031",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 31,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "1260",
            ["itemType"] = "Cable",
        },
    },
    ["70013032"] = {
        ["id"] = "70013032",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 32,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1260",
            ["itemType"] = "SteelBlock",
        },
    },
    ["70013033"] = {
        ["id"] = "70013033",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 33,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 21,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1260",
            ["itemType"] = "Dynamo",
        },
    },
    ["70013034"] = {
        ["id"] = "70013034",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 34,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 21.1,
        ["task"] = {
            ["count"] = "88",
        },
    },
    ["70013035"] = {
        ["id"] = "70013035",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 35,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 21.5,
        ["task"] = {
            ["count"] = "46",
            ["zoneId"] = "C7_Dorm_9",
        },
    },
    ["70013036"] = {
        ["id"] = "70013036",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 36,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 21.6,
        ["task"] = {
            ["count"] = "46",
            ["hunger"] = "0",
        },
    },
    ["70013037"] = {
        ["id"] = "70013037",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 37,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 23,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "1380",
            ["itemType"] = "Coal",
        },
    },
    ["70013038"] = {
        ["id"] = "70013038",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 38,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "1440",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013039"] = {
        ["id"] = "70013039",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 39,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "2700",
            ["countByTime"] = "1440",
            ["itemType"] = "Plastic",
        },
    },
    ["70013040"] = {
        ["id"] = "70013040",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 40,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "1440",
            ["itemType"] = "Cable",
        },
    },
    ["70013041"] = {
        ["id"] = "70013041",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 41,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1440",
            ["itemType"] = "SteelBlock",
        },
    },
    ["70013042"] = {
        ["id"] = "70013042",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 42,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1440",
            ["itemType"] = "Dynamo",
        },
    },
    ["70013043"] = {
        ["id"] = "70013043",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 43,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 24,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1440",
            ["itemType"] = "PowerArm",
        },
    },
    ["70013044"] = {
        ["id"] = "70013044",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 44,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 24.3,
        ["task"] = {
            ["count"] = "54",
            ["zoneId"] = "C7_Dorm_13",
        },
    },
    ["70013045"] = {
        ["id"] = "70013045",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 45,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 24.6,
        ["task"] = {
            ["count"] = "108",
        },
    },
    ["70013046"] = {
        ["id"] = "70013046",
        ["action"] = "SURVIVOR_COUNT",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 46,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 25.2,
        ["task"] = {
            ["count"] = "56",
            ["zoneId"] = "C7_Dorm_14",
        },
    },
    ["70013047"] = {
        ["id"] = "70013047",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 47,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 26,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "1560",
            ["itemType"] = "Coal",
        },
    },
    ["70013048"] = {
        ["id"] = "70013048",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 48,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Coal7&guarantee=1",
        ["stage"] = 26.4,
        ["task"] = {
            ["count"] = "56",
            ["hunger"] = "0",
        },
    },
    ["70013049"] = {
        ["id"] = "70013049",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 49,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 26.4,
        ["task"] = {
            ["count"] = "112",
        },
    },
    ["70013050"] = {
        ["id"] = "70013050",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 50,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "1620",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013051"] = {
        ["id"] = "70013051",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 51,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Plastic&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "2700",
            ["countByTime"] = "1620",
            ["itemType"] = "Plastic",
        },
    },
    ["70013052"] = {
        ["id"] = "70013052",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 52,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "1620",
            ["itemType"] = "Cable",
        },
    },
    ["70013053"] = {
        ["id"] = "70013053",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 53,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1620",
            ["itemType"] = "SteelBlock",
        },
    },
    ["70013054"] = {
        ["id"] = "70013054",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 54,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Dynamo&guarantee=1",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1620",
            ["itemType"] = "Dynamo",
        },
    },
    ["70013055"] = {
        ["id"] = "70013055",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 55,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 27,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1620",
            ["itemType"] = "PowerArm",
        },
    },
    ["70013056"] = {
        ["id"] = "70013056",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 56,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 27.7,
        ["task"] = {
            ["count"] = "56",
            ["hunger"] = "0",
        },
    },
    ["70013057"] = {
        ["id"] = "70013057",
        ["action"] = "EAT_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 57,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 28.1,
        ["task"] = {
            ["count"] = "112",
        },
    },
    ["70013058"] = {
        ["id"] = "70013058",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 58,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 29,
        ["task"] = {
            ["count"] = "24000",
            ["countByTime"] = "1740",
            ["itemType"] = "Coal",
        },
    },
    ["70013059"] = {
        ["id"] = "70013059",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 59,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "5760",
            ["countByTime"] = "1800",
            ["itemType"] = "CopperWire",
        },
    },
    ["70013060"] = {
        ["id"] = "70013060",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 60,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "1800",
            ["itemType"] = "Cable",
        },
    },
    ["70013061"] = {
        ["id"] = "70013061",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 61,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1800",
            ["itemType"] = "SteelBlock",
        },
    },
    ["70013062"] = {
        ["id"] = "70013062",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 62,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1800",
            ["itemType"] = "Dynamo",
        },
    },
    ["70013063"] = {
        ["id"] = "70013063",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 63,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=PowerArm&guarantee=1",
        ["stage"] = 30,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1800",
            ["itemType"] = "PowerArm",
        },
    },
    ["70013064"] = {
        ["id"] = "70013064",
        ["action"] = "SLEEP_WELL",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 64,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOpenBox*1?id=box_task_wood",
        ["stage"] = 31.6,
        ["task"] = {
            ["count"] = "56",
            ["hunger"] = "0",
        },
    },
    ["70013065"] = {
        ["id"] = "70013065",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 65,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "1980",
            ["itemType"] = "Cable",
        },
    },
    ["70013066"] = {
        ["id"] = "70013066",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 66,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=SteelBlock2&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "7200",
            ["countByTime"] = "1980",
            ["itemType"] = "SteelBlock",
        },
    },
    ["70013067"] = {
        ["id"] = "70013067",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 67,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToItem*10?id=Gem",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "420",
            ["countByTime"] = "1980",
            ["itemType"] = "Dynamo",
        },
    },
    ["70013068"] = {
        ["id"] = "70013068",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 68,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*1200?id=Heart&guarantee=1",
        ["stage"] = 33,
        ["task"] = {
            ["count"] = "400",
            ["countByTime"] = "1980",
            ["itemType"] = "PowerArm",
        },
    },
    ["70013069"] = {
        ["id"] = "70013069",
        ["action"] = "COLLECT_ITEM",
        ["city"] = 7,
        ["desc"] = "",
        ["group"] = 3,
        ["index"] = 69,
        ["isAvailable"] = 1,
        ["part"] = 1,
        ["rewards"] = "addToOverTime*900?id=Cable&guarantee=1",
        ["stage"] = 36,
        ["task"] = {
            ["count"] = "1240",
            ["countByTime"] = "2160",
            ["itemType"] = "Cable",
        },
    },  
} 
