return {
    ["CHARACTER_PROFESSION_CHANGE"] = {
        ["id"] = "CHARACTER_PROFESSION_CHANGE",
        ["desc"] = "task_desc_change_profession",
        ["desc_short"] = "task_desc_change_profession_short",
        ["eventType"] = "CHARACTER_PROFESSION_CHANGE",
        ["icon"] = "icon_task_type_people",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskChangeProfession",
        ["stepType"] = "Current",
    },
    ["COLLECT_FOOD"] = {
        ["id"] = "COLLECT_FOOD",
        ["desc"] = "task_desc_collect_item",
        ["desc_short"] = "task_desc_collect_item_short",
        ["eventType"] = "COLLECT_FOOD",
        ["icon"] = "icon_task_type_collect",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskCollectFood",
        ["stepType"] = "Count",
    },
    ["COLLECT_ITEM"] = {
        ["id"] = "COLLECT_ITEM",
        ["desc"] = "task_desc_collect_item",
        ["desc_short"] = "task_desc_collect_item_short",
        ["eventType"] = "COLLECT_ITEM",
        ["icon"] = "icon_task_type_collect",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskCollectItem",
        ["stepType"] = "Count",
    },
    ["EAT_WELL"] = {
        ["id"] = "EAT_WELL",
        ["desc"] = "task_desc_eat_well",
        ["desc_short"] = "task_desc_eat_well_short",
        ["eventType"] = "CHARACTER_EATING_FOOD",
        ["icon"] = "icon_task_type_eat",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskEatWell",
        ["stepType"] = "Count",
    },
    ["OPEN_BOX"] = {
        ["id"] = "OPEN_BOX",
        ["desc"] = "task_desc_open_box",
        ["desc_short"] = "task_desc_open_box_short",
        ["eventType"] = "OPEN_BOX",
        ["icon"] = "icon_task_type_gem",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskOpenBox",
        ["stepType"] = "Count",
    },
    ["SLEEP_WELL"] = {
        ["id"] = "SLEEP_WELL",
        ["desc"] = "task_desc_sleep_well",
        ["desc_short"] = "task_desc_sleep_well_short",
        ["eventType"] = "SCHEDULES_REMOVE",
        ["icon"] = "icon_task_type_sleep",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskSleepWell",
        ["stepType"] = "Count",
    },
    ["SURVIVOR_COUNT"] = {
        ["id"] = "SURVIVOR_COUNT",
        ["desc"] = "task_desc_survivor_number",
        ["desc_short"] = "task_desc_survivor_number_short",
        ["eventType"] = "CHARACTER_REFRESH",
        ["icon"] = "icon_task_type_addPeople",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskSurvivorCount",
        ["stepType"] = "Current",
    },
    ["UPGRADE_CARD_LEVEL"] = {
        ["id"] = "UPGRADE_CARD_LEVEL",
        ["desc"] = "task_desc_upgrade_card",
        ["desc_short"] = "task_desc_upgrade_card_short",
        ["eventType"] = "UPGRADE_CARD_LEVEL",
        ["icon"] = "icon_task_type_upgrade",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskUpgradeCardLevel",
        ["stepType"] = "Current",
    },
    ["UPGRADE_FURNITURE"] = {
        ["id"] = "UPGRADE_FURNITURE",
        ["desc"] = "task_desc_upgrade_furniture",
        ["desc_short"] = "task_desc_upgrade_furniture_short",
        ["eventType"] = "UPGRADE_FURNITURE",
        ["icon"] = "icon_task_type_upgrade",
        ["iconColor"] = "284a91ff",
        ["logicName"] = "TaskUpgradeFurniture",
        ["stepType"] = "Current",
    },
    ["UPGRADE_TARGET_CARD_LEVEL"] = {
        ["id"] = "UPGRADE_TARGET_CARD_LEVEL",
        ["desc"] = "task_desc_upgrade_target_card",
        ["desc_short"] = "task_desc_upgrade_target_card_short",
        ["eventType"] = "UPGRADE_CARD_LEVEL",
        ["icon"] = "icon_task_type_upgrade",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskUpgradeTargetCardLevel",
        ["stepType"] = "Current",
    },
    ["UPGRADE_TARGET_FURNITURE"] = {
        ["id"] = "UPGRADE_TARGET_FURNITURE",
        ["desc"] = "task_desc_upgrade_target_furniture",
        ["desc_short"] = "task_desc_upgrade_target_furniture_short",
        ["eventType"] = "UPGRADE_FURNITURE",
        ["icon"] = "icon_task_type_upgrade",
        ["iconColor"] = "284a91ff",
        ["logicName"] = "TaskUpgradeTargetFurniture",
        ["stepType"] = "Current",
    },
    ["UPGRADE_ZONE"] = {
        ["id"] = "UPGRADE_ZONE",
        ["desc"] = "task_desc_upgrade_zone",
        ["desc_short"] = "task_desc_upgrade_zone_short",
        ["eventType"] = "UPGRADE_ZONE",
        ["icon"] = "icon_task_type_upgrade",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskUpgradeZone",
        ["stepType"] = "Current",
    },
    ["USE_ITEM"] = {
        ["id"] = "USE_ITEM",
        ["desc"] = "task_desc_UseItem",
        ["desc_short"] = "task_desc_use_item_short",
        ["eventType"] = "USE_ITEM",
        ["icon"] = "icon_task_type_coin",
        ["iconColor"] = "ffffffff",
        ["logicName"] = "TaskUseItem",
        ["stepType"] = "Count",
    },
}
