return {
    [10] = {
        ["id"] = 10,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialFirstEnterCity2",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [11] = {
        ["id"] = 11,
        ["cityId"] = 2,
        ["ignore"] = true,
        ["logicName"] = "TutorialCardIntroduce",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [12] = {
        ["id"] = 12,
        ["cityId"] = 2,
        ["ignore"] = true,
        ["logicName"] = "TutorialCardInfirmary",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [13] = {
        ["id"] = 13,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialToBattle",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [14] = {
        ["id"] = 14,
        ["cityId"] = 2,
        ["ignore"] = true,
        ["logicName"] = "TutorialOpenBox",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [15] = {
        ["id"] = 15,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialToHalo",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [16] = {
        ["id"] = 16,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialInsufficientResourceCity1",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [17] = {
        ["id"] = 17,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialInsufficientResourceCity2",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [18] = {
        ["id"] = 18,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialNightTalk",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [19] = {
        ["id"] = 19,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialToCity2",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [2] = {
        ["id"] = 2,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialFirstEnterCity",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1159,
        ["stopDay"] = 1,
    },
    [20] = {
        ["id"] = 20,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialSurvivorSick",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [21] = {
        ["id"] = 21,
        ["cityId"] = 2,
        ["ignore"] = true,
        ["logicName"] = "TutorialCardCoalMine",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [22] = {
        ["id"] = 22,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialCardInfirmaryV2",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [23] = {
        ["id"] = 23,
        ["cityId"] = -1,
        ["ignore"] = false,
        ["logicName"] = "TutorialRogueLike",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [24] = {
        ["id"] = 24,
        ["cityId"] = -1,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventIntro",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [25] = {
        ["id"] = 25,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventEnterCity",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [26] = {
        ["id"] = 26,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventAssignCard",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [27] = {
        ["id"] = 27,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventEnoughFood",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1159,
        ["stopDay"] = 1,
    },
    [28] = {
        ["id"] = 28,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventWarehouse",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [29] = {
        ["id"] = 29,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventCarMove",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [3] = {
        ["id"] = 3,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialBuildGenerator",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1159,
        ["stopDay"] = 1,
    },
    [30] = {
        ["id"] = 30,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventSlot",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [31] = {
        ["id"] = 31,
        ["cityId"] = 1001,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventTrick",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [32] = {
        ["id"] = 32,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialLackRawMat",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [33] = {
        ["id"] = 33,
        ["cityId"] = -1,
        ["ignore"] = false,
        ["logicName"] = "TutorialProtestTalks",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [34] = {
        ["id"] = 34,
        ["cityId"] = -1,
        ["ignore"] = false,
        ["logicName"] = "TutorialProtestRiots",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [35] = {
        ["id"] = 35,
        ["cityId"] = 1002,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventEnterCity1002",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [36] = {
        ["id"] = 36,
        ["cityId"] = 1002,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventAssignCard1002",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [37] = {
        ["id"] = 37,
        ["cityId"] = 1002,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventEnoughFood1002",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1159,
        ["stopDay"] = 1,
    },
    [38] = {
        ["id"] = 38,
        ["cityId"] = 1002,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventWarehouse1002",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [39] = {
        ["id"] = 39,
        ["cityId"] = 1002,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventCarMove1002",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [4] = {
        ["id"] = 4,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialBuildSawmill",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1159,
        ["stopDay"] = 1,
    },
    [40] = {
        ["id"] = 40,
        ["cityId"] = 1002,
        ["ignore"] = false,
        ["logicName"] = "TutorialEventSlot1002",
        ["needLimitSave"] = false,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [41] = {
        ["id"] = 41,
        ["cityId"] = 2,
        ["ignore"] = false,
        ["logicName"] = "TutorialTaskGetCard",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [5] = {
        ["id"] = 5,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialBuildKitchen",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1159,
        ["stopDay"] = 1,
    },
    [50] = {
        ["id"] = 50,
        ["cityId"] = 4,
        ["ignore"] = false,
        ["logicName"] = "TutorialFactoryGame",
        ["needLimitSave"] = true,
        ["needStop"] = false,
        ["stopClock"] = 0,
        ["stopDay"] = 0,
    },
    [6] = {
        ["id"] = 6,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialSchedulesEat",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1459,
        ["stopDay"] = 1,
    },
    [7] = {
        ["id"] = 7,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialBuildHunterCabin",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1700,
        ["stopDay"] = 1,
    },
    [8] = {
        ["id"] = 8,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialOverloadOpen",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 1735,
        ["stopDay"] = 1,
    },
    [9] = {
        ["id"] = 9,
        ["cityId"] = 1,
        ["ignore"] = false,
        ["logicName"] = "TutorialOverloadClose",
        ["needLimitSave"] = true,
        ["needStop"] = true,
        ["stopClock"] = 440,
        ["stopDay"] = 2,
    },
}
